### ISSUE TITLE
activedirectory: Add-DnsServerResourceRecord should include the -TimeToLive flag

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#10]
Creating DNS records via the ActiveDirectory driver should set the TTL:

Add-DnsServerResourceRecordA -ComputerName "ny-dc01" -ZoneName "internal" -Name "pingdomcheck.stackoverflow.com" -IPv4Address "10.10.10.10" -TimeToLive 123

It should only be included if the TTL value is non-zero and not 300 (or the default TTL for this zone).

**Comment by captncraig** [comment]
Fixed in #74
