### ISSUE TITLE
MSDNS: Enable running PowerShell commands on a remote (pssession) host

### ISSUE THREAD

**Issue by areynolds77** [StackExchange/dnscontrol#1010]
Hello all! Really appreciate this project, it's been a tremendous help to us--thank you!

I've been trying out the new MSDNS provider, and accidentally ran into an issue. If `pssession` is configured in creds.json, the Get-Zones command will only return domains--not records. 

Expected behavior (using the old ACTIVEDIRECTORY_PS provider): 
```
PS C:\github\dnscontrol> .\dnscontrol.exe get-zones --out draft.js activedir ACTIVEDIRECTORY_PS example.org
PS C:\github\dnscontrol> cat draft.js
$ORIGIN example.org.
$TTL 3600
record1      IN A     192.168.1.1
record2      IN A     192.168.1.2
record3      IN A     192.168.1.3
```

Actual behavior (using MSDNS):
```
PS C:\github\dnscontrol> .\dnscontrol.exe get-zones --out draft.js msdns MSDNS example.org
PS C:\github\dnscontrol> cat draft.js
$ORIGIN example.org.
$TTL 3600
```

I *think* that the issue occurs in the ` generatePSZoneDump` function in [powershell.go](https://github.com/StackExchange/dnscontrol/blob/master/providers/msdns/powershell.go#L132) because the output of `Get-DnsServerResourceRecord` is echo'd to a temp file on the remote machine, instead of on the machine running dnscontrol.

A possible solution would be use the stdout directly from the `generatePSZoneDump` command. I quickly tested this and it does work in both the local and remote configurations. It is substantially slower however (~5 seconds vs ~25 seconds for a zone with 100 records). 

(Relatedly, [Line 103](https://github.com/StackExchange/dnscontrol/blob/master/providers/msdns/powershell.go#L103) calls for the stdout to be displayed if not empty, but it references the stderr variable).

Another solution could be to copy the file from the remote computer to the local computer which I suspect would be much quicker. However, I'm not sure how best to achieve that? It looks like copy-item supports a `From-Session` variable, but I don't see a way to use that with the go-powershell module. I don't really have any experience with Go however, so it could be that I'm missing an obvious solution/fix. 

Anyways, hopefully this helps! If there's any other information you need, or anything you'd like me to try please don't hesitatet to ask. Really appreciate all the work. Thanks!

Cheers,
Al

**Comment by tlimoncelli** [comment]
Ah, good catch!  My test rig is a single VM and missed that bug.  Maybe I should list the pssession feature as "beta". (well, the whole provider is very beta still).

`~5 seconds vs ~25 seconds for a zone with 100 records`:  Yes, that is significant.  I originally used stdout but found some zones were taking 3 minutes and that was unacceptable, especially when writing to a file was less than a second. The "go tests" mechanism kills a test that runs over 10 minutes and after three or four 3m powershell commands, it was easy to hit that limit.

I think the easiest way to fix this is to return to using stdout, but fix the timing problem. Any idea why it might be so slow?

**Comment by areynolds77** [comment]
I *think* the issue is with the go-powershell module. I added a timer around `psh.shell.Execute(genneratePSZoneDump(..))` and it's taking about 10-15 seconds when the `generatePSZoneDump` function is set to output to stdout instead of a file--this happens regardless of whether you're in a remote session. 

Executing the powershell command directly takes about 2-3 seconds--even across a remote session. I'll try and look into this some more and see if I can figure out what's going on, or figure out a way to remotely access the file.

**Comment by tlimoncelli** [comment]
Is there any chance this is a Unicode issue?  I know it sounds weird but
years ago we faced a similar issue and the benchmarks all changed if we
were sending utf16 vs utf8.   --
Sent from Gmail Mobile

**Comment by tlimoncelli** [comment]
The issue mentioned in the title of this ticket is something that is going to take a while to fix. In the meanwhile, I've marked the feature as not working in the documentation.

**Comment by tlimoncelli** [comment]
Is setting "dnsserver" in creds.json sufficient for you?

**Comment by split-and-join** [comment]
@areynolds77 the provider was recently updated for pssessions in PR #1140

**Comment by tlimoncelli** [comment]
@areynolds77: We just merged PR #1140 which should fix this.  Could you give it a try?

**Comment by tlimoncelli** [comment]
Friendly ping?

**Comment by tlimoncelli** [comment]
I'm going to assume this is fixed. If not, please re-open this ticket.
