### ISSUE TITLE
release 3.5.1 does not exist anymore

### ISSUE THREAD

**Issue by chenrui333** [StackExchange/dnscontrol#1011]
👋  it looks like the release 3.5.1 is gone? Raise this issue to confirm it. Thanks!

---

relates to https://github.com/Homebrew/homebrew-core/pull/67761

**Comment by tlimoncelli** [comment]
I recalled it.  It wasn't ready.

**Comment by chenrui333** [comment]
OK, thanks for confirming it.

**Comment by chenrui333** [comment]
It would be great that the releases can be automated and immutable. :)

**Comment by tlimoncelli** [comment]
I agree!  Ironically, while trying to automate relates and make them
immutable, I accidentally created that tag! Hopefully we'll have that
automated soon.
