### ISSUE TITLE
executing javascript in dnsconfig.js: Error: ReferenceError: 'NNAMESERVER' is not defined

### ISSUE THREAD

**Issue by Knight1** [StackExchange/dnscontrol#1013]
Huhu!

I tried out the Nameserver Monitoring. But the only thing I get is

```
executing javascript in dnsconfig.js: Error: ReferenceError: 'NNAMESERVER' is not defined
```

The only reference for "NNAMESERVER" is in the documentation but i can not find any code for it.

**Comment by tlimoncelli** [comment]
Hmm... that's odd!

Is there a chance your dnsconfig.js refers to NNAMESERVER instead of NAMESERVER?

**Comment by Knight1** [comment]
Sure!

The documentation tells me to do it... But it sound like the documentation is wrong. 

https://github.com/StackExchange/dnscontrol/blob/678540cfdd109223c9dc213feb34a6d4870453bd/docs/_providers/internetbs.md#L33

https://github.com/StackExchange/dnscontrol/blob/678540cfdd109223c9dc213feb34a6d4870453bd/docs/_providers/doh.md#L34

**Comment by tlimoncelli** [comment]
Well that’s an embarrassing typo!

Please use NAMESERVER.   I’ll correct the docs tomorrow.
-- 
Sent from Gmail Mobile

**Comment by tlimoncelli** [comment]
https://github.com/StackExchange/dnscontrol/pull/1014
