### ISSUE TITLE
Helper for Microsoft 365

### ISSUE THREAD

**Issue by juliusrickert** [StackExchange/dnscontrol#1023]
I think that a helper that automatically configures domains to work with Microsoft 365 would be beneficial to a lot of people.

But I am not sure whether this is an overly specific helper for a single product. Do you think this would fit the goal of the project?

I have written a preliminary version of a helper for this, but struggle to find any information on the algorithm that generates the `domainGUID` from domains with dashes in them.

**Comment by tlimoncelli** [comment]
I'm not sure what O365 requires, but I'm open to including a helper function either in helpers.js or in the docs.

**Comment by tlimoncelli** [comment]
P.S. If you show me what you have so far, I'd be glad to help.

**Comment by tlimoncelli** [comment]
Neat!

here are my thoughts:

* domainGUID: It is reasonable to let the user specify it.  If the algorithm is discovered in the future we can use it then.
* domain verification TXT record: I'm fine leaving it out.  Google only checks it once, then you can delete it.  I don't know if Microsoft is similar.
* SPF: Leave it out.  Every company does it differently.  You can't please everyone, so make it separate.

I'll leave it up to you if you would prefer to put this in your own Git repo or add it to dnscontrol's repo.

**Comment by tlimoncelli** [comment]
If your version is stable, I'd be glad to add this to the next release. It needs documentation.

**Comment by juliusrickert** [comment]
I think it's reasonably stable. I'll have to see what I can do.

But I'm also implementing a provider (http.net) and the exam period is starting soon 😄

**Comment by tlimoncelli** [comment]
Exams are more important than open source projects!  I promise!

**Comment by tlimoncelli** [comment]
@juliusrickert Could you submit a PR to add this to pkg/js/helpers.js ?

Thanks!

**Comment by juliusrickert** [comment]
> @juliusrickert Could you submit a PR to add this to pkg/js/helpers.js ?

I've started preparing a PR.

Just noticing that there's no way to set TTLs in [my implementation](https://github.com/StackExchange/dnscontrol/issues/1023#issuecomment-764742232). I think they should be customisable but I'm not sure how we could add it elegantly.
