### ISSUE TITLE
Error "Punycode rtype CF_TEMP_REDIRECT unimplemented"

### ISSUE THREAD

**Issue by mderriey** [StackExchange/dnscontrol#1024]
We encounter this error when deploying our DNS infrastructure.

<details>
<summary>Expand to see the full stacktrace</summary>

```
******************** Domain: <redacted>
----- Getting nameservers from: cloudflare.com
----- DNS Provider: cloudflare.com...panic: Punycode rtype CF_TEMP_REDIRECT unimplemented

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/models.(*DomainConfig).Punycode(0xc0003cd930, 0xc0005b1868, 0x4d25f5)
    /go/src/github.com/StackExchange/dnscontrol/models/domain.go:87 +0x508
github.com/StackExchange/dnscontrol/v3/providers/cloudflare.(*cloudflareProvider).GetDomainCorrections(0xc001076e60, 0xc0003cd930, 0xe, 0xc0003cd900, 0x1, 0x0, 0x0)
    /go/src/github.com/StackExchange/dnscontrol/providers/cloudflare/cloudflareProvider.go:152 +0x43
github.com/StackExchange/dnscontrol/v3/commands.run(0x147904d, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:135 +0x3d4
github.com/StackExchange/dnscontrol/v3/commands.Preview(...)
    /go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:87
github.com/StackExchange/dnscontrol/v3/commands.glob..func6.1(0xc0003dec80, 0xc, 0x10)
    /go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x9c
github.com/urfave/cli/v2.(*Command).Run(0xc00011d680, 0xc0003de8c0, 0x0, 0x0)
    /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc0002bcea0, 0x17ef600, 0xc000038018, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
    /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
    /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/StackExchange/dnscontrol/v3/commands.Run(0xc0001008a0, 0x5e, 0xb)
    /go/src/github.com/StackExchange/dnscontrol/commands/commands.go:65 +0x2a2
main.main()
    /go/src/github.com/StackExchange/dnscontrol/main.go:35 +0x11c
```
</details>

We run our release on a schedule every 12 hours in Docker using the `latest` tag of the `stackexchange:dnscontrol` image.

Deploying the same commit failed when it started using a new image:

- Last passing release used the `859df8541626e80bdc14b24aad96fcd9283c327b2a3ae6d6ab8f44d2c984d7a8` tag which, interestingly, I can't find on Docker Hub, see <https://hub.docker.com/r/stackexchange/dnscontrol/tags?page=1&ordering=last_updated>.
- The first failing release used the [`f969a49f15e7cf76e19b10ab7bd0ba9fe27888cbbb69f8ebca6c8a233456313f`](https://hub.docker.com/layers/stackexchange/dnscontrol/latest/images/sha256-f969a49f15e7cf76e19b10ab7bd0ba9fe27888cbbb69f8ebca6c8a233456313f?context=explore) tag.

The image timestamp makes me think it might be related to https://github.com/StackExchange/dnscontrol/pull/1019.

Please let me know if you need any more information.
Cheers 🙏

**Comment by tlimoncelli** [comment]
The punycode bug was fixed in 0893f74895213a0e35b4f54e868280c3bd0bb193.

I'm not sure what happened to `859df8541626e80bdc14b24aad96fcd9283c327b2a3ae6d6ab8f44d2c984d7a8` but it may have been the release that I pushed accidentally and cancelled.

I'll do an official release in a week or so.  In the meanwhile, please run from `master` if you need Punycode support.
