### ISSUE TITLE
panic: short (mydomain.com) is not supposed to end with a dot

### ISSUE THREAD

**Issue by redochka** [StackExchange/dnscontrol#1039]
Trying to add mailjet DKIM. They ask to add the following txt record:

```
key: mailjet._domainkey.mydomain.com.
value: k=rsa; p=MIGfMA0GCSq...etc...
```

So in my config file I have something like:

```
TXT('mailjet._domainkey.mydomain.com.', 'k=rsa; p=MIGfMA0GCSq...etc...'),
```

But I am getting this error where running the preview:

```
panic: short (mydomain.com) is not supposed to end with a dot
```

**Comment by tlimoncelli** [comment]
Interesting.  That should give an error, not a panic.   What's the D() line for this?  It should be mydomain.com (without the dot).

**Comment by redochka** [comment]
Yes as shown below:

```
D('domain.com', registrar, DnsProvider(cloudflare), domainConfig)
```

**Comment by tlimoncelli** [comment]
The TXT record is in a D() that doesn't match:  mydomain.com vs domain.com.

This this:

    TXT('mailjet._domainkey.domain.com.', 'k=rsa; p=MIGfMA0GCSq...etc...'),

Or just:

    TXT('mailjet._domainkey', 'k=rsa; p=MIGfMA0GCSq...etc...'),

While investigating this I did find some bugs in how this is handled.  I've started a https://github.com/StackExchange/dnscontrol/pull/1040 to fix them.

**Comment by tlimoncelli** [comment]
I've merged this change in to master.  Please confirm if that fixes the issue for you.

**Comment by redochka** [comment]
OMG, I wrote a mistake, it is mydomain.com (forget about domain.com). Here is what I have:

```
D('mydomain.com', registrar, DnsProvider(cloudflare), domainConfig)
```

**Comment by tlimoncelli** [comment]
I thought that might be the case.

Anyway...

The code at master should fix this.  As a workaround, just remove the domain from the TXT() record:

    TXT('mailjet._domainkey', 'k=rsa; p=MIGfMA0GCSq...etc...'),

**Comment by tlimoncelli** [comment]
I'm taking the liberty of closing this ticket.  If you need further assistance please re-open it.
