### ISSUE TITLE
D_EXTEND applies DEFAULTS

### ISSUE THREAD

**Issue by juliusrickert** [StackExchange/dnscontrol#1042]
The `D_EXTEND` method applies the locally valid `DEFAULTS`. This prevents `D_EXTEND` from being used in combination with records in `DEFAULTS` if the records sets are not disjoint.

Is this behaviour intended?

Minimal example:
```js
DEFAULTS(
  MX('@', 0, '.')
);

D('example.com', REG_NONE);

// Modified defaults with disjoint record set: no problem
DEFAULTS(
  MX('@', 1, '.')
);

D_EXTEND('example.com');

// Back to the original set: error
DEFAULTS(
  MX('@', 0, '.')
);

D_EXTEND('example.com');
```

It throws this error: `ERROR: exact duplicate record found: example.com MX 0 . ttl=300`

**Comment by tlimoncelli** [comment]
Interesting!   I never expected anyone to change DEFAULTS or to use DEFAULTS with records, just metadata.

**Comment by tlimoncelli** [comment]
What behavior would you expect in this situation?  My hunch is that DEFAULTS should apply to D but not D_EXTEND.  In othere words, it should apply to a domain once.

**Comment by juliusrickert** [comment]
> it should apply to a domain once

That's what I expected.

**Comment by patschi** [comment]
I asked Julian to open the issue to discuss if that's something being supported. Based on the description of the [docs](https://stackexchange.github.io/dnscontrol/js#DEFAULTS) I think this should bee indeed something what should be supported.

As the defaults should only applied to `D()` and not `D_EXTEND()`, the fix might be simply removing those lines:
https://github.com/StackExchange/dnscontrol/blob/6efedd689daf7a009067a649891e3a1715c14495/pkg/js/helpers.js#L113-L115

Haven't considered this scenario when building `D_EXTEND()`...

**Comment by tlimoncelli** [comment]
I think we're all in alignment: (1)  `DEFAULTS` should apply to `D`, not `D_EXTEND`.

Removing those lines should be sufficient.  I don't currently use D_EXTEND() at work or at home, so please let me know if that breaks for you.

**Comment by juliusrickert** [comment]
> As the defaults should only applied to `D()` and not `D_EXTEND()`, the fix might be simply removing those lines:
> https://github.com/StackExchange/dnscontrol/blob/6efedd689daf7a009067a649891e3a1715c14495/pkg/js/helpers.js#L113-L115

This seems reasonable. I tried this and it works for me™.

**Comment by tlimoncelli** [comment]
Oops!  I forgot to merge this!  I'll get to this today.
