### ISSUE TITLE
Add "infrastructure-as-code" to topics

### ISSUE THREAD

**Issue by juliusrickert** [StackExchange/dnscontrol#1049]
This would surface the project to people who are interested in managing DNS as code on the [infrastructure-as-code](https://github.com/topics/infrastructure-as-code) topic, along [OctoDNS](https://github.com/octodns/octodns).

**Comment by tlimoncelli** [comment]
Done.  Please verify.

**Comment by juliusrickert** [comment]
Perfect. It is already listed on the [infrastructure-as-code](https://github.com/topics/infrastructure-as-code) topic.
