### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by roachmd** [StackExchange/dnscontrol#105]
## TEST JS.
var registrar = NewRegistrar("none","NONE");
var r53 = NewDnsProvider("r53", "ROUTE53");

D("test.net", registrar, DnsProvider(r53),
                A("test","10.160.40.22")
);

## Running: 
dnscontrol -providers all -js ../config/test_com.js -creds ../config/creds.js -bindtree ../zones

## RESULTS
Initialized 1 registrars and 1 dns service providers.
******************** Domain: test.net
----- Getting nameservers from: r53
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x15aef1b]

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/route53.(*route53Provider).GetNameservers(0xc420295160, 0xc420294b60, 0x10, 0x3, 0xc42017bca8, 0x1, 0x0, 0x0)
	/gocode/src/github.com/StackExchange/dnscontrol/providers/route53/route53Provider.go:102 +0x13b
github.com/StackExchange/dnscontrol/nameservers.DetermineNameservers(0xc42001e310, 0x0, 0xc42036f7a0, 0x1, 0x1, 0x2e, 0x0, 0x0)
	gocode/src/github.com/StackExchange/dnscontrol/nameservers/nameservers.go:29 +0x239
main.main()
	gocode/src/github.com/StackExchange/dnscontrol/main.go:161 +0x91c

**Comment by roachmd** [comment]
Recompiled with debug mode on.

----- Getting nameservers from: r53
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x15aef1b]

goroutine 1 [running]:
panic(0x164c6c0, 0x1ab7140)
	/usr/local/opt/go/libexec/src/runtime/panic.go:531 +0x1cf fp=0xc420241648 sp=0xc4202415b0
runtime.panicmem()
	/usr/local/opt/go/libexec/src/runtime/panic.go:63 +0x5e fp=0xc420241668 sp=0xc420241648
runtime.sigpanic()
	/usr/local/opt/go/libexec/src/runtime/signal_unix.go:290 +0x29f fp=0xc4202416b8 sp=0xc420241668
github.com/StackExchange/dnscontrol/providers/route53.(*route53Provider).GetNameservers(0xc4202e7ed0, 0xc4202e7600, 0x10, 0x3, 0xc42008ba68, 0x1, 0x0, 0x0)
	/gocode/src/github.com/StackExchange/dnscontrol/providers/route53/route53Provider.go:102 +0x13b fp=0xc420241778 sp=0xc4202416b8
github.com/StackExchange/dnscontrol/nameservers.DetermineNameservers(0xc42031c3f0, 0x0, 0xc420053830, 0x1, 0x1, 0x2e, 0x0, 0x0)
	/gocode/src/github.com/StackExchange/dnscontrol/nameservers/nameservers.go:29 +0x239 fp=0xc4202418c0 sp=0xc420241778
main.main()
	gocode/src/github.com/StackExchange/dnscontrol/main.go:161 +0x91c fp=0xc420241f88 sp=0xc4202418c0
runtime.main()
	/usr/local/opt/go/libexec/src/runtime/proc.go:185 +0x20a fp=0xc420241fe0 sp=0xc420241f88
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420241fe8 sp=0xc420241fe0

**Comment by tlimoncelli** [comment]
Sadly I haven't been able to reproduce this.

- What version of Go are you using?
- Does your creds.json file pass validation?  (Try running `python -m json.tool creds.json`)
- Can you share your creds.json (after stripping any secrets, of course)

**Comment by captncraig** [comment]
Looks to me like something unexcpected from the api about this domain. Any chance it's a private hosted zone? On an airplane, so I'm not very useful, but I'd like to see the API output. I can get some code for you to try in a bit.

**Comment by captncraig** [comment]
His credentials are good, or it would not have gotten as far as it has.

**Comment by roachmd** [comment]
## go version
go version go1.8.1 darwin/amd64

## python -m json.tool ./creds.js 
{
    "r53": {
        "KeyId": "HIDDEN",
        "SecretKey": "HIDDEN"
    }
}

**Comment by mathieuherbert** [comment]
Hi, 
When I wrote #93 I had an issue like that. So I added  [this](https://github.com/StackExchange/dnscontrol/pull/93/files#diff-6e91ccc7a8001b516752445175e22a32R106)
The AWS API does not provide automatically `z.DelegationSet`, so I added a condition on this attribute.
Can you test with the new stable code  ?,  (the #93 has been merged)

**Comment by roachmd** [comment]
@mathieuherbert , I will give this a try and let you know

**Comment by roachmd** [comment]
@mathieuherbert This works now. Created a new Private zone on Route53 and tested.

SUCCESS!

**Comment by roachmd** [comment]
I'm closing this issue

**Comment by tlimoncelli** [comment]
Go team!
