### ISSUE TITLE
Reenginer TXT record handling

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1052]
TXT records should work as follows:

The user specifies either a string or a list of strings:

    TXT("label", "124abc"),
    TXT("another", ["one", "two", "three"]),

The provider either works, warns, or errors:

Warnings: (printed by check/preview/push)
* String length > 255 octets: Will be split along 255-octet boundaries.
* Provider does not support multiple strings.  Strings will be joined then re-split along 255-octet boundaries.

Errors: (check/preview/push will exit with error)
* Provider does not support TXT strings longer than 255 octets.
* Provider does not support multiple TXT strings. Attempt to join failed due to total length > 255 octets.

The warnings/errors must be output during check/preview/push.  Therefore, checking will be done by the provider module, not by doing the API call and seeing if it fails.

Providers that mishandle quoting and are unable to (for example) support a txt record with an embedded quote, should warn about this in check/preview/push but may rely on the actual API call to error.  Rationale: Sometimes these bugs get fixed at the server end.

Open issue: Should there be a way to not print the warnings?   (Meta flag such as TXT_NO_WARNING?  AUTOSPLIT?)

**Comment by juliusrickert** [comment]
> Open issue: Should there be a way to not print the warnings? (Meta flag such as TXT_NO_WARNING? AUTOSPLIT?)

I think there should definitely be a way to suppress the warnings, one for each type of adjustment, maybe another one to suppress all (could be "created" by the users by forming an array?).

The suppression should work on a per-record and per-domain/default basis.

**Comment by tlimoncelli** [comment]
Here's a thought: "The right way" to remove the warnings is to split the string at the appropriate boundaries so that the warning isn't needed.   Can we make that easier rather than invent some general "warning suppression system"?

We could provide functions that make doing that easy.  Something like:

    TXT("label", LONGTXT("my very long string")),
    TXT("other", REPACK255("my", "list", "which", "should", "be", "re-split at 255-octet intervals"),

This way (1) the warning goes away, (2) the user doesn't have to work too hard (splitting a string manually is a pita), and (3) if they change provider, the right thing will happen at that provider.

I don't like the naes LONGTXT andd REPACK255 but I'm sure we can come up with something better.

**Comment by juliusrickert** [comment]
From my understanding, `LONGTXT` would split the string into (at most) 255-octet chunks?
At least for `LONGTXT`, it is too verbose, in my opinion. It is the behaviour I am expecting.

Are these functions just indications to the providers?
I would leave splitting the strings, or not, to the provider.

I am trying to think of a use case for `REPACK255`. Is there a case in which the strings should be split, but do not have to be?

**Comment by tlimoncelli** [comment]
The use-case for REPACK255 would be a DSP that only takes one long string and splits it up for the user.  In this case, the .Target would be the joined string and the .TxtStrings would be an array of 255-octet chunks.

The provider would see that these two are equivalent: It will send the long string to the API, which will split it into 255-octet chunks, thus would not output any warnings.

Without REPACK255, it would have to output a warning like, "This provider doesn't support variable-length sub-strings. I'll join this to be one big string and let the provider do the splitting along 255-octet boundaries. If this is ok, use REPACK255("string") to remove this warning. If this isn't ok, find a different DSP."

**Comment by juliusrickert** [comment]
I understood the functionality you expressed with `REPACK255`.

I am just asking myself whether there is any use case in which it would be beneficial to have that function instead of calling `.join('')` on a list of strings. I could not think of any.
That use case would need to be okay with the strings being concatenated but "prefer" them to be split, right?
And in that case, you would not need to have the strings separate anyways.

I think this should be an error if my reasoning is correct.
Then, only one type of warning would remain.

Regarding `CanUseTXTMulti`: how is that going to fit with the re-engineered `TXT` function?

**Comment by tlimoncelli** [comment]
Good point about REPACK255.  Maybe it isn't needed?  I guess what is needed is a way for users to acknowledge that their strings are going to be joined and re-split.

CanUseTXTMulti: I don't think I'll be sure until I get into the code.  Ideally I'd like to eliminate it.  However I have a hunch it might be repurposed to mean "provider supports TXT records that aren't the usually single string less than 255 octets".

**Comment by juliusrickert** [comment]
> I guess what is needed is a way for users to acknowledge that their strings are going to be joined and re-split

I would argue that it is somehow best practice to join strings when they do not need to be separate. That is why I would be fine with throwing an error for providers that do not support strings of custom length.

**Comment by tlimoncelli** [comment]
I agree.  That situation should be an error, not a warning.

I'd like the error message to recommend a solution so that people aren't left high and dry.  I'm thinking of including a URL to the TXT() page which could list recommendations.

**Comment by tlimoncelli** [comment]
Some thoughts:

1. No warnings, only errors.  Handling both makes the code complex and doesn't add value.

2. I'm going to generalize this.  Each provider will have a function called `ValidateRecords([].models.RecordConfig) []error` that reports errors about records it can't handle. Initial implementation will just report TXT records.

**Comment by tlimoncelli** [comment]
Updating docs too: https://github.com/StackExchange/dnscontrol/pull/1083
