### ISSUE TITLE
Provider request: Infoblox/NIOS

### ISSUE THREAD

**Issue by DonEstefan** [StackExchange/dnscontrol#1077]
Hi,

I'd love to see support for [Infoblox/NIOS Appliances](https://www.infoblox.com/products/dns/) in dnscontrol. For Details see

- [Python WebAPI Client](https://github.com/infobloxopen/infoblox-client) (seems to support only a subset of the functionality of the webapi)
- [Go Client](https://github.com/infobloxopen/infoblox-go-client) (seems to support only a tiny subset of the functionality of the webapi)
- WebAPI Documentation [here](https://www.infoblox.com/wp-content/uploads/infoblox-deployment-infoblox-rest-api.pdf) or [here](https://github.com/infobloxopen/infoblox-swagger-wapi)

**Comment by tlimoncelli** [comment]
I hear good things a bout Infoblox!  Would you be interested in writing this provider?  It's pretty easy if you can do 2 things: Download the records of a zone, change/add/delete a record in a zone.  DnsControl does the rest.

**Comment by donestefan** [comment]
Sorry, but I'm not a programmer. I do some simple scripting but have no experience with golang.

**Comment by tlimoncelli** [comment]
Thank you for requesting this provider!

I've tagged this issue as a provider-request.  It will (soon) be listed as a    "requested provider" on the provider list web page:
https://docs.dnscontrol.org/service-providers/providers

I will now close the issue.  I know that's a bit confusing, but it will remain  on the "requested provider" list.

If someone would like to volunteer to implement this, please re-open this issue and add the tag `has-pr`.

We encourage you to try adding this provider yourself.  We've tried to make the process as friendly as possible.  Many people have reported that adding a       provider was their first experience writing Go.  The process is documented here:
https://docs.dnscontrol.org/developer-info/writing-providers
If you need assistance, please speak up in this issue and someone will get back to you ASAP.
