### ISSUE TITLE
Gandi provider should validate TTL max 2592000

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#108]
Gandi does not permit TTLs larger than 30 days.  We should detect this problem on validation, not during "push":

    FAILURE! error: "Error on object : OBJECT_DNS_RECORD (CAUSE_BADPARAMETER) [2629800 is greater than maximum value 2592000]" code: 581137

**Comment by captncraig** [comment]
Should we validate that as a maximum throughout our system, just for sanity?

**Comment by tlimoncelli** [comment]
Short answer: yes.

Longer answer:  We could just declare that one of the system's "opinions" is that TTLs should never be more than 30 days, then implement it as a system-wide validation. That certainly make implementation easier. If anyone ever complains, they could show a business need and we can deal with it then.
