### ISSUE TITLE
D_EXTEND using subdomains behaves incorrectly with IDNs

### ISSUE THREAD

**Issue by juliusrickert** [StackExchange/dnscontrol#1092]
I will get straight to the root cause: Otto's `String.substr()` method behaves incorrectly when used with multi-byte unicode characters, as described in [this issue](https://github.com/robertkrimen/otto/issues/399).

This causes missing characters at the end of the subdomain when used with IDNs.

Expected behaviour:
```js
'u.de'.substr(0,3) // u.d
'ü.de'.substr(0,3) // ü.d
```

Otto's behaviour:
```js
'u.de'.substr(0,3) // u.d
'ü.de'.substr(0,3) // ü.
```

This impacts [subdomains with multi-byte characters](https://github.com/StackExchange/dnscontrol/blob/49b065ec4fe8507500f72b5b92e1f449ed1f2665/pkg/js/helpers.js#L112) and [zones with multi-byte characters](https://github.com/StackExchange/dnscontrol/blob/49b065ec4fe8507500f72b5b92e1f449ed1f2665/pkg/js/helpers.js#L130).

Test code for subdomain with multi-byte characters:
```js
D('example.com', REG_NONE);
D_EXTEND('düsseldorf.example.com'); // extends düsseldor.example.com
```

Test code for zones with multi-byte characters:
```js
D('düsseldorf.example.com', REG_NONE);
D_EXTEND('subdomain.düsseldorf.example.com'); // subdomain.düsseldorf.example.com was not declared yet and therefore cannot be updated. Use D() before.
```

**Comment by tlimoncelli** [comment]
I think this PR fixes that: https://github.com/robertkrimen/otto/pull/361/files

**Comment by juliusrickert** [comment]
Open since 1.5 years. I have asked the maintainer to take a look at this.

**Comment by tlimoncelli** [comment]
I think this isn't going to be fixed unless someone forks the otto project and starts applying the various PRs that have been submitted.  Sadly that's not something I can do.

**Comment by juliusrickert** [comment]
@tlimoncelli See #1302.
