### ISSUE TITLE
Unable to create records in Route53 - "limit of 1000 exceeded"

### ISSUE THREAD

**Issue by jmpenalosa** [StackExchange/dnscontrol#1114]
Hi,

I got a strange error when adding zones to Route53 using DNSControl.

`FAILURE! InvalidChangeBatch: [Number of records limit of 1000 exceeded.]
        status code: 400, request id: 2c25e708-a75d-4391-b56d-66c286545e29`

I know I only have 780 records, so I am unable to make sense of this error.

I used the same script, same records in Google Cloud DNS and I did not get this issue.

I just need to make Route53 a backup DNS Provider in the event of complete Google Cloud DNS failure.

I reached out to AWS support and got this response below:

Thank you for contacting us. Please see a summary of my investigation below:
- From error output that you kindly shared with us: 
  InvalidChangeBatch: This exception contains a list of messages that might contain one or more error messages. Each error message indicates one error in the change batch.

Looks like there's been hitting a limit on ChangeResourceRecordSets[1]

From AWS Docs:
"A request cannot contain more than 1,000 ResourceRecord elements. When the value of the Action element is UPSERT, each ResourceRecord element is counted twice." [2]

UPSERT: If a resource record set does not already exist, AWS creates it. If a resource set does exist, Route 53 updates it with the values in the request.

As you stated on your previous comment, records do not reach 1000, could be that DNSControl is using UPSERT in the value of action in the request that is making counted twice and reaching this limit.

[1] https://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html
[2] https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html

Looking forward to your response,
Thanks

**Comment by jmpenalosa** [comment]
Hi @tlimoncelli 

Thanks for the tips.

I will try to do the segregated deployment. See if this helps complete the task at hand.

I will try to do it as standalone for now, not using the GCP Cloud Build/Repo Triggers that I currently have in place on GCP.

Will post results here as soon as possible.

**Comment by tlimoncelli** [comment]
Hope it was successful!

**Comment by jmpenalosa** [comment]
Hi @tlimoncelli 

It did work. Tried it just now. Apologies it took me a while, I was caught up with something else.

Thanks for your kind help!
