### ISSUE TITLE
Hostingde provider overrides TTL of NS records

### ISSUE THREAD

**Issue by maxbraeutigam** [StackExchange/dnscontrol#1121]
Hi @membero and @juliusrickert,
Thanks a lot for writing the `hostingde` provider! If I am using the `hostingde` provider, it overrides the TTL of the NS records to 300s although I am explicitly setting the `DefaultTTL` to something different.

```bash
$ dnscontrol preview
MODIFY NS my.eu: (ns2.hosting.de. ttl=3600) -> (ns2.hosting.de. ttl=300)
MODIFY NS my.eu: (ns1.hosting.de. ttl=3600) -> (ns1.hosting.de. ttl=300)
MODIFY NS my.eu: (ns3.hosting.de. ttl=3600) -> (ns3.hosting.de. ttl=300)
MODIFY A my.eu: (85.13.X.X ttl=3600) -> (85.13.X.X ttl=14400)
```

Configuration looks like

```js
D(
  "my.eu",
  REG_NONE,
  DnsProvider(HOSTINGDE),
  DefaultTTL("4h"),
  A("@", ALLINCL_IP)
);
```
Any help is highly appreciated.
Cheers,
Max

**Comment by juliusrickert** [comment]
Hey @maxbraeutigam,

you can use `NAMESERVER_TTL` to set the default TTL for nameservers.

But I do not know whether `DefaultTTL` should or should not apply to nameservers.
That is something @tlimoncelli will be able to tell you.

**Comment by maxbraeutigam** [comment]
Hi @juliusrickert, thank you very much. Indeed, it’s working. I am very sorry for the confusion. The name `DefaultTTL` was a bit misleading here. [`NAMESERVER_TTL` solves the problem.](https://stackexchange.github.io/dnscontrol/js#NAMESERVER_TTL)
