### ISSUE TITLE
R53_ALIAS to Cloudfront Distribution - InvalidChangeBatch

### ISSUE THREAD

**Issue by DrewTurner** [StackExchange/dnscontrol#1128]
DNSControl-Linux version 3.8.0

When adding an A record for R53_ALIAS to a cloudfront distribution like so:

`R53_ALIAS('@', 'A', '38d2dc74ceaa.cloudfront.net', R53_ZONE('Z2FDTNDATAQYW2'))`

I receive the following error:
```
MODIFY R53_ALIAS example.com: (38d2dc74ceaa.cloudfront.net. atype=A zone_id=Z2FDTNDATAQYW2 ttl=300 type=A zone_id=Z2FDTNDATAQYW2) -> (38d2dc74ceaa.cloudfront.net atype=A zone_id=Z2FDTNDATAQYW2 ttl=300 type=A zone_id=Z2FDTNDATAQYW2)
FAILURE! InvalidChangeBatch: [The request contains an invalid set of changes for a resource record set 'A example.com.']
```
The docs indicate I need the cloudfront distribution to include the alternate domain name that matches the record and that is present.

Do I have the syntax of that R53 alias correct?

**Comment by tlimoncelli** [comment]
CC: @masterzen @maclennann

**Comment by tlimoncelli** [comment]
Should there be a `.` at the end of `'38d2dc74ceaa.cloudfront.net.'`  ?

I ask because when I look at the error message (and insert line breaks to make it easier to examine) I see one is missing:

```
MODIFY R53_ALIAS example.com: 
(38d2dc74ceaa.cloudfront.net. atype=A zone_id=Z2FDTNDATAQYW2 ttl=300 type=A zone_id=Z2FDTNDATAQYW2) -> (38d2dc74ceaa.cloudfront.net atype=A zone_id=Z2FDTNDATAQYW2 ttl=300 type=A zone_id=Z2FDTNDATAQYW2)
```

**Comment by tlimoncelli** [comment]
Note to self: If adding the `.` fixes this, we should update `docs/_functions/domain/R53_ALIAS.md`'s examples (which don't have trailing dots) and document that this error sometimes means there is a missing dot.

**Comment by DrewTurner** [comment]
@tlimoncelli - Tom thank you for your quick feedback.  Adding the . as the standard for these does indeed fix the issue.
