### ISSUE TITLE
PowerDNS: credentials for integration test

### ISSUE THREAD

**Issue by jpbede** [StackExchange/dnscontrol#1137]
@tlimoncelli is there a way to send you credentials for the integration test of PowerDNS. 
I've setup a stage PowerDNS server for the integration tests which i already use in my fork.

**Comment by tlimoncelli** [comment]
Sure!  Use https://transfer.secretoverflow.com/u/tlimoncelli to securely send me anything.

**Comment by jpbede** [comment]
Thanks 👍
