### ISSUE TITLE
Long TXT not working with NS1

### ISSUE THREAD

**Issue by kurthockenbury** [StackExchange/dnscontrol#1139]
Similar to #996 and #1003, I would like to see long TXT support for NS1. Testing the API with curl, and later confirmed when talking with NS1 over Zoom today, NS1 falls into the group of providers that accept TXT records >255 characters and autosplit them on their end.

**Comment by tlimoncelli** [comment]
Sadly the maintainer of the NS1 provider is no longer with the project.

I'd be glad to walk you through fixing this.  The code for TXT record handling was recently rewritten and is much cleaner than before.

**Comment by kurthockenbury** [comment]
I may be stepping in over my head, but I can try. I have never coded in golang before. I have followed the instructions, used "go get" and was able to build 3.8.1-dev, so I suppose I am ready to take my first bite of the elephant.

**Comment by kurthockenbury** [comment]
I was going to take a crack at this, but work has now decided on Cloudflare DNS (since we were paying for Cloudflare anyway), so this has dropped off my priority list.

**Comment by norman-zon** [comment]
@tlimoncelli, I was looking into making the NS1 provider work with long TXT records, but found the `TxtNoMultipleStrings` function not to be suitable, as it [also checks for string length](https://github.com/StackExchange/dnscontrol/blob/3405757271b66c7e679b78af74810bedd3e7b50b/pkg/recordaudit/txt.go#L100).
NS1 does not support multiple strings, but supports any length of string, as long as it is only a single string.

How would you want to move forward from here? Implement a `TxtNoMultipleStrings` directly in the `auditrecords.go` file of the provider, omitting the length check? Or would you prefer to make changes to the general implementation in `pkg/recordaudit/txt.go`, so other provider with the same capabilities could use it too?

**Comment by tlimoncelli** [comment]
Hi there!  Thanks for looking into this!

I would love to see this added to `pkg/recordaudit/txt.go`.  I think a few providers will benefit. (In fact, I think some have it in their own `auditrecords.go` file).  `providers/cloudns/auditrecords.go`

In hindsight, each function in txt.go should test exactly one thing. I think `TxtNoMultipleStrings` is the one that tests 2 attributes.

**Comment by tlimoncelli** [comment]
Fixed and shipped!
