### ISSUE TITLE
ClouDNS Support

### ISSUE THREAD

**Issue by tiernano** [StackExchange/dnscontrol#114]
Another provider i seem to have setup is one called [ClouDNS](http://www.cloudns.net). they have an [API](https://www.cloudns.net/wiki/article/42/) which seems to do all the stuff required... Might take a stab at doing this myself, but just adding it here is case anyone else knows anything about it...

**Comment by captncraig** [comment]
Looks interesting. Free tier and an api, so we should be ok. Let me know if you need any help.

**Comment by tlimoncelli** [comment]
I've added this to the [list of requests](https://stackexchange.github.io/dnscontrol/provider-list). If someone would like to volunteer to implement this, please re-open this issue. 

Advice on how to write a provider is documented [here](https://stackexchange.github.io/dnscontrol/writing-providers). Also, speak up in this issue and someone will get back to you asap.
