### ISSUE TITLE
Delete tag 'v999.0.0' from 'stackexchange/dnscontrol' Docker Hub repository

### ISSUE THREAD

**Issue by koenrh** [StackExchange/dnscontrol#1155]
Hey folks! Would it be possible to get the tag [`v999.0.0`](https://hub.docker.com/layers/stackexchange/dnscontrol/v999.0.0/images/sha256-d94bacace7a25256fc08386f636b204bc16eeecef059f04ebab64769babd2f42?context=explore) deleted from the '[stackexchange/dnscontrol](https://hub.docker.com/r/stackexchange/dnscontrol/)' Docker Hub repository? It is messing with some tools like GitHub's Dependabot for automated pull requests to update dependencies. Since the tag is still there, it thinks that `v999.0.0` is the latest version, which means it won't be creating any new pull requests. For example: https://github.com/koenrh/dnscontrol-action/pull/51. Thanks.

See: https://docs.docker.com/docker-hub/repos/#viewing-repository-tags

>To delete a tag, select the corresponding checkbox and select **Delete** from the **Action** drop-down list.

**Comment by tlimoncelli** [comment]
I've deleted v999.0.0 and v777 and a few other tags that looked like tests or mistakes.

**Comment by tlimoncelli** [comment]
Closing (done). Please re-open if it is closed in error.
