### ISSUE TITLE
Route53 DNS Provider NS record default TTL - need none default value

### ISSUE THREAD

**Issue by isindir** [StackExchange/dnscontrol#116]
Is it possible to set none default TTL value for NS records in AWS R53 Provider ?

When I'm trying to manage already existing node `dnscontrol preview` prints following output:
```
#1: MODIFY NS example.com: (ns-1249.awsdns-28.org. 172800) -> (ns-1249.awsdns-28.org. 300)
MODIFY NS example.com: (ns-427.awsdns-53.com. 172800) -> (ns-427.awsdns-53.com. 300)
MODIFY NS exmaple.com: (ns-921.awsdns-51.net. 172800) -> (ns-921.awsdns-51.net. 300)
MODIFY NS example.com: (ns-2012.awsdns-59.co.uk. 172800) -> (ns-2012.awsdns-59.co.uk. 300)
```

I'd like to set NS to TTL which 172800 and can't find out how. Is it possible ? If not, are there plans in implementing this ?

**Comment by isindir** [comment]
Looks like a duplicate:
https://github.com/StackExchange/dnscontrol/issues/99
Will check.

**Comment by captncraig** [comment]
Yeah, just gotta specify `D('example.com',{ns_ttl:172800},...`

Or just put `DEFAULTS({ns_ttl:172800})` somewhere near the top.

**Comment by isindir** [comment]
Thanks
