### ISSUE TITLE
Automatic code review for PR

### ISSUE THREAD

**Issue by jpbede** [StackExchange/dnscontrol#1163]
I'm using more and more [Codacy](https://www.codacy.com/) in my projects for automatic code review. An example: https://app.codacy.com/gh/jpbede/loki-auth-proxy/dashboard. 

Maybe this is something you may consider for pull requests, this would enhance your workflow @tlimoncelli as it may catch some of your code style suggestions.

I'm happy to help there.

**Comment by tlimoncelli** [comment]
I'll try anything once! :-)

**Comment by jpbede** [comment]
Since CodeQL comes with PR #1172, i close this issue
