### ISSUE TITLE
update RPM package information in future releases

### ISSUE THREAD

**Issue by wfu-linuxadmin** [StackExchange/dnscontrol#1168]
For the RPM packages created with each release, the package info such as URL & summary are filled in with generic template information instead of real information.

```
# rpm -p -qi dnscontrol-3.9.0-1.x86_64.rpm 
Name        : dnscontrol
Version     : 3.9.0
Release     : 1
Architecture: x86_64
Group       : default
Size        : 27516928
License     : unknown
Source RPM  : dnscontrol-3.9.0-1.src.rpm
Build Date  : Thu 13 May 2021 12:52:14 PM EDT
Build Host  : 4d4189c1bb8d
Relocations : / 
Packager    : <@4d4189c1bb8d>
Vendor      : @4d4189c1bb8d
URL         : http://example.com/no-uri-given
Summary     : no description given
Description :
no description given
```

As you build new releases, would you consider filling in at least the URL field with https://stackexchange.github.io/dnscontrol/  instead of the invalid example.com URL?

**Comment by tlimoncelli** [comment]
Hi there!

We'd be glad to fix this.   I'll get to this in the next week or so.

Note to self: `dnscontrol/.github/workflows/release.yml`

Tom

**Comment by tlimoncelli** [comment]
CC @atma-stackoverflow
