### ISSUE TITLE
deSEC Provider and Pagination

### ISSUE THREAD

**Issue by tmkis2** [StackExchange/dnscontrol#1177]
Using deSEC will stop working as soon as you reach the 500 domain limit there. Pagination is required to get the whole domain list. @peterthomassen mentioned that the validity of a domain should be checked without getting the whole domain list.
In EnsureDomainExists() the whole domainlist is fetched and then checked against the domain name. Right solution would be to append the domainname to the endpoint and check the return code. 200 = domain exists and 404 domain does not exist.

https://github.com/StackExchange/dnscontrol/blob/master/providers/desec/desecProvider.go#L109

@tlimoncelli or @D3luxee any spare time to fix this? :)

Futhermore the whole domain list is being fetched to check if the token is valid. @peterthomassen suggests to make a simple request for example: GET /api/v1/auth/account/ - this would fetch some account information in which you can check if the Token is valid and also you would get the max number of domains in the reply.

https://github.com/StackExchange/dnscontrol/blob/master/providers/desec/desecProvider.go#L31
https://desec.readthedocs.io/en/latest/auth/account.html#retrieve-account-information

**Comment by tlimoncelli** [comment]
I don't have a deSEC account, so @D3luxee will have to fix this.

**Comment by D3luxee** [comment]
I will take a look at it in July, but do you really have over 500 domains or is this a theoretical issue? :D
I'm just curious.

**Comment by tmkis2** [comment]
I have 499 at deSEC at the moment because I rely heavily on dnscontrol to manage them. My other domains at (mostly at hosting.de) should be transferred over to deSEC which makes a total of ~850 Domains. :)

**Comment by D3luxee** [comment]
I started to work on this and already implemented the token validation using the /auth/account api endpoint.

I've also change the EnsureDomainExists() function to validate each individual domain instead of fetching the whole list. 
This means that dnscontrol will do one api call for each domain configured when ever you run `dnscontrol create-domains`, in your case this will be ~850 api calls which could let us run into the rate limit. 

But thats how dnscontrol works and i don't think we can get around this. (see https://github.com/StackExchange/dnscontrol/blob/master/commands/createDomains.go#L49)

**Comment by tmkis2** [comment]
Thank you very much @D3luxee - great to hear about the progress. Because of the rate limits I already splitted domains in separate directories for all domains starting with 0-9, a, b, .... so there are only a few of them in each dnsconfig.js - using require for shared variables and credentials works fine for me.

**Comment by D3luxee** [comment]
Can you build and test the long_txt branch over here: https://github.com/D3luxee/dnscontrol/tree/long_txt

**Comment by tmkis2** [comment]
> Can you build and test the long_txt branch over here: https://github.com/D3luxee/dnscontrol/tree/long_txt

I did. Create domain worked great but after dnscontrol push I get:

`~/dns/domains/0-9# dnscontrol push
failed fetching domain list (deSEC): Pagination required. You can query up to 500 items at a time (501 total). Please use the `first` page link (see Link header).`

**Comment by tlimoncelli** [comment]
> domains`, in your case this will be ~850 api calls which could let us run into the rate limit.

Would it be possible to handle rate limits here the same way they are handled in `protocol.go`?   It would be excellent if people didn't have to split their config files.  

In `protocol.go` this provider handles rate limits in a very clean way.  If `resp.StatusCode == 429` we know we've hit a rate limit. The code sleeps for 500ms and tries again.  `429` guarantees that the exact same request can be sent again.

**Comment by peterthomassen** [comment]
When a request is throttled, the response will contain a `Retry-After` header stating the number of seconds after which the next request will be allowed. (This is currently not documented, but I'll add it to https://desec.readthedocs.io/en/latest/rate-limits.html later.)

So the preferred time to sleep would be the value of the `Retry-After` header, possible with 500ms subtracted (that may give you an edge when considering latency and you're very close to the limit expiring, but it may also mean that you have to try again).

**Comment by D3luxee** [comment]
> When a request is throttled, the response will contain a `Retry-After` header stating the number of seconds after which the next request will be allowed. (This is currently not documented, but I'll add it to https://desec.readthedocs.io/en/latest/rate-limits.html later.)
> 
> So the preferred time to sleep would be the value of the `Retry-After` header, possibly with 500ms subtracted (that may give you an edge when considering latency and you're very close to the limit expiring, but it may also mean that you have to try again).

Thanks for this information, i think this should be easy to implement.

**Comment by peterthomassen** [comment]
I just checked, and the number given by the header is converted from float to int, so it is already the case that 500ms are subtracted (on average). The best sleeping duration would thus simply be the header's value.

**Comment by D3luxee** [comment]
> domain list

Are you sure that you build the correct branch? The error message you quoted is part of the old code(master branch) not the new one (long_txt).
The error you sent was in the fetchDomainList function which does not exist anymore.

**Comment by D3luxee** [comment]
> > Can you build and test the long_txt branch over here: https://github.com/D3luxee/dnscontrol/tree/long_txt
> 
> I did. Create domain worked great but after dnscontrol push I get:
> 
> `~/dns/domains/0-9# dnscontrol push failed fetching domain list (deSEC): Pagination required. You can query up to 500 items at a time (501 total). Please use the `first` page link (see Link header).`

Are you sure that you build the correct branch? The error message you quoted is part of the old code(master branch) not the new one (long_txt).
The error you sent was in the fetchDomainList function which does not exist anymore.

**Comment by D3luxee** [comment]
> I just checked, and the number given by the header is converted from float to int, so it is already the case that 500ms are subtracted (on average). The best sleeping duration would thus simply be the header's value.

I've implemented this and its working perfectly, this is now part of the PR: #1204

**Comment by tmkis2** [comment]
> > > Can you build and test the long_txt branch over here: https://github.com/D3luxee/dnscontrol/tree/long_txt
> > 
> > 
> > I did. Create domain worked great but after dnscontrol push I get:
> > `~/dns/domains/0-9# dnscontrol push failed fetching domain list (deSEC): Pagination required. You can query up to 500 items at a time (501 total). Please use the `first` page link (see Link header).`
> 
> Are you sure that you build the correct branch? The error message you quoted is part of the old code(master branch) not the new one (long_txt).
> The error you sent was in the fetchDomainList function which does not exist anymore.

my fault! Sorry - it works as expected! Great work! 👍

**Comment by D3luxee** [comment]
> > > > Can you build and test the long_txt branch over here: https://github.com/D3luxee/dnscontrol/tree/long_txt
> > > 
> > > 
> > > I did. Create domain worked great but after dnscontrol push I get:
> > > `~/dns/domains/0-9# dnscontrol push failed fetching domain list (deSEC): Pagination required. You can query up to 500 items at a time (501 total). Please use the `first` page link (see Link header).`
> > 
> > 
> > Are you sure that you build the correct branch? The error message you quoted is part of the old code(master branch) not the new one (long_txt).
> > The error you sent was in the fetchDomainList function which does not exist anymore.
> 
> my fault! Sorry - it works as expected! Great work!

Great, thats good to hear!

**Comment by D3luxee** [comment]
@tlimoncelli this issue was also resolved with #1204 and can be closed.

**Comment by peterthomassen** [comment]
Thinking about it: if you have 2000 domains and query each one's existence individually, you will run into the daily rate limit. I'd thus say this issue should remain open until a better solution is found.

**Comment by tlimoncelli** [comment]
@peterthomassen Good point.  Maybe it would be better for the first instance to download the complete list and store it for future instances to use as a reference.

**Comment by D3luxee** [comment]
@peterthomassen is there any documentation regarding pagination on the domain list?
I could only find pagination for the rrsets https://desec.readthedocs.io/en/latest/dns/rrsets.html?highlight=pagination#pagination

**Comment by peterthomassen** [comment]
Pagination for domains works the same way as for RRsets, so the docs [just reference it](https://desec.readthedocs.io/en/latest/dns/domains.html#listing-domains):
> Up to 500 items are returned at a time. If you have a larger number of domains configured, the use of [Pagination](https://desec.readthedocs.io/en/latest/dns/rrsets.html#pagination) is required.

There is an example implementation [here (Python)](https://github.com/desec-io/desec-tools/blob/master/fetch_zone.py#L30).

**Comment by D3luxee** [comment]
@tmkis2 could you build and test the desec_pagination branch: https://github.com/D3luxee/dnscontrol/tree/desec_pagination
In theory this should work but i couldn't test it with my 3 domains :D 

Please run dnscontrol with "-v" and send me its output if there are any errors 
`dnscontrol -v preview` should be sufficient for the test

**Comment by tmkis2** [comment]
Seems to work great. 👍 

```dnscontrol -v preview
requiring: ../../providers.js (../../providers.js)
requiring: ../../variables.js (../../variables.js)
Header: <https://desec.io/api/v1/domains/?cursor=>; rel="first"
initial endpoint /domains/?cursor=
Header: <https://desec.io/api/v1/domains/?cursor=>; rel="first", <https://desec.io/api/v1/domains/?cursor=cD0yMDIxLTA0LTA1KzE3JTNBMjYlM0EyOC4wMjg5NTclMkIwMCUzQTAw>; rel="next"
next endpoint /domains/?cursor=cD0yMDIxLTA0LTA1KzE3JTNBMjYlM0EyOC4wMjg5NTclMkIwMCUzQTAw
Header: <https://desec.io/api/v1/domains/?cursor=>; rel="first", <https://desec.io/api/v1/domains/?cursor=cj0xJnA9MjAyMS0wNC0wNSsxNyUzQTI2JTNBMjYuODAxOTIzJTJCMDAlM0EwMA%3D%3D>; rel="prev"
next endpoint 
Domain Index initilized with pagination (501 domains)

**Comment by D3luxee** [comment]
Thats great, i will implement this pagination for the rrsets aswell.

**Comment by tlimoncelli** [comment]
Is this issue ready to be closed?

**Comment by tlimoncelli** [comment]
Thanks!
