### ISSUE TITLE
Google Domains (dynamic DNS)

### ISSUE THREAD

**Issue by TorvusBog** [StackExchange/dnscontrol#1178]
Is there any support for this (creds.json)?

I didn't found any documentation associated and it will be awesome for my projects.

Thanks a lot!

**Comment by tlimoncelli** [comment]
The [Google DNS provider](https://stackexchange.github.io/dnscontrol/providers/gcloud) doesn't support the Dynamic DNS feature at this time.

Sadly this isn't a feature we use, so I wouldn't know how to go about adding it.  I'd be glad to walk you through adding it yourself.   There's a tutorial called [Creating new DNS Resource Types](https://stackexchange.github.io/dnscontrol/adding-new-rtypes) which walks you through the process.  I'd be glad to help you along the way.

**Comment by tlimoncelli** [comment]
This request has gone stale. Closing issue.  Please re-open if needed.
