### ISSUE TITLE
Provider request: dns.he.net

### ISSUE THREAD

**Issue by tiernano** [StackExchange/dnscontrol#118]
More providers found... not even sure these lads have an API, but would be silly if they did not. 

Provider name: Hurricane Electric
Website: https://dns.he.net/
API Documentation: N/A (Still searching)
Price: Free (50 domains)
Other features: Reverse DNS for IPv6 also supported, which is nice!

**Comment by tlimoncelli** [comment]
I've added this to the [list of requests](https://stackexchange.github.io/dnscontrol/provider-list). If someone would like to volunteer to implement this, please re-open this issue. 

Advice on how to write a provider is documented [here](https://stackexchange.github.io/dnscontrol/writing-providers). Also, speak up in this issue and someone will get back to you asap.

**Comment by rblenkinsopp** [comment]
The above MR (#822) has an initial implementation of this.

**Comment by tlimoncelli** [comment]
Done!  Thanks for the PR!
