### ISSUE TITLE
Commented out NAMESERVER() applied in ROUTE53

### ISSUE THREAD

**Issue by kotnik** [StackExchange/dnscontrol#1195]
I am probably doing something wrong, or this is related to #741.

Fresh Route53 zone, ` dnscontrol get-zones` gave following `dnscontrol.js`:

```js
var awsr53 = NewDnsProvider("awsr53", "ROUTE53");
var no_registrar = NewRegistrar("ThirdParty", "NONE");

D("DOMAIN.TLD", no_registrar, DnsProvider(awsr53)
        //, NAMESERVER('ns-908.awsdns-49.net.')
        //, NAMESERVER('ns-1897.awsdns-45.co.uk.')
        //, NAMESERVER('ns-69.awsdns-08.com.')
        //, NAMESERVER('ns-1473.awsdns-56.org.')
        , A('test', '1.2.3.4')
)
```

Even though `NAMESERVER()` ones are commented out, `dnscontrol push` does:

```
******************** Domain: DOMAIN.TLD
----- Getting nameservers from: awsr53
----- DNS Provider: awsr53...
1 correction
#1: 
MODIFY NS DOMAIN.TLD: (ns-1473.awsdns-56.org. ttl=172800) -> (ns-1473.awsdns-56.org. ttl=300)
MODIFY NS DOMAIN.TLD: (ns-69.awsdns-08.com. ttl=172800) -> (ns-69.awsdns-08.com. ttl=300)
MODIFY NS DOMAIN.TLD: (ns-1897.awsdns-45.co.uk. ttl=172800) -> (ns-1897.awsdns-45.co.uk. ttl=300)
MODIFY NS DOMAIN.TLD: (ns-908.awsdns-49.net. ttl=172800) -> (ns-908.awsdns-49.net. ttl=300)
SUCCESS!
----- Registrar: ThirdParty...
0 corrections
Done. 1 corrections.
```

How is this possible?

**Comment by tlimoncelli** [comment]
Ah, this is a great question!

The change is to the TTL (from 172800 to 300).  However, you may be asking why is it changing something that is commented out?

2 things are happening here:

First, `DnsProvider(awsr53)` actually means two things:
  - DNS updates should be sent to awsr53, and
  - Ask awsr53 what my NS records should be, and act as if there are NAMESERVER() statements for them.  You can specify `DnsProvider(awsr53, 0)` to turn this off. ([more info](https://stackexchange.github.io/dnscontrol/js#DNSProvider))

Second, the TTL on those records is being changed.  The TTL for NAMESERVER() statements is set using [NAMESERVER_TTL()](https://stackexchange.github.io/dnscontrol/js#NAMESERVER_TTL).  If you want to be fancy, you can set that globally using the DEFAULTS() command:

```
DEFAULTS(  // These statements will be added to all domains.
     NAMESERVER_TTL(300)
);
```

**Comment by kotnik** [comment]
Thank you for complete explanation, it really helped me to understand what is going on here.
