### ISSUE TITLE
Linode Support

### ISSUE THREAD

**Issue by markdorison** [StackExchange/dnscontrol#121]
[Linode API Docs: DNS](https://www.linode.com/api/dns)

**Comment by tlimoncelli** [comment]
I've added this to the [list of requests](https://stackexchange.github.io/dnscontrol/provider-list). If someone would like to volunteer to implement this, please re-open this issue. 

Advice on how to write a provider is documented [here](https://stackexchange.github.io/dnscontrol/writing-providers). Also, speak up in this issue and someone will get back to you asap.
