### ISSUE TITLE
deSEC: quoting with TXT records

### ISSUE THREAD

**Issue by problame** [StackExchange/dnscontrol#1211]
Using the `TXT` modifier currently requires double-quoting, which is unintuitive and detrimental to the portability of the `dnsconfig.js` to other providers.

---

As a user, I expect to be able to write the following `TXT` modifier:

```
    TXT('@', 'v=spf1 include:spf.messagingengine.com ?all'),
```

However, this results in the following `dnscontrol` error:

```
FAILURE! Failed create RRset (deSEC): HTTP status 400 400 Bad Request, the API does not provide more information
```

After a bunch of head-scratching, I found https://desec.readthedocs.io/en/latest/dns/rrsets.html#caveats

> The contents of the TXT record must be enclosed in double quotes. Thus, when POSTing to the API, make sure to do proper escaping etc. as required by the client you are using. Here’s an example of how to create a TXT RRset:

This resulted in the **workaround** of double-quoting in `dnsconfig.js`.

```
    TXT('@', '"v=spf1 include:spf.messagingengine.com ?all"'),
```

---

The workaround is suboptimal because the `dnsconfig.js` is no longer portable.
For example, when using another `DnsProvider` such as `hosting.de`, `dnscontrol` replicates the double-quoting, resulting in

![image](https://user-images.githubusercontent.com/956573/125793297-025cc408-b87f-4cd2-b9d9-9ec88b65d2f8.png)

---

Proposed fix: the deSEC provider should wrap the string in quotes by itself.

Implementation concerns: need to make sure that the delete path still works after this change.

**Comment by D3luxee** [comment]
Hi @problame ,
which version did you use?
I've recently made alot of changes to the desec provider which are only part of the master branch.
This double quoting shoud already be fixed i guess.

**Comment by problame** [comment]
I ran `go get github.com/StackExchange/dnscontrol/v3` today.

```
dnscontrol version
dnscontrol v3.10.1-dev
```

**Comment by problame** [comment]
I just tried your commit

```
go get -v github.com/StackExchange/dnscontrol@228b57e445e18349cd0d9d100005c487884d29ee
```

Seems to work :pray:

**Comment by blackshadev** [comment]
@tlimoncelli Can you close this one? The last status indicates this is resolved.

**Comment by tlimoncelli** [comment]
Thanks!
