### ISSUE TITLE
Provide examples of CI/CD tests.

### ISSUE THREAD

**Issue by markdorison** [StackExchange/dnscontrol#122]
The README discusses CI/CD tests:

> Adopt CI/CD principles to DNS! At StackOverflow we maintain our DNSControl configurations in Git and use our CI system to roll out changes. Keeping DNS information in a VCS means we have full history. Using CI enables us to include unit-tests and system-tests. Remember when you forgot to include a "." at the end of an MX record? We haven't had that problem since we included a test to make sure Tom doesn't make that mistake... again.

I think it would be extremely valuable to provide/document some standard tests that could be run such as the MX record test that is mentioned.

**Comment by tlimoncelli** [comment]
I've updated the docs as requested. https://stackexchange.github.io/dnscontrol/unittests
