### ISSUE TITLE
OVH: "Invalid subfield found in DKIM" on correction

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#1235]
After updating dnscontrol from 3.3.0 to commit 6fc3534aa3b74bdb4b7fb7092068abc26e4753e1 (basically 3.11, reason: due to INWX fix) doing any corrections on OVH-owned domains fail with:

```
******************** Domain: domain.tld
----- Getting nameservers from: PK-OVH-IE
----- DNS Provider: PK-OVH-IE...
2 corrections
#1: MODIFY TXT 2018101._domainkey.domain.tld: ("v=DKIM1; k=rsa; t=s; s=email; p=MII[...]QAB" ttl=1800) -> ("v=DKIM1; k=rsa; t=s; s=email; p=MII[...]I4I" "uEv[...]QAB" ttl=1800)
FAILURE! Error 400: "Invalid subfield found in DKIM : \"v=DKIM1"
#2: REFRESH zone domain.tld
SUCCESS!
```

Relevant config for this TXT record is:
```javascript
		TXT('2018101._domainkey', 'v=DKIM1; k=rsa; t=s; s=email; p=MII[...]QAB'),
```

I'm not sure if that's related to the reworked TXT logic in [v3.8.0](https://github.com/StackExchange/dnscontrol/releases/tag/v3.8.0), as it passed the tests when implementing this. It appears that OVH does some magic on their API when they detect the TXT is a DKIM key?

There're no issues editing the DKIM entry in the OVH Manager WebUI.

@masterzen Do you have a few minutes to spare?

**Comment by tlimoncelli** [comment]
Does [DMARC_BUILDER()](https://stackexchange.github.io/dnscontrol/js#dmarc-builder) generate the same string?

**Comment by patschi** [comment]
That's for DMARC, not for DKIM (what's causing the error above), so unfortunately won't help. Noteworthy is, that INWX works just great with the exact same record, and also the record hasn't changed in the config.

(But indeed a good idea switching over to the DMARC_BUILDER for my DMARC entries, thanks for the note!)

**Comment by tlimoncelli** [comment]
Oops! I conflated the two :-(   Thanks for the correction.  (There used to be a DKIM() function but now TXT() does splitting and DKIM() is just a no-op.

**Comment by patschi** [comment]
No worries!

The OVH API really acts strange...

When using as TXT record:
```
TXT('2018101._domainkey', 'k=rsa; t=s; s=email; [...]
```
The error is:
```
FAILURE! Error 400: "Invalid subfield found in DKIM : \"k=rsa"
```

**Comment by patschi** [comment]
Some further observations...

Here we do normalize the DNS records we receive from the OVH provider:
https://github.com/StackExchange/dnscontrol/blob/ce6006cce7b6877bc56dfb6c9df969e47e7cbb86/providers/ovh/ovhProvider.go#L120-L131

To do the automated splitting with the provider, what OVH does not need, we use the function `txtutil.SplitSingleLongTxt(dc.Records)` here.

When I use dnscontrol without any changes, resulting in error:
```
#1: CREATE TXT test2._domainkey.domain.tld "v=DKIM1; k=rsa; t=s; s=email; p=MIIBI...KP0dI4I" "uEv4BHbwqak5ce5...wW6xZaMCild2xaIEtMsFewIDAQAB" ttl=43200
FAILURE! Error 400: "Invalid subfield found in DKIM : \"v=DKIM1"
```

When simply commenting out the above mentioned functionality to DISABLE splitting TXT records:
```
#1: CREATE TXT test._domainkey.domain.tld "v=DKIM1; k=rsa; t=s; s=email; p=MIIB...sFewIDAQAB" ttl=43200
SUCCESS!
#2: REFRESH zone domain.tld
SUCCESS!
```

So, for me, I think the "solution" might be simply disabling the TXT-splitting feature altogether, as OVH doesn't need and handle this with some magic on the backend anyway. What's your opinion on this, @tlimoncelli?

**Comment by JBOClara** [comment]
Using 
```
./.tools/dnscontrol.v3.17.0 version
dnscontrol v3.17.0 ("015c3d184adc8f0f8a62e69e44d8b83d0d5da5e1") built 19 Jun 22 15:52 CEST
```

I've got `FAILURE! Error 400: "Invalid subfield found in DKIM : \"v=DKIM1"` modifying an OVH TXT record
```
******************** Domain: domain.tld
----- Getting nameservers from: ovh
----- DNS Provider: ovh...
2 corrections
#1: MODIFY TXT 29012022._domainkey.domain.tld: ("v=DKIM1; t=s; p=MII[..]QAB" ttl=3600) -> ("v=DKIM1; t=s; p=MII[..]QAB" ttl=300)
FAILURE! Error 400: "Invalid subfield found in DKIM : \"v=DKIM1"
#2: REFRESH zone domain.tld
```
