### ISSUE TITLE
vultr: TXT Records are not working

### ISSUE THREAD

**Issue by fleaz** [StackExchange/dnscontrol#1240]
Hey,

after migrating my mail server recently I had to update my DKIM keys after a long time and discovered that changing/creating TXT records at Vultr is broken and results in a `FAILURE! Unable to add record: Record data must be enclosed in quotes` error when running `dnscontrol deploy` (check and preview both work fine).

I started going back one release after another and rerun my pipeline and discovered that the last version where it worked was 3.7.0 so I guess this is probably related to the big "TXT makeover" which happended in 3.8.0 (#1063)

This also happens with my short SPF record, so it's not a length issue.

Let me know if I can provide any more infos to help with this issue.

Best,
Felix

**Comment by tlimoncelli** [comment]
The fix will be in the next release.  If you build from master that has the fix in it.

**Comment by fleaz** [comment]
Just tested the latest code and I can confirm it works like a charm. Thanks! :)
