### ISSUE TITLE
Digital Ocean Support

### ISSUE THREAD

**Issue by riyadhalnur** [StackExchange/dnscontrol#125]
Having DO support would be the cherry on the cake (sorry for the bad pun). If it's on the roadmap, I would like to pick it up. API docs - [https://developers.digitalocean.com/documentation/v2/#domains](https://developers.digitalocean.com/documentation/v2/#domains)

**Comment by tlimoncelli** [comment]
We'd love to have a DO provider!  The documentation on https://stackexchange.github.io/dnscontrol/writing-providers is fairly sparse but should be enough to get your started. (Feel free to tell us what was the most confusing so we can update the doc)

**Comment by tlimoncelli** [comment]
I've added this to the [list of requests](https://stackexchange.github.io/dnscontrol/provider-list). If someone would like to volunteer to implement this, please re-open this issue. 

Advice on how to write a provider is documented [here](https://stackexchange.github.io/dnscontrol/writing-providers). Also, speak up in this issue and someone will get back to you asap.

**Comment by riyadhalnur** [comment]
Already started working on it but slow progress due to my schedule.

**Comment by tlimoncelli** [comment]
Re-opened. (we closed a lot of tickets in bulk and this ticket shouldn't have been included.  My apologies.)

**Comment by riyadhalnur** [comment]
No worries.
