### ISSUE TITLE
feature request: Please provide aarch64/arm64 builds for future releases as well

### ISSUE THREAD

**Issue by m-ueberall** [StackExchange/dnscontrol#1255]
It would be nice to be able to directly download an `*_arm64.deb` package.

**Comment by tlimoncelli** [comment]
Sounds good!

I don't have access to a arm64 deb machine.  Would you consider writing a PR to implement this?

**Comment by m-ueberall** [comment]
I've submitted PR #1259.
(TBH, I have _absolutely no idea_ how to add additional labels to `strategy.matrix` in conjunction with [`runs-on`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on) in order to adapt to individual environments with different sets of registered runners—for testing purposes, I only registered two local ones—but maybe it works as is or someone else is able to figure this out.)

**Comment by m-ueberall** [comment]
Given that it's likely overkill to use multiple, native runners for a Go binary (that is, unless you intend to run integration tests in native environments), I've submitted PR #1260.

**Comment by peerau** [comment]
> Sounds good!
> 
> I don't have access to a arm64 deb machine. Would you consider writing a PR to implement this?

Would you like one?

**Comment by tlimoncelli** [comment]
Sure!

**Comment by peerau** [comment]
> Sure!

hit up https://fossho.st/apply :D

**Comment by tlimoncelli** [comment]
FYI: We'll be moving this to CircleCI between now and July, hopefully sooner.  Adjust the amount of effort you put into this accordingly.  (I assume this is a simple eddit to `dnscontrol/.github/workflows/release.yml` )

**Comment by peerau** [comment]
> FYI: We'll be moving this to CircleCI between now and July, hopefully sooner. Adjust the amount of effort you put into this accordingly. (I assume this is a simple eddit to `dnscontrol/.github/workflows/release.yml` )

I can supply GH Runners, GL, runners and CircleCI runners on ARM64, no problem. email me at peer@fosshost.org and we can work something out

**Comment by tlimoncelli** [comment]
I believe this is fixed.  Please re-open this issue if it isn't.
