### ISSUE TITLE
Hexonet with TXT (DKIM) records: ERROR: strings >255 octets

### ISSUE THREAD

**Issue by buraktamturk** [StackExchange/dnscontrol#1264]
Long TXT records were supported by the old version of dnscontrol tool with Hexonet provider.
After an upgrade to the latest version, I am having this issue

```
printIR.go:94: ERROR: strings >255 octets
```

A quick lookup for the provider code shows that it calls TxtNoMultipleStrings - however not TxtNoLongStrings. But this call (TxtNoMultipleStrings) seems also checks for TxtNoLongStrings. Is it intentional?

https://github.com/StackExchange/dnscontrol/blob/c33c5956a9fd3d662ac4e5fa3063bdf656531b2f/providers/hexonet/auditrecords.go#L17

If so, how should I modify my TXT records?

```javascript
    TXT("mail._domainkey", DKIM("v=DKIM1; h=sha256; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwOuoMsFtVVSOokeXkyk3yovjQUsMQK1tLEFeEFaDKSQ7Qzy6JuI7FZ/Xc0r0F+c8hA3O5K8wLYIffUbKxfBbepKSYHtnzLkS9TX77tmsFDzysHJTc4xvzn/SPxuWPIu95hjUgcfDx0db1gk8I3aYUUytM9tswDPUX9pdqwirAHj3ubaGg4B/x2RjdKaZt3ISg29XNS2OltKXNpPQQxXrZTIwmV4f0xnLIKRmbBwqorZdjMBMuIpPknalWFG3ZoMMWtXP4slxuRjm5fDbWOElePz30akp0w9uN3K8h4NFsXym9VG52Zm93wQUTufFkcYy/XiLz14uW8uHBWdOxF23MQIDAQAB"))
```

**Comment by tlimoncelli** [comment]
The name TxtNoMultipleStrings is non-optimal.

Hey, Kai, what is/isn't supported in Hexonet TXT records?  When I simply remove the TxtNoMultipleStrings tests fail.

CC: @papakai 

Tom

**Comment by papakai** [comment]
@tlimoncelli yes, or API is supporting Multi-Line TXT RR. The easiest way is to just concatenate everything together without space. Even though I expect both below ways to be supported, the later one I consider as best and uncomplicated way. We're accepting 4096 chars length (that's at least something I found documented), but could be even more.

For example:
IN TXT "v=spf1 .... first" "second string..."
IN TXT "v=spf1 .... firstsecond string..."

Does that help?

**Comment by buraktamturk** [comment]
I am not too familiar with Golang.

Does SetTargetTXT function split the input into arrays by 255 octets? Or does the input get splitted on somewhere else (apart from the provider)? If not the comment above the function is very misleading.

https://github.com/StackExchange/dnscontrol/blob/master/models/t_txt.go#L45-L72

I would love to submit a PR for this issue, so far I think encodeTxt function on the provider code needs do the splitting if only one string passed to it? Would that be correct?

https://github.com/StackExchange/dnscontrol/blob/master/providers/hexonet/records.go#L278-L288

**Comment by tlimoncelli** [comment]
No worries.  That bit of code is a bit wonky (I'm waiting for Go to have Generics before I clean it up).

SetTargetTXT does not split text.  That's done by calling txtutil.SplitSingleLongTxt().  I don't see that called in this provider (which is expected).
```
$ grep -rl txtutil.SplitSingleLongTxt providers/hexonet 
$
```

If you want to call it, call it immediately after `models.PostProcessRecords()` (See where it is called in other providers.)

From what @papakai says, it seems that we can simply send the whole string (up to 4096 chars) as the first string and Hexonet will do the splitting in the background. (I hope it preserves this and sends it back to us as a long string.  If not, dnscontrol will probably get confused and try to "fix" the record.)

Hope that helps!

Tom
