### ISSUE TITLE
CLOUDFLAREAPI: Remove AccountName

### ISSUE THREAD

**Issue by fdcastel** [StackExchange/dnscontrol#1275]
I'm in favor of removing `AccountName` from Cloudflare configuration.

To the best of my understanding, this is not being used anywhere in this provider. Except in (unnecessary) validation checks.

@tresni: In light of your (excellent) recent changes, could you give us your opinion about this matter? Do you see any need to keep it?

CC @tlimoncelli

**Comment by tresni** [comment]
The only place it's used is in the [`createZone` call](https://github.com/StackExchange/dnscontrol/blob/d8941a04bc8804d68279270f0fe89a56b059114c/providers/cloudflare/rest.go#L59) and is unused according to the [API documentation](https://api.cloudflare.com/#zone-create-zone).  I'm in favor of deprecating/removing it.  We should continue to allow AccountID to be set, but we don't need AccountName at all.

**Comment by fdcastel** [comment]
Yeah. Fully agreed.

**Comment by tlimoncelli** [comment]
How about a default value like not-required@example.com ?

**Comment by tresni** [comment]
@tlimoncelli there's no reason to use the account email at all from what I can find.  We are literally passing something that the API is just going to ignore (or eventually it could choose to error it out.)  I think it's better to remove its use since it's backwards compatible and doesn't break anything.

**Comment by tlimoncelli** [comment]
Agreed!  Remove account name.  The less configuration the better!

**Comment by tresni** [comment]
PR incoming.  Did a little bit of related cleanup while I was in there.
