### ISSUE TITLE
Provider request: coredns

### ISSUE THREAD

**Issue by jauderho** [StackExchange/dnscontrol#1284]
Opening this as a request to gauge the level of interest in having dnscontrol being able to speak to coredns.  https://coredns.io/

**Comment by jauderho** [comment]
@TomOnTime Please label accordingly when you get a chance. Thanks.

**Comment by tlimoncelli** [comment]
Thank you for requesting this provider!

I've tagged this issue as a provider-request.  It will (soon) be listed as a    "requested provider" on the provider list web page:
https://docs.dnscontrol.org/service-providers/providers

I will now close the issue.  I know that's a bit confusing, but it will remain  on the "requested provider" list.

If someone would like to volunteer to implement this, please re-open this issue and add the tag `has-pr`.

We encourage you to try adding this provider yourself.  We've tried to make the process as friendly as possible.  Many people have reported that adding a       provider was their first experience writing Go.  The process is documented here:
https://docs.dnscontrol.org/developer-info/writing-providers
If you need assistance, please speak up in this issue and someone will get back to you ASAP.

**Comment by ztNIE** [comment]
Hi I'm happy to volunteer for this issue. I just read the developer doc and am about to begin soon

**Comment by prologic** [comment]
That page 404's btw

=> https://docs.dnscontrol.org/service-providers/providers

**Comment by tlimoncelli** [comment]
Thanks. We moved things around recently. That page is now https://docs.dnscontrol.org/provider/index

**Comment by chicks-net** [comment]
I have used coredns with `dnscontrol` using files generated with our native BIND provider.  I'm actually working on a demo of this very thing.

- Do we need a new provider for this for some reason?  I'm sure there are other folks that are effectively BIND compatible that we don't need to write or maintain code for.
- Should we just document this somehow?
