### ISSUE TITLE
 Feature request: preferred-chain option for get-certs

### ISSUE THREAD

**Issue by itelmenko** [StackExchange/dnscontrol#1285]
For resolving the big problem from LetsEcrypt https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

please add option  preferred-chain for get-certs like certbot has. 

It need be run with  --preferred-chain ISRG Root X1 for resolving the problem.

Thanks

**Comment by tlimoncelli** [comment]
Sadly the person that wrote the get-certs command is no longer with the project, and we don't have much expertise remaining.  This feature will have to come from the community.

**Comment by tlimoncelli** [comment]
Closing this issue.  The get-certs feature is deprecated and no new features are being added at this time.  The code will be removed from the project after Dec 31, 2022.  Please move to another SSL renewal system.
