### ISSUE TITLE
Close provider-request issues

### ISSUE THREAD

**Issue by captncraig** [StackExchange/dnscontrol#130]
I propose we close all provider-request issues to keep issues clean.

I would like to add a page to the docs to list them (via api) and make them available to see and/or work on. Essentially [this search](https://github.com/StackExchange/dnscontrol/issues?q=is%3Aissue+is%3Aopen+label%3Aprovider-request)

If someone starts working on one, we can add the label provider-in-progress and maybe re-open it (or maybe not).

**Comment by tlimoncelli** [comment]
I did some work on this. PTAL
