### ISSUE TITLE
Provide a way to alert on changes

### ISSUE THREAD

**Issue by truthdoug** [StackExchange/dnscontrol#1326]
**The problem I'm trying to solve:** We're using dnscontrol to manage our DNS (hosted via AWS Route53). Some staff have access to Route53 via web console and _occasionally_ make changes directly there rather than using dnscontrol. I want to know when this happens.

**Possible solutions** (not mutually exclusive):
* Change the exit status of `dnscontrol preview` based on whether or not there are pending changes. Since returning 0 generally indicates normal completion, I think returning non-zero would indicate an unexpected change
* Change the output of `dnscontrol preview` so that only the changes are written to stdout and other messages are written to stderr. So that in the below example, the only line that would be written to stdout would be the line starting with `DELETE`
```
******************** Domain: example.org
----- Getting nameservers from: r53_main
----- DNS Provider: r53_main...
0 corrections
----- Registrar: none...
0 corrections

******************** Domain: example.xyz
----- Getting nameservers from: r53_main
----- DNS Provider: r53_main...
1 correction
#1:
DELETE CNAME sso.ssoprovider.example.com. ttl=300

----- Registrar: none...
0 corrections
````

**What's Left to Me**
After either of these changes, I can script something that runs `dnscontrol preview` regularly and triggers an alert to let me know that somebody needs a talking to about how to make DNS changes.

**Comment by tlimoncelli** [comment]
Yup!  Seen that before!   I think we have just the thing for ya!

    dnscontrol preview --expect-no-changes

You can run that periodically and alert on error.  I wouldn't recommend running it in a tight loop as you may trigger your provider's rate limit.

Tom

**Comment by truthdoug** [comment]
Oh, that's great! That'll work!
