### ISSUE TITLE
Access environment variables in dnsconfig.js

### ISSUE THREAD

**Issue by luckydonald** [StackExchange/dnscontrol#1327]
Basically I want to keep the actual IP addresses in environment variables.
But I couldn't find a way how to read them.

I tried the following, hoping to somehow tap into the same magic `creds.json` is using:

#### 1. just use them: 
```js
D("...", ...
  A('subdomain', '$SERVER1_IP', CF_PROXY_ON),
)
```

#### 2. as variable
```js
var SERVER1_IP = '$SERVER1_IP';
...
D("...", ...
  A('subdomain', SERVER1_IP, CF_PROXY_ON),
)
```

#### 3. using an config file
`environment.json`:
```json
{
  "SERVER1_IP": "$SERVER1_IP"
}
```
```js
var environment = require('./environment.json')
var SERVER1_IP = environment .SERVER1_IP;
...
D("...", ...
  A('subdomain', SERVER1_IP, CF_PROXY_ON),
)
```

#### 4. using Nodejs' `process.env` object
```js
var SERVER1_IP = process.env.SERVER1_IP;
...
D("...", ...
  A('subdomain', SERVER1_IP, CF_PROXY_ON),
)
```

**Comment by tlimoncelli** [comment]
I'd suggest setting values via the command line as documented here: https://stackexchange.github.io/dnscontrol/cli-variables

NOTE: I'm about to submit a PR with improved documentation.

**Comment by tlimoncelli** [comment]
I'd love your feedback on my PR with better documentation (https://github.com/StackExchange/dnscontrol/pull/1328).  

Here's the raw file: [view as displayed](https://github.com/StackExchange/dnscontrol/blob/27776d7de585818d4d4832948ecd9b0183ecc3c0/docs/cli-variables.md)

**Comment by tlimoncelli** [comment]
I'm closing this feature request as I believe the cli-variables are sufficient for the goal.
