### ISSUE TITLE
ORACLE: Fix staticcheck errors

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1334]
CC @kallsyms

I'm moving from go-lint to staticcheck (https://staticcheck.io/). It finds some issues that I think are worth fixing.

Docs on how to install staticcheck are here: https://staticcheck.io/docs/getting-started/
The command line that produced these errors was: `staticcheck ./...`

The warnings/errors related to this provider are:

```
providers/oracle/oracleProvider.go:232:25: this result of append is never used, except maybe in other appends (SA4010)
providers/oracle/oracleProvider.go:246:24: this result of append is never used, except maybe in other appends (SA4010)
```

**Comment by kallsyms** [comment]
After #1341 I'm not getting any errors running `staticcheck` locally

**Comment by tlimoncelli** [comment]
Confirmed.  Thanks!
