### ISSUE TITLE
Use old changelog style again

### ISSUE THREAD

**Issue by SuperSandro2000** [StackExchange/dnscontrol#1339]
The changelog for version 3.13.0 and below where nice and short and you knew with one look if there are breaking changes and what else happened. The changelog for 3.13.1 is basically the git log which contains a lot of noise which is very insignificant for the average person. I would appreciate if the short writeups would come back.

**Comment by tlimoncelli** [comment]
Yes, I noticed that too.  In 1.13.1 we tried an automated changelog creator.  

@cdhunt: Can you recommend what to do to balance automated changelogs but with the human editing?

**Comment by cdhunt** [comment]
I have a few ideas. Can you describe an ideal feature list for the release notes?

The commit history is obviously too messy and looking through the PRs the titles are partially consistent, but not reliable enough for automated notes. 

Keeping a CHANGELOG file in the repo would be an option to allow the contributors to help curate the notes and just not attempt to automate it.

**Comment by SuperSandro2000** [comment]
> Can you describe an ideal feature list for the release notes?

Like it was before it was fine.

**Comment by tlimoncelli** [comment]
The last 2 releases demonstrate that we've fixed this.

Closing issue.  Please re-open if needed.
