### ISSUE TITLE
Support DNAME Records

### ISSUE THREAD

**Issue by bhuntley-cu** [StackExchange/dnscontrol#134]
https://tools.ietf.org/html/rfc6672

Thanks!

**Comment by tlimoncelli** [comment]
Which providers support this?

**Comment by bhuntley-cu** [comment]
I had expected R53 to do so since the only DNAME record we have at this point came from Amazon SES, but it does appear that R53 and most of the other providers don't know what to do with them.  Clearly, this is a feature request more about RFC compliance than a pressing need.

**Comment by tlimoncelli** [comment]
Marking this "wontfix".  We'll gladly reopen if someone has a live use-case.

**Comment by spreegabe** [comment]
my active directory / msdns environment has DNAME records. v3 silently ignores them and v4 crashes during get-zone.
```
failed GetZone gzr: msdns/convert.go:nativeToRecord rtype="DNAME" unknown: props=map[DomainNameAlias:asdfasdfasdfasdfasdf.gx.internal.cloudapp.net.] and map[]
```

**Comment by cafferata** [comment]
@spreegabe would you mind creating a new [bug report issue](https://github.com/StackExchange/dnscontrol/issues/new?template=bug_report.md)? This GitHub issue concerns the implementation of DNAME record.

**Comment by spreegabe** [comment]
Of course. I guess I did find a use case though!
>  We'll gladly reopen if someone has a live use-case.

see https://github.com/StackExchange/dnscontrol/issues/2840
