### ISSUE TITLE
Wrong version number in 3.13.1 dnscontrol-Linux download

### ISSUE THREAD

**Issue by andreaso** [StackExchange/dnscontrol#1342]
Looks like the version number is a bit off for the _dnscontrol-Linux_ binary?

```
$ cd $(mktemp -d)
$ curl -fsSLOJ https://github.com/StackExchange/dnscontrol/releases/download/v3.13.1/dnscontrol-Linux
$ chmod 755 dnscontrol-Linux
$ ./dnscontrol-Linux version
dnscontrol v3.13.0 ("cc4eba6f16248449245de9ee283a7a393024b2f9") built 17 Dec 21 13:29 CET
$
```

The binary included in the tarball on the other hand does show the expected version number.

```
$ cd $(mktemp -d)
$ curl -fsSLOJ https://github.com/StackExchange/dnscontrol/releases/download/v3.13.1/dnscontrol_3.13.1_Linux_x86_64.tar.gz
$ tar xf dnscontrol_3.13.1_Linux_x86_64.tar.gz
$ ./dnscontrol version
dnscontrol "3.13.1" ("cc4eba6f16248449245de9ee283a7a393024b2f9") built 17 Dec 21 13:26 CET
$
```

**Comment by tlimoncelli** [comment]
CC @cdhunt

**Comment by tlimoncelli** [comment]
Good catch!  We'll look into it.

@cdhunt FYI: The current way the version number is updated is by manually running `bin/make-release.sh` with the new version number. (See `docs/release-engineering.md`)

**Comment by cdhunt** [comment]
@andreaso Do you use usually download the raw binary or the package version?

**Comment by andreaso** [comment]
> ... Do you use usually download the raw binary or the package version?

Yepp, up until now I've been grabbing the raw binary, even if I'll be equally happy to have my Ansible setup download and extract the tarball.

deb/rpm packages don't feel that useful (to me) in the case of standalone go binaries.

**Comment by avdija** [comment]
looks like if you fetch https://github.com/StackExchange/dnscontrol/archive/refs/heads/master.zip and compile it version will stay dnscontrol v3.13.0 ("") built 18 Dec 21 11:54 UTC

**Comment by andreaso** [comment]
Looks like the version numbers have started to line up again.

```
$ /opt/dnscontrol/3.14.0/dnscontrol version
dnscontrol v3.14.0 ("adbec1167c6fdc63242fef7e2c232e65b3cc2a91") built 05 Feb 22 16:06 CET
$ /opt/dnscontrol/3.15.0/dnscontrol version
dnscontrol v3.15.0 ("eb81a7f4e54e4d48b421d6003eae151480b2fea9") built 07 Mar 22 19:52 CET
$ 
```

These are both the `dnscontrol-Linux` raw binary download.

**Comment by tlimoncelli** [comment]
Resolving
