### ISSUE TITLE
DOCS: README should mention dnscontrol-action

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1344]
@koenrh has encapsulated the a GitOps workflow for dnscontrol PRs as a Github Actions module:

       https://github.com/koenrh/dnscontrol-action

We should mention it in the README.  (If that's ok with you, @koenrh)

**Comment by koenrh** [comment]
@tlimoncelli Makes sense! 

How do you feel about transferring the repository to the StackExchange GitHub organization? As @firefishy suggested here: https://github.com/koenrh/dnscontrol-action/issues/48#issuecomment-841871481 Happy to maintain it and add some documentation.

**Comment by tlimoncelli** [comment]
I'd rather keep it separate and just link to it in the README.
