### ISSUE TITLE
SPF optimiser causes check/print-ir to depend on DNS

### ISSUE THREAD

**Issue by ad8-bdl** [StackExchange/dnscontrol#1348]
(a sibling problem to #1071, I believe)

`check` / `print-ir` should not depend on external things such as DNS.

Using the SPF Optimizer causes the `check` / `print-ir` commands to execute DNS lookups which in and of itself is not great; worse is that failed DNS lookups raise incorrect validation errors.

For example, where the _current_ SPF record for the domain includes an invalid name `mailsenders.netsuite.com` but the config file is otherwise valid:

    % dnscontrol preview --expect-no-changes
    2021/12/24 07:27:33 printIR.go:88: 2 Validation errors:
    2021/12/24 07:27:33 printIR.go:94: ERROR: in included SPF: lookup mailsenders.netsuite.com on 192.168.65.5:53: read udp 172.17.0.2:38283->192.168.65.5:53: i/o timeout
    2021/12/24 07:27:33 printIR.go:91: WARNING: problem resolving SPF record: lookup mailsenders.netsuite.com on 192.168.65.5:53: read udp 172.17.0.2:38283->192.168.65.5:53: i/o timeout
    exiting due to validation errors

**Comment by tlimoncelli** [comment]
Good point that check / print-ir should not depend on DNS.

The spf optimizer uses DNS but fails quickly to using `spfcache.json` if DNS is down.  Maybe for check/print-ir it should just use the file.

**Comment by tlimoncelli** [comment]
Sadly SPF is in maintenance mode. I'm not going to be adding new features.

Closing. Feel free to re-open if it becomes hot again.
