### ISSUE TITLE
CF_UNIVERSALSSL_OFF Not working!

### ISSUE THREAD

**Issue by IzumiSena** [StackExchange/dnscontrol#1352]
```
// UniversalSSL Off For Entire Domain:
var CF_UNIVERSALSSL_OFF = { 'cloudflare_universalssl': 'off' };
// UniversalSSL On For Entire Domain:
var CF_UNIVERSALSSL_ON = { 'cloudflare_universalssl': 'on' };

D('example.org', REG_NONE, DnsProvider(CLOUDFLARE), CF_UNIVERSALSSL_OFF,
    A('@', 10.0.0.1), // The Naked Or 'APEX' Domain.
    A('www', 10.0.0.1)
);
````

Can anyone help me? .... I can change proxy on/off but can't change universalssl on/off help please!
DNSControl Version: 3:13:1

**Comment by tlimoncelli** [comment]
These constants are already defined for you: (see helpers.js in the source code)

```
// UniversalSSL off for entire domain:
var CF_UNIVERSALSSL_OFF = { cloudflare_universalssl: 'off' };
// UniversalSSL on for entire domain:
var CF_UNIVERSALSSL_ON = { cloudflare_universalssl: 'on' };
```

Does it work if you remove the `var CF_UNI....` lines in your example?

**Comment by IzumiSena** [comment]
> These constants are already defined for you: (see helpers.js in the source code)
> 
> ```
> // UniversalSSL off for entire domain:
> var CF_UNIVERSALSSL_OFF = { cloudflare_universalssl: 'off' };
> // UniversalSSL on for entire domain:
> var CF_UNIVERSALSSL_ON = { cloudflare_universalssl: 'on' };
> ```
> 
> Does it work if you remove the `var CF_UNI....` lines in your example?

No! Its not working!... I just tried! 
I removed `var CF_UNI....` lines but nothing happening!

**Comment by tlimoncelli** [comment]
@IzumiSena Would you look at https://github.com/StackExchange/dnscontrol/pull/1358 please?

**Comment by IzumiSena** [comment]
> @IzumiSena Would you look at #1358 please?

Looks good!...
