### ISSUE TITLE
Domain Registrar support for Network Solutions

### ISSUE THREAD

**Issue by shawnz88** [StackExchange/dnscontrol#1363]
We have a list of domains from Network Solutions that we would like to manage with DNSControl. But the registrar is not currently supported. Any suggestions on how to add support for a new registrar?

**Comment by tlimoncelli** [comment]
Hi there!

There's a step-by-step guide for adding new providers: https://stackexchange.github.io/dnscontrol/writing-providers

I'd be glad to coach you through the process if you have any questions.

Please note that if you contribute a provider, you are responsible for responding to bug reports and PR related to it.

Best,
Tom

**Comment by shawnz88** [comment]
@tlimoncelli Our domains are registered with Network Solutions, which is not in the following supported list. Are the steps to add a new registrar the same as the steps to add a provider?

Currently supported Domain Registrars:
AWS Route 53
CSC Global
DNSOVERHTTPS
easyname
Gandi
HEXONET
hosting.de
Internet.bs
INWX
Name.com
Namecheap
OVH
OpenSRS

**Comment by hamptonmoore** [comment]
@shawnz88 do you intend to register with Network Solutions using DNSControl or just manage the DNS zones?

**Comment by shawnz88** [comment]
@hamptonmoore  @tlimoncelli  My use case is to migrate DNS zones from AWS Route 53 to DNSControl and then move them to Azure DNS and manage them in Azure DNS with DNSControl afterwards. All existing domains are registered with Network Solutions. 

Route 53 and Azure DNS are supported providers so I am good there. My only concern is that Network Solutions is not supported registrar and I am wondering what's the implication of that.

**Comment by tlimoncelli** [comment]
That's not a problem.... it just creates some manual work any time you need to change the delegation.

At Stackoverflow we have a number of domains like that (there are some TLDs that are only offered by obscure companies who tend to not have an API).  For those, we just declare:

```
var REG_THIRDPARTY = NewRegistrar("ThirdParty", "NONE"); // i.e. someone else controls it.
```

Then later in `dnsconfig.js` we declare a domain like:

```
D("example.com", REG_THIRDPARTY,
    DnsProvider(DSP_R53),  /// (just an example)
    ...
    ....
);
```

Now the domain works but any changes to the delegation has to be done manually.   Those are very rare for us.

Recently someone supported a provider that is like NONE, but it verifies that the nameservers are correct. It can't fix them, but it's nice to validate that they are set correctly.  See https://stackexchange.github.io/dnscontrol/providers/doh

**Comment by shawnz88** [comment]
@tlimoncelli  Thanks for the info. I am closing the issue.

**Comment by tlimoncelli** [comment]
I just updated https://stackexchange.github.io/dnscontrol/nameservers to be more clear about this situation. Enjoy!
