### ISSUE TITLE
Hetzner: dnscontrol create-domains does not work if no zones are present yet

### ISSUE THREAD

**Issue by nomeata** [StackExchange/dnscontrol#1370]
Just about to start using `dnscontrol`, and it seems that the Hetzner DNS support does not support creating zones there?
```
~/projekte/dns $ dnscontrol create-domains 
***  nomeata.de
  - hetzner
{"zones":[],"meta":{"pagination":{"page":0,"per_page":0,"previous_page":0,"next_page":0,"last_page":0,"total_entries":0}},"error":{"message":"zone not found","code":404}}

Error creating domain: failed fetching zones: bad status code from HETZNER: 404 not 200
```

Unless I am doing something wrong, and this is really not supported, maybe the tool could give a help suitable error message?

Ping @das7pad.

**Comment by nomeata** [comment]
Ah, it works after I have created a fist domain in the DNS console.

**Comment by tlimoncelli** [comment]
CC @das7pad

Interesting!  Do you think there's a bug in dnscontrol that makes create-domains not work unless there are pre-existing domains?  At a minimum we should update `docs/_providers/hetzner.md` to have a warning and a workaround.  At best, we should fix the code.

**Comment by nomeata** [comment]
That's my observation: it failed until I manually added one domain. I didn't debug, but maybe the code path that lists existing domains fails (404) if the list is empty, and then dnscontrol falls over.

**Comment by das7pad** [comment]
Thanks for the ping. Based on their API documentation at https://dns.hetzner.com/api-docs/#operation/GetZones, a 404 is not to be expected when listing zones.
I've opened https://github.com/StackExchange/dnscontrol/pull/1371 with a workaround while I get in contact with their support.

**Comment by tlimoncelli** [comment]
Thanks!  I appreciate the fast response!
