### ISSUE TITLE
Fails on Cloudflare CAA record

### ISSUE THREAD

**Issue by timkgh** [StackExchange/dnscontrol#1374]
I can push a CAA record to Cloudflare, but then when I preview again I get an error:

```
----- DNS Provider: cloudflare...
ERROR
Error getting corrections: unparsable record received from cloudflare: CAA value does not contain 3 fields: ("0 issue \"letsencrypt.org; validationmethods=dns-01; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/1234\"")
```

Record in `dnsconfig.js`:
`CAA('@', 'issue', 'letsencrypt.org; validationmethods=dns-01; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/1234'),`

**Comment by timkgh** [comment]
It appears the spaces in the 3rd value are causing the error. If I remove the spaces, it works. But still a bug that should probably be fixed in dnscontrol.

**Comment by tlimoncelli** [comment]
I can't believe I found a solution so quickly.  I was going to leave this for later but it looks like that PR should be sufficient.  I have one more (unrelated) thing on my todo list before I merge that.
