### ISSUE TITLE
Latest Docker image seems broken

### ISSUE THREAD

**Issue by djbe** [StackExchange/dnscontrol#1375]
Getting this error when using the latest docker image:
> failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

This issue wasn't present 3 days ago, when the latest tag was v3.11.0 (from 6 months ago). The issue happens during "setup" of CI.

Extra info:
- using bitbucket pipelines
- invoking `dnscontrol preview` and `dnscontrol push`

**Comment by juliusrickert** [comment]
It appears to me that your Bitbucket pipeline is manually setting the entrypoint to a shell. The `dnscontrol` image is shipping without a shell and [uses the Go binary as the entrypoint](https://github.com/StackExchange/dnscontrol/blob/98a951885eb67ce6d8aaefdb31ec5c11c04a7dbf/Dockerfile#L2).

But this is just me speculating without knowing anything about Bickbucket pipelines.

**Comment by djbe** [comment]
To clarify, this is even before the pipeline starts running (it hasn't even checked out the repo or anything). 

The config looks something like this:
```yaml
pipelines:
  default:
    - step:
      name: Preview
      image: stackexchange/dnscontrol
      script:
        - dnscontrol preview
```

I don't expect you to know anything about bitbucket pipelines, but from what I can gather it's just your typical CI thing of using a docker image as a runner 🤷 I've tried checking the docs:
- [This doc](https://support.atlassian.com/bitbucket-cloud/docs/use-docker-images-as-build-environments/) is about using custom images, no requirements listed there
- [This doc](https://support.atlassian.com/bitbucket-cloud/docs/write-a-pipe-for-bitbucket-pipelines/) is about creating your own docker image for bitbucket CI, and explicitly mentions overriding `ENTRYPOINT`.

I'm honestly not sure what's even going on in that error tbh 🤔

**Comment by djbe** [comment]
A found a potential solution:
https://stackoverflow.com/questions/54820846/starting-container-process-caused-exec-bin-sh-stat-bin-sh-no-such-file

Not sure if I understand it correctly though. Is it saying that a `scratch` image cannot have an `ENTRYPOINT` like that?

**Comment by djbe** [comment]
Hmmm seems like the images based on `scratch` have been removed from docker hub?
- The highest versioned one right now is v3.11.0. Versions 3.12 and later are no longer there.
- At some point the 3.13 RC images were on docker hub, that's when I created this issue.
- The `latest` "tag" now points back to 3.11

**Comment by djbe** [comment]
If it helps any, I used github actions to build docker images, you can find the config here.
https://github.com/SwiftGen/swift-docker/blob/main/.github/workflows/docker-image-ci.yml

**Comment by jauderho** [comment]
@juliusrickert Docker may have removed building but AFAIK, you can still push to Docker Hub after building elsewhere. For example, I've been publishing dnscontrol images for a while now at https://hub.docker.com/r/jauderho/dnscontrol/

- Dockerfile - https://github.com/jauderho/dockerfiles/blob/main/dnscontrol/Dockerfile
- GHA workflow - https://github.com/jauderho/dockerfiles/blob/main/.github/workflows/dnscontrol.yml

**Comment by juliusrickert** [comment]
@jauderho Sure. But DNSControl relied on that for building the images.

**Comment by jauderho** [comment]
Nvm, I forgot that @tlimoncelli had indicated that they were moving to CircleCI. But I don't see why CircleCI can't push to Docker Hub.

**Comment by juliusrickert** [comment]
It can for sure. But it's not set up yet.

**Comment by cdhunt** [comment]
Sorry for the slow response. The docker image does have `dnscontrol` as the `entrypoint`. You should be able to pass arguments as part of the `docker run cmd`. eg `docker run --rm -it -v $PWD:/dns stackexchange/dnscontrol version`  It's not intended to be used as a `build execution` environment. 

If you can execute `docker run` from your workflow you should be able to use the image. Otherwise, could you pull the binaries into a build container with a shell (`atlassian/default-image:3`)? We have a preview release published to a [CloudSmith repository](https://cloudsmith.io/~stackoverflow/repos/dnscontrol/setup/#formats-rpm) or you can grab the binary directly from GitHub (https://github.com/StackExchange/dnscontrol/releases/download/latest/dnscontrol-Linux).

**Comment by tlimoncelli** [comment]
I believe this is fixed. If not, please re-open this issue.
