### ISSUE TITLE
FEAT: Add detailed exit codes

### ISSUE THREAD

**Issue by norman-zon** [StackExchange/dnscontrol#1395]
dnscontrol always returns 0, when it runs successfully. But having detailed exit codes to determine, for example, if corrections are necessary would be a great benefit for CI jobs.

Terraform does it the [same way](https://www.terraform.io/cli/commands/plan#detailed-exitcode).

**Comment by tlimoncelli** [comment]
The `preview` and `push` subcommands have:

```
   --expect-no-changes         set to true for non-zero return code if there are changes (default: false)
```

Is that sufficient?

**Comment by norman-zon** [comment]
Absolutely! Sorry I didn't find the option myself and had to ask.
Keep up the great work!
