### ISSUE TITLE
package context: unrecognized import path "context"

### ISSUE THREAD

**Issue by tibu** [StackExchange/dnscontrol#140]
When I try to install the package I get 

`package context: unrecognized import path "context" (import path does not begin with hostname)`

**Comment by tibu** [comment]
`$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tibu/go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
`

**Comment by captncraig** [comment]
You need a more recent version of go. I'd recommend 1.8.4 at this point.

**Comment by tibu** [comment]
Ok, thanks. Would be worth to mention this on the main page. On the other side I already solve this by adding full path to the context package. I'm not sure you wanted to merge it into the main repo but it helped me.

**Comment by captncraig** [comment]
Yeah, I'll note that. Thanks.

**Comment by captncraig** [comment]
Its not the "full path" to the context package, `golang.org/x/net/context` is a different package than `context` which was added to the standard library in go 1.7. I'll add a note to the readme.
