### ISSUE TITLE
DNS over HTTPS (DoH) provider not checking delegation

### ISSUE THREAD

**Issue by juliusrickert** [StackExchange/dnscontrol#1402]
The DNS over HTTPS (DoH) provider is solely a _registrar_ provider, intended to check whether the nameservers at the registrar are matching those of the zone.

But instead, it checks the _zone's_ `NS` records, so it does not check whether the _delegation_ is correct.

#### Example (from my list of weird DNS setups :D)

```bash
$ dig @a.gtld-servers.net vallourec.com ns
…
;; AUTHORITY SECTION:
vallourec.com.		172800	IN	NS	dns1.vallourec.fr.
vallourec.com.		172800	IN	NS	dns2.vallourec.fr.
vallourec.com.		172800	IN	NS	dns3.vallourec.fr.
…

$ dig @dns1.vallourec.fr vallourec.com ns
…
;; ANSWER SECTION:
vallourec.com.		28800	IN	NS	dns2.vallourec.fr.
vallourec.com.		28800	IN	NS	dns1.vallourec.fr.
…
```

##### dnsconfig.js

```js
var DOH = NewRegistrar('doh', 'DNSOVERHTTPS');

var BIND = NewDnsProvider('bind', 'BIND');

D('vallourec.com', DOH, DnsProvider(BIND), [
  NAMESERVER('dns1.vallourec.fr.'),
  NAMESERVER('dns2.vallourec.fr.'),
]);
```

##### Result

```bash
$ dnscontrol push
******************** Domain: vallourec.com
----- Getting nameservers from: bind
----- DNS Provider: bind...
0 corrections
----- Registrar: doh...
0 corrections
Done. 0 corrections.
```

##### Expected

```bash
$ dnscontrol push
******************** Domain: vallourec.com
----- Getting nameservers from: bind
----- DNS Provider: bind...
0 corrections
----- Registrar: doh...
1 correction
#1: Update nameservers dns1.vallourec.fr,dns2.vallourec.fr,dns3.vallourec.fr -> dns1.vallourec.fr,dns2.vallourec.fr
FAILURE! DNS-over-HTTPS 'Registrar' is read only, changes must be applied to vallourec.com manually
Done. 1 corrections.
completed with errors
```

**Comment by tlimoncelli** [comment]
CC @mikenz

**Comment by tlimoncelli** [comment]
Here's my take on this:

This is a documentation issue, not a code bug.  The documentation should be clear about that.

Here's my suggested change: https://github.com/StackExchange/dnscontrol/issues/1402

Thoughts?

**Comment by juliusrickert** [comment]
So this provider can only check that it exists a delegation that results in an authoritative nameserver returning the _expected_ nameserver set or a nameserver set differing from the nameserver set expected.

So running DNSControl without changes expected—assuming no other state changes—depends on the resolver choosing an authoritative nameserver that provides the nameservers DNSControl expects.

Imagine I were to dual host my zone with Cloudflare (NS for Cloudflare only) and Route 53 (NS for Cloudflare and Route 53).
The zone is correctly delegated to both.
My `dnsconfig.js` only features Cloudflare, so DNSControl expects only Cloudflare to be featured in the nameserver set.

Now, depending on which delegation the resolver chooses, my run will either fail or succeed.
If the resolver chooses Cloudflare the run will succeed.
If it chooses Route 53 it will fail.

This issue can persist for some time when the resolver caches the nameserver set provided by the authoritative nameserver and not the one indicated by the parent zone.

**Comment by juliusrickert** [comment]
That's not the point I was trying to make. Sorry for the confusion.
I didn't pick Cloudflare to demonstrate that this is broken with single-homed providers, but rather to pick an example where it's clear that the zones wouldn't match.

Example dnsconfig.js:

```js
var REG_DOH = NewRegistrar('doh', 'DNSOVERHTTPS');

var DNS_CLOUDFLARE = NewDnsProvider('cloudflare', 'CLOUDFLARE');

D('example.com', REG_DOH, DnsProvider(DNS_CLOUDFLARE, 2));
```

Delegation in `com.` zone, featuring an unexpected delegation to Route 53:

- `alice.ns.cloudflare.com.` (expected, present at Cloudflare DNS and Route 53)
- `bob.ns.clouflare.com.` (expected, present at Cloudflare DNS and Route 53)
- `ns-1.awsdns-2.com.` (unexpected, present at Route 53 only)
- `ns-3.awsdns-4.org.` (unexpected, present at Route 53 only)

Performing `dnscontrol push` can lead to two states now:

#### 1. The DoH resolver chooses a Cloudflare DNS delegation

Cloudflare will return the expected nameserver set. DNSControl will succeed.

#### 2. The DoH resolver chooses a Route 53 delegation

Route 53 will return the expected nameservers and two additional, unexpected nameservers. DNSControl will fail.

**Comment by tlimoncelli** [comment]
Since  @mikenz wrote the provider, I'll let him reply.
