### ISSUE TITLE
NS1: remove strings.Split(fmt.Sprintf(), " ") invocations

### ISSUE THREAD

**Issue by costasd** [StackExchange/dnscontrol#1406]
In `buildRecord()`, we use the following trick a lot to create an array of strings, which is what the ns1 api client is expecting for rdata.
```
strings.Split(fmt.Sprintf("%d %v", r.MxPreference, r.GetTargetField()), " ")
```
Effectively it joins and casts attributes into a single string and then splits it by space to get the array. Unfortunately this is guaranteed to break if an attribute contains spaces, such as in #1404.

Fix that by replacing this trick with something that works independently of attribute contents.
replace:
```
strings.Split(fmt.Sprintf("%d %s %v", intAttribute, stringAttribute, otherAttribute), " ")
```
with 
```
[]string{
fmt.Sprintf("%d", intAttribute),
stringAttribute,
fmt.Sprintf("%v", otherAttribute)
}

**Comment by costasd** [comment]
Or... as @tlimoncelli suggested, `strconv.Itoa` where supported.

**Comment by tlimoncelli** [comment]
Fixed by https://github.com/StackExchange/dnscontrol/pull/1405
