### ISSUE TITLE
netcup: Long `TXT` records cause unnecessary entry modification

### ISSUE THREAD

**Issue by nomeata** [StackExchange/dnscontrol#1416]
When pushing domains to netcup, I observe that long `TXT` records (e.g. domainkeys) are fetched without any breaks, but pushed with a space inserted after a certain length. This causes `dnscontrol` to think the entry has to be updated.

**Comment by tlimoncelli** [comment]
CC @kordianbruck (the maintainer of that provider)

P.S.  Running the integration tests (see Step 7 of [this doc](https://stackexchange.github.io/dnscontrol/writing-providers) should help debug this.

**Comment by tlimoncelli** [comment]
@kordianbruck: Anything I can do to help?   I'd like to see this fixed this month if possible.

**Comment by Olivetti** [comment]
My quick hack is commenting out 'txtutil' in netcupProvider.go:

`--- netcupProvider.go.bak	2022-03-07 19:51:14.000000000 +0100
+++ netcupProvider.go	2022-03-08 11:46:14.511889706 +0100
@@ -6,7 +6,7 @@ import (
 
 	"github.com/StackExchange/dnscontrol/v3/models"
 	"github.com/StackExchange/dnscontrol/v3/pkg/diff"
-	"github.com/StackExchange/dnscontrol/v3/pkg/txtutil"
+//	"github.com/StackExchange/dnscontrol/v3/pkg/txtutil"
 	"github.com/StackExchange/dnscontrol/v3/providers"
 )
 
@@ -98,7 +98,7 @@ func (api *netcupProvider) GetDomainCorr
 
 	// Normalize
 	models.PostProcessRecords(existingRecords)
-	txtutil.SplitSingleLongTxt(dc.Records) // Autosplit long TXT records
+//	txtutil.SplitSingleLongTxt(dc.Records) // Autosplit long TXT records
 
 	differ := diff.New(dc)
 	_, create, del, modify, err := differ.IncrementalDiff(existingRecords)
`

**Comment by tlimoncelli** [comment]
Yup!  That looks like the right thing!  Thanks for investigating that!

@Olivetti Could you submit a PR with that change?   

Tom

P.S. When you submit the PR, please post as a comment the output of the integration test.  Thanks!

**Comment by Olivetti** [comment]
Yes, i'll try my best and hopefully can count on your support if i get stuck at testing (never did).

**Comment by Olivetti** [comment]
Hello Tom, here it comes … #1481

**Comment by tlimoncelli** [comment]
Fixed by https://github.com/StackExchange/dnscontrol/pull/1481
