### ISSUE TITLE
preview always shows changes for CloudFlare A record

### ISSUE THREAD

**Issue by markdorison** [StackExchange/dnscontrol#142]
One of the A records in my CloudFlare DNS configuration always shows as modified when I run `dnscontrol preview`. When I run `push` it claims to have executed a change, but a subsequent run of `preview` shows a diff with a new id. See example below.

Example with sanitized values:
```
----- Getting nameservers from: cloudflare.com
----- DNS Provider: cloudflare.com... 2 corrections
#1: DELETE record: tk.mydomain.com A 1 151.101.1.69 (id=99999999999999999999999999999999)
#2: CREATE record: tk.mydomain.com A 1 151.101.1.69
----- Registrar: none
```

**Comment by captncraig** [comment]
Can you share your input for this domain?

**Comment by markdorison** [comment]
@captncraig Sure:

```
D("shouldiupgradetodrupal8.com", REG_NONE, DnsProvider(CFLARE),
  CF_PROXY_DEFAULT_OFF,
  A('tk.mydomain.com', '151.101.1.69', TTL(1), CF_PROXY_OFF),
);
```

**Comment by tlimoncelli** [comment]
I haven't seen something like that before.  Is id=99999999999999999999999999999999 real or did you redact the actual ID number?  (I ask because that's a rather odd id).

Does the bug happen with TTL(300)?

**Comment by captncraig** [comment]
Likely an issue with the syntax. You should not indlude the full domain name in the A record part.

Should probably just be `A('tk', '151.101.1.69', TTL(1), CF_PROXY_OFF),`

**Comment by markdorison** [comment]
@tlimoncelli I redacted the id. Changing the TTL does not change the issue.

**Comment by markdorison** [comment]
> Likely an issue with the syntax. You should not indlude the full domain name in the A record part.

This solved the issue. Thank you!
