### ISSUE TITLE
Documentation Examples not being formatted correctly

### ISSUE THREAD

**Issue by misilot** [StackExchange/dnscontrol#1420]
Function example are showing raw text instead of parsing the Markdown tags

````
```js
````

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/1446856/155807034-41eb628d-ce6d-4e0d-9e42-c636039a5b0a.png">

**Comment by tlimoncelli** [comment]
Hey @juliusrickert !  It looks like d5665ceaf65ca93a0d06075c2eeea642e6935581 had an unexpected bug.  Can you take a look?

**Comment by tlimoncelli** [comment]
(also... I don't find much value in having the examples hidden until the triangle is clicked.  Do you?  I'd be fine with removing that.)

**Comment by tlimoncelli** [comment]
To build the pages locally, use the command in the README.md file:

```bash
cd docs
docker run --rm -it --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" --env JEKYLL_ENV=production jekyll/jekyll:3.8 jekyll build -V
```

You can add `--watch` to the end of the line if you want it to auto-regenerate.

Note: Links that use the site.github.url variable don't work.  It's on my list of things to investigate too.

**Comment by juliusrickert** [comment]
Sorry for the delay.

Didn't get Jekyll to work with Rancher Desktop.
Ended up reinstalling Docker Desktop.
