### ISSUE TITLE
GoDaddy Support

### ISSUE THREAD

**Issue by rnhurt** [StackExchange/dnscontrol#145]
I would like to add my request for GoDaddy support.  It looks like they have a pretty good [REST API](https://developer.godaddy.com/doc) and some [tips to get started](https://developer.godaddy.com/getstarted).  Both DNS and Registrar support would be good to have.

BTW: I tried to take a stab at adding a provider but my Go skills are nearly non-existent.  :(

**Comment by tlimoncelli** [comment]
Thanks for the request and the links to the API stuff.  I've added this to our "list of requested providers" and linked to this Github Issue.  If someone picks this project up, we'll re-open this ticket.

By the way... other people with little Go experience have written providers. You basically copy a provider with a similar API and go from there. We'd be glad to help you with any questions along the way.

**Comment by rnhurt** [comment]
So, I'm trying to get something, anything, working and am hitting an early snag.  I've followed [the directions](godaddyProvider.go) and created a new `providers/godaddy/godaddyProvider.go` file but it looks like the build is ignoring it.  I've even injected syntax errors into my code and `go build` completes without complaining.  Also, I get this when I tried to test my code:

    $ ./dnscontrol preview
    2017/06/21 22:55:20 main.go:132: Error creating dsps: DSP type GODADDY not declared

_NOTE: One suggestion I have to help newbies would be to create a working "example" provider file instead of telling us to copy one of the other files.  This gives us a clean place to start without a lot of overhead and allows us to replace functions with actual, working code in a piecemeal manor._

**Comment by captncraig** [comment]
Ah, that is a bit hidden, but you need to add your package to [`all.go`](https://github.com/StackExchange/dnscontrol/blob/master/providers/_all/all.go) to get it linked to the rest of the code.

**Comment by rnhurt** [comment]
Hmmm... my provider is listed with the other providers in the `all.go` file, but I'm still not able to get it to fail to build (or actually use my godaddy provider either).  Any other hints?

> 	....
        _ "github.com/StackExchange/dnscontrol/providers/route53"
	_ "github.com/StackExchange/dnscontrol/providers/godaddy"
)

**Comment by captncraig** [comment]
Do you have a branch on a fork I can take a look at?

**Comment by rnhurt** [comment]
I do now: https://github.com/rnhurt/dnscontrol/tree/godaddy_dns

I should have done this first so you could see what I'm doing.

**Comment by tlimoncelli** [comment]
If I check that out `~/src/github.com/rnhurt/dnscontrol` I get the same problem.

If I check that out as `~/src/github.com/StackExchange/dnscontrol` then it compiles.

Maybe I don't understand how vendoring works but that seems odd.

**Comment by pmoroney** [comment]
I believe that is because the import paths are not relative to the local repo. So if it is trying to import github.com/StackExchange/dnscontrol/providers/godaddy but that actually exists in github.com/rnhurt/dnscontrol/providers/godaddy it won't load

**Comment by rnhurt** [comment]
Ah, I think I have it now.  My problem was two fold; both the location of my source code and the pathing of the provider was wrong.  Being a non-Go programmer I didn't realize that it was sensitive to where your source code was located.  Once I moved my code into my GOPATH directory things started to change for the better; at least the build was failing now.  😄 

The next step was to localize the paths in `all.go` as well as `main.go` to use `github.com/rnhurt/dnscontrol/providers` instead of the default `github.com/StackExchange/dnscontrol/providers`.  My code still doesn't work but at least it compiles now.  😄   However, this pathing thing seems wrong.  Does everyone else upload their code to the StackExchange repo before compiling it?

**Comment by pmoroney** [comment]
I typically clone the stackexchange repo, but then add a remote so I can
push to my fork, but I am still new at this so others may have a better
flow.

**Comment by captncraig** [comment]
Yeah, all of the files really need to live under $GOPATH/src/github.com/stackexchange/dnscontrol, or else you have to change like every file. Best policy is to keep it there, and add separate remotes for each fork.

**Comment by rnhurt** [comment]
I seem to be making good progress; I can talk to the GoDaddy API and get a list of records.  😄  Now I'm working on building the diff and am getting a weird panic.  What does it mean when the error is "DUPLICATE E_RECORD FOUND"?  I can't seem to find a duplicate record at all, it just looks like it's complaining if there are two records of any type (A, CNAME, etc.) regardless of what the Target is.

    panic: DUPLICATE E_RECORD FOUND: { CNAME} @. 3600

BTW: Is there a better place to discuss these things?

**Comment by tlimoncelli** [comment]
I'm traveling right now but I believe you are in the right direction.  The provider should expand @ before sending to diff.  When doing updates it can shorten domains to "@" if it wants.  The point is that the provider produces a canonical format that diff can use.

P.S.  Good work so far!  You've come a long way!

**Comment by rnhurt** [comment]
Ok, it looks like I have the basic preview functionality working.  Using
the `github.com/miekg/dns/dnsutil` package helped with some of the details
around domain names.

Next up, making CREATE work.  :)

Later...

Richard Hurt
<http://www.facebook.com/rnhurt>  <http://www.twitter.com/rnhurt>
<http://www.linkedin.com/in/rnhurt>  <http://github.com/rnhurt>

**Comment by tlimoncelli** [comment]
thumbs up!

**Comment by settle0x** [comment]
any update here? :)

**Comment by rnhurt** [comment]
Sorry, I have not worked on this in years.  In fact, I had completely forgotten what this project was or that I tried to write Go code at all.  :laughing: 

Feel free to take my (meager, non-working, completely out of date) code and do with it what you wish.  Honestly, you're probably better off starting from scratch.  :shrug:
