### ISSUE TITLE
Docker Image with v3.15.0

### ISSUE THREAD

**Issue by aba-rechsteiner** [StackExchange/dnscontrol#1459]
for the release v3.15.0 there is no Docker image on [Docker Hub](https://hub.docker.com/r/stackexchange/dnscontrol/tags) yet. Would it be possible to create one?

**Comment by aba-rechsteiner** [comment]
@tlimoncelli can you please have a look at this?

**Comment by aba-rechsteiner** [comment]
@tlimoncelli please trigger the docker image build pipeline

**Comment by adrian-hoasted** [comment]
+1 would love to have a version bump with cloudflare PTR support

**Comment by extremeshok** [comment]
@tlimoncelli do you need help with the docker images ?

**Comment by fdcastel** [comment]
Who is the current maintainer for dnscontrol docker image? If there is none, I would like to apply for the job 😉

**Comment by tlimoncelli** [comment]
Yes. I definitely need assistance.  I don't know docker very well and I'm unsure how to properly integrate it into our current CI/CD pipeline.

CC @ghost who asked the same question in https://github.com/StackExchange/dnscontrol/issues/1534

What I'm looking for is someone to decide what the docker result should be, send me a PR that implements that, instruct me if there is something I'd need to do with each release.

**Comment by fdcastel** [comment]
Looking into it!

**Comment by jauderho** [comment]
@tlimoncelli Does it have to be CircleCI? As previously mentioned, I already have a working GHA workflow and it has been working with no issue for over a year now. 

Not the fastest but it works. 

* Workflow: https://github.com/jauderho/dockerfiles/blob/main/.github/workflows/dnscontrol.yml
* Dockerfile: https://github.com/jauderho/dockerfiles/blob/main/dnscontrol/Dockerfile
* Docker Hub: https://hub.docker.com/r/jauderho/dnscontrol/tags

@fdcastel This should be easily adaptable into a pull request for @tlimoncelli

**Comment by fdcastel** [comment]
I'm very short on time right now, but I promise to look further into this in a few days. 

@jauderho Thanks for the great work!

**Comment by tlimoncelli** [comment]
It doesn't have to be CircleCI.

In 12-18 months we plan on moving to CircleCI but at that point we can re-use what you develop.

**Comment by aba-rechsteiner** [comment]
@tlimoncelli thanks for taking care of this. Should it have a new image docker hub now?
