### ISSUE TITLE
HEXONET: Update github.com/hexonet/go-sdk/v3

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1460]
Tests are failing. 

"In case you experience trouble with DNSControl's automated tests for provider HEXONET: Our OT&E System switched to another DC and its endpoint URL has changed. We released an update of our GO-SDK (https://github.com/hexonet/go-sdk, v3.5.3) in the go module namespace v3 that you just might to update. It is a dependency of our provider module."

**Comment by papakai** [comment]
Please rely on the domain provided via PM. Just in case you guys again experience issues with the test domain, we will find another way. actually you're using a demo user that is accessible in public and anyone could apply changes or move it away.
