### ISSUE TITLE
Question: How to set a default nameserver for multiple zones?

### ISSUE THREAD

**Issue by riku22** [StackExchange/dnscontrol#1483]
Hello.

I created a delegation set in Route53.
And I'm trying to use the white-labeled name server with the delegation set I created.
Is there a way to use the white-labeled name server created in multiple zones using Route53 as the default?
I know it can be overwritten with `NAMESERVER`, but writing many of the same records is hard and can lead to mistakes.
Do you have any ideas?

Best regards.

**Comment by tlimoncelli** [comment]
I don't know much about delegation sets, but I do know a little something about repeating records (and the pain created when they aren't all the same!).

For example, you can define a list of records and re-use them in many different `D()` statements.  Some examples are here: https://stackexchange.github.io/dnscontrol/code-tricks

Does that help?  if not, please show me what you've tried so far.

I'd also like to see your working result (redacted, of course) for potential inclusion in the documentation.

Tom

**Comment by riku22** [comment]
Hello.

Thank you for your advice.
I think I can do what I want by using the list.
Thank you very much.

Best regards.
