### ISSUE TITLE
Provider request: Imperva

### ISSUE THREAD

**Issue by scoobydooxp** [StackExchange/dnscontrol#1484]
Imperva has a DNS API for their DNS protection service. It would be amazing to have support added to dnscontrol for it.

https://docs.imperva.com/bundle/cloud-application-security/page/dns-api-definition.htm

**Comment by tlimoncelli** [comment]
Thank you for requesting this provider!

I've tagged this issue as a provider-request.  It will (soon) be listed as a    "requested provider" on the provider list web page:
https://docs.dnscontrol.org/service-providers/providers

I will now close the issue.  I know that's a bit confusing, but it will remain  on the "requested provider" list.

If someone would like to volunteer to implement this, please re-open this issue and add the tag `has-pr`.

We encourage you to try adding this provider yourself.  We've tried to make the process as friendly as possible.  Many people have reported that adding a       provider was their first experience writing Go.  The process is documented here:
https://docs.dnscontrol.org/developer-info/writing-providers
If you need assistance, please speak up in this issue and someone will get back to you ASAP.
