### ISSUE TITLE
CLOUDFLAREAPI (Cloudflare DNS) add PTR support

### ISSUE THREAD

**Issue by adrian-hoasted** [StackExchange/dnscontrol#1492]
Cloudflare DNS has PTR support

https://www.cloudflare.com/en-gb/learning/dns/dns-records/dns-ptr-record/

https://developers.cloudflare.com/dns/additional-options/reverse-zones/

Fixes:  
```
ERROR: domain xx.xx.xx.in-addr.arpa uses PTR records, but DNS provider type CLOUDFLAREAPI does not support them
```

**Comment by extremeshok** [comment]
+1

**Comment by tlimoncelli** [comment]
I'm glad to hear they added PTR support.  Please send a PR!  

Github will run tests for you.  You can also run tests locally with the instructions in [Creating new DNS Resource Types (rtypes)](https://stackexchange.github.io/dnscontrol/adding-new-rtypes)  (I can help with running tests, etc.)

**Comment by adrian-hoasted** [comment]
@tlimoncelli I have started with a PR #1496

**Comment by tlimoncelli** [comment]
Thanks for the PR!
