### ISSUE TITLE
About SOA records on Gcloud

### ISSUE THREAD

**Issue by riku22** [StackExchange/dnscontrol#1504]
Hello.

I'm trying to change a SOA record in Gcloud.
However, the following error is displayed and I cannot change it.

`printIR.go:94: ERROR: domain example.com uses SOA records, but DNS provider type GCLOUD does not support them`

SOA records are listed under [Supported DNS record types] and can be changed from the web.
Is this an API limitation?

Best regards.

[Supported DNS record types]: https://cloud.google.com/dns/docs/records-overview#supported_dns_record_types

**Comment by tlimoncelli** [comment]
Those two fields (the nameserver and email address) aren't used any more.

Your nameservers are specified by the NS records of the parent domain. The value in the SOA is ignored.  It used to be used to indicate which nameserver was the primary for zone transfers, but that kind of info is now stored in the configuration of the DNS servers involved in the transfer.

The email address is only used by spammers.

You can set the nameserver of the parent domain using the NAMESERVER() function.  It won't update the SOA record but like I said, nobody uses the information in the SOA record any more. (The one exception is ISC BIND, but that provider has support for SOA records)

**Comment by riku22** [comment]
Hi.

> You can set the nameserver of the parent domain using the NAMESERVER() function. It won't update the SOA record but like I said, nobody uses the information in the SOA record any more. (The one exception is ISC BIND, but that provider has support for SOA records)

Yes, I am using NAMESERVER records and was wondering because the nameservers in the SOA records are not changing.
Thank you very much for your help.

Best regards.
