### ISSUE TITLE
[Feature] Check for different TTLs on records of same name

### ISSUE THREAD

**Issue by norman-zon** [StackExchange/dnscontrol#1505]
Despite not being describet in the [RFC1035](https://www.rfc-editor.org/rfc/rfc1035), it seems to be a quasi standard to normalize TTLs across records of the same name.
For example, a record like this:
```
TXT('@', 'mytext1', TTL(300)),
TXT('@', 'mytext2', TTL(6000)),
```
will be normalized to use only one TTL by most providers, which makes sense, as described [here](https://superuser.com/a/1036682).

It would be a nice feature for dnscontrol to check for records of the same name, that have differing TTLs and warn about them in the validation.

**Comment by tlimoncelli** [comment]
Funny you should mention that!  https://github.com/StackExchange/dnscontrol/pull/1489 warns about this and will be in the next release.

**Comment by tlimoncelli** [comment]
Another side-effect if this is some DNS providers update the TTLs on the related records to match the last inserted.  Dnscontrol's next run tried to fix those records, which then begins a loop where each run of dnscontrol thinks there are records to be updated.

**Comment by norman-zon** [comment]
> Another side-effect if this is some DNS providers update the TTLs on the related records to match the last inserted. Dnscontrol's next run tried to fix those records, which then begins a loop where each run of dnscontrol thinks there are records to be updated.

That's what I experienced with NS1
