### ISSUE TITLE
CLOUDFLARE: Quotes around TXT records mishandled

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1509]
CC @tresni 

When a TXT record includes quotes around a TXT string, it never doesn't do the update correctly.  I tested this with NAMEDOTCOM and didn't see the problem there.  I think the bug must be in the Cloudflareapi provider itself.

How to reproduce:

Create a domain that uses Cloudflare as the DSP.  Include a TXT record with double-quotes around the string:

```
D("yesthatblog.com", ...
...
    TXT("test1", '"thing"'),
...
);
```

When you "preview" or "push", it keeps trying to do the update over and over.

```
$ dnscontrol push --domains yesthatblog.com
******************** Domain: yesthatblog.com
----- Getting nameservers from: cloudflare_tal
----- DNS Provider: cloudflare_tal...
1 correction
#1: MODIFY TXT test1.yesthatblog.com: ("thing" ttl=1) -> ("\"thing\"" ttl=1)
SUCCESS!
----- Registrar: gandi_v5_tal...
0 corrections
Done. 1 corrections.
$ dnscontrol push --domains yesthatblog.com
******************** Domain: yesthatblog.com
----- Getting nameservers from: cloudflare_tal
----- DNS Provider: cloudflare_tal...
1 correction
#1: MODIFY TXT test1.yesthatblog.com: ("thing" ttl=1) -> ("\"thing\"" ttl=1)
SUCCESS!
----- Registrar: gandi_v5_tal...
0 corrections
Done. 1 corrections.
```

**Comment by tlimoncelli** [comment]
I noticed this too.  https://github.com/StackExchange/dnscontrol/issues/1509   I used the same work-around.

@tresni Brian: Any thoughts on this?

**Comment by tlimoncelli** [comment]
FYI: `git diff v3.12.0 v3.13.0 providers/cloudflare` shows a lot of changes between those versions.

**Comment by tlimoncelli** [comment]
I think I found the problem! PR is progress: https://github.com/StackExchange/dnscontrol/pull/1538

**Comment by tresni** [comment]
You are too fast for me :)

**Comment by tlimoncelli** [comment]
No worries, @tresni.  I was Oops... I merged the PR to master before verifying the fix worked.  

Hey, @virtualroot, can you verify that this fixed your issue?

Tom

P.S.  @tresni no worries. I think github's notifications don't always get delivered.

**Comment by tlimoncelli** [comment]
https://github.com/StackExchange/dnscontrol/pull/1538 fixed only half of the problem. I see legacy domains with TXT records that have inappropriate quotes in them.  DNSControl should notice those and fix them.

Here's an example:
<img width="682" alt="screencapture_2022-06-17_12 59 18" src="https://user-images.githubusercontent.com/6293917/174344057-965d896e-093a-4c1e-896e-cafdca876712.png">

Some of the TXT records were inserted with quotes (this was a bug in dnscontrol a long, long, time ago) and others without.  As a result, those SPF records are invalid.

I'll look into why dnscontrol isn't correcting those.

**Comment by tlimoncelli** [comment]
Side note... Cloudflare may be "fixing this" at the back end:

```
$ host -t txt _spf5.askpatents.com
_spf5.askpatents.com descriptive text "v=spf1 ip4:146.20.112.0/26 ip4:161.38.192.0/20 ip4:143.55.224.0/21 ip4:143.55.232.0/22 ip4:159.112.240.0/20 ip4:141.193.32.0/23 ip4:159.135.140.80/29 ip4:159.135.132.128/25 ip4:161.38.204.0/22 ip4:87.253.232.0/21 include:_spf6.askpatents.com ~all"
$ host -t txt _spf6.askpatents.com
_spf6.askpatents.com descriptive text "v=spf1 ip4:185.189.236.0/22 ip4:185.211.120.0/22 ip4:185.250.236.0/22 ip4:143.55.236.0/22 ip4:167.89.0.0/17 ip4:208.117.48.0/20 ip4:50.31.32.0/19 ip4:198.37.144.0/20 ip4:198.21.0.0/21 ip4:192.254.112.0/20 include:_spf7.askpatents.com ~all"
```

**Comment by tlimoncelli** [comment]
@tresni @virtualroot I've merged this (much better) fix to master.  I found the exact same problem with one of our domains (askpatents.com) and it now finds and fixes the problem that @virtualroot reported.

I'm surprised this bug hasn't bitten other people, especially anyone using the SPF optimizer.

**Comment by jauderho** [comment]
Any chance we can get a point release for this?

**Comment by tlimoncelli** [comment]
> Any chance we can get a point release for this?

Yup!  My plan is a full release Sunday or Monday.
