### ISSUE TITLE
Support for Automatic PTR for A records

### ISSUE THREAD

**Issue by extremeshok** [StackExchange/dnscontrol#1524]
According to the docs: "In the future we plan on adding a flag to A() which will insert the correct PTR() record if the appropriate .arpa domain has been defined."

Any idea when this feature is planned ?

**Comment by adrian-hoasted** [comment]
is there a way to check if there is an existing PTR domain defined for the A record IP of a different domain ? 
along the lines of..
loop A records for mysite.com, 
if  record IP exists in reverse zone 77.66.44.in-addr.arpa
then add PTR for A record under reverse zone
end if
end loop

**Comment by tlimoncelli** [comment]
Interesting question!  Sadly there's no API for that.

A work-around would be to run "dnscontrol check" and remove the PTR() that isn't in the loop.  Repeat until you get no errors.  "dnscontrol check" doesn't talk to the network* or access creds.json, which means it is easy to do this 

Tom

* If you use the SPF optimizer, it will do some network access. We consider this a bug but fixing it is going to be difficult. See https://github.com/StackExchange/dnscontrol/issues/1348

**Comment by tlimoncelli** [comment]
Two more thoughts:

First, to check if a PTR has a matching A record, use the output of `dnscontrol print-ir`. It is a JSON representation of the compiled version of dnsconfig.js.  You can use the information in that JSON file to determine if a PTR has a matching A.

Second, here's a macro that you might find useful:

```
function HOSTIP(ipaddr, name) {

    var dom;
    var fqdn;
    if (name.slice(-1) == ".") { // If name ends with "."
        // If name ends in a ".", we know that name is a FQDN.
        // extract the domain:
        dom = name.slice(name.indexOf(".") + 1);
        dom = dom.slice(0, -1);
        // fqdn is the name.
        fqdn = name
    } else {
        // "name" doesn't end in ".", make some assumptions:
        dom = "mydomain.com"
        fqdn = name + ".mydomain.com.";
    }

    // Add an "A" and "PTR" record for this host:
    D_EXTEND(dom,
        A(fqdn, ipaddr, TTL(ttl))
    );
    D_EXTEND(REV(ipaddr),
        PTR(ipaddr, fqdn, TTL(ptrttl))
    );

}

// PTRTTL(v): Set the TTL for a DNS record.
function PTRTTL(v) {
    if (_.isString(v)) {
        v = stringToDuration(v);
    }
    return function(r) {
        r.ptrttl = v;
    };
}
```

Outside of any D() function, you can now make statements like:

```
HOSTIP("10.7.0.65", "host1.mydomain.com.", TTL(3600));
HOSTIP("10.7.0.64", "host2", TTL(1200), PTRTTL(1200));
```

In the first example we use a FQDN.  In the second example we use a shortname and the macro adds ".mydomain.com".  Also notice that we're able to set different TTLs for the A and TTL record. I don't recommend doing that, but I had to create the macro when I was converting an old domain.

Hope that helps!

Tom
