### ISSUE TITLE
Create Multiple (A) Record From Single VAR

### ISSUE THREAD

**Issue by IzumiSenaSora** [StackExchange/dnscontrol#1527]
We can do like this

`var GitLab = IP('35.185.44.232');`
Results
`example.com IN A 35.185.44.232`

But is it possible to do like this? Or any alternative?

`var Github = IP('185.199.108.153', '185.199.109.153', '185.199.110.153', '185.199.111.153');`
Results
`example.com IN A 185.199.108.153`
`example.com IN A 185.199.109.153`
`example.com IN A 185.199.110.153`
`example.com IN A 185.199.111.153`

**Comment by IzumiSenaSora** [comment]
I think it would be a good idea to make lot of advance config available in docs as an example ... what do you think?
Like how function like this can be useful!...
I am just suggesting .... cause i have no idea how function or java script works...

**Comment by tlimoncelli** [comment]
Good idea!

The docs do have some [Code Tricks](https://stackexchange.github.io/dnscontrol/code-tricks) and notes about [CLI variables](https://stackexchange.github.io/dnscontrol/cli-variables).  I'd be glad to add functions that are useful if people find them.

I, too, am not a javascript expert. Usually when I need anything complex I find a web designer and ask them to write the function for me.  They're generally surprised that I use JS for something unrelated to the web and are happy to help.

Tom
