### ISSUE TITLE
Make it easier to debug credentials (no-op mode or something)

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#153]
It would be useful to have a command (perhaps "dnscontrol test-creds") that would connect to each provider and test whether or not the credentials are working. It should output a LOT of debugging information.

**Comment by captncraig** [comment]
I have recently realized we should probably move towards a convention where the provider initialization should do some operation to test connectivity (usually a list domains or something). Currently, some do and others do not. Some just check that they have valid looking credentials, but never use them until you start getting corrections.

**Comment by tlimoncelli** [comment]
When we add the generic "dnscontrol getzone" command, it can be used for this purpose.

**Comment by tlimoncelli** [comment]
This command should be close.  Still need to test the error messages to see if they are verbose enough.

`dnscontrol get-zones --format=nameonly x y all`

**Comment by tlimoncelli** [comment]
Adding a `check-creds` subcommand: https://github.com/StackExchange/dnscontrol/pull/665

**Comment by tlimoncelli** [comment]
With the inclusion of check-creds, I'm going to consider this issue closed.
