### ISSUE TITLE
Who is the current maintainer of dnscontrol docker image? If there is none, I would like to apply for the job 😉

### ISSUE THREAD

**Issue by ghost** [StackExchange/dnscontrol#1534]
Who is the current maintainer of dnscontrol docker image? If there is none, I would like to apply for the job 😉

_Originally posted by @fdcastel in https://github.com/StackExchange/dnscontrol/issues/1459#issuecomment-1152963626_

**Comment by bybtiz-nedfic-1jigfA** [comment]
Can you fill me in on this please as I'm not quite sure what this is about or means

**Comment by tlimoncelli** [comment]
I put my answer in the original issue: https://github.com/StackExchange/dnscontrol/issues/1459#issuecomment-1153285944

**Comment by fdcastel** [comment]
P.S.: I believe this is a bogus issue created by somebody playing with Github (from an account which is now deleted, hence the "ghost").

This issue can surely be closed.

**Comment by tlimoncelli** [comment]
Ah.  I hadn't clicked on the profile to see what a ghost acct was.  Thanks!
