### ISSUE TITLE
Populate domain at Gandi not working as expected

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1540]
CC @jpbede @TomOnTime

I'm not sure if this is a bug in https://github.com/StackExchange/dnscontrol/pull/1528 or in the Gandi provider, but I'm seeing warnings from Gandi that I don't see elsewhere.

```
$ dnscontrol preview
[...]
******************** Domain: best-spaghetti-sauce-ever.com
----- Getting nameservers from: gandi_v5_tal
WARNING: Domain 'best-spaghetti-sauce-ever.com' does not exist in the 'gandi_v5_tal' profile and will be added automatically.
----- Registrar: gandi_v5_tal...
0 corrections
```

Yet, when we "push" everything is fine:

```
$ dnscontrol push --domains best-spaghetti-sauce-ever.com
******************** Domain: best-spaghetti-sauce-ever.com
----- Getting nameservers from: gandi_v5_tal
----- DNS Provider: gandi_v5_tal...
0 corrections
----- Registrar: gandi_v5_tal...
0 corrections
Done. 0 corrections.
```

**Comment by jpbede** [comment]
E.g. `gcloud` is trimming the dot at the end.

**Comment by tlimoncelli** [comment]
I looked into this and ListZones() is returning an empty list.  Hmm....

**Comment by tlimoncelli** [comment]
I found the issue.... it turns out to be a configuration issue!

My Gandi account didn't have the `sharing_id` set in creds.json, which meant ListZones() defaulted to the default org, which has nothing in it.  Setting `sharing_id` to the "main" org (why isn't main the default???) fixed the problem.


I have a PR to improve the docs in this area: https://github.com/StackExchange/dnscontrol/pull/1542
