### ISSUE TITLE
Replace SetTargetTXTString with alternatives

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1545]
The quote parsing in SetTargetTXTString() doesn't handle escaped quotes. It is also badly named, because it doesn't imply that the string is parsed, which may lead to providers using it accidentally on strings that should not be parsed.

SetTargetTXTString should be depreciated.  Users are better off with the new function SetTargetTXTfromRFC1025Quoted() or simply SetTargetTXT() (single string) or SetTargetTXTs() (multiple strings).

digitalocean, msdns and packetframe are the only providers that use the function.  Please eliminate the use of SetTargetTXTString() when you can.

- [x] Fix DIGITALOCEAN.  @Deraen
- [x] Fix MSDNS.  @tlimoncelli 
- [x] Fix PACKETFRAME.  @hamptonmoore
- [ ] When the above are done, remove the old function from the repo  @tlimoncelli 

To clarify: Most providers should use SetTargetTXT() or SetTargetTXTs().   I've written a longer explanation in `models/t_txt.go`.

**Comment by tlimoncelli** [comment]
@Deraen @hamptonmoore Friendly ping?

**Comment by Deraen** [comment]
It seems like Digitalocean is already done:
https://github.com/StackExchange/dnscontrol/commit/eb4af05d319c1ee6127306cb5b450e8499ded259
https://github.com/StackExchange/dnscontrol/commit/2586e2b611c0054abbc25c15fe64a25d0ee7b51f#diff-b71933063db51c94fac5af976d4589ff5b578d283d1f857cd37676cc5fcd20d2

The tests are passing for me.

(Seems like Packetframe is also using `SetTargetTXT` already.)

**Comment by tlimoncelli** [comment]
Thanks for checking!

Yup!  Looks like we're ready to close this.
