### ISSUE TITLE
Add one password tpl file example

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1551]
@plttn Jack, could you do me a favor and help other people use one password with dnscontrol by including
your `creds.json.tpl` file in the documentation?

More specifically:

1.  Add the template to the repo.

Put it in docs/assets/creds.json.tpl--example.txt

2.  Refer to it in the docs.

In `docs/creds-json.md` (seen as https://stackexchange.github.io/dnscontrol/creds-json.html) mention it as

`[creds.json.tpl-example.txt]({{ site.github.url }}/assets/creds.json.tpl-example.txt))`

Thanks!
Tom

**Comment by plttn** [comment]
Hi, just wanted to acknowledge this and should have a PR to add this sometime later today. Thanks for the heads up!
