### ISSUE TITLE
About V3.17 release name

### ISSUE THREAD

**Issue by riku22** [StackExchange/dnscontrol#1555]
Hello.

The release name of V3.17 is "vv3.17", but the correct name is "v3.17", isn't it?
Is it possible to fix it?

Best regards.

**Comment by tlimoncelli** [comment]
Oops!  Sadly there is 1 manual step in the release process and, of course, that's where the typo happened!

Thanks for pointing this out.

I've renamed the release.  Does the "vv" appear any place else?

**Comment by riku22** [comment]
Thank you.

It seems to have been fixed.
