### ISSUE TITLE
MAINT: DIGITALOCEAN upgrade dependencies 

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1562]
@Deraen

It looks like this provider depends on a module that has a newer version.  Would you please test your provider with the newer version and submit a PR?

```
$ go list -mod=mod -u -m -json all | go-mod-outdated -update -direct
+---------------------------------+---------+-------------+--------+------------------+
|             MODULE              | VERSION | NEW VERSION | DIRECT | VALID TIMESTAMPS |
+---------------------------------+---------+-------------+--------+------------------+
| github.com/digitalocean/godo    | v1.80.0 | v1.81.0     | true   | true             |
+---------------------------------+---------+-------------+--------+------------------+
```

Near the end of `docs/release-engineering.md` are 2 different techniques for finding dependencies that need to be upgraded.

TLDR: Please submit a PR to upgrade this dependency.  Basically you'll be running these commands:

```
$ git checkout master
$ git pull
$ git checkout -b INSERT_BRANCH_NAME
$ go get INSERT_MODULE_NAME_HERE
$ go mod tidy
$ cd integrationTest
$ go test -v -verbose -provider INSERT_PROVIDER_NAME_HERE
```

Please fix any issues then submit a PR.

Thanks!

**Comment by tresni** [comment]
This was done in #1697 , can close this issue for cleanup :)

**Comment by Deraen** [comment]
Oh, sorry, I missed this during my summer vacation. 

The integrations tests are passing for me on master, so dependency upgrade and other changes seem OK.

**Comment by tlimoncelli** [comment]
Thanks for checking!
