### ISSUE TITLE
MAINT: DNSIMPLE upgrade dependencies 

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1563]
@aeden

It looks like this provider depends on a module that has a newer version.  Would you please test your provider with the newer version and submit a PR?

```
$ go list -mod=mod -u -m -json all | go-mod-outdated -update -direct
+---------------------------------+---------+-------------+--------+------------------+
|             MODULE              | VERSION | NEW VERSION | DIRECT | VALID TIMESTAMPS |
+---------------------------------+---------+-------------+--------+------------------+
| github.com/dnsimple/dnsimple-go | v0.70.1 | v0.71.1     | true   | true             |
+---------------------------------+---------+-------------+--------+------------------+
```

Near the end of `docs/release-engineering.md` are 2 different techniques for finding dependencies that need to be upgraded.

TLDR: Please submit a PR to upgrade this dependency.  Basically you'll be running these commands:

```
$ git checkout master
$ git pull
$ git checkout -b INSERT_BRANCH_NAME
$ go get INSERT_MODULE_NAME_HERE
$ go mod tidy
$ cd integrationTest
$ go test -v -verbose -provider INSERT_PROVIDER_NAME_HERE
```

Please fix any issues then submit a PR.

Thanks!

**Comment by aeden** [comment]
Hey, @tlimoncelli , I think @onlyhavecans will take a look into this as she actively uses dnscontrol.

**Comment by onlyhavecans** [comment]
I have put this on my list, thanks
