### ISSUE TITLE
MAINT: NS1 upgrade dependencies 

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1565]
@costasd

It looks like this provider depends on a module that has a newer version.  Would you please test your provider with the newer version and submit a PR?

```
$ go list -mod=mod -u -m -json all | go-mod-outdated -update -direct
+---------------------------------+---------+-------------+--------+------------------+
|             MODULE              | VERSION | NEW VERSION | DIRECT | VALID TIMESTAMPS |
+---------------------------------+---------+-------------+--------+------------------+
| gopkg.in/ns1/ns1-go.v2          | v2.5.1  | v2.6.5      | true   | true             |
+---------------------------------+---------+-------------+--------+------------------+
```

Near the end of `docs/release-engineering.md` are 2 different techniques for finding dependencies that need to be upgraded.

TLDR: Please submit a PR to upgrade this dependency.  Basically you'll be running these commands:

```
$ git checkout master
$ git pull
$ git checkout -b INSERT_BRANCH_NAME
$ go get INSERT_MODULE_NAME_HERE
$ go mod tidy
$ cd integrationTest
$ go test -v -verbose -provider INSERT_PROVIDER_NAME_HERE
```

Please fix any issues then submit a PR.

Thanks!

**Comment by tlimoncelli** [comment]
@costasd I'd like to produce a new release in a few days. Could you check this?

**Comment by costasd** [comment]
oops. Yup, will have a PR up by tomorrow. Sorry for the delay!
