### ISSUE TITLE
INWX: Please verify recordaudit.TxtNoStringsExactlyLen255 is required

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1566]
CC @svenpeter42

The INWX provider uses recordaudit.TxtNoStringsExactlyLen255()  in providers/inwx/auditrecords.go but does not use recordaudit.TxtNoStringsLen256orLonger().  This means the provider will accept a string that is length 254, 254, and 256... but not 255. 

Is this true?  It seems more likely that you want to use recordaudit.TxtNoStringsLen256orLonger() instead.

Please try it both ways and see if the integration tests work.

(Note: I recently improved the documentation and renamed some functions. See https://github.com/StackExchange/dnscontrol/pull/1548)

**Comment by tlimoncelli** [comment]
@svenpeter42 Friendly ping?

**Comment by svenpeter42** [comment]
You probably meant to ping the current INWX maintainer instead :)Sven—Sent from my phoneOn 16. May 2023, at 02:35, Tom Limoncelli ***@***.***> wrote:﻿
@svenpeter42 Friendly ping?

**Comment by patschi** [comment]
Sorry for the delay, @tlimoncelli. Have been crazy weeks lately.

I've just tested it with the very latest dnscontrol git commit version with the INWX Prod API:
```
******************** Domain: domain.tld
2 corrections (PK-INWX)
#1: + CREATE TXT test1.domain.tld "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ttl=43200
SUCCESS!
#2: + CREATE TXT test2.domain.tld "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" "a" ttl=43200
SUCCESS!
Done. 2 corrections.
```

- `test1` has 254 characters
- `test2` has 256 characters

Both working fine.

**Comment by tlimoncelli** [comment]
Thanks!

Can you also test 255?  (This might require removing the `rejectif.TxtIsExactlyLen255` line from `providers/inwx/auditrecords.go`)

**Comment by patschi** [comment]
This fails indeed:
```
2023/05/19 20:45:18 printIR.go:113: ERROR: INWX rejects domain rofllol.eu: txtstring length is 255
exiting due to validation errors
```

Removed the attribute you mentioned. Then retried:
```
******************** Domain: domain.tld
1 correction (PK-INWX)
#1: + CREATE TXT test3.domain.tld "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ttl=43200
SUCCESS!
Done. 1 corrections.
```

When running again:
```
******************** Domain: domain.tld
Done. 0 corrections.
```

So seems to work.
