### ISSUE TITLE
go get to install commands is no longer supported

### ISSUE THREAD

**Issue by pnorman** [StackExchange/dnscontrol#1573]
https://github.com/StackExchange/dnscontrol/blob/b140b2eb45025c32774998b63ca607bbf3265353/README.md?plain=1#L146 suggests using `go get` to install the binary. When I do this on my system I get 

```
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

I worked around this with a build from git, but the right go command would be good. I did try `go install github.com/StackExchange/dnscontrol@v3` but it fails with the error `go: github.com/StackExchange/dnscontrol@v3: no matching versions for query "v3"`

**Comment by tlimoncelli** [comment]
Try this?

```
git clone https://github.com/StackExchange/dnscontrol.git
```

That worked for me.  If it works for you, I'll update the README

**Comment by pnorman** [comment]
That clones the git repo, not installs the binary.

**Comment by tlimoncelli** [comment]
Good point. You'd have to "go install" after the clone completes.
