### ISSUE TITLE
EXOSCALE: SRV records not working

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1612]
CC @pierre-emmanuelJ 

This was discovered in https://github.com/StackExchange/dnscontrol/pull/1597 but I'm filing a different issue for this bug.

```
=== RUN   TestDNSProviders/exoscale-test-dns-simple.ch/28:SRV:SRV_record
    integration_test.go:220: CREATE SRV _sip._tcp.exoscale-test-dns-simple.ch 5 6 7 foo.com. ttl=300
    integration_test.go:224: dns error: Validation failed (content: must consist of <weight (0-65535)> <port (0-65535)> <target> fields)
```

The error message doesn't mention priority. Maybe the priority is transmitted using the priority field used for MX records?

ProTip: For faster integration tests, just run the tests you want with `go test -v -verbose -provider EXOSCALE -start 27 -end 30`

**Comment by tlimoncelli** [comment]
Did that change fix it?

**Comment by pierre-emmanuelJ** [comment]
Thanks for the patch! Let me test it ASAP, I was in holiday :)
