### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [StackExchange/dnscontrol#1617]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@sampaguitas) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by tlimoncelli** [comment]
Hi there!

Thanks for contacting us.  I'll look into creating the SECURITY.md file.  It will take a while because... reasons.

In the meanwhile, you can contact me directly via email using my tlimoncelli at stack over flow dot com address.

Thanks!
Tom

**Comment by JamieSlome** [comment]
@tlimoncelli - thanks for your diligence 👍 

I will send further details via e-mail now, but just for reference, the report can be found directly here:
https://huntr.dev/bounties/93e9a9fb-a676-4db5-b0b1-cd5c5375503d/

It is currently private and only accessible to maintainers with repository write permissions :)
