### ISSUE TITLE
Error creating registrars: Registrar namecheap.com not listed in -providers file

### ISSUE THREAD

**Issue by sdugoten** [StackExchange/dnscontrol#162]
I am keep getting the error "Error creating registrars: Registrar namecheap.com not listed in -providers file"

var REG_NAMECHEAPCOM = NewRegistrar('namecheap.com','NAMECHEAP');
var CFLARE = NewDnsProvider('cloudflare.com','CLOUDFLAREAPI');

D("abc.com", REG_NAMECHEAPCOM, DnsProvider(CFLARE),
        A('@', '111.239.240.110', TTL(43200)),
        MX('@', 1, 'aspmx.l.google.com.', TTL(3600)),
        MX('@', 5, 'alt1.aspmx.l.google.com.', TTL(3600)),
        MX('@', 10, 'ALT2.ASPMX.L.GOOGLE.COM.', TTL(3600)),
        TXT('@', "v=spf1 include:_spf.google.com ~all", TTL(3600)),
        CNAME('03', 'abc.com.', TTL(3600)),
        TXT('google._domainkey', "v=DKIM1; k=rsa; p=asdfdsfasdfasdfasdfsdfasdfasdfadsfds$
        CNAME('central', 'abccom.', TTL(3600)),
        CNAME('ftp', abc.com.', TTL(3600)),
        CNAME('goten', 'abc.com.', TTL(3600)),
        A('localhost', '127.0.0.1', TTL(3600)),
        CNAME('mail', 'abc.com.', TTL(3600)),
        A('ns', '111.80.244.250', TTL(3600)),
        A('ns1', '111.239.240.110', TTL(3600)),
        A('ns2', '111.239.240.110', TTL(3600)),
        CNAME('stream', 'abc.com.', TTL(3600)),
        CNAME('webmail', 'abc.com.', TTL(3600)),
        CNAME('www', 'abc.com.', TTL(3600))
)

iMac:namedb root# more creds.json 
{
  "cloudflare.com":{
    "apikey": "ssssssssssssssssssssssssssssssssssa",
    "apiuser": "abc@gmail.com"
  }
}

**Comment by sdugoten** [comment]
iMac:namedb root# dnscontrol -js testing.js  -providers all  preview        
2017/07/26 19:27:55 main.go:127: Error creating registrars: Registrar name.com not listed in -providers file.

**Comment by sdugoten** [comment]
Moreover, having these entries would also throw error

 NS('@', 'ns.abc.com.', TTL(43200)),
NS('@', 'ns2.abc.com.', TTL(43200)),


ERROR: In NS @.abc.com: cannot create NS record for bare domain. Use NAMESERVER instead

**Comment by whs** [comment]
In your creds.json, you need to have

```json
{
    "namecheap.com": {
        "apikey": "yourApiKeyFromNameCheap",
        "apiuser": "yourUsername"
    }
}
```

i.e. the first argument of `NewRegistrar` must match the key in your creds.json.

And for root NS record, use `NAMESERVER('ns.abc.com.'),` instead. If you need TTL for your nameserver, add `{'ns_ttl': '43200'}` to your `D()` argument. Note that the value is a string and not a number.

However, usually you wouldn't want to use `NAMESERVER`. If you have DNS providers configured dnscontrol will automatically register their DNS servers with your registrar.

**Comment by sdugoten** [comment]
Thanks for reply.  

Since I am using the provided tools convertzone to make the config file, anyway to make the convertzone to create those entry using the tag NAMESERVER instead of NS?

**Comment by tlimoncelli** [comment]
It is difficult to automatically guess whether an NS should be converted to a NS() or a NAMESERVER() call. That said, I added some logic to make a better guess than what's happening now.

convertzone isn't intended to do a perfect job of converting BIND zones... we're shooting for 90%.  That said, this should help a bit.
