### ISSUE TITLE
"CNAME unimplemented" error

### ISSUE THREAD

**Issue by rnhurt** [StackExchange/dnscontrol#164]
I'm now getting a "PANIC=rc.String rtype CNAME unimplemented" error when I CREATE new CNAME records.  In pull request #136 it looks like the record config type was updated to include the new types (A, AAAA, MX, SOA, etc.), however CNAME is not among the list.  Am I doing something wrong?  Did the definition of CNAME change or something?

**Comment by captncraig** [comment]
Can you post the full stack trace details please?

**Comment by rnhurt** [comment]
Sorry, I didn't mean to alarm you.  My code isn't actually panicking, it just has the word PANIC in the error for some reason.  The process actually works and it does create the DNS record in GoDaddy just like it's supposed to.  However, that error is new and appeared after I synced up fork up with the master branch.

```
$ go build && ./dnscontrol push
1 Validation errors:
WARNING: label _domainconnect.aocdnstest.org contains an underscore
Initialized 1 registrars and 1 dns service providers.
******************** Domain: aocdnstest.org
----- Getting nameservers from: godaddy
----- DNS Provider: godaddy...

2017/07/31 15:37:57 godaddyProvider.go:122: C: %!s(PANIC=rc.String rtype CNAME unimplemented)
0 corrections
----- Registrar: none
Done. 0 corrections.
```

**Comment by captncraig** [comment]
Where is your code for this godaddy provider?

**Comment by captncraig** [comment]
Ah, I think I see the problem. @tlimoncelli I believe RecordConfig.String() may be broken in this case. The line of code is just doing a `log.Printf("%s", rec)`

**Comment by captncraig** [comment]
baf045d0ab5219dd784e3064e2c6422222da6cea should fix the printing error there. Thanks for pointing it out.

**Comment by rnhurt** [comment]
Ah, that makes more sense now.  😄 

Thank you for this change; I thought I was going crazy.  😨
