### ISSUE TITLE
preview and push commands exit when they encounter a Hetzner zone that doesn't exist

### ISSUE THREAD

**Issue by gregdotca** [StackExchange/dnscontrol#1641]
Hello! It's my understanding that the _create-domains_ command is now deprecated, and going forward the _push_ command will create DNS zones for you, however this doesn't seem to work with Hetzner. Also, running the _preview_ command exits as soon as it gets to a Hetzner zone that doesn't exist.

**preview**
```
./dnscontrol preview
******************** Domain: example.com
----- Getting nameservers from: hetzner
"example.com" is not a zone in this HETZNER account
(There are more domains after example.com, however DNSControl exits right here)
```
**push**
```
./dnscontrol push
******************** Domain: example.com
----- Getting nameservers from: hetzner
"example.com" is not a zone in this HETZNER account
(There are more domains after example.com, however DNSControl exits right here)
```

Have I misunderstood how this is supposed to work? If so, is there a way to do a preview without having it exit when it encounters a zone that doesn't exist, or a way to create DNS zones at Hetzner if they don't already exist?

DNSControl version v3.17.0
OS: Debian 11  (running in an LXC container on Proxmox 7.2-7)

**Comment by tlimoncelli** [comment]
CC @das7pad

Not all providers in DNSControl supports populating domains in the account.  If it doesn't, it errors out as you described.  The user must either create the domain in the account (usually via a web portal) or remove the domain from dnsconfig.js.

However it looks like HETZER supports populating domains in the account.   In Go terms, it "completes the DomainCreator interface" (i.e. has a function called `EnsureDomainExists`)

Jakob, could you investigate?

Thanks!
Tom

**Comment by das7pad** [comment]
Looking at the preview process in dnscontrol core, it fetches nameservers ahead of checking whether a given zone exists.

https://github.com/StackExchange/dnscontrol/blob/c0450223c2e3eb0a67a42092cc5620bb05ebab8d/commands/previewPush.go#L132-L158

In other words, the HETZNER provider has not had a chance to create the zone before the listing of nameservers started.

We need to flip the order here:
old:
1. list nameserver
2. for each provider
    1. create zone if needed
    2. get corrections

new:
1. for each provider
    1. create zone if needed
2. list nameserver
3. for each provider
    1. get corrections

I'll open a PR for this fix.

**Comment by tlimoncelli** [comment]
Dude, you're awesome!

**Comment by das7pad** [comment]
It turned out to be a big more involved as some providers (including HETZNER) have zone caches that need clearing when creating a domain. -> PR https://github.com/StackExchange/dnscontrol/pull/1642

I've tested the changes for HETZNER. I did not test the ROUTE53 changes and tagged the current maintainer on the PR.

**Comment by tresni** [comment]
Happy to take a look!

**Comment by tlimoncelli** [comment]
Fixed with https://github.com/StackExchange/dnscontrol/pull/1642
