### ISSUE TITLE
Support for TLSA records

### ISSUE THREAD

**Issue by eliheady** [StackExchange/dnscontrol#165]
TLSA record support

I started work on this in [elih_tlsa](https://github.com/eliheady/dnscontrol/tree/0e109cac85fc52bd8188e88a13781396c87c309d). Validation and tests are lacking. And it's just a clone of SRV.

I would consider this blocked by #157 addRecord refactor, but I'm opening this now anyway :)

I'll watch #157 and can work on this later on.

**Comment by eliheady** [comment]
I started working on this again and have something that might soon be PR worthy at https://github.com/eliheady/dnscontrol/tree/elih_tlsa

pkg/normalize/validate_test.go TLSA tests aren't finished as there's no RFC compliance checking happening.

**Comment by tlimoncelli** [comment]
Sounds good!  Looking forward to the PR!

**Comment by captncraig** [comment]
closed via #203
