### ISSUE TITLE
Most recent releases missing from DockerHub 

### ISSUE THREAD

**Issue by flz** [StackExchange/dnscontrol#1653]
It looks like no new docker release has been uploaded to [dockerhub](https://hub.docker.com/r/stackexchange/dnscontrol/) in at least 6 months.

**Comment by cafferata** [comment]
Hi @tlimoncelli! I started using DNSControl since last week. I've locally everything working (_after the change from my merge request https://github.com/StackExchange/dnscontrol/pull/1661_). Now I wanted our Gitlab CI to do the `dnscontrol push` and so I ran into the same problem as many others:
>_The Docker image is not updated._

I'm new to Circle CI, but I'm happy to help tie this loose end. That's why I set up a Circle CI set-up in which you can see a [working Circle CI workflow](https://app.circleci.com/pipelines/github/cafferata/dnscontrol/17/workflows/eb1db94f-288a-4ab2-b7e3-5e22f2d262ee/jobs/19) that's pushing to [Docker hub](https://hub.docker.com/repository/docker/jcid/stackexchange-dnscontrol).

Shall we [schedule a meeting](https://calendly.com/jeffrey-cafferata/beschikbaarheid) to loop Circle CI and Docker Hub together? ☺️

**Comment by cafferata** [comment]
I came across issue https://github.com/StackExchange/dnscontrol/issues/1375, and would like to say that these two are duplicates of each other. What do you think?

**Comment by tlimoncelli** [comment]
@cafferata Yes, I think those are duplicates.

**Comment by tlimoncelli** [comment]
> Hi @tlimoncelli! I started using DNSControl since last week. I've locally everything working (_after the change from my merge request #1661_). Now I wanted our Gitlab CI to do the `dnscontrol push` and so I ran into the same problem as many others:
> 
> > _The Docker image is not updated._
> 
> I'm new to Circle CI, but I'm happy to help tie this loose end. That's why I set up a Circle CI set-up in which you can see a [working Circle CI workflow](https://app.circleci.com/pipelines/github/cafferata/dnscontrol/17/workflows/eb1db94f-288a-4ab2-b7e3-5e22f2d262ee/jobs/19) that's pushing to [Docker hub](https://hub.docker.com/repository/docker/jcid/stackexchange-dnscontrol).
> 
> Shall we [schedule a meeting](https://calendly.com/jeffrey-cafferata/beschikbaarheid) to loop Circle CI and Docker Hub together? ☺️

That would be VERY appreciated!  Yes!

I've used the link to schedule time.  See you then!

**Comment by cafferata** [comment]
Great! I'll talk to you later (today)! 👋

**Comment by flz** [comment]
Looks like the new releases are flowing!

However, running docker build from the checkout seems broken (the Dockerfile is suspiciously empty):

```
❯ docker build -t dnscontrol .
[+] Building 4.2s (10/11)                                                                                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                                                                       0.0s
 => => transferring dockerfile: 397B                                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4                                                                                                                               1.8s
 => docker-image://docker.io/docker/dockerfile:1.4@sha256:443aab4ca21183e069e7d8b2dc68006594f40bddf1b15bbd83f5137bd93e80e2                                                                 1.0s
 => => resolve docker.io/docker/dockerfile:1.4@sha256:443aab4ca21183e069e7d8b2dc68006594f40bddf1b15bbd83f5137bd93e80e2                                                                     0.0s
 => => sha256:24d064a369eda7bc7839b6c1c227eac7212d06ca09a8235a4bed467f8acf180d 528B / 528B                                                                                                 0.0s
 => => sha256:84495a15555de1a8f4738f58268fa8949547068198f8d0fa2a3e3a693d7f923f 2.37kB / 2.37kB                                                                                             0.0s
 => => sha256:09768fef35f2ee387f57e401ae685727d12d1c70c6fd8545a422850167bf1940 9.94MB / 9.94MB                                                                                             0.6s
 => => sha256:443aab4ca21183e069e7d8b2dc68006594f40bddf1b15bbd83f5137bd93e80e2 2.00kB / 2.00kB                                                                                             0.0s
 => => extracting sha256:09768fef35f2ee387f57e401ae685727d12d1c70c6fd8545a422850167bf1940                                                                                                  0.2s
 => [internal] load build definition from Dockerfile                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/alpine:3.16.2@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                                   1.1s
 => [internal] load build context                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                            0.0s
 => CANCELED [1/3] FROM docker.io/library/alpine:3.16.2@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                                            0.0s
 => => resolve docker.io/library/alpine:3.16.2@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                                                     0.0s
 => => sha256:9c6f0724472873bb50a2ae67a9e7adcb57673a183cea8b06eb778dca859181b5 1.47kB / 1.47kB                                                                                             0.0s
 => => sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad 1.64kB / 1.64kB                                                                                             0.0s
 => => sha256:1304f174557314a7ed9eddb4eab12fed12cb0cd9809e4c28f29af86979a3c870 528B / 528B                                                                                                 0.0s
 => ERROR [2/3] COPY dnscontrol /usr/local/bin/                                                                                                                                            0.0s
------
 > [2/3] COPY dnscontrol /usr/local/bin/:
------
failed to compute cache key: "/dnscontrol" not found: not found
```

**Comment by cafferata** [comment]
@flz I have noticed the same. @cdhunt has from PR https://github.com/StackExchange/dnscontrol/pull/1682 refactor the `Dockerfile`. So I guess it's up to him to tell what the idea is behind a local Docker build. Also, I think it's better to create a new issue so that both closed issues don't continue indefinitely.

**Comment by jauderho** [comment]
The Dockerfile as it stands currently expects the binary to be built first outside Docker packaging whereas the previous iteration IIRC built everything within Docker. 

My $0.02. Revert to the previous form for Dockerfile and create a separate Dockerfile.local. It really depends on what the intended use of the Dockerfile is.

**Comment by cdhunt** [comment]
You can produce the docker images locally using [goreleaser](https://goreleaser.com/cmd/goreleaser_release/) the same as they are built in CI. Or just drop the version of `dnscontrol` that you want to include in the project root. Does that work for you?

```shell
goreleaser release --skip-publish --rm-dist --snapshot
```
