### ISSUE TITLE
Provider request: RRPPRoxy (Related to Hexonet Provider)

### ISSUE THREAD

**Issue by felixrichardt** [StackExchange/dnscontrol#1656]
Could you please add RRPPRoxy as supported provider - RRPProxy uses nearly the same API since both companies belong togehter. RRPProxy is a sister company of Hexonet.

So I guess there should not be that many differences in the API and one could reuse existing Hexonet provider support (?)

See below the current api docs for RRPPRoxy
https://wiki.rrpproxy.net/api/api-commands/api-command-reference

Maybe the provider can be supported without much effort.

Thanks!

**Comment by tlimoncelli** [comment]
CC @KaiSchwarz-cnic for input

**Comment by KaiSchwarz-cnic** [comment]
@tlimoncelli thanks for tagging. to be honest, I am highly overloaded atm, but let me give some insights.
1) RRPproxy -> relabeled to "CentralNic Reseller" (short CNR)

2) HEXONET (HX) and CNR Backend APIs have been initially founded by the former CEO of HEXONET and are in their Core therefore very similar. I guess HX is behind the scenes using the DNS of CNR so-called KeyDNS anyway, just some minor differences maybe regarding API Commands / Responses. The CNR API is at least more integrator-friendly regarding its DNS API as it provides the Resource Records already in a parsed format (TTL, hostname, ...)

3) CNR API Resources:

* [KeyDNS](https://kb.centralnicreseller.com/dns/keydns)
* [API Commands](https://kb.centralnicreseller.com/dns/keydns/command-reference)
* [API Communication Insights](https://kb.centralnicreseller.com/api/connecting/hypertext-transfer-protocol-socket)

From long-term perspective, even though there are no detailed plans available yet, the HX Brand will probably merge into CNR. Means, Backend System will merge in direction of CNR. Therefore it is of course also of interest for us coming to a CNR integration for DNSControl. For HX we use the so-called GO-SDK as software dependency for communicating to the HX API - this library would have to be extended to add support for the CNR API. Then, imho, the dnscontrol integration can be covered smoothly.

**Comment by KaiSchwarz-cnic** [comment]
That were the facts - still, my team is currently overloaded with work related to a Partnership with WHMCS. I can't promise a lot for now.

**Comment by KaiSchwarz-cnic** [comment]
--> #3203

Discussion to be continued there.

**Comment by KaiSchwarz-cnic** [comment]
@tlimoncelli I guess, this issue can be closed as we made the CentralNic Reseller Provider (CNR) available.
