### ISSUE TITLE
Ghandi.net API changes

### ISSUE THREAD

**Issue by mhenderson-so** [StackExchange/dnscontrol#166]
Received this email from ghandi today. Not sure if this affects functionality in DNS Control, but adding this as an issue as we should double check:

> Dear Customer,
> 
> We contact you today because you are identified as an active user of our
> public production API.
> 
> We would like to inform you that an EMERGENCY patch for our public API
> has been deployed today [02/08/2017 Paris time] on our producton
> platform, in order to counter an incident[1] that impacted all of our
> customers.
> 
> This corrective action has resulted in significant changes in our public
> API.
> 
> It is therefore necessary that you check your code, and more precisely
> the use of the following method: "gandi.api.domains.zone.record::list"
> 
> If this is your case, please note that the use of that method has been
> updated, particularly the 'id' field type returned by that fuction. Your
> code now needs to accept the fact that the 'id' type is a string of
> characters, and no longer an integer (i4 in xmlrpc).
> 
> The two functions which use this 'id' as an entry are:
> 
>  - gandi.api.domains.zone.record::update
>  - gandi.api.domains.zone.record::list (filtre sur l'id)
> 
> In order to ensure optimal backward compatibility, those two functions
> still accept an "integer" type as entry for the 'id' field, in addition
> to the "string of characters" type. It is strongly recommended, however,
> to use the "string" type.
> 
> Our online public API documentation[2] has been updated as a result of
> these changes.
> 
> Given the urgency and consequences of this incident, we had no choice
> but to deploy this patch without prior notification and we apologize for
> any inconvenience.
> 
> Our customer service is of course at your disposal to assist you if you
> encounter difficulties in the implementation of the modifications.
> 
> We thank you for your confidence in Gandi.
> 
> Gandi.net
> 
> [1] http://status.gandi.net/timeline/events/957
> [2] http://doc.rpc.gandi.net/domain/reference.html?zone.record.list#ZoneRecordReturn
> & http://doc.rpc.gandi.net/domain/reference.html#RecordUpdateOptions

**Comment by captncraig** [comment]
Yeah, it looks like we'll be affected by this. The type that needs updating is in https://github.com/prasmussen/gandi-api/blob/master/domain/zone/record/structs.go#L3

**Comment by tlimoncelli** [comment]
Fixed with https://github.com/StackExchange/dnscontrol/commit/30d26ffd724c53036ef7c3e9e4a8db8bd36f6e41 and made official by https://github.com/StackExchange/dnscontrol/commit/4ae2e172eb77c91ff81b1e1e3991cdced91504f5
