### ISSUE TITLE
Mark 3.18.2-dev as a prerelease

### ISSUE THREAD

**Issue by SuperSandro2000** [StackExchange/dnscontrol#1693]
It would be nice if ``3.18.2-dev`` would be marked as a prerelease to not be listed as a possible update for distributions.

**Comment by tlimoncelli** [comment]
Hey @cafferata @cdhunt: Advice on how to fix that?

**Comment by cdhunt** [comment]
I've removed the release. It shouldn't have been created.

**Comment by tlimoncelli** [comment]
Thanks, @cdhunt !
