### ISSUE TITLE
AZUREDNS: Migrate to newer library

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1698]
CC: @vatsalyagoel 

staticcheck reports:

providers/azuredns/azureDnsProvider.go:12:7: "github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns" is deprecated: Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details. (SA1019)

**Comment by vatsalyagoel** [comment]
Will have a PR soon.

**Comment by vatsalyagoel** [comment]
This issue can be closed @tlimoncelli
