### ISSUE TITLE
[Web] Examples no longer expanding

### ISSUE THREAD

**Issue by fm** [StackExchange/dnscontrol#1702]
in the [Language Reference / Javascript DSL](https://stackexchange.github.io/dnscontrol/js) page, examples are no longer expandable

Chrome 104.0.5112.79
<img width="639" alt="Screen Shot 2022-08-14 at 1 17 36 PM" src="https://user-images.githubusercontent.com/3654256/184534299-578f4f4c-fdb4-4c0d-87d5-d7c80d7f4c75.png">

Safari 15.5 (17613.2.7.1.8
<img width="945" alt="Screen Shot 2022-08-14 at 1 18 34 PM" src="https://user-images.githubusercontent.com/3654256/184534340-edb84a7b-c210-4dda-8b59-a04f7493fe50.png">
)

**Comment by tlimoncelli** [comment]
Fixed in #1703

Thanks for pointing this out!
