### ISSUE TITLE
Fix GoReleaser 'Provider-specific changes:' regex

### ISSUE THREAD

**Issue by cdhunt** [StackExchange/dnscontrol#1710]
For some reason, that pattern isn't picking up any of the commits with provider strings in them. See [releases/tag/v3.18.2-pre013](https://github.com/StackExchange/dnscontrol/releases/tag/v3.18.2-pre013).

**Comment by tlimoncelli** [comment]
I believe this is fixed. Can you confirm?

**Comment by cdhunt** [comment]
I haven't created any releases with affected commits, but if it is working for you then 👍 .
