### ISSUE TITLE
New brief format. Should it be the default?

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1720]
There is a new output format that is much more brief.  Should it be the default (in which case a `--verbose` flag will get the old format), or should it require a flag (such as `--brief`)?

I currently achieve the "brief" format by piping the output to a filter.

Current format:

```
$ dnscontrol preview
******************** Domain: sstatic.net
----- Getting nameservers from: gcloud
----- Getting nameservers from: r53
----- DNS Provider: gcloud...
0 corrections
----- DNS Provider: r53...
0 corrections
----- Registrar: namedotcom_main...
0 corrections
******************** Domain: blogoverflow.com
----- Getting nameservers from: gcloud
----- Getting nameservers from: r53
----- DNS Provider: gcloud...
1 correction
#1: CREATE A testrecord.blogoverflow.com 1.2.3.4 ttl=300
----- Registrar: cscglobal_ltom215...
0 corrections
******************** Domain: example.com
----- Getting nameservers from: gcloud
----- Getting nameservers from: r53
----- DNS Provider: gcloud...
0 corrections
----- DNS Provider: r53...
0 corrections
----- Registrar: namedotcom_main...
0 corrections
******************** Domain: example2.com
----- Getting nameservers from: gcloud
----- Getting nameservers from: r53
----- DNS Provider: gcloud...
0 corrections
----- DNS Provider: r53...
0 corrections
----- Registrar: namedotcom_main...
0 corrections
Done. 0 Corrections.
```

Filtered format:

```
$ dnscontrol preview | bin/filter-preview.sh
******************** Domain: sstatic.net
******************** Domain: blogoverflow.com
1 correction
#1: CREATE A testrecord.blogoverflow.com 1.2.3.4 ttl=300
******************** Domain: example.com
******************** Domain: example2.com
Done. 0 Corrections.
```

In case you were wondering, here is the `filter-preview.sh` shell script:

```shell
#!/bin/bash

exec grep -v -e '^\.\.\.0 corrections$' \
   -e '^ *$' \
   -e '^0 corrections' \
   -e '\.\.\. \(skipping\)' \
   -e '^----- DNS Provider: ' \
   -e '^----- Registrar: ' \
   -e '^----- Getting nameservers from:'
```

When you have many, many domains, this makes it easier to visually
spot a change.  This is particularly useful in a GitOps-style or CI
system where a second person must review a change.

The question is:

Should the flag be `--brief` or `--verbose`?  That is, should the
default be verbose, and you must add a flag to get less output,
or should the default be short and you need to add the extra
information.

Reasons I like `--brief`:

* A new user needs that extra output to help them understand
  what's going on and debug issues as they get started.  Once 
  they are comfortable with the system, they can add `--brief`.

Reasons I like `--verbose`:

* I have a lot of domains and the brief format is much easier to
  read.  Looking at my .history, I see that nearly every time I've
  used dnscontrol I piped the output to my filter.

What do you think?  Should brief be the default format?

**Comment by SimenBai** [comment]
I think we should I think cafferata alluded to.
I.e. filtered format as standard and either have verbosity levels, or different verbosity commands.

**Comment by tlimoncelli** [comment]
Thanks for the feedback (here and elsewhere), folks!  Looks like people are in favor of the new format, with `--verbose` getting the old format.
