### ISSUE TITLE
CI/CD examples

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1760]
What do you think of the idea of including CI/CD sample configurations in the DNSControl https://github.com/StackExchange/dnscontrol/labels/Category%3A%20Documentation? I've been thinking of extracting our Gitlab CI setup and bringing it back to the DNSControl documentation so it might help other developers along. I hope this will increase the developer experience.

In addition, I would like to be able to help others on their way in their Gitlab CI/CD set-up. So if a Github issue/question comes in, you can give me a mention. Just as happened with the various DNS provider issues.

Let me know what you think of the idea. ☺️

**Comment by tlimoncelli** [comment]
I would love to include more examples!

I'd also like to link to videos of people showing what their CI/CD system looks like in action.

Tom

**Comment by cafferata** [comment]
I just finished a first draft. I'm curious what you think.
