### ISSUE TITLE
VULTR: cannot unmarshal number into Go struct field Account.balance of type string

### ISSUE THREAD

**Issue by androw** [StackExchange/dnscontrol#1769]
VULTR provider doesn't seem to work anymore.

```
$ dnscontrol -v check-creds vultr
failed GetZone CDP: json: cannot unmarshal number into Go struct field Account.balance of type string
```

From what I understand the issue is more in the underliying govultr dependency.

I've opened PR GH-1768 as a move to the v2 API and this seems to fix the problem.

**Comment by tlimoncelli** [comment]
https://github.com/StackExchange/dnscontrol/pull/1768 is merged. Does that mean we can close this issue?

CC @pgaskin
