### ISSUE TITLE
DOCS: Javascript DSL table of contents (TOC)

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1777]
I have the desire to have an overview at a glance of the Javascript DSL. For me it would be enough to have table of contents (TOC) at the top of the page. What do you think of this idea? I looked into how this could be realized, and I ended up with `js.md` in combination with a derivative of `funcList.md`. However, I have no idea how to (local) render the output. Can you tell more about this? Perhaps it would be a good idea to include this knowledge under `Developer Info`?

**(Hardcode) table of contents example.**

![javascript-dsl-table-of-contents](https://user-images.githubusercontent.com/1150425/198386749-3ae6a4ff-cd67-4dbf-a82d-549b95ee82e0.png)

>**Domain Modifiers**
>- [A](https://stackexchange.github.io/dnscontrol/js#A)
>- [AAAA](https://stackexchange.github.io/dnscontrol/js#AAAA)
>- [AKAMAICDN](https://stackexchange.github.io/dnscontrol/js#AKAMAICDN)
>- [ALIAS](https://stackexchange.github.io/dnscontrol/js#ALIAS)
>- [AUTODNSSEC_OFF](https://stackexchange.github.io/dnscontrol/js#AUTODNSSEC_OFF)
>- [AUTODNSSEC_ON](https://stackexchange.github.io/dnscontrol/js#AUTODNSSEC_ON)
>- [AZURE_ALIAS](https://stackexchange.github.io/dnscontrol/js#AZURE_ALIAS)
>- [CAA](https://stackexchange.github.io/dnscontrol/js#CAA)
>- [CF_REDIRECT](https://stackexchange.github.io/dnscontrol/js#CF_REDIRECT)
>- [CF_TEMP_REDIRECT](https://stackexchange.github.io/dnscontrol/js#CF_TEMP_REDIRECT)
>- [CF_WORKER_ROUTE](https://stackexchange.github.io/dnscontrol/js#CF_WORKER_ROUTE)
>- [CNAME](https://stackexchange.github.io/dnscontrol/js#CNAME)
>- [DefaultTTL](https://stackexchange.github.io/dnscontrol/js#DefaultTTL)
>- [DnsProvider](https://stackexchange.github.io/dnscontrol/js#DnsProvider)
>- [DS](https://stackexchange.github.io/dnscontrol/js#DS)
>- [FRAME](https://stackexchange.github.io/dnscontrol/js#FRAME)
>- [IGNORE](https://stackexchange.github.io/dnscontrol/js#IGNORE)
>- [IGNORE_NAME](https://stackexchange.github.io/dnscontrol/js#IGNORE_NAME)
>- [IGNORE_TARGET](https://stackexchange.github.io/dnscontrol/js#IGNORE_TARGET)
>- [IMPORT_TRANSFORM](https://stackexchange.github.io/dnscontrol/js#IMPORT_TRANSFORM)
>- [INCLUDE](https://stackexchange.github.io/dnscontrol/js#INCLUDE)
>- [MX](https://stackexchange.github.io/dnscontrol/js#MX)
>- [NAMESERVER](https://stackexchange.github.io/dnscontrol/js#NAMESERVER)
>- [NAMESERVER_TTL](https://stackexchange.github.io/dnscontrol/js#NAMESERVER_TTL)
>- [NO_PURGE](https://stackexchange.github.io/dnscontrol/js#NO_PURGE)
>- [NS](https://stackexchange.github.io/dnscontrol/js#NS)
>- [PTR](https://stackexchange.github.io/dnscontrol/js#PTR)
>- [PURGE](https://stackexchange.github.io/dnscontrol/js#PURGE)
>- [R53_ALIAS](https://stackexchange.github.io/dnscontrol/js#R53_ALIAS)
>- [SOA](https://stackexchange.github.io/dnscontrol/js#SOA)
>- [SRV](https://stackexchange.github.io/dnscontrol/js#SRV)
>- [SSHFP](https://stackexchange.github.io/dnscontrol/js#SSHFP)
>- [TLSA](https://stackexchange.github.io/dnscontrol/js#TLSA)
>- [TXT](https://stackexchange.github.io/dnscontrol/js#TXT)
>- [URL](https://stackexchange.github.io/dnscontrol/js#URL)
>- [URL301](https://stackexchange.github.io/dnscontrol/js#URL301)
>
>**Top Level Functions**
>- [D](https://stackexchange.github.io/dnscontrol/js#D)
>- [D_EXTEND](https://stackexchange.github.io/dnscontrol/js#D_EXTEND)
>- [DEFAULTS](https://stackexchange.github.io/dnscontrol/js#DEFAULTS)
>- [DOMAIN_ELSEWHERE](https://stackexchange.github.io/dnscontrol/js#DOMAIN_ELSEWHERE)
>- [DOMAIN_ELSEWHERE_AUTO](https://stackexchange.github.io/dnscontrol/js#DOMAIN_ELSEWHERE_AUTO)
>- [FETCH](https://stackexchange.github.io/dnscontrol/js#FETCH)
>- [getConfiguredDomains](https://stackexchange.github.io/dnscontrol/js#getConfiguredDomains)
>- [IP](https://stackexchange.github.io/dnscontrol/js#IP)
>- [NewDnsProvider](https://stackexchange.github.io/dnscontrol/js#NewDnsProvider)
>- [NewRegistrar](https://stackexchange.github.io/dnscontrol/js#NewRegistrar)
>- [PANIC](https://stackexchange.github.io/dnscontrol/js#PANIC)
>- [require](https://stackexchange.github.io/dnscontrol/js#require)
>- [require_glob](https://stackexchange.github.io/dnscontrol/js#require_glob)
>- [REV](https://stackexchange.github.io/dnscontrol/js#REV)
>
>**Record Modifiers**
>- [DMARC_BUILDER](https://stackexchange.github.io/dnscontrol/js#DMARC_BUILDER)
>- [R53_ZONE](https://stackexchange.github.io/dnscontrol/js#R53_ZONE)
>- [TTL](https://stackexchange.github.io/dnscontrol/js#TTL)

**Comment by tlimoncelli** [comment]
Yeah, that would be a big improvement!  Good idea!

The README.md file has instructions on how to preview docs changes using Docker.

Would it be possible to generate the TOC automatically?

Tom

**Comment by cafferata** [comment]
>*Would it be possible to generate the TOC automatically?*

Yes, that's was also my idea. See PR https://github.com/StackExchange/dnscontrol/pull/1778 for the results.

>*The README.md file has instructions on how to preview docs changes using Docker.*

Wow! I didn't found it/look over there because it's in the `Installation` > `Docker` section. I would suggest to move this part to [Developer Info](https://stackexchange.github.io/dnscontrol/#:~:text=Developer%20Info) (separated issue). There are two ways of 'testing' the documentation output.

1. https://github.com/StackExchange/dnscontrol#via-docker
2. https://github.com/StackExchange/dnscontrol/blob/7ba051d/docs/runDocker.sh
