### ISSUE TITLE
DOCS: creds-json - Double hyphen

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1792]
Within the [creds-json](https://stackexchange.github.io/dnscontrol/creds-json.html) `hyphen` is included twice. Which of these two is correct according to your @tlimoncelli?

### hyphen

Message: ERROR: creds.json entry ... has invalid ... value ...

> This indicates the entry for `creds.json` has a TYPE value that is
> invalid i.e. it is the empty string or a hyphen (`-`).
> 
> The fix is to correct the `TYPE` parameter in the `creds.json` entry.
> Change it to one of the all caps identifiers in [the service provider list](https://stackexchange.github.io/dnscontrol/provider-list).

### hyphen

> This indicates that the type `-` was specified in a `TYPE` value in
> `creds.json`. There is no provider named `-` therefore that is
> invalid. Perhaps you meant to specify a `-` on a command-line tool?
> 
> The fix is to change the `TYPE` subkey entry in `creds.json` from `-` to
> a valid service provider identifier, as listed
> in [the service provider list](https://stackexchange.github.io/dnscontrol/provider-list).

**Comment by tlimoncelli** [comment]
Yes, the new wording is better.  Good point!

**Comment by cafferata** [comment]
Close by https://github.com/StackExchange/dnscontrol/pull/1807
