### ISSUE TITLE
Linter issue: errorsas

### ISSUE THREAD

**Issue by bits01** [StackExchange/dnscontrol#1810]
https://github.com/StackExchange/dnscontrol/blob/1010138fb6c8e7e456763ef4ebf4bc9cc5174578/providers/ns1/ns1Provider.go#L65

```
# github.com/StackExchange/dnscontrol/v3/providers/ns1
providers/ns1/ns1Provider.go:65:5: second argument to errors.As should not be *error
```

**Comment by bits01** [comment]
It appears we need to pick up gopkg.in/ns1/ns1-go.v2 v2.7.0
https://github.com/ns1/ns1-go/issues/163#issuecomment-1292495230

**Comment by tlimoncelli** [comment]
CC @costasd

**Comment by costasd** [comment]
yup saw it couple days ago, it's new in golang 1.19
```
Vet
The vet checker “errorsas” now reports when errors.As is called with a second argument of type *error, a common mistake.
```

Trying to find some time to test v2.7.0 properly - which will solve this as well by removing this errors.As code.

**Comment by costasd** [comment]
apologies, this took me a bit. Attached PR #1857 should be fixing the error emitted by go1.19's vet linter.
