### ISSUE TITLE
[Netlify] Records are missing trailing dot

### ISSUE THREAD

**Issue by j-f1** [StackExchange/dnscontrol#1825]
I was super excited to see @SphericalKat added support for Netlify!

I tried setting up my DNS config from my existing Netlify setup (using `dnscontrol get-zones --format=js netlify - mydomain.com` with the version of `dnscontrol` on the `master` branch). However, the records it generates are missing the trailing `.`, resulting in a bunch of errors when I tried to run `dnscontrol preview`.
I manually added the necessary dots and now `dnscontrol preview` reports a bunch of changes where `.` will be added to the records on Netlify’s end. I’m not sure if this is just a quirk of how the code parses the responses from Netlify or if Netlify stores DNS information differently from other providers.

**Comment by SphericalKat** [comment]
Thanks for your report @j-f1. I'm looking into why this is happening.

**Comment by tlimoncelli** [comment]
FYI:

I'm 90% sure this means the code just needs to add the missing dot (perhaps only in certain situations).  However, if it isn't that, take a look at this for a weird AWS bug: https://github.com/StackExchange/dnscontrol/blob/master/providers/route53/route53Provider.go#L501

**Comment by j-f1** [comment]
To be clear, this is happening in the values of e.g. CNAME records. `get-zones` pulled in the record `CNAME('feeds', 'cname.vercel-dns.com')`, which looks like this in the web console:

<img width="268" alt="Screenshot_2022-11-29 07 34 17" src="https://user-images.githubusercontent.com/25517624/204530484-efed163d-a7b6-4647-8add-38197989b536.png">

**Comment by SphericalKat** [comment]
Hm, since the trailing dot is optional, would it be necessary to add it in the provider? I think the current behavior seems ideal if netlify "does the right thing" behind the scenes.

**Comment by SphericalKat** [comment]
Makes sense. I'll implement this; sorry about the oversight!
