### ISSUE TITLE
Docs: Document NAPTR

### ISSUE THREAD

**Issue by j-f1** [StackExchange/dnscontrol#1829]
This record type is supported by several providers, as well as DNSControl itself, but there is no documentation of what it is or what parameters can be passed to `NAPTR()`.

**Comment by tlimoncelli** [comment]
I don't think the people that wrote the RFC knew what the parameters are supposed to be :-)

j/k

```
$ grep CanUseNAPTR providers/*/*Provider.go | grep -v Cannot | wc -l
      12
```

Yes, this needs to be documented.

**Comment by cafferata** [comment]
This GitHub issue is resolved by @systemcrash. See here the online [NAPTR documentation](https://docs.dnscontrol.org/language-reference/domain-modifiers/naptr).  cc: @tlimoncelli
