### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by misilot** [StackExchange/dnscontrol#1843]
Looks like the site https://www.dnscontrol.org/ is down. Well I am getting NXDOMAIN when doing an nslookup

**Comment by rmbolger** [comment]
Isn't the documentation site at https://stackexchange.github.io/dnscontrol/? At least, that's what is linked in the Readme.md

**Comment by misilot** [comment]
For me at least it https://stackexchange.github.io/dnscontrol/ tries to direct to dnscontrol.org (and that is linked to on the main GH page https://github.com/StackExchange/dnscontrol under About   🤷🏼‍♂️

**Comment by rmbolger** [comment]
Indeed. Though the About links to https://dnscontrol.org without the `www.` which does seem to be resolving and redirects to https://stackexchange.github.io/dnscontrol/ for me. The `www.` name does seem to be missing in DNS though.

**Comment by misilot** [comment]
Interesting, for me in Firefox it is adding the www. ... let me go clear my cache ..

Clearing my cache fixed it. Thanks @rmbolger!

**Comment by tlimoncelli** [comment]
www.dnscontrol.org is a redirect to `https://stackexchange.github.io/dnscontrol/`.  I was trying to use the github "custom domain" feature to eliminate the need for the redirect. However, I think I messed up.

I've un-done my change.  It should work now ... until my next attempt :-)
