### ISSUE TITLE
dnscontrol version does not return released version number, but commit hash

### ISSUE THREAD

**Issue by misilot** [StackExchange/dnscontrol#1844]
I downloaded the latest release and both the Linux and Darwin version return the hashed version, and not the pretty version

For example I get 
```
dnscontrol  ("38f24ea7aab697fae3cfbdd0b707b1e67b0e8964") built 02 Dec 22 15:17 UTC
```

I would assume it would be v3.23.0 and maybe the hash as well?

**Comment by tlimoncelli** [comment]
CC @cdhunt

**Comment by cdhunt** [comment]
>I would assume it would be v3.23.0 and maybe the hash as well?

That is a correct assumption.

**Comment by cdhunt** [comment]
I see the [3.23.0](https://github.com/StackExchange/dnscontrol/releases/tag/v3.23.0) binaries are returning an empty string for the `Semver` part of the `version.Banner()`. However, I'm unable to build a binary that reproduces the behavior. Neither locally nor in CI. It may have been a temporary bug in goreleaser, but I don't see any apparent issue.

@tlimoncelli, ping me when you are doing the next release. Let's see if this happens again.

**Comment by cafferata** [comment]
Ping @cdhunt for two new releases [v3.24.0](https://github.com/StackExchange/dnscontrol/releases/tag/v3.24.0) & [v3.25.0](https://github.com/StackExchange/dnscontrol/releases/tag/v3.25.0).

```shell
/usr/local/Cellar/dnscontrol/3.25.0/bin/dnscontrol version
```
```text
dnscontrol -dev
```

**Comment by misilot** [comment]
@cdhunt v3.26.0 does the same.

**Comment by cdhunt** [comment]
I pushed a prerelease build to validate.

`dnscontrol "3.26.1-pre" ("07a04c36ceeffbea4abde81cd8d4a16f96097449") built 16 Feb 23 11:46 EST`

**Comment by tlimoncelli** [comment]
@cdhunt Thanks!  That looks a lot better.

I hope to do a release in the next few days. (sorry about the lack of a firm date... there's a weird bug I want to fix first).
