### ISSUE TITLE
Gandi defaults to 100 items_per_page for domain.list API

### ISSUE THREAD

**Issue by chewrocca** [StackExchange/dnscontrol#185]
The default items_per_page returned by the API is 100 :

Reference: http://doc.rpc.gandi.net/domain/reference.html#DomainListOptions

If you have over 100 domains in your account, then not all will be returned in the default call. You can increase this value or pass the 'page' option to show the second page of results.

Reference: http://doc.rpc.gandi.net/domain/reference.html#domain.list

**Comment by tlimoncelli** [comment]
I don't have >100 domains on my gandi account so I can't test this.

Can someone attach the error messages (or bad output) that happens in this situation?

**Comment by chewrocca** [comment]
******************** Domain: _realdomain.com_
----- Getting nameservers from: GANDI
2017/08/30 17:48:14 main.go:194: _realdomain.com_ not listed in zones for gandi account

I opened this issue over here: https://github.com/prasmussen/gandi-api/issues/7 

"I'm not sure if this the right place to ask but Gandi items_per_page when listing domains through their API defaults to 100. I was wondering if adding the parameter {items_per_page:500} would do the trick, or would something more elegant be desirable?"

**Comment by captncraig** [comment]
Most providers that have paging, we need to iterate in a loop to make sure we get everything. @tlimoncelli  perhaps you can replicate by changing page size to an arbitrarily small `1`?

**Comment by tlimoncelli** [comment]
I agree with @chewrocca that this should be fixed at the library level (https://github.com/prasmussen/gandi-api/issues/7)

**Comment by tlimoncelli** [comment]
@captncraig submitted a fix to pramussen.  https://github.com/prasmussen/gandi-api/pull/8
