### ISSUE TITLE
DIFF2: Ongoing discussion

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1854]
- [x] akamaiedgedns @svernick https://github.com/StackExchange/dnscontrol/pull/1872/files?diff=split&w=1
- [ ] autodns @arnoschoon https://github.com/StackExchange/dnscontrol/issues/1904 
- [x] axfrddns @hnrgrgr https://github.com/StackExchange/dnscontrol/pull/1905/files?diff=split&w=1 
- [x] azuredns @vatsalyagoel (https://github.com/StackExchange/dnscontrol/issues/1907) 
- [X] bind @tlimoncelli 
- [x] cloudflare @tresni https://github.com/StackExchange/dnscontrol/issues/1906 
- [x] cloudns @pragmaton https://github.com/StackExchange/dnscontrol/pull/1874/files?diff=split&w=1 
- [x] cscglobal @mikenz https://github.com/StackExchange/dnscontrol/pull/1875/files?diff=split&w=1
- [x] desec @D3luxee https://github.com/StackExchange/dnscontrol/pull/1876/files?diff=split&w=1 
- [x] digitalocean @Deraen https://github.com/StackExchange/dnscontrol/pull/1877/files?diff=split&w=1 
- [x] dnsimple @onlyhavecans https://github.com/StackExchange/dnscontrol/pull/1878/files?diff=split&w=1 
- [x] dnsmadeeasy @vojtad https://github.com/StackExchange/dnscontrol/pull/1879/files?diff=split&w=1 
- [x] domainnameshop @SimenBai https://github.com/StackExchange/dnscontrol/pull/1880/files?diff=split&w=1 
- [x] exoscale @pierre-emmanuelJ https://github.com/StackExchange/dnscontrol/pull/1881/files?diff=split&w=1 
- [X] gandi_v5 @TomOnTime 
- [x] gcloud @riyadhalnur https://github.com/StackExchange/dnscontrol/pull/1856
- [X] gcore @xddxdd #1867 
- [x] hedns @rblenkinsopp https://github.com/StackExchange/dnscontrol/pull/1887 and https://github.com/StackExchange/dnscontrol/pull/1915 
- [x] hetzner @das7pad https://github.com/StackExchange/dnscontrol/pull/1888/files?diff=split&w=1 
- [x] hexonet @papakai https://github.com/StackExchange/dnscontrol/pull/1889/files?diff=split&w=1 
- [x] hostingde @juliusrickert https://github.com/StackExchange/dnscontrol/pull/1890/files?diff=split&w=1 
- [x] inwx @patschi https://github.com/StackExchange/dnscontrol/pull/1891/files?diff=split&w=1 
- [x] linode @koesie10 https://github.com/StackExchange/dnscontrol/pull/1892/files?diff=split&w=1 
- [x] msdns @tlimoncelli https://github.com/StackExchange/dnscontrol/pull/1893/files?diff=split&w=1 
- [x] namecheap @captncraig https://github.com/StackExchange/dnscontrol/pull/1894/files?diff=split&w=1 
- [x] namedotcom @tlimoncelli  https://github.com/StackExchange/dnscontrol/pull/1870 
- [x] netcup @kordianbruck https://github.com/StackExchange/dnscontrol/pull/1895/files?diff=split&w=1 
- [x] netlify @SphericalKat https://github.com/StackExchange/dnscontrol/pull/1896/files?diff=split&w=1 
- [X] ns1 @costasd #1858 
- [x] oracle @kallsyms https://github.com/StackExchange/dnscontrol/pull/1897/files?diff=split&w=1 
- [X] ovh @masterzen https://github.com/StackExchange/dnscontrol/pull/1861/files?diff=split&w=1 
- [x] packetframe @hamptonmoore https://github.com/StackExchange/dnscontrol/pull/1898/files?diff=split&w=1 
- [X] porkbun @imlonghao https://github.com/StackExchange/dnscontrol/pull/1855
- [x] powerdns @jpbede https://github.com/StackExchange/dnscontrol/pull/1899/files?diff=split&w=1 
- [x] route53 @tresni https://github.com/StackExchange/dnscontrol/issues/1908 
- [x] rwth @mistererwin https://github.com/StackExchange/dnscontrol/pull/1900/files?diff=split&w=1 
- [X] softlayer (unowned) https://github.com/StackExchange/dnscontrol/pull/1901 
- [x] transip @blackshadev https://github.com/StackExchange/dnscontrol/pull/1860 
- [x] vultr @pgaskin https://github.com/StackExchange/dnscontrol/pull/2014

**Comment by vatsalyagoel** [comment]
You mentioned that AzureDNS provider is buggy with Diff2, can you expand a bit on that. I have some time this week that I can look to resolve the bugs.

**Comment by tlimoncelli** [comment]
[vatsalyagoel](https://github.com/vatsalyagoel) Thanks for asking! 

The existing code is my first attempt. It mostly works but ... not entirely.  Sadly I don't know the Azure APIs well enough to determine what I've done wrong.  Would you mind taking a look?

Here's a repo case:

```
cd $git/dnscontrol/integrationTest
go test -v -verbose -provider AZURE_DNS -diff2 -end 1
```

Tom

**Comment by masterzen** [comment]
@tlimoncelli please see #1861 for adaptation of the OVH provider to diff2.

**Comment by tlimoncelli** [comment]
Hey folks!  I have good news!  I've made it a lot easier to adopt the diff2 code.  Since the diff2 code makes it easy to have one algorithm that packages the results different ways, I realized I could package the results exactly as the old pkg/diff code presents it.  Yes, that means extra work is being done behind the scenes, but its just moving pointers around so it won't be too much of a performance burden. 

To adopt this method, simply call `diff.NewCompat(dc)` instead of `diff.New(dc)`.  Here's an example:

```
  var corrections []*models.Correction
  var create, del, mod diff.Changeset
  if !diff2.EnableDiff2 {
    differ := diff.New(dc)
    _, create, del, mod, err = differ.IncrementalDiff(actual)
  } else {
    differ := diff.NewCompat(dc)
    _, create, del, mod, err = differ.IncrementalDiff(actual)
  }
  if err != nil {
    return nil, err
  }
```

**Comment by systemcrash** [comment]
> Hey folks! I have good news! I've made it a lot easier to adopt the diff2 code. Since the diff2 code makes it easy to have one algorithm that packages the results different ways, I realized I could package the results exactly as the old pkg/diff code presents it. Yes, that means extra work is being done behind the scenes, but its just moving pointers around so it won't be too much of a performance burden.
> 
> To adopt this method, simply call `diff.NewCompat(dc)` instead of `diff.New(dc)`. Here's an example:
> 
> ```
>   var corrections []*models.Correction
>   var create, del, mod diff.Changeset
>   if !diff2.EnableDiff2 {
>     differ := diff.New(dc)
>     _, create, del, mod, err = differ.IncrementalDiff(actual)
>   } else {
>     differ := diff.NewCompat(dc)
>     _, create, del, mod, err = differ.IncrementalDiff(actual)
>   }
>   if err != nil {
>     return nil, err
>   }
> ```
> 
> I would prefer that people adopt the new `pkg/diff2/By*()` functions eventually, but this new method has the benefit of getting people off the old code faster.
> 
> Once everyone is off the old code, I will introduce the new `IGNORE*()` features which are much more reliable in the `pkg/diff2` world.

Thought it worthwhile to chime in here. Your code-block is nice and short and succinct, but... the `err` variable passes immediately out of scope and the error check outside of the if block does not happen. 

I noticed this after I ran `staticcheck ./...` so to pass the check I had to:

```go
	if !diff2.EnableDiff2 {
		differ := diff.New(dc)
		_, create, del, modify, err = differ.IncrementalDiff(existingRecords)
		if err != nil {
			return nil, err
		}
	} else {
		differ := diff.NewCompat(dc)
		_, create, del, modify, err = differ.IncrementalDiff(existingRecords)
		if err != nil {
			return nil, err
		}
	}
```

declaring `err` before the `if` block is also an option.

**Comment by tlimoncelli** [comment]
> declaring `err` before the `if` block is also an option.

Good catch!   I'm surprised that staticcheck didn't catch that. It catches similar problems.

I see that `providers/packetframe/packetframeProvider.go` fixed this a different way.  I'll review both and make the change.

**Comment by tlimoncelli** [comment]
FYI: The "err" issue is split out to https://github.com/StackExchange/dnscontrol/issues/2159

**Comment by systemcrash** [comment]
I might actually be in error here. (no pun) Other providers seem to correctly declare `err` before the `if` block - although the `staticcheck` picked up on this for me because I did not have `err` declared before the block. Anyway, if we catch some more potential errors, even better.

**Comment by tlimoncelli** [comment]
[@https://github.com/arnoschoon](https://github.com/arnoschoon) we haven't heard from you.  I'm going to close this issue and ask that we pick it up in https://github.com/StackExchange/dnscontrol/issues/2214
