### ISSUE TITLE
Powershell should check if elevated

### ISSUE THREAD

**Issue by mhenderson-so** [StackExchange/dnscontrol#19]
`getzones_windows.go:16` should be preceeded by a command that checks to see if PowerShell is being run with elevated privileges (administrator) and should warn the user accordingly.

**Comment by tlimoncelli** [comment]
Or perhaps check for errors that indicate DNS updates didn't happen due to lack of permission.

**Comment by tlimoncelli** [comment]
ACTIVEDIRECTORY_PS is decommed.  Not going to implement this.
