### ISSUE TITLE
AZURE_DNS: Adopt diff2 code

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1907]
Greetings @vatsalyagoel!

I'm opening this issue to track converting the AZURE_DNS provider to use the new pkg/diff2 code. 

This provider has custom record types and therefore must use the pkg/diff2/By*() functions (i.e. not the NewCompat() function that makes conversion easier to do. Sorry!)

Would you have time to look into this?  I'd like to eliminate the old pkg/diff code in the next month or so, if not sooner.  Obviously I'd be glad to assist any way I can.

Thanks!

Tom

Refers to https://github.com/StackExchange/dnscontrol/issues/1854

**Comment by vatsalyagoel** [comment]
Hey @tlimoncelli,

Happy new year. I was AFK during the break. I'll look at it and submit a PR soon.

**Comment by tlimoncelli** [comment]
Fixed as of e3dc60424732ab65e179fe1817f3789d9c89e065
