### ISSUE TITLE
v0.2.8 checksum mismatch

### ISSUE THREAD

**Issue by jtagcat** [StackExchange/dnscontrol#1914]
https://github.com/kubernetes-sigs/external-dns/issues/2861

```
$ git clone https://github.com/kubernetes-sigs/external-dns.git
$ cd external-dns
$ go mod download
verifying github.com/StackExchange/dnscontrol@v0.2.8: checksum mismatch
        downloaded: h1:QIQtmVs6hIIeu+KjTOkr7XIcSnGwOPWUqqDbS0cQIt8=
        go.sum:     h1:7jviqDH9cIqRSRpH0UxgmpT7a8CwEhs9mLHBhoYhXo8=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

**Comment by tlimoncelli** [comment]
IIRC the 0.2.8 release was recalled and I messed things up in a way that resulted in two 0.2.8 releases.

My recommendation is that we (1) review code changes near that version to make sure nothing bad was inserted, (2) the `kubernetes-sigs/external-dns` project should update to a newer version of dnscontrol.
