### ISSUE TITLE
TransIP: TXT-records

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1917]
I have experienced that new TXT records are provided with extra double quotes. The consequence of this is that, for example, the SPF record cannot be properly parsed by, for example, Azure/Office 365.

**How to reproduce?**

1. Delete the existing SPF record.
    ```diff
    var PROVIDER_NONE = NewRegistrar('none');
    var PROVIDER_TRANSIP = NewDnsProvider('transip', '-');

    D('cafferata.dev',
        PROVIDER_NONE,
        DnsProvider(PROVIDER_TRANSIP),
        DefaultTTL('1d'),
    -   TXT('@', 'v=spf1 -all')
    );
    ```
    ```shell
    dnscontrol push
    ```
    ```text
    ******************** Domain: cafferata.dev
    1 correction
    #1: DELETE TXT cafferata.dev "v=spf1 -all" ttl=86400
    SUCCESS!
    Done. 1 corrections.
    ```
1. Add a new SPF record.
    ```diff
    var PROVIDER_NONE = NewRegistrar('none');
    var PROVIDER_TRANSIP = NewDnsProvider('transip', '-');

    D('cafferata.dev',
        PROVIDER_NONE,
        DnsProvider(PROVIDER_TRANSIP),
        DefaultTTL('1d'),
    +   TXT('@', 'v=spf1 -all')
    );
    ```
    ```shell
    dnscontrol push
    ```
    ```text
    ******************** Domain: cafferata.dev
    1 correction
    #1: CREATE TXT cafferata.dev "v=spf1 -all" ttl=86400
    SUCCESS!
    Done. 1 corrections.
    ```

<img width="1440" alt="transip-cafferata dev-quoted-txt-record" src="https://user-images.githubusercontent.com/1150425/210822852-22348936-d01c-4623-9ece-f7bd2d6237bc.png"><br>_https://www.transip.nl/cp/domein-hosting/domeinnaam/prm/200855038/cafferata.dev/_

<img width="1137" alt="mxtoolbox-txt-records" src="https://user-images.githubusercontent.com/1150425/210825652-d15a4a3e-8566-49a0-8977-bdf712fa1ef3.png"><br>_https://mxtoolbox.com/SuperTool.aspx?action=txt:cafferata.dev_

cc: @blackshadev

**Comment by blackshadev** [comment]
Hi, thanks for the issue report and detailed report.

I created a fix and opened a PR for it.

In the meantime: 
I never had these issues because I always use the [SPF builder functionality](https://stackexchange.github.io/dnscontrol/js#SPF_BUILDER) of dnscontrol. Maybe this can be a working work-arround for you.

**Comment by tlimoncelli** [comment]
(I was away for a few days. This may be redundant)

1. I haven't found an automated way to test this bug. I did, however, find a manual process: https://stackexchange.github.io/dnscontrol/testing-txt-records
2. For a long time I've suspected that SPF Optimizer adds quotes when they aren't needed but I've never been able to prove it.  I'd love a definitive repo case.
