### ISSUE TITLE
TransIP: Multiple matches found for DNS entry

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1919]
**Where do I come from?**
I initially did an import of the TransIP DNS record. From there I found that there are several (older) Google Workspace MX records implementations. I have equalized this from a Javascript macros and variables.

**The problem?**
After deduplication, a diff arises that DNSControl cannot resolve. Perhaps diff2 https://github.com/StackExchange/dnscontrol/pull/1860 will solve this problem? I wanted to share the case with you.

**Reproducible test case**

```diff
var PROVIDER_NONE = NewRegistrar('none');
var PROVIDER_TRANSIP = NewDnsProvider('transip', '-');

D('cafferata.dev',
    PROVIDER_NONE,
    DnsProvider(PROVIDER_TRANSIP),
    DefaultTTL('1d'),
+   MX('@', 10, 'ASPMX.L.GOOGLE.COM.'),
+   MX('@', 20, 'ALT1.ASPMX.L.GOOGLE.COM.'),
+   MX('@', 30, 'ALT2.ASPMX.L.GOOGLE.COM.'),
+   MX('@', 40, 'ASPMX2.GOOGLEMAIL.COM.'),
+   MX('@', 50, 'ASPMX3.GOOGLEMAIL.COM.'),
+   MX('@', 60, 'ASPMX4.GOOGLEMAIL.COM.'),
+   MX('@', 70, 'ASPMX5.GOOGLEMAIL.COM.')
);
```

```shell
dnscontrol push
```
```text
******************** Domain: cafferata.dev
7 corrections
#1: CREATE MX cafferata.dev 10 aspmx.l.google.com. ttl=86400
SUCCESS!
#2: CREATE MX cafferata.dev 20 alt1.aspmx.l.google.com. ttl=86400
SUCCESS!
#3: CREATE MX cafferata.dev 30 alt2.aspmx.l.google.com. ttl=86400
SUCCESS!
#4: CREATE MX cafferata.dev 40 aspmx2.googlemail.com. ttl=86400
SUCCESS!
#5: CREATE MX cafferata.dev 50 aspmx3.googlemail.com. ttl=86400
SUCCESS!
#6: CREATE MX cafferata.dev 60 aspmx4.googlemail.com. ttl=86400
SUCCESS!
#7: CREATE MX cafferata.dev 70 aspmx5.googlemail.com. ttl=86400
SUCCESS!
Done. 7 corrections.
```

The DNSControl domain setup to the single Google Workspace configuration.

```diff

var PROVIDER_NONE = NewRegistrar('none');
var PROVIDER_TRANSIP = NewDnsProvider('transip', '-');

D('cafferata.dev',
    PROVIDER_NONE,
    DnsProvider(PROVIDER_TRANSIP),
    DefaultTTL('1d'),
-   MX('@', 10, 'ASPMX.L.GOOGLE.COM.'),
-   MX('@', 20, 'ALT1.ASPMX.L.GOOGLE.COM.'),
-   MX('@', 30, 'ALT2.ASPMX.L.GOOGLE.COM.'),
-   MX('@', 40, 'ASPMX2.GOOGLEMAIL.COM.'),
-   MX('@', 50, 'ASPMX3.GOOGLEMAIL.COM.'),
-   MX('@', 60, 'ASPMX4.GOOGLEMAIL.COM.'),
-   MX('@', 70, 'ASPMX5.GOOGLEMAIL.COM.')
+   MX('@', 1, 'aspmx.l.google.com.'),
+   MX('@', 5, 'alt1.aspmx.l.google.com.'),
+   MX('@', 5, 'alt2.aspmx.l.google.com.'),
+   MX('@', 10, 'alt3.aspmx.l.google.com.'),
+   MX('@', 10, 'alt4.aspmx.l.google.com.')
);
```
_https://support.google.com/a/answer/174125?hl=en_

```shell
dnscontrol push
```
```
******************** Domain: cafferata.dev
7 corrections
#1: DELETE MX cafferata.dev 60 aspmx4.googlemail.com. ttl=86400
SUCCESS!
#2: DELETE MX cafferata.dev 70 aspmx5.googlemail.com. ttl=86400
SUCCESS!
#3: MODIFY MX cafferata.dev: (30 alt2.aspmx.l.google.com. ttl=86400) -> (5 alt2.aspmx.l.google.com. ttl=86400)
FAILURE! Multiple matches found for DNS entry '@ 86400 MX'
#4: MODIFY MX cafferata.dev: (20 alt1.aspmx.l.google.com. ttl=86400) -> (5 alt1.aspmx.l.google.com. ttl=86400)
FAILURE! Multiple matches found for DNS entry '@ 86400 MX'
#5: MODIFY MX cafferata.dev: (10 aspmx.l.google.com. ttl=86400) -> (1 aspmx.l.google.com. ttl=86400)
FAILURE! Multiple matches found for DNS entry '@ 86400 MX'
#6: MODIFY MX cafferata.dev: (40 aspmx2.googlemail.com. ttl=86400) -> (10 alt3.aspmx.l.google.com. ttl=86400)
FAILURE! Multiple matches found for DNS entry '@ 86400 MX'
#7: MODIFY MX cafferata.dev: (50 aspmx3.googlemail.com. ttl=86400) -> (10 alt4.aspmx.l.google.com. ttl=86400)
FAILURE! Multiple matches found for DNS entry '@ 86400 MX'
Done. 7 corrections.
completed with errors
```

cc: @blackshadev

**Comment by cafferata** [comment]
Perhaps additionally, observed from this work. What should be the desired effect when it comes to case sensitivity?

```diff
var PROVIDER_NONE = NewRegistrar('none');
var PROVIDER_TRANSIP = NewDnsProvider('transip', '-');

D('cafferata.dev',
    PROVIDER_NONE,
    DnsProvider(PROVIDER_TRANSIP),
    DefaultTTL('1d'),
-   MX('@', 10, 'ASPMX.L.GOOGLE.COM.'),
-   MX('@', 20, 'ALT1.ASPMX.L.GOOGLE.COM.'),
-   MX('@', 30, 'ALT2.ASPMX.L.GOOGLE.COM.'),
-   MX('@', 40, 'ASPMX2.GOOGLEMAIL.COM.'),
-   MX('@', 50, 'ASPMX3.GOOGLEMAIL.COM.'),
-   MX('@', 60, 'ASPMX4.GOOGLEMAIL.COM.'),
-   MX('@', 70, 'ASPMX5.GOOGLEMAIL.COM.')
+   mx('@', 10, 'aspmx.l.google.com.'),
+   mx('@', 20, 'alt1.aspmx.l.google.com.'),
+   mx('@', 30, 'alt2.aspmx.l.google.com.'),
+   mx('@', 40, 'aspmx2.googlemail.com.'),
+   mx('@', 50, 'aspmx3.googlemail.com.'),
+   mx('@', 60, 'aspmx4.googlemail.com.'),
+   mx('@', 70, 'aspmx5.googlemail.com.')
);
```

```shell
dnscontrol push
```
```text
******************** Domain: cafferata.dev
Done. 0 corrections.
```

**Comment by blackshadev** [comment]
That is very odd. The problem is TransIP's API doesn't handle updating multi record record sets at all. I have a workarround inplace: removing the recordset altogether and re-add alll records. Which did work, and I recently reïmplemented for diff2. I will look into it with regards to the normal algorithm.

**Comment by cafferata** [comment]
Hi @blackshadev thanks for your work! 👏 I observed the above situation in a [GitLab CI/CD environment](https://stackexchange.github.io/dnscontrol/ci-cd-gitlab) at the time. There it was slightly less easy to apply this work-a-round for the many domains. I eventually chose to delete all MX records for the affected domains from the TransIP API. That ultimately comes down to the same work-a-round, only without the power of DNSControl. Subsequently, DNSControl was allowed to guarantee the end state. 😇 This solved my diff problem.

Would you like me to test `diff2` https://github.com/StackExchange/dnscontrol/pull/1860 with you?

**Comment by blackshadev** [comment]
Oh wauw, I didn't even know about that documentation. Nice.

Regarding the diff2, yes if you want to go the extra mile. Go ahead. I will focus on creating a fix for the current diff algorithm first.

**Comment by tlimoncelli** [comment]
(I was away for a few days. I'm just catching up now)

Interesting bug!  It looks like you have it handled but I thought I'd make two comments:

1. Is there a test you could add to `integrationTest/integration_test.go` that would detect this in the future? (Ideally the test fails in master but passes after applying https://github.com/StackExchange/dnscontrol/pull/1920)

2.  Case sensitivity in DNSControl: [Option #4](https://stackexchange.github.io/dnscontrol/opinions) is that users can specify upper or lowercase but internally everything is downcased and used that way.
