### ISSUE TITLE
Support for GeoIP features in BIND

### ISSUE THREAD

**Issue by ximaera** [StackExchange/dnscontrol#194]
https://kb.isc.org/article/AA-01149/0/Using-the-GeoIP-Features-in-BIND-9.10.html

Are there any plans to support that in BIND?

Moreover, a lot of managed DNS providers out there support geolocation-based balancing. It may be a good idea to learn which providers do that via their API, and add support for that API as well.

**Comment by tlimoncelli** [comment]
I don't use GeoIP in BIND so Im not sure.  From what I've read, Dnscontrol doesn't prevent you from doing that. Is there something specific that would be needed?

**Comment by captncraig** [comment]
I think it would be nice to have geo availible. Most of the big cloud ones support it in some form. 

I wonder if it is really possible to do in a provider independent way. If we do it for anybody we should try to have a unified way of representing it. I'd like someone more experienced in the space to probably make a good design.

I imagine it would look somewhat like our current transform setup. Where we always define records with the "safe" or "primary" address, and we have some transform description that we apply to a zone, or give to the provider as metadata. That would define the different regions and transforms and things needed, and then the provider would need to implement. 

It may be that there is a unique transform schema per provider if they are not generic enough. I imagine they all have different pops, and you may map them differently depending on the topology.

**Comment by captncraig** [comment]
If I read the docs right: https://kb.isc.org/article/AA-01149/0/Using-the-GeoIP-Features-in-BIND-9.10.html

Bind pretty much configures routing in all of the config files that dnscontrol does not really manage. You just have to generate different zones with different views for different clients?

I wonder if you could accomplish that with creative use of `require`. Something like:

`zoneA.js`:
```
var mainIP = "1.2.3.4";
require("commonZones.js"); //which presumably uses the above variable.
```

`zoneB.js`:
```
var mainIP = "5.6.7.8";
require("commonZones.js"); 
```

And just run dnscontrol multiple times with different bind directories. Maybe not super helpful, but it may work.

**Comment by tlimoncelli** [comment]
I would love to add support for GeoIP but I can't design the feature if I don't have a concrete example of when people would need this. Please tell us a simple example.  Thanks!

**Comment by ximaera** [comment]
@tlimoncelli, @captncraig, thank you for your response. I'd provide an overview of the geographic and topological options available in most popular cloud DNS providers in several days.

**Comment by tlimoncelli** [comment]
That would be great.  I'm particularly interested in knowing how you use GeoIP right now (assuming you are)

**Comment by RehanSaeed** [comment]
Came here looking for this feature. It seems that OctoDNS [has this support](https://github.com/github/octodns#supported-providers) for a limited set of providers. Unfortunately, Cloudflare is not one of them.

**Comment by RehanSaeed** [comment]
I'm new to both so I'm not sure about designs but I'm thinking you can 'borrow' some ideas from OctoDNS.

**Comment by tlimoncelli** [comment]
After all this time there's been no demand for this. Closing.  Can re-open if we need this in the future.
