### ISSUE TITLE
Release v3.24.0

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1943]
Hi  @tlimoncelli, I miss the release/release notes of `v3.24.0`.
- https://github.com/StackExchange/dnscontrol/releases/tag/v3.24.0

The latest version from the GitHub release page is `v3.23.0`.
- https://github.com/StackExchange/dnscontrol/releases/latest

**Comment by tlimoncelli** [comment]
@cafferata The release notes are marked as "Draft".  They'll appear when I finish them. (it's going slowly)

**Comment by cafferata** [comment]
Thanks! I see the release notes have been added.
