### ISSUE TITLE
TypeScript typings: JetBrains PHPStorm rendering

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1944]
Because I was asked to read https://github.com/StackExchange/dnscontrol/pull/1940 I tested the TypeScript typings. In addition, the content cleaning does not seem to be done correctly. Is this something from JetBrains IDE? Or does this also happen in other editors (Visual Studio Code)? 🤷‍♂️ 

<img width="1440" alt="typescript-typings-cleaning" src="https://user-images.githubusercontent.com/1150425/212427856-6dbb79ae-451e-4834-861d-29138db5334f.png">

cc: @j-f1

**Comment by j-f1** [comment]
Weird! That looks like an editor bug! Here’s what I see in VS Code:
<img width="659" alt="Screenshot_2023-01-13 17 08 22" src="https://user-images.githubusercontent.com/25517624/212428346-75101db8-19ce-4305-8a20-b392baa599d6.png">

**Comment by cafferata** [comment]
Thanks for the Visual Studio Code screenshot. Do you @j-f1 or @tlimoncelli want to take further action with the issue? Perhaps include it in the documentation as a current 'known issue'? Or should I close the issue for now?

**Comment by j-f1** [comment]
I’d say close this issue for now but definitely file it as a bug in JetBrains/their TS plugin

**Comment by cafferata** [comment]
I found this issue and thought I would report back that this problem no longer occurs within PHPStorm.

![Screenshot 2023-12-15 at 10 09 01](https://github.com/StackExchange/dnscontrol/assets/1150425/7547411a-dbd0-4eee-9e31-073ea5ecc99b)
