### ISSUE TITLE
Duplicate domain definitions should not be allowed

### ISSUE THREAD

**Issue by pmoroney** [StackExchange/dnscontrol#195]
It seems duplicates are allowed:
The following config is legal but should probably display an error:
```
var namecom = NewRegistrar("name.com", "NAMEDOTCOM");
var namecom_dns = NewDnsProvider("name.com", "NAMEDOTCOM")

D("example.org", namecom,
  A("@", "127.0.0.1")
)

D("example.org", namecom)
```

**Comment by tlimoncelli** [comment]
Good point.

An easy way to implement this:

`function D()` in `pkg/js/helpers.js` should "throw" if the domain name already is defined.

**Comment by captncraig** [comment]
I'm wondering if there is any valid use case for this at all. What if I want to do slightly different configs to different providers? Maybe I'm stretching here. Two possible situations:

Perhaps I want to use proxider X as my primary, but have provider Y set up as a standby with a slightly different config for emergency purposes:

```
D("example.com", REG_NAMECOM, DnsProvider(CF), 
      A("whatever", "1.2.3.4"),
      ALIAS("ack", "foo.com.")
)

D("example.com", REG_NONE, DnsProvider(NS1), 
      A("whatever", "1.2.3.4"),
      ALIAS("ack", "emergencyDownPage.com.")
)
```

Actually not sure if there are valid use cases there. But this one may be more realistic:

```
// main domain served from provider X
D("example.com", REG_NAMECOM, DnsProvider(CF), 
      A("whatever", "1.2.3.4"),
      NS("a", "ns1.providerY.com.")
)

// Delegated subdomain served from provider Y
D("example.com", REG_NONE, DnsProvider(NS1), 
      A("a", "1.2.3.4"),
      A("b.a", "2.3.4.5")
)
```

My gut tells me more often than not it will be an error though.

**Comment by tlimoncelli** [comment]
I'd rather prevent the error than handle a use-case that nobody can point to in reality.

If someone does come up with a use-case, we can add some kind of "DUP_OK" meta flag.

**Comment by tlimoncelli** [comment]
@chewrocca You seem to be awesome at JavaScript. Would you be interested in taking a try at this?  I think a simple "error if a domain is defined the second time" would be sufficient.

**Comment by captncraig** [comment]
We could also just detect it in the validation phase on the go end. Or add a quick check to the `D` function in helpers.js. Either way is fine. There is a section [in the js tests for error cases](https://github.com/StackExchange/dnscontrol/blob/master/pkg/js/js_test.go#L72) that this would go nicely in.

**Comment by tlimoncelli** [comment]
Question for @jeanpaulgalea: are the examples you listed in production today or are they hypothetical?   I'd like to merge @pmoroney 's PR.

**Comment by jeanpaulgalea** [comment]
It is in production, but I wouldn't want to hold this back just because of our use case.

In general, I think not allowing duplicates by default makes sense, though having a flag to disable it would be greatly appreciated.
