### ISSUE TITLE
Duplicate records when use get-zones with microsoft dns

### ISSUE THREAD

**Issue by xeonkeeper** [StackExchange/dnscontrol#1954]
Hi there!
I have zone on windows server 2019 with about 1000+ A records and subdomains. I have tried  to convert this zone with command "dnscontrol get-zones --format=js --out=draft.js MSDNS MSDNS domain.com"
and i got duplicate records like: 
        A('rms', '10.247.192.114'),
	A('roc', '10.247.192.115'),
	A('roc2016', '10.247.192.30'),
	A('rms.domain.com', '10.247.192.114'),
	A('roc.domain.com, '10.247.192.115'),
	A('roc2016.domain.com', '10.247.192.30'),

I don't know why this happen. I have tried to convert other small zones from the server and no issue with them... I'm stuck...

**Comment by xeonkeeper** [comment]
I was able to find what the problem is. Someone mistakenly added an empty subdomain domain.com inside the main domain.com domain. And it caused such behavior. Removing it solved my problem

**Comment by tlimoncelli** [comment]
Glad you were able to find the issue!
