### ISSUE TITLE
DOCS: notes and suggestions

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1960]
I'm going to list a bunch of random thoughts and ideas
here rather than open a bunch of issues. We can split them out later 
if needed.

### "Domain Modifiers" header

"Domain Modifiers" is big and unwieldy. We should split it up.

* DNS Domain Settings
* DNS Records

Or maybe split it even more:

* DNS Domain Settings
* DNS Records 
* DNS Record Builders

### "JavaScript DSL"

I think we should change this to "The Language"
and the content should say:

> The DNSControl configuration file (`dnsconfig.js`) is
a powerful declarative "infrastructure as code" (IaC) language for defining your
DNS domains, records, and other attributes.
>
> You may notice it looks a lot like JavaScript. That's because
it is the subset of JavaScript that is implemented by the 
[otto](https://github.com/robertkrimen/otto) projects. This means your
configuration can define macros, functions, even loop through a list 
of domain names or other values!

In hindsight, I should have given this project a cute name that makes sense as both the name of the language and the name of the implementation. Terraform really got that right!

Tom

**Comment by andrewbaxter** [comment]
I immediately got bit by this - unexpected keyword `const` when trying to define a function.

The documentation says

> DNSControl uses JavaScript as its primary input language to provide power and flexibility to configure your domains.

which seems to be just wrong.

**Comment by tlimoncelli** [comment]
The Otto docs say:

> Otto targets ES5. ES6 features (eg: Typed Arrays) are not supported.

**Comment by andrewbaxter** [comment]
Yeah, but targeting ES5 doesn't mean it's necessarily feature complete, right? TBF I think I was also having trouble remembering which language features were ES5 vs ES6 when I wrote the comment.

I think the new language you have is great.  It might be good to mention that it's ES5 too, since I expect most people will assume ES6 and that limitation is pretty well hidden in the otto readme.

**Comment by systemcrash** [comment]
I figured the ES5 thing out eventually. Would do well to be documented. 

Also, PR #2197 eases the structuring part substantially. Just move docs to appropriate folder structure and `go generate ./...` 

I don't know what happens on the server side, but perhaps some adjustments to accommodate for receiving the new auto compiled structure are necessary there.
