### ISSUE TITLE
Release v3.24.0 - Broken link - TypeScript typings

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1967]
With the merge of https://github.com/StackExchange/dnscontrol/pull/1809, the documentation URL in the latest release [v3.24.0](https://github.com/StackExchange/dnscontrol/releases/tag/v3.24.0) (_from 4 days ago_) is broken. I think it's good to fix it since these release notes have just been published.

```diff
-https://stackexchange.github.io/dnscontrol/typescript
+https://docs.dnscontrol.org/getting-started/typescript
```

cc: @tlimoncelli @cdhunt

**Comment by cafferata** [comment]
Cross reference https://github.com/StackExchange/dnscontrol/issues/1967 https://github.com/StackExchange/dnscontrol/issues/1985.

**Comment by tlimoncelli** [comment]
I don't see this link in on https://github.com/StackExchange/dnscontrol/releases/tag/v3.24.0  

Where should I be looking?

**Comment by cafferata** [comment]
See the link from the first bull point: [TypeScript typings](https://github.com/StackExchange/dnscontrol/releases/tag/v3.24.0#:~:text=of%20small%20bugs%3A-,TypeScript%20typings,-%3A%20Your%20IDE%20now).
