### ISSUE TITLE
HOSTINGDE: AUTODNSSEC Suport

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#1973]
The `HOSTINGDE` API does support auto dnssec. However, this is not implemented within the dnscontrol provider right now.

I'm creating this issue to track implementation of this feature.

@juliusrickert @membero Would you be interested in adding this? DNSSEC is such a crucial mechanism since so many security features rely on DNS nowadays, it would be great to have this working.

**Comment by Yannik** [comment]
Hey @juliusrickert 

Could you give me a short heads-up if this is something you might tackle any time soon?

**Comment by juliusrickert** [comment]
> Could you give me a short heads-up if this is something you might tackle any time soon?

No, I won't. It's not of interest to me. Feel free to implement it yourself, ask hosting.de to implement it, or commission me or someone else to do so.
