### ISSUE TITLE
HOSTINGDE: Subaccount support

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#1974]
The `HOSTINGDE` API features an option to create domains and zones under sub accounts:

![Screenshot from 2023-01-23 08-41-39](https://user-images.githubusercontent.com/801996/213949452-f8d18f6d-7345-41c0-afce-8e2b3c984138.png)

This is a great feature and it would be awesome to have this supported within the dnscontrol providers.

I think it would be sufficient to provide the `accountId` to the `NewRegistrar` and `NewDnsProvider` functions, I don't really see a need do do this on a per-zone 

I'm creating this issue to track implementation of this feature.

@juliusrickert @membero Would you be interested in adding this?

**Comment by juliusrickert** [comment]
I have not implemented this feature as we don't need it.

I don't see the value of this either, maybe in combination with #1975. Otherwise, there are no operations that work on all DNS zones. To limit the scope of operations or privileges, this functionality isn't suited either.

Feel free to tell me if I have missed anything.

**Comment by tlimoncelli** [comment]
If someone needed this, I would add it as a field to creds.json.  Gandi has something similar (but I don't think anyone uses it).

**Comment by Yannik** [comment]
> I have not implemented this feature as we don't need it.
> 
> I don't see the value of this either, maybe in combination with #1975. Otherwise, there are no operations that work on all DNS zones. To limit the scope of operations or privileges, this functionality isn't suited either.
> 
> Feel free to tell me if I have missed anything.


Our need for this is the following:

We are a http.net partner and resell domains to our managed-services customers. This means that we manage the purchase/deletion of domains, and, most importantly, configuration of dns zones for these customers. 
However, we cannot have all these customers domains/zones in our main account: It is crucial to create them in subaccounts, as we need to get accurate billing information for each customer. Our billing system can then split the billing csv by subaccount id and assigns the relevant line-item to the correct customer.

Additionally, it is much easier to reference which customer a domain belongs to in the webinterface if attached to a subaccount. It also makes handoff easier in case customers decides to go with a different managed service provider.

I do agree with your assessment that this is also useful in combination with #1975. Especially when adopting dnscontrol  on a per-customer basis, which we would very much like to do :-)

It would also be very useful in combination with #1976, as it would allow to split up domain/dns config per-customer.

@juliusrickert 

I hope I was able to convince you that this is a useful feature :)

**Comment by juliusrickert** [comment]
> This means that we manage the purchase/deletion of domains, and, most importantly, configuration of dns zones for these customers.

You can access domains in subaccounts. So I don't see the need for subaccount support for this specific case.
But for retrieving all zones or creating new ones, this could be useful indeed.

> I think it would be sufficient to provide the accountId to the NewRegistrar and NewDnsProvider functions, I don't really see a need do do this on a per-zone

In general, I'm with Tom regarding the location of the option in `creds.json` and not as an option in the `NewDnsProvider` function, [like the nameservers](https://github.com/StackExchange/dnscontrol/blob/bb88b7c4b0f403cf5568e99d91142ad936d17d9f/documentation/providers/hostingde.md#example-httpnet-configuration); I don't see the need for `NewRegistrar` to be edited, as DNSControl doesn't register domains and can access domains in subaccounts.

This behaviour would be in line with providers like [AutoDNS](https://github.com/StackExchange/dnscontrol/blob/bb88b7c4b0f403cf5568e99d91142ad936d17d9f/documentation/providers/autodns.md?plain=1#L14), [ClouDNS](https://github.com/StackExchange/dnscontrol/blob/bb88b7c4b0f403cf5568e99d91142ad936d17d9f/documentation/providers/cloudns.md?plain=1#L13), etc.

**Comment by Yannik** [comment]
> You can access domains in subaccounts. So I don't see the need for subaccount support for this specific case.

Absolutely. I was just describing the overall structure of what we do with the subaccounts :)

>  But for retrieving all zones or creating new ones, this could be useful indeed.

Right, this is what I'd like to use it for.

> In general, I'm with Tom regarding the location of the option in creds.json and not as an option in the NewDnsProvider function, [like the nameservers](https://github.com/StackExchange/dnscontrol/blob/bb88b7c4b0f403cf5568e99d91142ad936d17d9f/documentation/providers/hostingde.md#example-httpnet-configuration); I don't see the need for NewRegistrar to be edited, as DNSControl doesn't register domains and can access domains in subaccounts.

That's fine with me :)
