### ISSUE TITLE
HOSTINGDE: get-zone all support

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#1975]
The `HOSTINGDE` API does support listing all zones. However, this is not implemented within the dnscontrol provider right now.

Running `dnscontrol get-zone hosting.de - all` where `hosting.de` is a `HOSTINGDE` DnsProvider results in:

```
provider type - cannot list zones to use the 'all' feature
```

I'm creating this issue to track implementation of this feature.

@juliusrickert @membero

**Comment by Yannik** [comment]
@tlimoncelli 
I'm currently trying to implement this, as it seemed like the easiest feature to me. (I don't have any go experience)

I have defined these functions:
```
func (hp *hostingdeProvider) getAllZoneConfigs() ([]*zoneConfig, error) {
	params := request{}

	resp, err := hp.get("dns", "zoneConfigsFind", params)
	if err != nil {
		return nil, fmt.Errorf("could not get zones: %w", err)
	}

	zc := []*zoneConfig{}
	if err := json.Unmarshal(resp.Data, &zc); err != nil {
		return nil, fmt.Errorf("could not parse response: %w", err)
	}

	return zc, nil
}```
in `api.go`

and 

```

**Comment by Yannik** [comment]
I'm currently trying to implement this, as it seemed like the easiest feature to me. (I don't have any go experience)

I have defined these functions:
```
func (hp *hostingdeProvider) getAllZoneConfigs() ([]*zoneConfig, error) {
	params := request{}

	resp, err := hp.get("dns", "zoneConfigsFind", params)
	if err != nil {
		return nil, fmt.Errorf("could not get zones: %w", err)
	}

	zc := []*zoneConfig{}
	if err := json.Unmarshal(resp.Data, &zc); err != nil {
		return nil, fmt.Errorf("could not parse response: %w", err)
	}

	return zc, nil
}
```

in `api.go`

and 

```
func (hp *hostingdeProvider) ListZones() ([]string, error) {
	zcs, err := hp.getAllZoneConfigs()
	if err != nil {
		return nil, err
	}
	zones := make([]string, 0, len(zcs))
	for _, zoneConfig := range zcs {
		zones = append(zones, zoneConfig.Name)
	}
	return zones, nil

}
```
in `hostingdeProvider.go`

However, I am running into an issue that the `json.Marshal(params)` command ([here](https://github.com/StackExchange/dnscontrol/blob/master/providers/hostingde/api.go#L239)) converts the fields of the request type like this:

![Screenshot from 2023-01-31 00-08-37](https://user-images.githubusercontent.com/801996/215530474-54f566ae-d9a7-425e-b0ad-5b33d4ace30b.png)

As you can see the filter field (which has not been set: `params := request{}`) is being encoded as `"filter":{"field":"","value":""}`. This results in an error reponse from the API. 

As far as I understand the Marshal function, the [type definition](https://github.com/StackExchange/dnscontrol/blob/master/providers/hostingde/types.go#L18) 

```
	Filter         filter `json:"filter,omitempty"`
```

should result in the filter field **not**  being encoded. With my limited go experience, I am at a loss what is wrong here.

@tlimoncelli Can you help here?

**Comment by tlimoncelli** [comment]
Ah!  "omitempty" is smart enough to handle a single item that is the "zero value", but not a struct that has all members that are zero.

Change the filter to be a pointer that is nil when you want it omitted, and a pointer to a filter when it should be included.

**Comment by Yannik** [comment]
Thanks, that fixed it. It is generally working now, however it's really slow (more than 2 minutes) I don't know why, since the api request itself only takes about 4 seconds. 

Do you have any idea what's causing this? @tlimoncelli
