### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by jmwallach** [StackExchange/dnscontrol#199]
All links on https://stackexchange.github.io/dnscontrol/ are broken.

**Comment by captncraig** [comment]
Looks like at some point github pages changed how they generate links. I can fix.

**Comment by captncraig** [comment]
For some reason `{{site.github.url}}` is coming out empty. We have not changed anything recently, so I'm not sure why it is broken. Still digging.

**Comment by captncraig** [comment]
I believe some rebuilds and force refresh has it looking good for me. Can you confirm?

**Comment by jmwallach** [comment]
Working, thanks.
