### ISSUE TITLE
Allow ttl to be specified as duration string.

### ISSUE THREAD

**Issue by captncraig** [StackExchange/dnscontrol#20]
Currently we expect `DefaultTTL(3000)` or `TTL(100)` with only numbers.

Would be cool if you could do `DefaultTTL("4h")` instead and defer to go's ParseDuration.

**Comment by tlimoncelli** [comment]
This should be handled at the JS layer, so that what makes it to the json file is pure.

helpers.js is going to need to call out to some Go code, perhaps a function called DURATION() which calls some go code like:

	orig := "4h"   // The original string.
	i, err := strconv.Atoi(orig)
	if err != nil {
		d, err := time.ParseDuration(orig)
		if err != nil {
			panic(err)  // Do something wiser than panic
		}
		i = int(d.Seconds())
	}
	fmt.Printf("%d\n", i)

**Comment by tlimoncelli** [comment]
We added this a while ago.  TTL("1h") is the same as TTL("3600") (and is more readable)

This is documented here: https://stackexchange.github.io/dnscontrol/js
