### ISSUE TITLE
DOCS: Docker Hub readme Getting Started page link gives 404.

### ISSUE THREAD

**Issue by Aartsie** [StackExchange/dnscontrol#2001]
Hi i think the Docker hub readme is out dated and not updating automatically anymore.
When i check the link in the Git readme it works fine but on the Docker hub page i got a 404 page.

[https://hub.docker.com/r/stackexchange/dnscontrol](https://hub.docker.com/r/stackexchange/dnscontrol)
**On section "An Example":**
There is an link in: See [Getting Started](https://stackexchange.github.io/dnscontrol/getting-started) page on documentation site.

**On section "More info at our web site":**
The getting started guide: https://stackexchange.github.io/dnscontrol/getting-started

**Comment by Aartsie** [comment]
Friendly ping @TomOnTime

**Comment by tlimoncelli** [comment]
Sadly Docker builds are broken right now and there's no resources for fixing it. If someone from the community can step up, I'd gladly accept help.

**Comment by tlimoncelli** [comment]
Docker is working again.  (Thanks @SignalRichard !)

```
$ docker run --rm   -it   -v $(pwd)/dnsconfig.js:/dns/dnsconfig.js   -v $(pwd)/creds.json:/dns/creds.json   -v $(pwd)/spfcache.updated.json:/dns/spfcache.updated.json   -v $(pwd)/spfcache.json:/dns/spfcache.json   -v $(pwd)/zones/:/dns/zones/   -u $(id -u ${USER}):$(id -g ${USER})   stackexchange/dnscontrol  --diff2  version
dnscontrol "3.31.5" ("9e66c3760ef1a5a41091b9c28ea47d1cc3d026bd") built 12 May 23 14:57 UTC
```
