### ISSUE TITLE
DOCS: Integration Tests

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#2002]
What do you think of the idea of including [integrationTest/readme.md](https://github.com/StackExchange/dnscontrol/blob/master/integrationTest/readme.md) in the online docs https://docs.dnscontrol.org/developer-info/integration-tests?

**Comment by tlimoncelli** [comment]
Yes, but we should split out the `Debugger` section into its own doc.

**Comment by cafferata** [comment]
Thanks for your quick response, see https://github.com/StackExchange/dnscontrol/pull/2007
