### ISSUE TITLE
INWX: Add support for URL/URL301

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#2009]
This is a issue to track feature request/support for `URL()` and `URL301()` for INWX.

It was indirectly requested in #1091, which I slightly mistakenly hijacked with a different issue. But as original issue refers to issues with unsupported feature with INWX, I decided to create new issue to explicitly add support.

**Comment by tlimoncelli** [comment]
CC @patschi (owner of the INWX provider)

**Comment by patschi** [comment]
Sorry - time constraints and there seem to be no further requests or interest in any implementation. I'm not using it personally, and don't plan to do so.

Anyway, some basic implementation wasn't too difficult, but I underestimated the changes needed. Either I'm doing something wrong, or dnscontrol in general is lacking support of URL/301 and FRAME type.

The basic implementation was pretty easy:
```
diff --git forkSrcPrefix/providers/inwx/inwxProvider.go forkDstPrefix/providers/inwx/inwxProvider.go
index 1e5e546cab44f56c08a0a4cf98281df83a04bba7..e09b8bd87154d4c04f9ebe185f33e00c39724cef 100644
--- forkSrcPrefix/providers/inwx/inwxProvider.go
+++ forkDstPrefix/providers/inwx/inwxProvider.go
@@ -74,6 +74,10 @@ func init() {
 		RecordAuditor: AuditRecords,
 	}
 	providers.RegisterDomainServiceProviderType("INWX", fns, features)
+
+	providers.RegisterCustomRecordType("URL", "INWX", "")
+	providers.RegisterCustomRecordType("URL301", "INWX", "")
+	providers.RegisterCustomRecordType("FRAME", "INWX", "")
 }
 
 // getOTP either returns the TOTPValue or uses TOTPKey and the current time to generate a valid TOTPValue.
@@ -186,6 +190,15 @@ func makeNameserverRecordRequest(domain string, rec *models.RecordConfig) *goinw
 	case "SRV":
 		req.Priority = int(rec.SrvPriority)
 		req.Content = fmt.Sprintf("%d %d %v", rec.SrvWeight, rec.SrvPort, content[:len(content)-1])
+	case "URL":
+		req.URLRedirectType = "HEADER302"
+	case "URL301":
+		req.Type = "URL"
+		req.URLRedirectType = "HEADER301"
+	case "FRAME":
+		req.Type = "URL"
+		req.URLRedirectType = "FRAME"
+		req.URLRedirectTitle = "Redirect"
 	default:
 		req.Content = rec.GetTargetCombined()
 	}
```

Adding records is working good:
```
******************** Domain: domain.tld
3 corrections (PK-INWX)
#1: + CREATE FRAME test3.frame.domain.tld https://urlframe.com ttl=43200
SUCCESS!
#2: + CREATE URL301 test2.url301.domain.tld https://url301.com ttl=43200
SUCCESS!
#3: + CREATE URL test1.url302.domain.tld https://url302.com ttl=43200
SUCCESS!
Done. 3 corrections.
```

By using:
```
URL("test1.url302", "https://url302.com"),
URL301("test2.url301", "https://url301.com"),
FRAME("test3.frame", "https://urlframe.com"),
```

But when you run dnscontrol, it just fails:
```
******************** Domain: domain.tld
ERROR
Error getting corrections (PK-INWX): INWX: unparsable record received: unknown rtype (URL) when parsing (https://url302.com) domain=(domain.tld)
Done. 0 corrections.
completed with errors
```

The code here is lacking understanding of the URL type: (or URL301 or FRAME)
https://github.com/StackExchange/dnscontrol/blob/e166160072704365cb7874a40675518a5dfeb918/models/t_parse.go#L39-L84

Not sure how to move forward or how much work a implementation takes up and if it's worth the time.

**Comment by patschi** [comment]
Lack of standardization is making it indeed more difficult. `REDIRECT` is not supported by INWX, there's no selectable type for the same. I'd honestly just think about dropping this until there's broader support in dnscontrol - and if there're plans supporting those types more broadly across more providers.

**Comment by TomOnTime** [comment]
Ideally there should be a generic REDIRECT() feature, that selects the provider-specific feature (INWX_REDIRECT(), CLOUDFLARE_REDIRECT(), etc.)  (Those names don't exist yet, and we'd have to deal with backwards compatibility... yadda yadda yadda).

I recently realized that no provider supports HTTPS on their redirects, just HTTP.  Doesn't that make this feature unusable?

Tom

**Comment by patschi** [comment]
That was something I've been discovering with my tests as well. Using `URL` (and similar), it also just uses IPv4 and non-SSL to create the redirect. So I don't think its worth adding it - at least for now.

**Comment by TomOnTime** [comment]
I shouldn't say "unusable".... a better word is "antiquated".

That said... I think an even better thing would be to create a new pseudo-type called "UNKNOWN" which can store any record type that DNSControl is unaware of.  It could handle both records with an RFC and vendor-specific records.

I've opened https://github.com/StackExchange/dnscontrol/issues/2432 to collect thoughts about UNKNOWN.

Tom

**Comment by patschi** [comment]
Sounds good. I think it might be indeed a good thing to not error and exit once a unknown DNS type is being reported from the API. It should be logged for sure, but dnscontrol should be able to continue to work and doing its job.

I'll be then closing this issue down and favor of your new created issue. If there's any interesting in getting this for INWX implemented, we can get back to this at a later date.
