### ISSUE TITLE
docs: remove references to get-domains command

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#2017]
There are [various](https://docs.dnscontrol.org/service-providers/providers/gcloud#new-domains) [providers](https://docs.dnscontrol.org/service-providers/providers/route53#new-domains) which have the following text in their documentation:

`If a domain does not exist in your Route53 account, DNSControl will not automatically add it with the push command. You can do that either manually via the control panel, or via the command dnscontrol create-domains command.`

As far as I can see, that command is deprecated, and domains are created automatically if the provider supports it. 

Therefore this should be removed from the documentation.

(Perhaps it would be nice to clarify that domain/zone creation is done automatically in the docs a bit more. Maybe [here](https://docs.dnscontrol.org/#use-it)?)

**Comment by tlimoncelli** [comment]
Valid points!  Would you be interested in submitting a PR?
