### ISSUE TITLE
Questions regarding TTL warnings

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#2018]
Hi @tlimoncelli,

I was just running dnscontrol and I'm seeing following warnings:

```text
2023/01/30 22:55:22 printIR.go:110: WARNING: label with multipe TTLs: domain1.tld TXT ([3600 43200])
2023/01/30 22:55:22 printIR.go:110: WARNING: label with multipe TTLs: domain2.tld TXT ([3600 43200])
2023/01/30 22:55:22 printIR.go:110: WARNING: label with multipe TTLs: domain3.tld TXT ([3600 43200])
```

Two points:
1. Small typo `multiple`
2. The given output like `domain1.tld TXT` unfortunately doesn't help me to see which TXT record it complains about, as there are multiple ones. Is there any way to get more output here? (Like name, truncated output of the value, etc)

In my setup I'm using:
```
DEFAULTS(
	DefaultTTL('1h')
);
```

So the chance of having multiple TTLs is quite high. I'm not sure if there're alternative/better ways handling those warnings in general or when using such default values.

**Comment by tlimoncelli** [comment]
1. Late night coding!
2. Yeah, the format could be improved.  My first step was just to make it visible.  How about something like: `A:3600 MX:43200`.  Would you be interested in writing the PR?

Some providers reject DNS updates if they don't all have the same TTL (on the same label).  Others (like one I was editing recently) simply uses the TTL of the last entry, which might not be what you expect.  

A better solution might instead be to have `pkg/normalize` set all TTLs on the same label to the lowest value and output a warning.

The reality is that most TTLs are ignored.  I'm not sure how much effort to put into this.
