### ISSUE TITLE
Pull request template asks to run `go tidy`, which does not exist

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#2020]
The pull request template (https://github.com/StackExchange/dnscontrol/blob/master/.github/pull_request_template.md)  asks to run `go tidy`. However, that seems to be an invalid command:

```
$ go tidy            
go tidy: unknown command
Run 'go help' for usage.
```

**Comment by cafferata** [comment]
Thanks for the feedback. Fixed by https://github.com/StackExchange/dnscontrol/pull/2021
