### ISSUE TITLE
HOSTINGDE: Setting records for zone which is tied to a template does not work

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#2024]
Setting records for zone which is tied to a template results in this error:

```
FAILURE! [{Code:11008 ContextObject: ContextPath:zoneConfig.templateValues Text:'zoneConfig.templateValues' may not be edited. The value must match the currently stored value. Value:}]
```

I suspect this is due to `templateValues` not being encoded in the `zoneConfig` struct.

**Comment by Yannik** [comment]
`templateValues` looks like this:
```
{
	"templateValues": {
		"templateId": "xxx",
		"templateName": "yyyy",
		"templateReplacements": {
			"ipv4Replacement": "",
			"ipv6Replacement": "",
			"mailIpv4Replacement": "",
			"mailIpv6Replacement": ""
		},
		"tieToTemplate": true
	}
}
```

As we don't want to edit it using dnscontrol, I'd simply like to keep it as is, without having to define a whole templateValues struct. Is that possible @tlimoncelli ?

**Comment by tlimoncelli** [comment]
That might be a good place to use `json.RawMessage` or `interface{}`.  
https://noamt.medium.com/using-gos-json-rawmessage-a2371a1c11b7

**Comment by Yannik** [comment]
@tlimoncelli 

Thanks, that worked. PR: #2035
