### ISSUE TITLE
Should this example be updated or removed?

### ISSUE THREAD

**Issue by dkim1970** [StackExchange/dnscontrol#2032]
I was reading the docs and noticed that the [Add comments along complex SPF records
](https://docs.dnscontrol.org/getting-started/examples#add-comments-along-complex-spf-records) uses TXT but wouldn't the correct way be using the example from the SPF_BUILDER function [The DNSControl way](https://docs.dnscontrol.org/language-reference/record-modifiers/spf_builder#the-dnscontrol-way)

**Comment by tlimoncelli** [comment]
Good point!  That example was created before the SPF_BUILDER existed.
