### ISSUE TITLE
DOCS: Number characters per line

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#2033]
I was wondering; what is 'the policy' regarding characters per line? I see several forms used.

**Comment by tlimoncelli** [comment]
This project doesn't really have a policy other than "comply with the format that exists in the file".

I prefer to keep things less than 80 chars.  However some Markdown systems have bugs (usually with bullet lists) that appear if you don't include an entire paragraph on one line.  So, I've gotten in the (bad) habit of making bullet list items a single line.

**Comment by cafferata** [comment]
Thanks for your comment! I'm going to look further into the possibilities to guarantee this preference within Gitbook.

**Comment by j-f1** [comment]
Prettier (which is already used for the JS code) also supports Markdown, and has [an option](https://prettier.io/docs/en/options.html#prose-wrap) that lets you choose between automatically wrapping at 80 characters or forcing all paragraphs to a single line.

**Comment by cafferata** [comment]
Thanks for the suggestion, it's more that the interface from Gitbook generates exactly the reversed result, which is unwrapping the lines. As a result, preparatory work from the Gitbook interface is not (yet) possible.

**Comment by cafferata** [comment]
I jokingly played prettier with the idea that maybe it can fix the inconsistency without Gitbook. There are several diffs that I wonder if @tlimoncelli would like to pass them on to master.

```diff
-var REG_NONE = NewRegistrar('none');    // No registrar.
-var DNS_BIND = NewDnsProvider('bind');  // ISC BIND.
+var REG_NONE = NewRegistrar('none'); // No registrar.
+var DNS_BIND = NewDnsProvider('bind'); // ISC BIND.
```

```diff
 Providers in this category and their maintainers are:
 
-|Name|Maintainer|
-|---|---|
-|`AZURE_DNS`|@vatsalyagoel|
-|`BIND`|@tlimoncelli|
-|`GCLOUD`|@riyadhalnur|
-|`NAMEDOTCOM`|@tlimoncelli|
+| Name         | Maintainer    |
+| ------------ | ------------- |
+| `AZURE_DNS`  | @vatsalyagoel |
+| `BIND`       | @tlimoncelli  |
+| `GCLOUD`     | @riyadhalnur  |
+| `NAMEDOTCOM` | @tlimoncelli  |
```

```diff
-{% hint style="info" %}
-**NOTE**: The `--pretty` flag is optional.
-{% endhint %}
+{% hint style="info" %} **NOTE**: The `--pretty` flag is optional. {% endhint %}
```

```diff
 ---
 name: CNAME
 parameters:
-  - name
-  - target
-  - modifiers...
+    - name
+    - target
+    - modifiers...
 parameter_types:
-  name: string
-  target: string
-  "modifiers...": RecordModifier[]
+    name: string
+    target: string
+    'modifiers...': RecordModifier[]
 ---
```

I personally think that a too large change/diff with multiple risk invoices (parsing Gitbook, generation TypeScript declaration file, etc) does not offer any added value.

Would you like to check the outcome yourself? See my steps here.

```shell
npm install prettier
```

```shell
echo "/documentation/flattener/" > .prettierignore
echo "/node_modules/" >> .gitignore
```

```shell
echo "" >> .editorconfig
echo "[*.md]" >> .editorconfig
echo "indent_size = 2" >> .editorconfig
echo "indent_style = space" >> .editorconfig
echo "max_line_length = 80" >> .editorconfig
```

```shell
node_modules/.bin/prettier --prose-wrap=always --write documentation/**/*.md
```

```shell
git diff
```

**Comment by j-f1** [comment]
for 3 you could add blank lines if you don’t want it to collapse like that. 4 suggests to me that the indent options in the `.editorconfig` options aren’t being applied — I’ve worked on Prettier’s editorconfig support and I’m pretty sure it only looks at the global settings.

**Comment by cafferata** [comment]
I understand that a lot is possible, Also through the `prettierrc.json` configuration. For me it is more the question of whether @tlimoncelli  is open to a change like this.

**Comment by tlimoncelli** [comment]
It's not really a priority to me.

For text, I prefer to put a new line between each sentence or thought so that future diffs are small.  Formatters wreck that.  For code, I absolutely like strict formatting.

I'm also not in love with installing npm, or having to include it in the pipeline.

**Comment by tlimoncelli** [comment]
Closing this issue.  We can revisit this if the issue comes up again.
