### ISSUE TITLE
ConvertZone should be moved into a dedicated subcommand

### ISSUE THREAD

**Issue by captncraig** [StackExchange/dnscontrol#204]
Should probably be moved from cmd to commands.

And docs adjusted.

No rush, but it would be nice to have i the main binary.

**Comment by pierrehenrymuller** [comment]
Until convertzone is reintegrated into dnscontrol control, is it possible to put the compiled binary in the releases and in the docker image?

I can't compile it either like #258 and it's not present in the docker image, so I can't evaluate dnscontrol for zone management.

Thank you.

**Comment by pierrehenrymuller** [comment]
compilation is ok now

**Comment by signalwerk** [comment]
I also struggle to get convertzone to run. I would love to see it in de docker build

**Comment by tlimoncelli** [comment]
Did f1572c4b11690178c97a091a9b168feba0089d1c fix this?

**Comment by signalwerk** [comment]
@tlimoncelli for my case yes. ((it's my commit to the dockerfile))
