### ISSUE TITLE
creds.json cannot contain anything other than non-nested string values due to unmarshalling into map[string]string

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#2053]
Currently, `creds.json` is being unmarshalled into `map[string]string`. That means that configurations like this

```
{
  "hosting.de": {
    "TYPE": "HOSTINGDE",
    "authToken": "$DNSCONTROL_AUTH_TOKEN",
    "baseURL": "https://partner.http.net",
    "defaultContacts": [
      { "type": "owner", "name": "contact-id-123" },
      { "type": "admin", "name": "contact-id-123" },
      { "type": "zone", "name": "contact-id-456" },
      { "type": "tech", "name": "contact-id-578" }
    ]
  }
}
```

are not allowed. (Specifically, no nesting is allowed, no arrays are allowed, no types other than string are allowed)

To make this more flexible, one could pass the config as `json.RawMessage` to the provider initializers and let them unmarshal it however they like it.

(I'm surprised this isn't the case, as many providers internally have a struct that represents the `creds.json` values already!)

What do you think? @tlimoncelli

**Comment by tlimoncelli** [comment]
No and yes.

No:

If that kind of feature is needed for a provider, we can add it when the need arises. That way we're not bloating the code with future-proofing that is never needed, yet becomes a testing/maintenance burden.

`creds.json` should store only the secrets that you don't want in `dnsconfig.js`.  The file name is `creds.json`, not `creds_and_everything_else.json`.   So far no provider needs a complex struct to store authentication information. If one does appear, we'll deal with it then. (Even GCLOUD with its complex google auth stuff doesn't need a complex structure).

Yes:

I think what you're looking for is a way to store default contacts for a provider. That should go in the registrar's meta data.  See https://docs.dnscontrol.org/service-providers/providers/bind for how BIND can store default `NS` information for a provider.

**Comment by Yannik** [comment]
Thanks! I think the BIND example is the way to go here.
