### ISSUE TITLE
AutoDNSSEC - check that dns provider and registrar are the same

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#2056]
Enabling and disabling autodnssec only makes sense when domain&zone are at the same provider (see #2055), as there is currently no mechanism for transferring DS keys from the zone provider to the registrar provider. (That would be a nice feature though :-))

(Not sure how other providers handle this, since some of them apparantly are zone-only? do you need to import DS key to the domain manually with them?)

In any case I would like to implement a check whether the registrar is the same as the dns provider we are enabling autodnssec for. However, I do not see how I can access that information within the provider.
Do you have any suggestion how to do this? @tlimoncelli

**Comment by tlimoncelli** [comment]
I don't use DNSSEC, therefore all DNSSEC-related features are community supported.

If I understand the situation correctly (and I don't claim that is true) this is a kind of test that could be done in `pkg/normalize/validate.go`

**Comment by Yannik** [comment]
@tlimoncelli 

The problem here is that we cannot know which registrar is used for a domain within `GetDomainCorrections`.
Only the DomainConfig for the concrete domain is passed into  `GetDomainCorrections`.
We also have access to the relevant provider object, but that also doesn't know anything about the registrar.

As far as I can see, it is currently impossible to do this check. Or do you see any way?

**Comment by tlimoncelli** [comment]
Good point. One of the design decisions was that GetDomainCorrections would receive only the info it needs, not even back-pointers (so to speak) to the main configuration  The concern was we didn't want a provider to "walk up the tree" and corrupt other providers. 

I think there are two options.

1. Add it to normalize.ValidateAndNormalizeConfig(). That has a complete copy of models.DNSConfig.  Sadly I think this is called multiple times. (The entire normalize/validate phase is very old code and needs to be restructured some day. I didn't like my design when I first wrote it and now it has grown and grown.)
2. Add it to commands/previewPush.go:run().  That would put it at the start of preview/push.  My advice would be to put the functionality in a new pkg and just call it from run().

Tom

Tom

**Comment by Yannik** [comment]
That totally makes sense. I will look into it further based on your suggestions.

**Comment by tlimoncelli** [comment]
@Yannik Can this be closed?

**Comment by Yannik** [comment]
@tlimoncelli 

Yep.
