### ISSUE TITLE
namedotcom: Domain Not Dns Ready

### ISSUE THREAD

**Issue by captncraig** [StackExchange/dnscontrol#206]
Name.com has an interesting quirk. If the domain is not currently using name.com nameservers, we are unable to manage it.

The dnscontrol process flow:

1. Get nameserver list from all dns providers.
2. Get/Apply corrections for all dns providers.
3. Submit final Nameserver list to the registrar.

We chose this ordering because it feels safer to set up a dns provider **before** you start sending traffic to it via the registrar.

In my situation, step 2 is failing with: `Error getting corrections: Parameter Value Error - Domain Not Dns Ready`

My only workaround now, is really hacky, and involves either manually adding name.com nameservers on thh website, or copying the entire provider config and filtering with `-providers` flag. Neither of those are optimal. 

My goal is to be able to switch from another provider in an emergency situation with no additional steps.

I have a few possible workarounds we could implement:

1. Ask name.com to allow managing and editing dns records regardless of current nameserver status. Maybe @pmoroney can put in a good word?
2. Catch the error and print a warning. Something like `Name.com not initialized. No corrections to run. Please run dnscontrol again after registrar updates`. You then have to run dnscontrol twice to get changes in, and it will be in a half-initialized state (likely with a default parking page) between the two runs.
3. Implicitly set nameservers to name.com when we detect this situation. This kinda breaks the preview/push paradigm, and we decided generally against this (created a dedicated create-domains command).

I don't really love 2 or 3 since they involve some window of inconsistency. But I don't have a lot of other ideas.

**Comment by captncraig** [comment]
I realized how to fix this on the train tomorrow. Its not quite analogous to other things we use the `create-domains` command for, but it is closer than anything else. 

I'll catch the error and print a message that says essentially "run dnscontrol create-domains to 'unstuck' yourself, then run dnscontrol push". 

Then implement create-domains for name.com to just register the nameservers to point to itself. There will be a window of inconsistency, but such is life unless name.com allows shadow domain management.

**Comment by tlimoncelli** [comment]
Sounds like a nice, simple, way to do it!

**Comment by pmoroney** [comment]
Sorry I had missed this thread. We were having a discussion about this today in fact. On our web interface we allow customers to create and modify DNS records even if they do not use our nameservers, but we display a warning. We will modify the API to allow DNS records to be created even if our nameservers are not in use. I will let you know when that is completed.

**Comment by captncraig** [comment]
Awesome @pmoroney! That's really good news. Any idea how long that will take to implement? I'll probably hold off making any changes on our end to work around it then.

**Comment by pmoroney** [comment]
I should have that working today or tomorrow.

**Comment by pmoroney** [comment]
That change is live. Let me know if you see any issues.

**Comment by captncraig** [comment]
Works wonderfully! Thanks @pmoroney!

**Comment by tlimoncelli** [comment]
Awesome!   I've been wanting this for a long, long time!  Our internal playbook is full of details about how to work around this issue... I'm happy to be able to delete all that now :)

Thanks!
