### ISSUE TITLE
How to parse DNS record

### ISSUE THREAD

**Issue by riku22** [StackExchange/dnscontrol#2065]
Hello.

I am currently looking into creating a new DNS provider.
However I have a problem, so let me ask you a question.

The contents of the record of the data obtained from the API are as follows.
This is an example of an MX record, but CAA records and other records have a similar format.

`10 mail.example.com.`

Maybe this is the same format as BIND, but I don't know how to parse this content and change it to `models.RecordConfig` or vice versa to generate the above string from `models.RecordConfig`.
I may be thinking of something wrong.
Any advice would be appreciated.

Sincerely yours.

**Comment by tlimoncelli** [comment]
Hello!

Glad to hear you're working on a new provider. I'd be glad to assist in any way possible.

If the data looks like BIND format, consider using rc.PopulateFromString().  It handles most cases.  The cases it doesn't work, simply handle those separately.  Look at nativeToRecords() in providers/gandiv5/convert.go for a good example of how it is used.

Tom

**Comment by riku22** [comment]
Hi.

Thank you for your advice.

Maybe `rc.PopulateFromString` will do the trick.

By the way, is it easier to write a new provider using `diff2`?
I'm a bit confused as to whether `diff` or `diff2` is easier to write, as I've barely touched Go code before.

Sincerely yours.

**Comment by tlimoncelli** [comment]
Excellent questions!

Yes, I would start with diff2.  Don't worry about diff... we hope it will go away in the next few months.

diff2 is easier. Much easier.  It was a design goal of diff2 to be easier to use by doing all the housekeeping for the provider.  If you select the correct diff2.By*() function, all the work is done for you and you just have to turn the list of changes into a list of corrections (you'll see what that means when you look at the code).

These providers have some of the cleanest diff2 implementations.  Copy their style:

providers/gandiv5/gandi_v5Provider.go 
providers/cloudflare/cloudflareProvider.go
providers/ns1/ns1Provider.go

Tom

**Comment by riku22** [comment]
Hi.

Thank you.

I think it's mostly done.
I'll do some more testing, such as integration testing, and then create a pull request.

Sincerely yours.
