### ISSUE TITLE
hosting_de create domain failure

### ISSUE THREAD

**Issue by tmkis2** [StackExchange/dnscontrol#2079]
Creating a new domain fails with:

`WARNING: Error creating domain: error creating zone: [{Code:12001 ContextObject: ContextPath:records[0].content Text:Domain name 'ns1.hosting.de.' is invalid Value:ns1.hosting.de.} {Code:12001 ContextObject: ContextPath:records[1].content Text:Domain name 'ns2.hosting.de.' is invalid Value:ns2.hosting.de.} {Code:12001 ContextObject: ContextPath:records[2].content Text:Domain name 'ns3.hosting.de.' is invalid Value:ns3.hosting.de.}]`

from dnsconfig.js:

```
D('xxxxxxx.de', REG_HOSTINGDE, DnsProvider(DNS_HOSTINGDE),
        AUTODNSSEC_ON,
        DefaultTTL(3600),
        A('@', admin14),
        A('*', admin14),
        mail_settings
);

```

**Comment by tlimoncelli** [comment]
CC @juliusrickert (maintainer of the hosting_de provider)

**Comment by Yannik** [comment]
@tmkis2 I'm not 100% sure what you are doing here: Creating a new domain, or a new zone?

**Comment by Yannik** [comment]
@tmkis2 Please check if this was fixed with #2297

**Comment by tmkis2** [comment]
No it still throws same error on me with latest release of dnscontrol

**Comment by Yannik** [comment]
@tmkis2 Do you have nameservers specified in your config or are you using the default ones provided by the dnscontrol hosting.de provider?

**Comment by tmkis2** [comment]
the default ones from hosting.de - no nameservers specified

**Comment by tmkis2** [comment]
You're absolutely right @Yannik - my fault. Just updated to v4.1.0 and now he created the zone and registered the domain but ended with:

```
SUCCESS!
ERROR
Error getting corrections (hosting.de): error getting nameservers: error getting domain config: could not get domain config: xxxxx-xxxxx.de
Done. 1 corrections.
completed with errors
```

**Comment by tmkis2** [comment]
Ah he created the zone correctly but NOT the domain

**Comment by Yannik** [comment]
@tmkis2 Yes, that's right. I don't think dnscontrol has support for domain creation right now. 

cc @tlimoncelli

**Comment by tlimoncelli** [comment]
Correct.  dnscontrol doesn't register new domains.  Some providers will populate the provider's zone.

**Comment by Yannik** [comment]
@tmkis2 @tlimoncelli Since the issue with creating zones has been resolved, I'd like to suggest closing this issue.

**Comment by tmkis2** [comment]
Yes. Thank you @Yannik and @tlimoncelli
