### ISSUE TITLE
BUGFIX: dnscontrol complains that the zones for IDNA domains do not exist

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#2096]
Hi,

I'm currently experiencing an issue with the handling of idna domain names: dnscontrol complains that the zones for these domains do not exist, even though they do.

The output looks like this:
```
WARNING: DEBUG: zones: [xn--berall-ist-8db.de]
WARNING: DEBUG: Name: überall-ist.de
WARNING: Zone 'überall-ist.de' does not exist in the 'hosting.de' profile and will be added automatically.
```

So, apparantly, the zones list contains the names as ACE-string, while the zone name is in idna format. When the zone name is configured in ACE format, there is no problem - but that is non really human-readable, especially if you have multiple similar domains.

Is this expected behaviour?

**Comment by Yannik** [comment]
I think the question here is whether interfaces like `ListZones` and `GetDomainCorrections` should expect/provide input/ouput as ACE or IDNA. Currently, this is not specified and can be implemented differently by each provider.

**Comment by tlimoncelli** [comment]
My recommendation is the code should convert IDNA to ACE before sending it to the API.   I say this because I assume that all APIs handle punycode, but some break when they see Unicode.

**Comment by tlimoncelli** [comment]
I've opened https://github.com/StackExchange/dnscontrol/issues/2097 to document the issue.  However to be honest, someone that isn't monolingual like myself should probably work on this.

Tom

**Comment by Yannik** [comment]
> My recommendation is the code should convert IDNA to ACE before sending it to the API. I say this because I assume that all APIs handle punycode, but some break when they see Unicode.

What do you man exactly by "sending it to the api"? 

Can you described what you mean in terms of the output and input of the ListZones and GetDomainCorrections Interfaces?

**Comment by tlimoncelli** [comment]
Oops!  Sorry for being unclear.

I mean... it sounds like the API wants the domain to be sent as punycode.

**Comment by Yannik** [comment]
@tlimoncelli 
When you say punycode (https://en.m.wikipedia.org/wiki/Punycode), you probably mean idna, right? 


> Oops! Sorry for being unclear.
> 
> I mean... it sounds like the API wants the domain to be sent as punycode.

No, not really. The problem in my OP is not about the hosting.de api input, but rather about the output: The hosting.de API lists zones using the idna format. 

Regarding the bigger question on how to handle this in dnscontrol, I still don't know what your position is on how this should be fixed :) Should the interfaces expect idna or unicode as input and provide idna or unicode as output?

**Comment by louis-lau** [comment]
Using cloudflare, I can't use either notation :(

```
******************** Domain: ͻ.ws
WARNING: Zone 'ͻ.ws' does not exist in the 'cloudflare' profile and will be added automatically.
WARNING: No nameservers declared; skipping registrar. Add {no_ns:'true'} to force.
```

```
******************** Domain: xn--2va.ws
WARNING: Zone 'xn--2va.ws' does not exist in the 'cloudflare' profile and will be added automatically.
WARNING: No nameservers declared; skipping registrar. Add {no_ns:'true'} to force.
```

I can pass ͻ.ws just fine to get-zones, xn--2va.ws does not work for get-zones.

**Comment by louis-lau** [comment]
Sure! I put it as a reply here because it seemed related. I'll open a new issue.
