### ISSUE TITLE
RecordConfig.SubDomain target is absent from go docs

### ISSUE THREAD

**Issue by systemcrash** [StackExchange/dnscontrol#2106]
https://github.com/StackExchange/dnscontrol/blob/2586e2b611c0054abbc25c15fe64a25d0ee7b51f/models/record.go#L91

Should it have ` `` `?

See
https://pkg.go.dev/github.com/StackExchange/dnscontrol/v3@v3.27.1/models#RecordConfig.SubDomain

**Comment by tlimoncelli** [comment]
I'm not sure what the question is.

Are you suggesting that `.target` needs `json:"target"` ?  It isn't exported, therefore the json module can't access it. That's why the Marshal code is so complex.

**Comment by systemcrash** [comment]
target does not appear in the compiled go docs. should it?

**Comment by tlimoncelli** [comment]
No, pkg.go.dev doesn't show un-exported fields.
