### ISSUE TITLE
Add tags to Docker image for releases

### ISSUE THREAD

**Issue by bfirsh** [StackExchange/dnscontrol#212]
It'd be nice to be able to do `docker run stackexchange/dnscontrol:0.1.5` to pin to a version. Docker Hub lets you automatically build tags from Git tags.

**Comment by captncraig** [comment]
Great idea. I set it up in docker hub like so:
![image](https://user-images.githubusercontent.com/192540/30915457-e5dc6af0-a364-11e7-913e-f5bc8715342b.png)

It seems to work. I added a `0.2.1` tag, and it looks like it built. 

I don't really want to go overboard and add too many combinations. I do like that the `go` image has useful variants like `1`, `1.8`, `1.8.1` and the options on each of those, but I don't think we want to go there.

We will try to tag a version anytime major features are added or change, and hopefully make a release in github as well.

**Comment by bfirsh** [comment]
Perfect thanks! 🎉
