### ISSUE TITLE
digitalocean provider struggling with TXT records

### ISSUE THREAD

**Issue by willpower232** [StackExchange/dnscontrol#2125]
as of the latest version v3.27.1, it seems the digitalocean provider is struggling to understand the current value of TXT records, creating output along the lines of

```
******************** Domain: example.com
1 correction
#1: ± MODIFY TXT example.com: ( ttl=3600) -> ("v=spf1 include:spf.whatever.com ~all" ttl=3600), DO ID: 123456789
```

note the space between `(` and `ttl` on the left hand side.

I also note the mention of `Use the more concise pattern of diff.NewCompat() (CSCGLOBAL, DIGITALOCEAN, NAMEDOTCOM)` in that releases notes.

The provider seems capable of pushing the changes it believes are required however a subsequent `preview` call suggests the change is still pending.

Other types of record seem unaffected from my limited sample size.

I have confirmed this isn't a problem for 3.27.0 but let me know if I can provide any more details.

**Comment by tlimoncelli** [comment]
Does this fix it?  https://github.com/StackExchange/dnscontrol/pull/2126

**Comment by willpower232** [comment]
it sure does! and it also corrected a couple which the previous version added extra quotes to somehow 😎

**Comment by tlimoncelli** [comment]
Oops!  Sadly that broke something else.  D'oh!

Try again.

**Comment by tlimoncelli** [comment]
Ok, now that I've gotten some sleep, I merged the ideas behind both of those.  Please test this one: https://github.com/StackExchange/dnscontrol/pull/2128

**Comment by willpower232** [comment]
I can confirm that this also works 🙏

**Comment by tlimoncelli** [comment]
yay!
