### ISSUE TITLE
Make IR tests for site-specific company policies super easy

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#215]
It would be a lot easier to do tests against the IR if they could be written as (an sql query, the expected output).  We could import the IR into sqllite and provide an interface similar to pkg/js/parse_tests

**Comment by tlimoncelli** [comment]
The “select” part of this might help:  
https://selecttransform.github.io/site/

**Comment by captncraig** [comment]
I guess my question is still, "what is the use case?"

Are we talking about:

1. Internal company dns policy validation
2. General rules for everything
3. Testing the dnscontrol code base

If this is about number 1, maybe an additional javascript file that gets run after post-processing, and can inspect the results in actual code? Perhaps the main script could even register a callback or something so it is all in one file:

```
D(...)
D(...)

AddDomainValidator(function(domain){
    for (var i = 0; i< domain.Records.length; i++){
       if (domain.Records[i].Type == "MX"){
          return
       }
    }
    throw("domain " + domain.Name + " has no MX records");
})
```

**Comment by tlimoncelli** [comment]
It is definitely "1. Internal company dns policy validation"

Here are some realistic but site-specific policies we would implement:

* All domains must have an SPF record.
* MX records must point to google.com or (list of domains)
* MX records must have TTLs that are at least n days.
* Never delete the TXT record at "foo.example.tld" (for example, we monitor the DNS servers by querying that record and don't want someone to "clean up" and delete it.)
* IP addresses in 10.0.0.0/8 should not appear in any domain except example.tld
* A-records in sub-domain test.example.tld should never point to the production IP cidr block 1.2.3.0/24.
* CNAME-records in sub-domain test.example.tld must always point to hostnames with "test" in their name (or must not point to hosts with "prod" in their name).

**Comment by tlimoncelli** [comment]
After all this time there's been no demand for this. Closing.  Can re-open if we need this in the future.
