### ISSUE TITLE
Unstable SRV records on Dnsimple

### ISSUE THREAD

**Issue by andrewbaxter** [StackExchange/dnscontrol#2157]
I have this (exported from Gandi):
```
    SRV("_imaps._tcp", 0, 1, 993, "mail.messagingengine.com."),
```

Every time I run dnscontrol it reports this modification:
```
#1: ± MODIFY SRV _imaps._tcp.mydomain: (0 1 993 mail.messagingengine.com.. ttl=10800) -> (0 1 993 mail.messagingengine.com. ttl=10800)
```
(removing duplicate final `.`)

On dnsimple's web ui it shows
```
SRV | _imaps._tcp.zarbosoft.com | 1 993 mail.messagingengine.com.
-- | -- | --
```
This is the only record listed there with a final `.` (i.e. there's no duplicate ., and the modifications are doing nothing).

**Comment by tlimoncelli** [comment]
CC @onlyhavecans (maintainer of the DNSimple provider)
