### ISSUE TITLE
Vultr support

### ISSUE THREAD

**Issue by geek1011** [StackExchange/dnscontrol#217]
Vultr DNS support would be nice to have. See https://www.vultr.com/api/#dns

**Comment by captncraig** [comment]
Sure would be. Looks like their API is pretty simple, if a bit under-documented. Should be fairly straightforward to implement. Are you planning to work on it?

**Comment by geek1011** [comment]
@captncraig yes, sometime this week most likely.

**Comment by geek1011** [comment]
@captncraig Finished. See #219.
