### ISSUE TITLE
Single file per domain

### ISSUE THREAD

**Issue by timhughes** [StackExchange/dnscontrol#218]
I cannot find anything in the docs on this.

I have approximatly 600 domains I need to manage. Having them all in a single file is over 20000 lines. 

Is there any directive to inport all these files so that I can manage each domain in a separate file?

At the moment I am catting them all together.

```
cat dnsconfig.js domains/* > final.js
dnscontrol -js final.js push
```

It seems like there should be a more elegant way.

**Comment by pmoroney** [comment]
There seems to be a require directive. It looks like it just pulls in and parses the other file.
```
require("pkg/js/parse_tests/import.js")
```
Although this will require you to have a js file that lists all the others as it doesn't look like it handles wildcards.

Maybe it can be modified or a new directive created to allow wildcards...

**Comment by tlimoncelli** [comment]
I was going to recommend using "require" too.   That's the supported method.

**Comment by captncraig** [comment]
I might be convinced that a `require("domains/*.js")` would be a useful addition, assuming there was a well-established go lib available for that kind of glob loading (I'm not sure what the state of the art is there).

The cat solution actually sounds like it may work as well as anything though.

**Comment by geek1011** [comment]
@captncraig For globbing, I usually use https://godoc.org/github.com/mattn/go-zglob

**Comment by timhughes** [comment]
Thanks all. This issue is complete as far as I am concerned so feel free to close. Although changing it to a feature request for require with globbing might be an idea.

**Comment by tlimoncelli** [comment]
I think globbing is too risky.  If a spurious file gets in that directory (a backup file, a temp file, etc.) everything goes bad.   I'd rather see people create their dnsconfig.js file with something like:

    cat header >dnsconfig.js
    ls -d domain/*.js | awk '{ print "require(\"" $1 "\")" }' >>dnsconfig.js
    cat tailer >>dnsconfig.js
    git diff dnsconfig.js

(You can do that in fewer lines, but I did it that way for readability)

If you put that in a "makefile" (and check dnsconfig.js into Git), you get a system that is more deterministic and easier to audit.

Tom
