### ISSUE TITLE
Bug: registrar and dns providers don't need to match if autodnssec is enabled

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#2189]
CC @Yannik @philpennock 

We need to re-think https://github.com/StackExchange/dnscontrol/pull/2090

People are pointing out that if their registrar is "none" they're blocked.  See https://matrix.to/#/!RtyMrVaRUUpzNdyTFQ:gitter.im/$MVQzpHDUh11jZNZsbh5RRl2-nQCT0ZRgXhq40hi4mgU?via=gitter.im&via=matrix.org

**Comment by Yannik** [comment]
How exactly would enabling DNSSEC work without access to the registrar? The DS keys need to be configured with the registrar.

**Comment by tlimoncelli** [comment]
> How exactly would enabling DNSSEC work without access to the registrar? The DS keys need to be configured with the registrar.

I presume that it can be configured manually.  @philpennock ?

How's this for a solution: https://github.com/StackExchange/dnscontrol/pull/2196

* Change the severity from error to warning, so it doesn't block any users
* Disable the check if the registrar is NONE

**Comment by tlimoncelli** [comment]
This broke existing configurations. That's bad.

DNScontrol configures DNS and prevents obvious mistakes like "trailing dot" typos. It can't and shouldn't deeply validate people's configurations or second-guess what they want to do.

**Comment by Yannik** [comment]
> This broke existing configurations. That's bad.

If I understand this correctly, it broke an existing configuration that could very well be viewed as broken. (Specifically, a configuration which lacks correct publishing of DS keys)

> DNScontrol configures DNS and prevents obvious mistakes like "trailing dot" typos. It can't and shouldn't deeply validate people's configurations or second-guess what they want to do.

There is not really any guesswork at play here. Publishing the DS record with the registrar is simply a prerequisite for automatic dnssec to work.

I guess it comes down to what you really expect the AutoDNSSEC functionality to do. I personally would expect it to do the things required for dnssec to *just work*. And that requires having the registrar configured so that the DS records can be published.

Currently, dnscontrol does not have any features to pass DS records between providers and registrars, nor does it have functionality to check DS records and return them to the user if they are not properly configured. While these things would be nice, they would require quite significant changes to dnscontrol.

**Comment by tlimoncelli** [comment]
>  I personally would expect it to do the things required for dnssec to just work.

Ah, I see!  We have a communication disconnect here.   DNSControl doesn't fully support AutoDNSSEC or DNSSEC.  It simply can tell a provider "turn it on or off".  I didn't even want that feature but people convinced me to accept the PR.  Now I'm left supporting something that I don't use and don't even really care about.

This is a tiny, community-driven, project that I do for fun in my spare time.  Don't confuse it with anything bigger.

Tom

**Comment by Yannik** [comment]
Hi Tom,

wow, really?! Then I certainly had a wrong impression - I always thought your work on dnscontrol was funded by stackexchange inc. (as the project is under their github namespace).

Yannik

**Comment by tlimoncelli** [comment]
It started at Stack and they still host the project and use the software.  I don't have any 9-5 time allocated to the project.

**Comment by tlimoncelli** [comment]
If someone would pay me to work on dnscontrol full time... that would be a dream job!

**Comment by philpennock** [comment]
The premise that parent glue updates can't happen if dnscontrol can't talk to the registrar is wrong.  In the case of the providers for which this feature was written, the DNS hoster will, if it is the registrar, update DS in the parent via registry updates, and supports CDS/CDNSKEY publication to allow for automatic updates, for all other cases.  _And_ if they can't see that, then they send an email warning every 3 months when they rotate keys, providing the new DS records to update.

Given CDS/CDNSKEY, it's wrong to assert that the parent can't be told about changes.  It can.  Modern standards allow this all to be automatic.

The AUTODNSSEC stuff just says "take care of it, as best you can".  It's also _harmless_ to enable DNSSEC inside the zone before configuring DS in the parent, as this is how initial setup is done.  So, the prior behavior of DNSControl was absolutely correct, and refusing to enable AUTODNSSEC unless we can also talk to the registrar is "probably wrong", but with some DNS providers it might, for that provider, be necessary.

**Comment by Yannik** [comment]
@philpennock 

TIL about CDS/CDNSKEY!

I had a hard time figuring out whether this is actually supported by major registries like verisign (.com / .net)?
