### ISSUE TITLE
NameSilo Support

### ISSUE THREAD

**Issue by geek1011** [StackExchange/dnscontrol#220]
Many of my domains are registered with NameSilo.

https://www.namesilo.com/api_reference.php

I probably will not work on this anytime soon, as the API is quite a bit more complex, and it will take quite a bit of trial and error to figure out some underdocumented parameters. Also, the only thing I would be using this for is automatically changing nameservers, which I currently use my own separate script for, therefore making this less of a priority for me to implement.

**Comment by tlimoncelli** [comment]
Sounds good. We look forward to the PR when you have the time.

P.S.  If you implement the providers.Registrar interface, dnscontrol will change nameservers for you.

**Comment by geek1011** [comment]
@tlimoncelli Thanks. It's not so much that I do not have time, it's that the time savings (~5 min) are not worth the time to add this registrar/DNS provider (~7 hours, mainly because the API isn't well documented).

For now, I am working on Vultr support, and some documentation/site improvements.

**Comment by tlimoncelli** [comment]
I've noted this  in https://stackexchange.github.io/dnscontrol/provider-list (46dca95d09bf2fb0807085796e5b7000a3654423)

If someone starts working on this, please re-open this issue.

**Comment by Southclaws** [comment]
NameSilo is the one registrar that I use that's not available in dnscontrol! I found this library which looks like most of the boilerplate request/response work is done: https://github.com/kf6nux/namesilo it would just be a case of gluing it into dnscontrol.

I will look into it and *may* take a stab at this time-permitting in future, if I do then I'll update here and you can re-open the issue 👍
