### ISSUE TITLE
CHORE: Upgrade to latest hexonet sdk

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#2223]
Hello [PapaKai](https://github.com/papakai)!

I was upgrading dependencies and I saw this error:

```
$ go get github.com/hexonet/go-sdk/v3@latest
go: github.com/hexonet/go-sdk/v3@v3.5.5: parsing go.mod:
	module declares its path as: github.com/centralnicgroup-opensource/rtldev-middleware-go-sdk/v3
	        but was required as: github.com/hexonet/go-sdk/v3
```

Sounds like there's some bigger changes going on.  

Could you upgrade to the newest SDK when you have some time?

No rush. The current code seems to be working fine.

**Comment by tlimoncelli** [comment]
CC @KaiSchwarz-cnic

**Comment by KaiSchwarz-cnic** [comment]
@tlimoncelli thanks for the friendly ping via CC, PapaKai is no longer in the house ;-)
I added this review to our backlog.

**Comment by AsifNawaz-cnic** [comment]
Hi @tlimoncelli,

We have upgraded the dependencies, please review the pull request.

Thanks
