### ISSUE TITLE
TRANSIP: Missing diff2

### ISSUE THREAD

**Issue by blackshadev** [StackExchange/dnscontrol#2227]
@tlimoncelli it seems my TransIP diff2 implementation is lost somehow. I provided you with the changes in [this MR](https://github.com/StackExchange/dnscontrol/pull/1860/files) . on [this issue](https://github.com/StackExchange/dnscontrol/issues/1854) it is marked as resolved. But it seems like it never hit master. Could you help out with this one?

**Comment by tlimoncelli** [comment]
Weird that it shows as merged but it isn't merged.  My apologies... I probably messed up my git commands.

**Comment by blackshadev** [comment]
Closed because of  #2228
