### ISSUE TITLE
request: rename all providers to match real world

### ISSUE THREAD

**Issue by systemcrash** [StackExchange/dnscontrol#2233]
Working on PR #2197 raised the question. 

I prefer snake_case for the naming.

**Comment by tlimoncelli** [comment]
rename them where?  Rename the identifier ("GCLOUD", "ROUTE53"), the directory (providers/gcloud), or the documentation TOC entries?

**Comment by systemcrash** [comment]
All of the above. At least so everything is synchronized.


I'd considered putting each provider markdown in the provider folder so
there's only 1 source tree for adding a provider, but perhaps this creates
problems when building/copying the docs and new record types would probably
seem like a weird exception if it wasn't handled similarly.

**Comment by tlimoncelli** [comment]
Rejected.

This would break all existing configurations for no other reason than "I prefer snake_case for the naming".

Please use the issues feature to file bugs and feature requests. This is neither.

**Comment by systemcrash** [comment]
Actually, as expressed in the auto TOC PR, the hope was to have all providers in snake_case so that TOC name printing would be reasonably predictable and elegant.

**Comment by tlimoncelli** [comment]
I apologize for the abrupt issue closure.  That was rude of me.
