### ISSUE TITLE
An additional step to enable TypeScript type-checking in VSCode

### ISSUE THREAD

**Issue by BirkhoffLee** [StackExchange/dnscontrol#2263]
Hello! Today I stumbled upon DNSControl. I read about the TypeScript integration and tried to have it enabled in VSCode. However it seemed that VSCode was not recognising the `.d.ts` file automatically -- I had to add this line to the top of the file to have it working properly. Thought this would be helpful to have in the documentations!

```
/// <reference path="types-dnscontrol.d.ts" />
```

**Comment by j-f1** [comment]
Yep, I must have missed that I added that. Would you be willing to submit a PR to the docs to add an instruction about that? (If not, I’d be happy to)

**Comment by BirkhoffLee** [comment]
I'll do that!

**Comment by tlimoncelli** [comment]
Thanks! Looks good!
