### ISSUE TITLE
Cloudflare create dns records support

### ISSUE THREAD

**Issue by GurdipS5** [StackExchange/dnscontrol#2290]
Hi,
Is it possible for support to create records in cloudflare? dnscontrol complains of lack of zone create permissions, but I have given zone edit.

**Comment by GurdipS5** [comment]
I'm just about to pop out but sure, I get the error:
Error creating domain: Requires permission "com.cloudflare.api.account.zone.create" to create zones for the selected account

**Comment by tlimoncelli** [comment]
I'm going to guess that is required to create (populate) a zone in your Cloudflare account.  The docs recommend `Add: Read zones (Zone → Zone → Read)` but that may not be sufficient any more.

Please let me know if additional permissions are required. I'd be glad to update the docs.

**Comment by GurdipS5** [comment]
But issue is the permissions it asks for don't exist? And it doesn't honour
the zone edit permissions

**Comment by tlimoncelli** [comment]
Hi there!

Contact Cloudflare customer support.  They should be able to tell you what permissions on the web portal are required.

You might also try adding the domain to your account using the web portal.  The "add a site" button.

**Comment by GurdipS5** [comment]
Surely cloudflare will pass it back to you guys? Adding it manually won't be an option as I am looking to automate. I will log a call with them still.

**Comment by GurdipS5** [comment]
Also, this was answered here:- https://community.cloudflare.com/t/api-token-for-com-cloudflare-api-account-zone-create/392489

I've given the token these permissions.

**Comment by GurdipS5** [comment]
Ok I have fixed this! My bad, each block beginning with d is a zone! Hnece the error. So my records go in the zone (duh, I am creating a subdomain!).

Two unrelated questions I have;
- Is this tested with Windows DNS for Server 2022?
- Can I have seperate dnsconfig.js files? Eg one provided in one, another in the other, etc.

**Comment by tlimoncelli** [comment]
> Ok I have fixed this! My bad, each block beginning with d is a zone! Hnece the error. So my records go in the zone (duh, I am creating a subdomain!).

Glad you got that working!

> Two unrelated questions I have;
> 
> * Is this tested with Windows DNS for Server 2022?

That that I know of.  In all transparency, testing of the MSDNS provider isn't great.

Please remember that DNSControl is a community-driven open source package.  It has no official support.  StackOverflow (my employer) sponsors the project but doesn't allocate much time for me to work on it.  Their support is mostly paying for Github and the CI/CD pipeline.  Most of my time on DNSControl is nights and weekends.

> * Can I have separate dnsconfig.js files? Eg one provided in one, another in the other, etc.

Yes.  The preview/push command accept a `--config filename` flag that lets you specify the name of the dnsconfig.js file.  See "dnscontrol preview -h" for all the options.

**Comment by tlimoncelli** [comment]
Hi @GurdipS5!   If you've had this problem then other people will have this problem. Can you recommend documentation changes that would help people in the future?
