### ISSUE TITLE
TTL(30) not available for Cloudflare enterprise domains

### ISSUE THREAD

**Issue by fabriziosalmi** [StackExchange/dnscontrol#2299]
Helo amazing wizards!!

I already read the doc regarding this behaviour but I cannot understand the 2-60s statement here: https://docs.dnscontrol.org/service-providers/providers/cloudflareapi

I'm trying to update a zone into Cloudflare via dnscontrol but I got this kind of "issue":

- `dnsconfig.js`: i have some records with `TTL(30)` defined;
- Cloudflare: same records are `TTL 1 min` on Cloudflare;
- if I run `dnscontrol preview` it does suggest 30 to 60s modification;;
- zone is Enterprise on Cloudflare;

Maybe it's related to the available TTL values which is different between Enterprise zones (30s is an option) and free ones (not an option), from Cloudflare docs:

> Unproxied records
For DNS only records, you can choose a TTL between 30 seconds (Enterprise) or 60 seconds (non-Enterprise) and 1 day.

Proposed solution: 
a variable to set enterprise zones for Cloudflare enterprise domains (something like `CF_ENTERPRISE_ZONE `with default value set to `off`) which accept 30s as TTL value.

Possible workarounds:
Can I ignore/comment affected 30s records to have a proper preview/push output in some way or there are others methods out there?

Thank you for your awesome tool, it's a good friend for any DNS administrator 🥇

**Comment by tlimoncelli** [comment]
Cloudflare plays with TTLs.  See the bottom of https://docs.dnscontrol.org/service-providers/providers/cloudflareapi as that might explain what's going on.

**Comment by cafferata** [comment]
FYI @tlimoncelli, you can also link to page sections. In this example '[Cloudflare special TTLs](https://docs.dnscontrol.org/service-providers/providers/cloudflareapi#cloudflare-special-ttls)'. The anchor will be showed by clicking on the page section title. 👍

**Comment by tlimoncelli** [comment]
@cafferata 

> FYI @tlimoncelli, you can also link to page sections. In this example '[Cloudflare special TTLs](https://docs.dnscontrol.org/service-providers/providers/cloudflareapi#cloudflare-special-ttls)'. The anchor will be showed by clicking on the page section title. 👍

Thanks for the tip!

**Comment by tlimoncelli** [comment]
[fabriziosalmi](https://github.com/fabriziosalmi) Does setting the TTL to 301 or higher work?

**Comment by tlimoncelli** [comment]
I'm closing this issue.  Please re-open it if you feel it is incomplete.
