### ISSUE TITLE
Don't count diff2.REPORT as a "correction"

### ISSUE THREAD

**Issue by fritterhoff** [StackExchange/dnscontrol#2300]
Hi,

I just stumbled over a litte "bug". In detail it is more or less a visual issue from my point of view but maybe it can be fixed sometime.

At the moment some DNSSEC records get injected by other scripts and tools into our zone files. These get ignored by us using the IGNORE statement. This causes the detection of corrections that get ignored afterwards. It would be great, if it would state "0 corrections" 😉 

```
******************** Domain: hm.edu
1 correction (axfrddns)
#1: DDNS UPDATES to 'hm.edu' (primary master: '**********'). Changes:
INFO: 44 records not being deleted because of IGNORE*():
    ad.hm.edu. DS 21836 8 2 1A353E1FA5A11D3842EF389ED31F1E3EFB29BFCE2B73A055E65BFB5C017BE94A
    admin.hm.edu. DS 9964 8 2 69203290C9FE2BAD3D2C86B951BC850596C0DCF654B2D89C1CD1DE42E119B38C
    al.hm.edu. DS 45175 8 2 9141B4F5803E042AA471A648EECA5C7D76886CE7B4E200645EA2042D79A21429
    ar.hm.edu. DS 39979 8 2 16748F73B63696AC74109634DAA58A62FB6B3DDB2B9C25641D4D61AD6256E735
    ba.hm.edu. DS 58907 8 2 6356C2EB62AE85F7D581230702B360189F594ECF3298883B56F5B099EBAF2480
    ...and 39 more... (use --full to show all)
```

**Comment by tlimoncelli** [comment]
Good point. This is confusing.  The informational messages shouldn't be counted as "corrections".

**Comment by tlimoncelli** [comment]
I reworked the output (See https://github.com/StackExchange/dnscontrol/pull/2361).  Please take a look.

I don't think it is perfect, but its the best I could figure out without breaking the providers that depend on diff2's backwards compatibility mode.  Once diff1 is eliminated, there are improvements I can make.

You can test https://github.com/StackExchange/dnscontrol/pull/2361 by doing:

```
git clone https://github.com/StackExchange/dnscontrol
cd dnscontrol
git checkout tlim_b2300_info
go install
(this will install dnscontrol in your ~/bin direcetory)
```

**Comment by fritterhoff** [comment]
Sorry... Had no time to check it. Looks fine for me.

**Comment by tlimoncelli** [comment]
Thanks!

**Comment by fritterhoff** [comment]
Sorry I have to reopen this issue. At least in case of AXFR it does not work as expected... I'm not sure why I did not get some corrections yesterday :(

**Comment by tlimoncelli** [comment]
[fritterhoff](https://github.com/fritterhoff) Can you paste a (redacted) example?

**Comment by fritterhoff** [comment]
Do you need the config or the output?

**Comment by tlimoncelli** [comment]
Ah!  That's interesting!  This is specific to how the AXFRDDNS provider was written.  My oversight!

The problem is that the provider collects all changes and puts them in a single `diff2.Change` struct.  The system has no way to tell if this is purely informational (diff2.REPORT) or a mix of REPORT and other changes.

@hnrgrgr: Do you think you could change the provider to return all the `diff2.REPORT` msgs in a separate `diff2.Change` struct?

**Comment by fritterhoff** [comment]
Ah that explains why I got the correct output using the CF Provider...

**Comment by tlimoncelli** [comment]
Looks good!

Yeah, AXFRPROVIDER and ROUTE53 had this issue.  I've now checked all the providers and I believe those are the only two.

Thank you for the fast fix!
