### ISSUE TITLE
dnscontrol version on Windows does not return the released version number

### ISSUE THREAD

**Issue by riku22** [StackExchange/dnscontrol#2316]
Hello.

As the title says, running `dnscontrol version` on Windows only shows the commit hash and build time, not the release version number.
#2078 seems to fix it, but `dnscontrol.exe` doesn't seem to fix it.
Could you check it out?
The version of dnscontrol uses 3.31.3.

**Comment by tlimoncelli** [comment]
Fixed.

I made a change (see 3d1cd30a1debced4b68449a638c09abeb1bb8b7c) and did a pre-release of 3.31.5 (this version won't be an actual release).  Anyway... it fixed the problem for Windows:

![screencapture_2023-05-15_19 26 28](https://github.com/StackExchange/dnscontrol/assets/6293917/8a164516-e4d6-429f-bef7-67ac9a497924)

The next release to include this PR will be 3.32.0
