### ISSUE TITLE
AXFRDDNS parameters in creds.json

### ISSUE THREAD

**Issue by hmoffatt** [StackExchange/dnscontrol#2322]
The documentation at https://docs.dnscontrol.org/service-providers/providers/axfrddns mentions setting the default name servers and the primary master in `creds.json`, but the syntax looks wrong or I don't understand the context.

```
{
   master = "10.20.30.40:5353"
}
```

I think this is meant to be something like

```
{
  "axfrddns": {
    "TYPE": "AXFRDDNS",
    "nameservers": "127.0.0.1",
    "master": "localhost"
  }
}
```

which works for me (and fails if I don't include one or the other).

**Comment by cafferata** [comment]
@tlimoncelli how can I help? ☺️

**Comment by tlimoncelli** [comment]
@hnrgrgr your input?

**Comment by tlimoncelli** [comment]
Fixed by https://github.com/StackExchange/dnscontrol/pull/2335
