### ISSUE TITLE
Totally messed up configuration with TransIP

### ISSUE THREAD

**Issue by tjveldhuizen** [StackExchange/dnscontrol#2323]
Using DNS Control 3.31.3

Before:
![image](https://user-images.githubusercontent.com/779998/236406658-f38d78fe-4295-4f65-83e0-405dda7d8bb3.png)

DNS Control config:
```js
D("svcreators.nl", REG_NONE,
	DnsProvider(DSP_TRANSIP),
	DefaultTTL(300),

	SPF_BUILDER({
		parts: [
			"v=spf1",
			"-all"
		]
	}),
	DMARC_BUILDER({policy: "none"}),

	A("@", IP4_LB1),
	AAAA("@", IP6_LB1),
	CNAME('www', '\@')
)
```

Duplicate MODIFY-lines in preview:
```bash
tjv@DESKTOP-IMJ8Q0T:~/nevobo/projecten/dns$ dnscontrol preview --domains svcreators.nl
[INFO: Old diff algorithm in use. Please test --diff2 as it will be the default in releases after 2023-05-07. See https://github.com/StackExchange/dnscontrol/issues/2262]
******************** Domain: svcreators.nl
14 corrections (transip)
#1: - DELETE MX svcreators.nl 10 \@ ttl=3600
#2: - DELETE CNAME transip-a._domainkey.svcreators.nl _dkim-a.transip.email. ttl=3600
#3: - DELETE CNAME transip-b._domainkey.svcreators.nl _dkim-b.transip.email. ttl=3600
#4: - DELETE CNAME transip-c._domainkey.svcreators.nl _dkim-c.transip.email. ttl=3600
#5: ± MODIFY TXT svcreators.nl: ("v=spf1 ~all" ttl=3600) -> ("v=spf1 -all" ttl=300)[1/2]
#6: ± MODIFY TXT svcreators.nl: ("v=spf1 ~all" ttl=3600) -> ("v=spf1 -all" ttl=300)[2/2]
#7: ± MODIFY CNAME www.svcreators.nl: (\@ ttl=3600) -> (svcreators.nl. ttl=300)[1/2]
#8: ± MODIFY CNAME www.svcreators.nl: (\@ ttl=3600) -> (svcreators.nl. ttl=300)[2/2]
#9: ± MODIFY TXT _dmarc.svcreators.nl: ("v=DMARC1; p=none;" ttl=3600) -> ("v=DMARC1; p=none" ttl=300)[1/2]
#10: ± MODIFY TXT _dmarc.svcreators.nl: ("v=DMARC1; p=none;" ttl=3600) -> ("v=DMARC1; p=none" ttl=300)[2/2]
#11: ± MODIFY A svcreators.nl: (37.97.254.27 ttl=3600) -> (84.22.116.53 ttl=300)[1/2]
#12: ± MODIFY A svcreators.nl: (37.97.254.27 ttl=3600) -> (84.22.116.53 ttl=300)[2/2]
#13: ± MODIFY AAAA svcreators.nl: (2a01:7c8:3:1337::27 ttl=3600) -> (2a02:2770:17:0:21a:4aff:fe6a:81a4 ttl=300)[1/2]
#14: ± MODIFY AAAA svcreators.nl: (2a01:7c8:3:1337::27 ttl=3600) -> (2a02:2770:17:0:21a:4aff:fe6a:81a4 ttl=300)[2/2]
Done. 14 corrections.

```

Log when pushing changes
```bash
tjv@DESKTOP-IMJ8Q0T:~/nevobo/projecten/dns$ dnscontrol push --domains svcreators.nl
[INFO: Old diff algorithm in use. Please test --diff2 as it will be the default in releases after 2023-05-07. See https://github.com/StackExchange/dnscontrol/issues/2262]
******************** Domain: svcreators.nl
14 corrections (transip)
#1: - DELETE MX svcreators.nl 10 \@ ttl=3600
FAILURE! Dns entry not found
#2: - DELETE CNAME transip-a._domainkey.svcreators.nl _dkim-a.transip.email. ttl=3600
FAILURE! Dns entry not found
#3: - DELETE CNAME transip-b._domainkey.svcreators.nl _dkim-b.transip.email. ttl=3600
FAILURE! Dns entry not found
#4: - DELETE CNAME transip-c._domainkey.svcreators.nl _dkim-c.transip.email. ttl=3600
FAILURE! Dns entry not found
#5: ± MODIFY CNAME www.svcreators.nl: (\@ ttl=3600) -> (svcreators.nl. ttl=300)[1/2]
FAILURE! Dns entry not found
#6: ± MODIFY CNAME www.svcreators.nl: (\@ ttl=3600) -> (svcreators.nl. ttl=300)[2/2]
FAILURE! A CNAME's name must be unique, there cannot exist other records with the same name according to RFC 1035.: www 3600 CNAME @
the expire of all records in an rrset must be all the same: www 3600 CNAME @
A CNAME's name must be unique, there cannot exist other records with the same name according to RFC 1035.: www 300 CNAME svcreators.nl.
the expire of all records in an rrset must be all the same: www 300 CNAME svcreators.nl.
#7: ± MODIFY TXT _dmarc.svcreators.nl: ("v=DMARC1; p=none;" ttl=3600) -> ("v=DMARC1; p=none" ttl=300)[1/2]
SUCCESS!
#8: ± MODIFY TXT _dmarc.svcreators.nl: ("v=DMARC1; p=none;" ttl=3600) -> ("v=DMARC1; p=none" ttl=300)[2/2]
SUCCESS!
#9: ± MODIFY A svcreators.nl: (37.97.254.27 ttl=3600) -> (84.22.116.53 ttl=300)[1/2]
SUCCESS!
#10: ± MODIFY A svcreators.nl: (37.97.254.27 ttl=3600) -> (84.22.116.53 ttl=300)[2/2]
FAILURE! Error setting Dns Entries
#11: ± MODIFY AAAA svcreators.nl: (2a01:7c8:3:1337::27 ttl=3600) -> (2a02:2770:17:0:21a:4aff:fe6a:81a4 ttl=300)[1/2]
FAILURE! A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): @ 3600 MX 10 @
#12: ± MODIFY AAAA svcreators.nl: (2a01:7c8:3:1337::27 ttl=3600) -> (2a02:2770:17:0:21a:4aff:fe6a:81a4 ttl=300)[2/2]
FAILURE! the expire of all records in an rrset must be all the same: @ 3600 AAAA 2a01:7c8:3:1337::27
the expire of all records in an rrset must be all the same: @ 300 AAAA 2a02:2770:17:0:21a:4aff:fe6a:81a4
#13: ± MODIFY TXT svcreators.nl: ("v=spf1 ~all" ttl=3600) -> ("v=spf1 -all" ttl=300)[1/2]
SUCCESS!
#14: ± MODIFY TXT svcreators.nl: ("v=spf1 ~all" ttl=3600) -> ("v=spf1 -all" ttl=300)[2/2]
SUCCESS!
Done. 14 corrections.
completed with errors
```

Totally mixed up configuration in config panel:
![image](https://user-images.githubusercontent.com/779998/236406699-a64df7cb-3273-4ec3-a4b6-2391bf70f1c1.png)

**Comment by tlimoncelli** [comment]
The TransIP provider is maintained by @blackshadev.  Would you please take a look?

Some notes:
* `CNAME('www', '\@')` should be `CNAME('www', '@')` (remove the `\`

Would you please run `dnscontrol print-ir -out out.json --pretty` and attach the file `out.json` to this issue?  Thanks!

**Comment by tjveldhuizen** [comment]
Attached the content of out.json (renamed to .json.txt because GitHub disallows uploading .json). Maybe good to know for reproduction: the 'before' configuration is the TransIP default configuration.

[out.json.txt](https://github.com/StackExchange/dnscontrol/files/11407982/out.json.txt)

**Comment by blackshadev** [comment]
This is really odd. First off a quick solution: you can manually delete all records, run DNS control and it should work.

Could you give me your "before" config? I only have really old transIP domains with defaults, but I think they changed it over time. 

I would also recommend to use the new `--diff2` option, as it will handle TransIP's pickiness with regards to changes in changesets a bit better. 

As a first gut feeling, I would say that they changed the behavior of the "@" in there backend so I would need to account for that. And their record names are case sensitive??? This is really odd and if so I will contact TransIP, because to my knowledge, DNS shouldn't be case sensitive.

**Comment by tjveldhuizen** [comment]
There is no 'before' DNS control config, since I'm trying to start with DNS control. The default config can be applied using the TransIP interface:

![image](https://user-images.githubusercontent.com/779998/236616091-9f3667db-c268-4b8f-87cc-6792cbcd0369.png)

I already found out that clearing the records before applying them from DNS control works, but in my final setup I would like to  automate the application of changes via GitHub actions, so clearing records on beforehand is not really doable, then.

`--diff2` is not working with my version of DNS control:
```bash
tjv@DESKTOP-IMJ8Q0T:~/nevobo/projecten/dns$ brew info dnscontrol
==> dnscontrol: stable 3.31.3 (bottled)
It is system for maintaining DNS zones
https://github.com/StackExchange/dnscontrol
/home/linuxbrew/.linuxbrew/Cellar/dnscontrol/3.31.3 (5 files, 33.1MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-05-05 at 10:00:42
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/dnscontrol.rb
License: MIT
==> Dependencies
Build: go ✘
Required: gcc ✔
==> Analytics
install: 0 (30 days), 102 (90 days), 1,468 (365 days)
install-on-request: 0 (30 days), 102 (90 days), 1,467 (365 days)
build-error: 0 (30 days)
tjv@DESKTOP-IMJ8Q0T:~/nevobo/projecten/dns$
tjv@DESKTOP-IMJ8Q0T:~/nevobo/projecten/dns$ 
tjv@DESKTOP-IMJ8Q0T:~/nevobo/projecten/dns$ 
tjv@DESKTOP-IMJ8Q0T:~/nevobo/projecten/dns$ dnscontrol preview --domains svcreators.nl --diff2
Incorrect Usage: flag provided but not defined: -diff2
```

**Comment by blackshadev** [comment]
Thanks for that.
You need the `--diff2` to be placed before push so `dnscontrol --diff2 preview ....`

 I have reproduced several problems and hopefully I will be able to solve them. 

But one think I will be unlikely to fix: I cannot delete A records with are referred  to by CNAME , MX records and the like. But I cannot "disable" this check from transIP and I am not able to "reorder" this in DNSControl. I will contact TransIP to request a feature flag or something to disable this check on a per API basis, as it is unlikely to help our usecase, but I have no idea how they will react to it (if at all)

**Comment by tjveldhuizen** [comment]
Thanks, using that diff2 position works (might be nice to describe that in the error message)

```bash
tjv@DESKTOP-IMJ8Q0T:~/nevobo/projecten/dns$ dnscontrol --diff2 preview --domains svcreators.nl
[INFO: Diff2 algorithm in use.]
******************** Domain: svcreators.nl
14 corrections (transip)
#1: [1/2] delete: ± MODIFY svcreators.nl A (37.97.254.27 ttl=3600) -> (84.22.116.53 ttl=300)
#2: [2/2] create: ± MODIFY svcreators.nl A (37.97.254.27 ttl=3600) -> (84.22.116.53 ttl=300)
#3: [1/2] delete: ± MODIFY svcreators.nl AAAA (2a01:7c8:3:1337::27 ttl=3600) -> (2a02:2770:17:0:21a:4aff:fe6a:81a4 ttl=300)
#4: [2/2] create: ± MODIFY svcreators.nl AAAA (2a01:7c8:3:1337::27 ttl=3600) -> (2a02:2770:17:0:21a:4aff:fe6a:81a4 ttl=300)
#5: - DELETE svcreators.nl MX 10 \@ ttl=3600
#6: [1/2] delete: ± MODIFY svcreators.nl TXT ("v=spf1 ~all" ttl=3600) -> ("v=spf1 -all" ttl=300)
#7: [2/2] create: ± MODIFY svcreators.nl TXT ("v=spf1 ~all" ttl=3600) -> ("v=spf1 -all" ttl=300)
#8: [1/2] delete: ± MODIFY _dmarc.svcreators.nl TXT ("v=DMARC1; p=none;" ttl=3600) -> ("v=DMARC1; p=none" ttl=300)
#9: [2/2] create: ± MODIFY _dmarc.svcreators.nl TXT ("v=DMARC1; p=none;" ttl=3600) -> ("v=DMARC1; p=none" ttl=300)
#10: - DELETE transip-a._domainkey.svcreators.nl CNAME _dkim-a.transip.email. ttl=3600
#11: - DELETE transip-b._domainkey.svcreators.nl CNAME _dkim-b.transip.email. ttl=3600
#12: - DELETE transip-c._domainkey.svcreators.nl CNAME _dkim-c.transip.email. ttl=3600
#13: [1/2] delete: ± MODIFY www.svcreators.nl CNAME (\@ ttl=3600) -> (svcreators.nl. ttl=300)
#14: [2/2] create: ± MODIFY www.svcreators.nl CNAME (\@ ttl=3600) -> (svcreators.nl. ttl=300)
Done. 14 corrections.
```

They might not fancy to add such feature flag because it can result in an inconsistent state, but maybe it helps if they can add a recursive-is-ok flag?

**Comment by blackshadev** [comment]
@tlimoncelli do you know any other providers which have the same issue where the remote provider requires you to have a valid state. And this you are unable to remove records with are referred to? Maybe they have a solution which I didn't find yet.

**Comment by blackshadev** [comment]
I have created an MR to solve most problems. The ordering is still an issue But you can resolve this by running it twice.

@tjveldhuizen can you run against my fixed branch?

**Comment by tlimoncelli** [comment]
[blackshadev](https://github.com/blackshadev)
> @tlimoncelli do you know any other providers which have the same issue where the remote provider requires you to have a valid state. And this you are unable to remove records with are referred to? Maybe they have a solution which I didn't find yet.

This is a known problem.  

Most providers just expect the user to run "push" twice. Some providers re-order their updates for critical things (route53 assures that an R53_ALIAS is created after its target; and that the target is deleted before an alias is deleted).


Fixing this for all providers becomes a lot easier with the diff2 change.  See https://github.com/StackExchange/dnscontrol/issues/2253 

My recommendation?   In reality this kind of situation is rare and "push twice" is a reasonable solution for now.  If you are interested in implementing https://github.com/StackExchange/dnscontrol/issues/2253 the community will be very grateful!
