### ISSUE TITLE
get-zones from BIND produces invalid DS records

### ISSUE THREAD

**Issue by hmoffatt** [StackExchange/dnscontrol#2324]
I have a zone file containing a DS record for a subdomain, like

```
geo		IN DS	14480 13 2 BB1C4B615CDED2B34347CF23710471934D972F1E34F53B54ED8D5F786202C73B
```

When I use `dnscontrol get-zones --format=js bind BIND domain.com` to convert this to js format, I get a DS record of the form:

```
DS('geo', '14480 13 2 BB1C4B615CDED2B34347CF23710471934D972F1E34F53B54ED8D5F786202C73B'),
 ```

but this is invalid syntax - should be separate parameters, not one string.

Despite this, preview works OK after fixing the js by hand.

**Comment by tlimoncelli** [comment]
Thanks for reporting this.  The goal of "--format=js" is to create a "decent first draft", not something that is perfect. However this seems like something that can be fixed.

I've created a PR that adds a unit test that shows the problem:

https://github.com/StackExchange/dnscontrol/pull/2326

Interested in fixing it?

**Comment by hmoffatt** [comment]
Interested, but not knowing either the code nor Go is not going to make it quick - I guess that's no excuse though right? :)

**Comment by tlimoncelli** [comment]
That would be awesome!  I'll give you a quick hint: getZones.go/GetZone() generates the output of `get-zones`.  For a "js" output, it calls getZones.go/formatDsl() for each line.

**Comment by hmoffatt** [comment]
That turned out way easier than expected. Thanks for the tip and the encouragement!
