### ISSUE TITLE
document functions in record list

### ISSUE THREAD

**Issue by hmoffatt** [StackExchange/dnscontrol#2339]
https://docs.dnscontrol.org/getting-started/examples gives an example of using a function in a record list, 

```
var FASTMAIL_DKIM = function(the_domain){
  return [
    CNAME('fm1._domainkey', 'fm1.' + the_domain + '.dkim.fmhosted.com.'),
    CNAME('fm2._domainkey', 'fm2.' + the_domain + '.dkim.fmhosted.com.'),
    CNAME('fm3._domainkey', 'fm3.' + the_domain + '.dkim.fmhosted.com.')
  ]
}
```

(Note there's a missing `{% endcode %}` causing this not to be formatted properly.)

I couldn't find any other documentation about this feature. It looks like something that could be useful to document at https://docs.dnscontrol.org/advanced-features/code-tricks ?

**Comment by tlimoncelli** [comment]
Good point!

Though, now I'm thinking I should merge those two pages.
