### ISSUE TITLE
DESEC: FEATURE REQUEST: Enable get-zones (ListZones) for deSEC

### ISSUE THREAD

**Issue by StuartMorrisAU** [StackExchange/dnscontrol#2346]
If I configure `creds.json` and `dnsconfig.js` to use deSEC [as instructed](https://docs.dnscontrol.org/service-providers/providers/desec) and then run either `dnscontrol check-creds desec` or `dnscontrol get-zones --format=nameonly desec - all`, I get the following error:

```
provider type desec: cannot list zones to use the 'all' feature
```

However, if I [query the deSEC API](https://desec.readthedocs.io/en/latest/dns/domains.html#listing-domains) directly, I do get back a json response with all the domains on my account. Is it possible to get this implemented?

**Comment by tlimoncelli** [comment]
CC @D3luxee  (maintainer of the DESEC provider)

That feature isn't enabled for deSEC.

To enable that feature, implement the ListZones() function.  The rest will take care of itself.

Would you be interested in submitting a PR?
