### ISSUE TITLE
DNSControl version (Homebrew)

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#2354]
`dnscontrol version` does no longer return the released version number. Possibly due to the GitHub Actions refactor?

```shell
dnscontrol version
```
```text
dnscontrol -dev
```

```shell
brew info dnscontrol
```
```text
==> dnscontrol: stable 3.31.4 (bottled)
It is system for maintaining DNS zones
https://github.com/StackExchange/dnscontrol
/usr/local/Cellar/dnscontrol/3.31.4 (5 files, 36.5MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-05-12 at 09:04:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/dnscontrol.rb
License: MIT
==> Dependencies
Build: go (installed)
```

**Comment by tlimoncelli** [comment]
Oh drat!  That versioning code gives me no end of trouble.

**Comment by tlimoncelli** [comment]
WTF!  This is driving me nuts!

I think the problem is that this was fixed in `draft_release.yml` but not in `release.yml`.  `release.yml` should have been disabled, as it is obsolete.  My guess is that `release.yml` ran unexpectedly.

I'm disabling `release.yml` and will try to generate a 4.0.1 later today.

**Comment by cafferata** [comment]
A crosslink for reference only: https://github.com/StackExchange/dnscontrol/pull/2369

**Comment by cafferata** [comment]
Confirmed from release https://github.com/StackExchange/dnscontrol/releases/tag/v4.0.1

**Comment by j-f1** [comment]
Still no dice for me on Homebrew, sorry!

```shellsession
$ brew upgrade dnscontrol
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################### 100.0%
==> Upgrading 1 outdated package:
dnscontrol 4.0.0 -> 4.0.1
==> Fetching dnscontrol
==> Downloading https://ghcr.io/v2/homebrew/core/dnscontrol/manifests/4.0.1
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/dnscontrol/blobs/sha256:4b25d3b
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################### 100.0%
==> Upgrading dnscontrol
  4.0.0 -> 4.0.1 

==> Pouring dnscontrol--4.0.1.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/dnscontrol/4.0.1: 5 files, 36.3MB
==> Running `brew cleanup dnscontrol`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/dnscontrol/4.0.0... (5 files, 36.2MB)
Removing: /Users/jed/Library/Caches/Homebrew/dnscontrol--4.0.0... (11.0MB)
$ dnscontrol version
dnscontrol -dev
$ which dnscontrol
/opt/homebrew/bin/dnscontrol
```

**Comment by tlimoncelli** [comment]
Does homebrew build it from scratch or use the binaries from the GitHub release?

**Comment by j-f1** [comment]
Ah, it looks like they build it manually: https://github.com/Homebrew/homebrew-core/blob/master/Formula/dnscontrol.rb

**Comment by cafferata** [comment]
Maybe it's better to update the Homebrew taps from GoReaser?
_https://goreleaser.com/customization/homebrew/_

**Comment by truthdoug** [comment]
@j-f1 if they build it manually, does that imply that this is an issue with the Homebrew formula and not a bug in dnscontrol?

**Comment by j-f1** [comment]
I believe so.

**Comment by truthdoug** [comment]
I know not much about how go works but I dug a bit and found `build/build.go` and I'm guessing that's what go uses to guide how something is built and installed. I then compared the [line 19 in that file](https://github.com/StackExchange/dnscontrol/blob/d00804b4f51c5b95137b50b15c747493de1475d5/build/build.go#L19)
to [line 30 of the dnscontrol Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/92d3dec565f40fd01cce7b903da634070cf727f6/Formula/dnscontrol.rb#L30) where the formula builds dnscontrol.

It looks like when building dnscontrol, homebrew's formula should pass `-X main.SHA=<version>` and it does not.

On my local machine, I tested the build both homebrew's way and what I think is the fix and I get:
```bash
# test build as done in Homebrew formula
$ go build -ldflags "-s -w"
$ ./dnscontrol version
dnscontrol -dev

# add definition of main.SHA
$ go build -ldflags '-s -w -X main.SHA=fake-version'
$ ./dnscontrol version
dnscontrol  (fake-version)
```

I'll submit an issue to Homebrew for this and mention this issue.

**Comment by truthdoug** [comment]
The change to the Homebrew formula is closed and merged!

I did:
```bash
$ brew uninstall dnscontrol
$ brew install dnscontrol
```

and now see:
```bash
$ dnscontrol version
dnscontrol 4.1.1 (Homebrew)
```

I'm ok with this issue being closed

**Comment by cafferata** [comment]
Confirmed! Immediately closed.

**Comment by cafferata** [comment]
Thank you for this work! 👏

**Comment by truthdoug** [comment]
Glad to do it – it was annoying me just as much!

**Comment by TomOnTime** [comment]
Thanks to everyone for working this out!   Go team!
