### ISSUE TITLE
New record type: OPENPGPKEY

### ISSUE THREAD

**Issue by systemcrash** [StackExchange/dnscontrol#2370]
Would this be interesting?

Some providers support this record type. I mainly did this as code-golf, for fun. 

It is PR ready, just needs a re-base. 

It required a PR for the miekg lib to fix a buffer issue, [which is now merged](https://github.com/miekg/dns/pull/1446). 

It requires at least https://github.com/miekg/dns/commit/730c265d18c3f51b447f6a4c61fe3cde336585d8 or 1.1.54

I know many orgs use (ECC) PGP Keys for security disclosures, and some (wish to) post those via DNS.

**Comment by tlimoncelli** [comment]
Hi Paul!

In general I'm weary of adding DNS types that aren't commonly used.  Can I see the PR?


Tom

**Comment by systemcrash** [comment]
You can [preview one here](https://github.com/StackExchange/dnscontrol/compare/master...systemcrash:openpgp_type?expand=1).

**Comment by tlimoncelli** [comment]
Well, that's quite an impressive bit of coding you've done there. You've even implemented the integration tests.

I'd be glad to include this in the project, but you'll be on the hook for maintaining it since it isn't something I have a lot of expertise in.  Ok?

One code change I'd like to suggest: Shift the logic out of helpers.js into the Go code.

A lot of the processing is done in Javascript in helpers.js.  That makes it difficult to test and debug.   (Not that there aren't testing frameworks for Javascript, but we can't use them because of otto, etc.)  In general the functions in helpers.js (like A, CNAME, etc.) just pass along the human input and do the "heavy lifting" in Go.  Go has the advantage of the libraries and testing frameworks that we know well.   I would suggest putting that code in its own module (for example  dnscontrol/pkg/openpgpkey)

Tom

**Comment by systemcrash** [comment]
I looked around for places to put the heavy lifting in go because it seems like better APIs are available especially for the UTF8 normalization parts, but there does not seem to be an appropriate place to do so. The multiple pathways seem to be set up to take data immediately from js files and into use in records. Do I just need to be creative or is there a recommended point to start massaging the data so it's ready for use everywhere, irrespective of the ingress route?

**Comment by tlimoncelli** [comment]
Good question!

The Javascript exports the result as JSON.  The fields are the names of the object keys.  The import is done by the UnmarshlJSON functions in models/record.go:

    func (rc *RecordConfig) UnmarshalJSON(b []byte) error

A good example is the "target" field.  It isn't exported. So, the javascript exports it with a field called `.Target` (creative name, eh?) and the imported specially to the `.target` field.

Your code would do something similar but would do transformations on the data first.

**Comment by tlimoncelli** [comment]
Any interest in submitting that as a PR?

**Comment by systemcrash** [comment]
Hi Tim, I never got round to this as it requires dumping functions from js
to go. Not quite sure where they'd go until I've spent some time on it. You
may close this if you wish.

**Comment by systemcrash** [comment]
> Good question!
> 
> The Javascript exports the result as JSON. The fields are the names of the object keys. The import is done by the UnmarshlJSON functions in models/record.go:
> 
> ```
> func (rc *RecordConfig) UnmarshalJSON(b []byte) error
> ```
> 
> A good example is the "target" field. It isn't exported. So, the javascript exports it with a field called `.Target` (creative name, eh?) and the imported specially to the `.target` field.

@tlimoncelli 

Could you write some skeleton code for where this should go and how this should look when you have some time?

**Comment by tlimoncelli** [comment]
How urgent is this?  In a few weeks I hope to merge in a new way to add new record types. It will make this a lot easier. Otherwise, I can look into the JSON issue.

**Comment by systemcrash** [comment]
Let's wait. I was just active in the code-base again with the other stuff recently, and was curious whether I could do this. 

The biggest challenge, I think, is ensuring the UTF-8 normalisation stuff is achievable. Can only really test that thoroughly if the plumbing is there :)

**Comment by systemcrash** [comment]
Hi Tim - I wonder what kind of progress has been made - whether it makes available these changes?

**Comment by systemcrash** [comment]
ping @tlimoncelli
