### ISSUE TITLE
Add support for Route 53 ALIAS record type

### ISSUE THREAD

**Issue by koenrh** [StackExchange/dnscontrol#239]
I'm looking to implement the Route 53 `ALIAS` record type. As you mentioned in the comments, Amazon's implementation of this record is a bit different from the implementation of other providers.

For an `ALIAS` record at Route 53 you not only need to specify the **name** and the **target**, but also the **target record type**. Which means we need to find a way to capture that in the DSL.

I think there are two options:

```
// 1. A custom "record type".

D("foo.com" "bar",
  R53_ALIAS("www", "A", "baz.cloudfront.net."),
  R53_ALIAS("www", "AAAA", "baz.cloudfront.net.")
);
```

```
// 2. A modifier for the existing ALIAS record type.

D("foo.com" "bar",
  ALIAS("www", "baz.cloudfront.net.", R53_RS_TYPE("A"),
  ALIAS("www", "baz.cloudfront.net.", R53_RS_TYPE("AAAA")
);
```

I'm curious to hear what you think is the right way to go.

These are the record types you could use in a Route 53 `ALIAS` record: `A`, `CNAME`, `AAAA`, `MX`, `TXT`, `PTR`, `SPF`, `NAPTR`, and `CAA`

**Comment by pmoroney** [comment]
If you don't need to support the non A and AAAA records, it might be possible to implement the ALIAS record type for route53 that works identically to the other ALIAS implementations by creating an R53 ALIAS for both A and AAAA types.

**Comment by koenrh** [comment]
That might be even a better solution. It would be nice to have the ALIAS records behave more or less the same across all provides. The only challenge I see is that in Route 53's case we would need to "synthesise" `A` and `AAAA` locally, where other providers do this server-side. It's not undoable, but I'm not sure whether that's something we should implement in `dnscontrol`.

**Comment by tlimoncelli** [comment]
I am not familiar with AWS's aliases so this may be ignorant but...

dnscontrol knows if an alias is pointing at an A or AAAA (or both)... at least in the case where the destination record is in a domain that dnscontrol manages.  Does that help?

If it can't automatically determine the destination type, dnscontrol could look for metadata ({ "aws_alias_type": "AAAA"}).  If there is no metadata it could error out with a message explaining the situation.  This error would generally only happen when changing providers, and could give a link to appropriate instruction about what to do.

**Comment by captncraig** [comment]
The problem I see is that R53's alias is fundamentally a different thing than what we mean by that word for other providers. An alias as we see it is essentially a CNAME that is dynamically flattened into A/AAAA by the provider who does a request-time lookup.

For R53, it is a different type of thing that points to aws resources only, and can have other types. See https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html. 

I don't think that records created for these are ever going to be compatible with other providers, particularly if they reference non public-addressable aws elements. I vote for a special record type for it.
