### ISSUE TITLE
Missing Release Assets

### ISSUE THREAD

**Issue by misilot** [StackExchange/dnscontrol#2398]
**Describe the bug**
Previous v3 releases included the following files? Are these no longer being included? https://github.com/StackExchange/dnscontrol/releases/tag/v3.31.4 This was the last release I could find them. I am not seeing them in the v4 releases. Well it looks like they are there just in the different tar files, just not explicitly provided.

dnscontrol-Darwin
dnscontrol-Linux
dnscontrol.exe 

**To Reproduce**
1. See https://github.com/StackExchange/dnscontrol/releases/tag/v4.1.0
2. https://github.com/StackExchange/dnscontrol/releases/tag/v3.31.4 (Has them)
**Expected behavior**
Be provided as top level files on release
dnscontrol-Darwin
dnscontrol-Linux
dnscontrol.exe

**Comment by tlimoncelli** [comment]
Those files are now in the .zip and .tar.gz files only.

For example:

* dnscontrol-Darwin: dnscontrol_4.1.0_darwin_all.tar.gz
* dnscontrol-Linux: dnscontrol_4.1.0_linux_amd64.tar.gz
* dnscontrol.exe: dnscontrol_4.1.0_windows_amd64.zip

**Comment by misilot** [comment]
Ok, thanks!
