### ISSUE TITLE
Feature extension: job runner to do the reconciliation 

### ISSUE THREAD

**Issue by gedw99** [StackExchange/dnscontrol#2401]
To reconcile devs can use git flow ops but there’s also the case of when you’re not . Day 2 ops.

then it’s a different job runner. GitHub is not the job runner.

and you want to run a check daily for example ..

so was wondering is anyone has through about NATS etc . It’s just one possibility of a job queue . Nats can even be embedded and so you can do what you do on GitHub locally or in a distributed system .

Food for thought …

**Comment by tlimoncelli** [comment]
Please move this discussion to the https://groups.google.com/g/dnscontrol-discuss email list.
