### ISSUE TITLE
DNSControl behaves differently in Alpine-based Docker container

### ISSUE THREAD

**Issue by DvdGiessen** [StackExchange/dnscontrol#2422]
When run in an Alpine-based Docker container, DNSControl is unable to list all my domain names. This means it doesn't work with [the official Docker image](https://hub.docker.com/r/stackexchange/dnscontrol/), while it works perfectly when run on my Mac, my Arch Linux system at home, or inside a Debian 11 container.

Using binary from `dnscontrol_4.1.0_linux_amd64.tar.gz` from latest release:
```
$ docker run -ti --rm -v $(pwd):/dns:ro -w /dns debian:latest
root@d2c4d8b7e3ec:/dns# cat /etc/issue
Debian GNU/Linux 11 \n \l

root@d2c4d8b7e3ec:/dns# # Note: In the Debian image some CA certificates are missing I need for my provider
root@d2c4d8b7e3ec:/dns# (apt update && apt install -y ca-certificates) >/dev/null 2>&1
root@d2c4d8b7e3ec:/dns# ./dnscontrol version
dnscontrol "4.1.0" ("e97cf017445a1a622ed4a7b2766b1aa83637d185") built 25 May 23 15:48 UTC
root@d2c4d8b7e3ec:/dns# ./dnscontrol check-creds transip | wc -l
56
root@3eba97af219b:/dns# ./dnscontrol check-creds transip | head -n1 | sha256sum 
a9a52a3164777288e7f3c0a13540c47c634743cd6e9aa7c4de5bd441c5d9414c  -
```
```
$ docker run -ti --rm -v $(pwd):/dns:ro -w /dns alpine:latest
/dns # cat /etc/issue
Welcome to Alpine Linux 3.18
Kernel \r on an \m (\l)

/dns # ./dnscontrol version
dnscontrol "4.1.0" ("e97cf017445a1a622ed4a7b2766b1aa83637d185") built 25 May 23 15:48 UTC
/dns # ./dnscontrol check-creds transip | wc -l
1
/dns # ./dnscontrol check-creds transip | sha256sum
a9a52a3164777288e7f3c0a13540c47c634743cd6e9aa7c4de5bd441c5d9414c  -
```

Left out the actual domain names, but as you can see it appears DNSControl is only seeing the very first domain when being run in Alpine.

This isn't just a matter of truncated output on the CLI; I actually first ran into this when doing `dnscontrol preview` in my CI (using the documented example which uses the Docker container) and I got a bunch of `WARNING: Zone '<REDACTED>' does not exist in the 'transip' profile and will be added automatically.` messages, so it appears it is really not seeing the other domain names.

The provider used is `TRANSIP`. I didn't have any other accounts around so was unable to test whether this bug is in DNSControl core or in the provider code. I also considered it might be a CA certificates related problem, but since it is able to correctly list at least one of my domain names, it seems to be connecting to the API's of my provider just fine. See also #2423 which I just opened about not clearly reporting CA certificate missing errors.

Regardless of whether this is a bug in the provider code, this issue also does raise the question whether the official DNSControl Docker container should be build with Alpine, considering that as far as I could see none of the automated tests are run on Alpine, and thus using a base image that's similar to the one DNSControl is tested on might be a safer choice given that apparently this can result in different behaviour? See also [the notes on the official Golang images](https://hub.docker.com/_/golang/), which state that running on Alpine might give different behaviour.

While I would definitely support making sure DNSControl runs just as well on musl as on glibc (if only because efforts like that usually help root out additional bugs in the process and DNSControl supports a wide range of platforms already anyway), it does seem like it would be a safer choice to stick with a similar base image as the tests are being run on.

**Comment by TomOnTime** [comment]
I confess I don't know a lot about Docker and the various base images.  Therefore, I rely on folks like yourself for suggestions and PRs.

Are you saying I should change the line:

    FROM alpine:3.18.0@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11 as RUN

to

    FROM golang:1.20 as RUN

instead?

Could you test this?

**Comment by DvdGiessen** [comment]
No problem, happy to help! I'll open a pull request with my proposed changes, so you can review them there.

Some background:

Actually, given that Go builds static linked binaries, we don't actually need the Golang image at all. That one contains a bunch of build-time dependencies that makes the image a lot bigger, and thus wastes a bit of time and bandwidth. Best would be to use a relatively small base image that only contains the dependencies needed for the application to run.

As mentioned, my recommendation would be to go with the `debian` base image. The `golang` images themselves are actually based on Debian, so it seems like a stable choice. They are a lot smaller than the `golang` image (124MiB vs 777MiB).

Note that it's not the smallest possible choice (which is actually one of the reasons `alpine` is so popular in the Docker world, because it only weights a mere 7MiB!). Usually the recommended base image for purely running a Go program would be Google's own `distroless` images. However, I'm not recommending using these because one of the use cases for the DNSControl Docker image is being able to very easily use it inside CI (as seen in the examples in the official docs), and that doesn't work with these images (`alpine` for the reasons mentioned above, and `distroless` because it lacks the basic functionalities needed by many CI systems).

**Comment by jauderho** [comment]
The prior issue with Alpine was to do with DNS resolution and must. This issue should have gone away with the latest Alpine 3.18 version. See the Alpine release log: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.18.0

As a counterpoint, the issue that you have highlighted with check-creds does not appear for me (albeit using my own image).

```
jauderho@host:~/dnsfiles$ docker run -ti --rm -v $(pwd):/dns:ro -w /dns ghcr.io/stackexchange/dnscontrol:latest check-creds cloudflare | wc -l
3
jauderho@host:~/dnsfiles$ dnscontrol check-creds cloudflare | wc -l
3
```

**Comment by DvdGiessen** [comment]
> The prior issue with Alpine was to do with DNS resolution and musl. This issue should have gone away with the latest Alpine 3.18 version.

Unfortunately, this issue occurred on Alpine 3.18.0 which the image uses since https://github.com/StackExchange/dnscontrol/commit/0d044fd121671b9b781d3dd0b5d0781e1d636549.

> As a counterpoint, the issue that you have highlighted with check-creds does not appear for me.

I don't know what the root cause of the issue is, it is a weird one for sure. My provider uses a REST API served over HTTPS. So, the fact that it is correctly returning the very first domain namename does mean it at least successfully connected to the API. Additionally this API happens to return its result as JSON, which if simply truncated would not be valid anymore. The provider implementation also doesn't appear to have any logic to only select a subset of domains, it always performs the same fixed GET request. So, either DNSControl is leaking information about which distro it is running on and my provider or a MITM attacker is also sniffing for those markers and sending a different response to a otherwise identical GET request, or there is a weird bug in Go/DNSControl/dependencies that only triggers on Alpine and somehow causes it to lose items on a list. Either way it's weird and I wouldn't expect it to arbitrarily reproduce for all users.

> So I'm perfectly happy to continue using a Alpine based image due to the smaller size.

As mentioned, I would like that if it worked identically! The main motivation for proposing we move to a different base image is because right now, that image is the *only* place that Alpine appears to be used. We don't build on Alpine, we don't test on Alpine. Additionally Go themselves don't support Alpine-based Docker images, noting it's "highly experimental". So moving to Debian seems a safer choice if a working image is more important than a small one.

The other option of course would to explicitly support Alpine. Build on it, test on it. That would take more work, which is why it wasn't my first recommendation. I'd love to see a PR for it though just because personally I do love Alpine. :)

**Comment by TomOnTime** [comment]
I'd prefer to stay with Alpine due to the smaller image size.  Can we figure out the cause of the problem and fix it instead?

Does this only affect TRANSIP?  Does anyone else have this problem?

**Comment by DvdGiessen** [comment]
I dug a bit deeper, and seems I found the cause for this specific issue: missing `tzdata` in Alpine.

The TransIP Go client implements a `UnmarshalJSON` function to decode timestamps: https://github.com/transip/gotransip/blob/1f362d7/rest/response.go#L45-L81.

That uses the builtin `time` module of Go to query the timezone, which gets it from the system timezone data. And on Alpine, that data isn't available by default, thus causing errors mid-parsing. And apparently in that case the Go JSON parser happily returns a partial result.

Installing the missing data with `apk add --no-cache tzdata` fixes this specific issue, and DNSControl can once again see all domain names instead of just one. So if sticking with the Alpine image, we'd probably need to install this, at the very least for this provider, possibly more for which the dependencies might use it as well?

(I'd still argue that if images are released using Alpine, it would make a lot of sense to run tests on Alpine as well, because then at least it's possible to automatically test for things like this, and it doesn't depend on someone filing a bugreport to spot issues. But that's perhaps for another day.)

**Comment by TomOnTime** [comment]
Thanks for researching that!

Including tzdata sounds like the best solution.
