### ISSUE TITLE
TRANSIP: dnscontrol does not error when CA certificates are missing

### ISSUE THREAD

**Issue by DvdGiessen** [StackExchange/dnscontrol#2423]
Note: I only observed this issue with the `TRANSIP` provider because that's the only provider I tested with. Might be that this actually affects more providers.

When the CA certificates for connecting to the TransIP API are missing, `dnscontrol` commands do show any warning or not return an error code.

Easy way to reproduce is to run in a Docker container which is missing the CA certificates, like the default Debian image:
```shell
$ docker run -ti --rm -v $(pwd):/dns:ro -w /dns debian:latest
root@62bfce2f317b:/dns# ./dnscontrol version
dnscontrol "4.1.0" ("e97cf017445a1a622ed4a7b2766b1aa83637d185") built 25 May 23 15:48 UTC
root@62bfce2f317b:/dns# ./dnscontrol check-creds transip && echo Return code was zero
Return code was zero
root@62bfce2f317b:/dns# (apt update && apt install -y ca-certificates) >/dev/null 2>&1 
root@62bfce2f317b:/dns# ./dnscontrol check-creds transip && echo Return code was zero
REDACTED.io
REDACTED.nl
REDACTED.nl
REDACTED.nl
<... more domain names>
Return code was zero
```

I would expect DNSControl to show an error message on stderr when it's totally unable to connect to the provider, and return an error code, so that the user can figure out what's going wrong.

**Comment by imlonghao** [comment]
The error in ListZones() got ignored, it should show a `x509: certificate signed by unknown authority` error when missing ca-certificates.

https://github.com/StackExchange/dnscontrol/blob/f80f94f94b54c3b1ed43f90a1c7d636aab1e4f93/providers/transip/transipProvider.go#L87

**Comment by TomOnTime** [comment]
> The error in ListZones() got ignored, it should show a `x509: certificate signed by unknown authority` error when missing ca-certificates.

Something like this?  https://github.com/StackExchange/dnscontrol/pull/2433

Dvd: Can you test that branch?
