### ISSUE TITLE
Feature request: INWX – Implement ListZones()

### ISSUE THREAD

**Issue by killerbees19** [StackExchange/dnscontrol#2425]
Currently there's no support for the `all` feature, because `ListZones()` isn't implemented at INWX provider.

API documentation for `nameserver.list`: https://www.inwx.com/en/help/apidoc/f/ch02s13.html#nameserver.list

/cc @patschi

**Comment by TomOnTime** [comment]
`dnscontrol get-zones` accepts the word "all" as a zonename to indicate "list zones".  The "all" keyword only works if ListZones() is defined for the provider.

**Comment by imlonghao** [comment]
> Do you have more context about the `all` feature you're referring to? I might have missed something, but I'm not sure which dnscontrol function you're referring to.

Here is a similar issue and solution, https://github.com/StackExchange/dnscontrol/issues/2346

**Comment by patschi** [comment]
Thanks @TomOnTime and @imlonghao! Never used `get-zones` at all, so I wasn't familiar with the more specific functionality.

Implemented this via PR #2428. The example was great help.
