### ISSUE TITLE
update the decontrol docker page

### ISSUE THREAD

**Issue by redochka** [StackExchange/dnscontrol#2445]
**Describe the bug**
The command line in the docker page https://hub.docker.com/r/stackexchange/dnscontrol is wrong.

Bad:

```
docker run --rm -it -v $(pwd)/dnsconfig.js:/dns/dnsconfig.js -v $(pwd)/creds.json:/dns/creds.json stackexchange/dnscontrol dnscontrol preview
```

Good:

```
docker run --rm -it -v $(pwd)/dnsconfig.js:/dns/dnsconfig.js -v $(pwd)/creds.json:/dns/creds.json stackexchange/dnscontrol preview

```

**Comment by tlimoncelli** [comment]
In c2eb98993 I updated it to:

    docker run --rm -it -v "$(pwd):/dns"  ghcr.io/stackexchange/dnscontrol preview

This has a few benefits:

* Shorter
* Works with fmt subcommand
* Uses ghcr which has higher daily limits
* Works on bash and PowerShell (I think)

Tom
