### ISSUE TITLE
M365 Builder indexOf error

### ISSUE THREAD

**Issue by tankerkiller125** [StackExchange/dnscontrol#2457]
**Describe the bug**
Adding the following to an existing dnscontrol domain file results in an `indexOf` error.

```
M365_BUILDER({
    initialDomain: 'example.onmicrosoft.com',
    autodiscover: true,
    dkim: true,
    mx: true,
    skypeForBusiness: true,
    mdm: true
  }),
```

I've also tried it with only the initialDomain set, and with and without the domainGuid.

The exact error is `executing dnsconfig.js: Error: File example.com.js: TypeError: 'indexOf' is not a function`

**To Reproduce**
1. Create a dnsconfig.js file that uses `require_glob('folder', false)`
2. Create the domain file, include the `M365_BUILDER` function
3. Execute dnscontrol preview

**Expected behavior**
This error shouldn't happen

**DNS Provider**
 - Cloudflare

**Additional context**
The existing DNS records on the domain have the M365 records, we're just trying to use the M365 Builder instead to clean up the config and make life a little easier. I don't think that's in anyway what's causing a conflict or issue though.

Commenting out the builder and everything works perfectly fine, bring it back though and this error get spit out.

**Comment by tlimoncelli** [comment]
Can you try this again with the v4.2.0 release?  354063cc09f9e0395b49be320a8c01833fbb0330 may have fixed this.

**Comment by tlimoncelli** [comment]
@juliusrickert I believe you contributed the code. Can you take a look?

(I have a hunch that `r` should be `var r` around line 1700 but I'm no Javascript expert!)

**Comment by tankerkiller125** [comment]
This seems to be fixed with the PR, not getting an error, and it published the M365 records successfully.

**Comment by tlimoncelli** [comment]
Thanks, @tankerkiller125 !

**Comment by nikolamilekic** [comment]
I get the same error with 4.9.0. It also goes away when I remove the M365 Builder. Same repro steps with one difference: I'm not using require_glob.

**Comment by Koopzington** [comment]
@nikolamilekic 

The example in the docs is wrong.
apparently you need to pass the domain as first argument and the other options as second argument https://github.com/StackExchange/dnscontrol/blob/v4.11.0/pkg/js/helpers.js#L1709

**Comment by nikolamilekic** [comment]
That fixed it, thanks!

On June 13, 2024, GitHub Notifications ***@***.***> wrote:
> @nikolamilekic <https://github.com/nikolamilekic>
>
> The example in the docs is wrong.
>  apparently you need to pass the domain as first argument and the
> other options as second argument
> <https://github.com/StackExchange/dnscontrol/blob/v4.11.0/pkg/js/helpers.js#L1709>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/dnscontrol/issues/2457#issuecomment-
2165769432>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AA6C377AQZBJSOGQL7KZH63ZHGRBBAVCNFSM6AAAAAAZPCO2SGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNRVG43DSNBTGI>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by cafferata** [comment]
Thanks @Koopzington for the feedback. I asked the author for clarification on the original implementation. See https://github.com/StackExchange/dnscontrol/issues/3008

**Comment by nikolamilekic** [comment]
Oh, I may have submitted a pull request fixing the examples too quickly then. For reference its #3009
