### ISSUE TITLE
Non-existing v3 version and broken go package

### ISSUE THREAD

**Issue by kobajagi** [StackExchange/dnscontrol#2468]
**Describe the bug**
Non-existing version (v3.31.6) is advertised as latest for v3 in [pkg.go.dev](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v3@v3.31.6).

Also checksum check fails when fetching latest using `go get`. I would guess issues are related: v3.31.6 is re-tagged as v3.31.4, changing checksum.

**To Reproduce**
1. `go get github.com/StackExchange/dnscontrol/v3`
2. See error:

```
$ go get github.com/StackExchange/dnscontrol/v3
go: downloading github.com/StackExchange/dnscontrol/v3 v3.31.4
go: github.com/StackExchange/dnscontrol/v3@v3.31.4: verifying module: checksum mismatch
        downloaded: h1:Wl4tQ/Go8gc8ldKlhsccT+eqhJZWyLSI1ePiaRg2INE=
        sum.golang.org: h1:H8y86mTNLKVVo5JmCRgxxGlEqETOk+xCjUOWgkLC3nY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Expected behavior**
Latest version is v3.31.4 and no error with `go get`.

**DNS Provider**
 - All

**Additional context**
/

**Comment by tlimoncelli** [comment]
Hi @kobajagi !  Thanks for reporting this.

The latest version is v4.1.1.  I don't know why pkg.go.dev shows the older version.  Can you instruct me on how to fix this?

**Comment by kobajagi** [comment]
Well issue is only with 3.x.x versions but because golang adds major version to import path (github.com/StackExchange/dnscontrol/**v3**) package is broken for anyone that targets v3. In particular I found this issue in [external-dns repo](https://github.com/kubernetes-sigs/external-dns/blob/master/go.mod#L15). Updating import path to `github.com/StackExchange/dnscontrol/v4` fixes both import and pkg.go.dev issues.

Still if you can fix v3 import that would be great. Issue with pkg.go.dev should be fixable with [retract](https://go.dev/ref/mod#go-mod-file-retract) directive in `go.mod` for versions v3.31.5 and v3.31.6. I'm not sure about `go import`, tagging v3.31.7 would work around sum.golang.org records but there is probably a better way.

**Comment by tlimoncelli** [comment]
@kobajagi I fixed https://github.com/kubernetes-sigs/external-dns/issues/3887 

Closing this issue.

Thanks for reporting this problem. If you know of any similar dependencies please let me know!
