### ISSUE TITLE
[OVH] Error 400: "Try to alter read-only properties: fieldType" SPF, DKIM, DMARC custom RR

### ISSUE THREAD

**Issue by HLFH** [StackExchange/dnscontrol#2488]
**Describe the bug**
The custom RR of SPF, DKIM, DMARC are non-standard on the OVH platform: they are registered as TXT in the DNS, but on OVH Manager and OVH API, it seems they are registered as custom SPF, DKIM and DMARC RR.

Getting the error:
> Error 400: "Try to alter read-only properties: fieldType" 

**DNS Provider**
 - OVH

Related to: https://github.com/StackExchange/dnscontrol/issues/483

I have added a PR to fix custom DMARC RR parsing: https://github.com/StackExchange/dnscontrol/pull/2485.
But we still need to fix `dnscontrol push` on OVH with the custom SPF, DKIM and DMARC RR.

I will debug these issues.

**Comment by HLFH** [comment]
@TomOnTime I am using TXT.

**Comment by tlimoncelli** [comment]
CC @masterzen (maintainer of the OVH provider)

**Comment by masterzen** [comment]
This used to work, so OVH certainly changed their API. That's strange that last time I ran the integration tests this didn't surface.
I'll come up with a patch over the week-end if I can

**Comment by masterzen** [comment]
>  That's strange that last time I ran the integration tests this didn't surface. 

That would be because we don't have any integration tests that validate we can publish specific TXT records such as SPF, DKIM or DMARC.

**Comment by masterzen** [comment]
So I did a few tests:
1. it's not possible to create a DMARC record with OVH web UI (nor API) if you specify its type as DMARC, it always fails with a `invalid subdomain` error
2. it does work with DKIM and SPF, though
3. those special records are returned through the API with their distinct specific record type
4. updating such special records with the API fails one time other two, sometimes truncating output (seems to be very bugged)
5. I have a patch almost ready (and integration tests that pass), but it doesn't really reflect the use case of "creating an entry from the web UI, then updating it through the API"

I'm going to check if I can find someone at OVH to have a look to those issues.

**Comment by masterzen** [comment]
@HLFH would you mind having a look to PR #2535 and see if that fixes your problem?
If not, please let me know.

**Comment by HLFH** [comment]
@tlimoncelli Could you merge this PR? https://github.com/StackExchange/dnscontrol/pull/2535 ; I'd love a 4.2.1 release ;)

@masterzen It does fix it. Thank you very much! 

Happy to close this issue once the PR is merged.

**Comment by tlimoncelli** [comment]
Thanks, everyone!
