### ISSUE TITLE
AXFRDDNS: Long TXT records broken?

### ISSUE THREAD

**Issue by terribleplan** [StackExchange/dnscontrol#2489]
**Describe the bug**

**To Reproduce**
1. Use axfrddns provider
2. Have a TXT record longer than 255 bytes, such as a long DKIM key.
3. Try to `dnscontrol push`

**Expected behavior**
The value is able to be written.

**DNS Provider**
 - AXFRDDNS

**Additional context**
Possibly caused by something similar to the issue with #2447 / #2435, as those exhibited the same problem but for the BIND provider. Dnscontrol thinks that record needs updated even though it has not changed (e.g. when switching back and forth between BIND and AXFRDDNS providers).

For now I am working around this issue using a compiled from source version of dnscontrol (as the fix for BIND is not yet released) and manually updating zone files, but ideally want to make this work without having to manage those files.

**Comment by yoshz** [comment]
Have the same problem with DigitalOcean. The TXT record is split in 2 quoted strings and is compared to a single quoted string which always results in a change is detected.

**Comment by terribleplan** [comment]
As a temporary workaround I am using this helper function to automatically split my TXT records:

```
function SPLIT_TXT(name, contents) {
  return TXT(name, contents.match(/.{255}|.{1,254}/g));
}
```

Sharing here in case anyone has the same problem and this helps.

**Comment by tlimoncelli** [comment]
CC @hnrgrgr (the maintainer of this provider)

Could you please take a look?

@yoshz Can you file a separate bug for DigitalOcean?  I'd like to work on this.

**Comment by tlimoncelli** [comment]
@yoshz and @hnrgrgr :  The TXT record handling has been rewritten in v4.7.x.  I have a Digital Ocean test account and can verify that works.  However I don't have an AXFRDDNS test environment, so I'll have to ask you to test that. Please let me know if it works.

**Comment by fritterhoff** [comment]
Hi,

We are using the latest version in our environment. so far everything looks fine. Is there anything special I should check?

**Comment by tlimoncelli** [comment]
@fritterhoff

The best thing to do is:

```
cd integrationTest
go test -v -verbose -provider AXFRDDNS
```

All tests should pass.  Tests 17 and 18 in particular test the limits of what a TXT record can do.

**Comment by pepiyox90** [comment]
****

**Comment by fritterhoff** [comment]
Hi @tlimoncelli

mhmmmm... we are actually running the latest versions against our production environment. Before Version 4.7 we noticed some bugs regarding long TXT records they are gone now ...

**Comment by tlimoncelli** [comment]
I believe this is fixed in v4.7 or later.  Could someone please run the [integration tests](https://docs.dnscontrol.org/developer-info/integration-tests) on the latest branch?  Thanks!

@hnrgrgr @terribleplan @fritterhoff

**Comment by fritterhoff** [comment]
I'll try to add a test domain in our environment. Currently we only use dnscontrol for plenty domains.

**Comment by terribleplan** [comment]
I am not in a position to run integration tests, but can confirm it working for my actual domains using version 4.7.3.

**Comment by tlimoncelli** [comment]
Thanks!
