### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by Deraen** [StackExchange/dnscontrol#249]
I just noticed Github has support for CODEOWNERS file: https://help.github.com/articles/about-codeowners/

I think this would be good place to document the [maintainers](https://github.com/StackExchange/dnscontrol/blob/master/docs/provider-list.md#providers-with-contributor-support) for different provides, and the owners get notifcations about PRs touching configured files.

e.g.

```
providers/digitalocean/* @Deraen
```

**Comment by tlimoncelli** [comment]
Good idea!

Fixed in fea1d7afff66d850e40cbda744f5fd54ce1223a5
