### ISSUE TITLE
Add no color flag option for output 

### ISSUE THREAD

**Issue by adamus1red** [StackExchange/dnscontrol#2499]
**Is your feature request related to a problem? Please describe.**
When running dnscontrol I would like to force it to not output any color

**Describe the solution you'd like**
an additional command line flag i.e. `--no-color` 

**Describe alternatives you've considered**
Currently for a CI process we have an additional job step to strip out ANSI color characters

**Additional context**

Before
![image](https://github.com/StackExchange/dnscontrol/assets/2502582/fa7af2f0-1497-4158-a44f-032ba3383baa)

After
![image](https://github.com/StackExchange/dnscontrol/assets/2502582/5cb4c061-b215-4a05-a907-f2fc71d208a9)

**Comment by cafferata** [comment]
This would also be a nice addition for the [Notifications](https://docs.dnscontrol.org/advanced-features/notifications).

In the current situation

```shell
dnscontrol push --domains=jcid.nl --notify
```
```shell
[INFO: Diff2 algorithm in use. Welcome to the future!]
******************** Domain: jcid.nl
1 correction (transip)
#1: + CREATE dnscontrol-slack-notificatie.jcid.nl A 1.2.3.4 ttl=86400
SUCCESS!
Done. 1 corrections.
```

<img width="1000" alt="DNSControl Slack notification" src="https://github.com/StackExchange/dnscontrol/assets/1150425/d16872b2-bb64-464a-9eb1-f99acff43a1e">

**Comment by costasd** [comment]
Pushed a PR for this - unfortunately I don't have access to a notification setup right now to test that part as well, it should work the same way though.

@cafferata could you check it in your setup if/when possible? Thanks!

**Comment by costasd** [comment]
Just for completeness, there's already a disable-via-env-variable mechanism (see below) but thought providing a cmd option would be helpful.

 https://github.com/StackExchange/dnscontrol/blob/1d9646d4ff2f9ca7313cb558674d6c5d2ad54f9b/main.go#L30-L32

**Comment by cafferata** [comment]
@costasd seems fine to me!

```shell
~/go/bin/dnscontrol --no-colors preview --domains=jcid.nl --notify
```

```shell
~/go/bin/dnscontrol --no-colors push --domains=jcid.nl --notify
```

<img width="932" alt="Screenshot 2023-08-11 at 15 36 57" src="https://github.com/StackExchange/dnscontrol/assets/1150425/ac922448-2ef0-4666-8bd7-fcdb25fb8563">

**Comment by cafferata** [comment]
@costasd thanks for your suggestions. I'm wondering, in which case would a notification want colors? I think: never. 🤷🏼‍♂️ So the current `--no-colors` option would be good for the local CLI and a hard coded solution where `color.NoColor = false` is applied when it comes to the notification output? Maybe something like that?

**Comment by costasd** [comment]
> Just for completeness, there's already a disable-via-env-variable mechanism (see below) but thought providing a cmd option would be helpful.
> 
> https://github.com/StackExchange/dnscontrol/blob/1d9646d4ff2f9ca7313cb558674d6c5d2ad54f9b/main.go#L30-L32

FWIW - the env variable mentioned here proved to be a noop (ie. colors are on by default, and the variable took care to ensure they're on), so it's removed completely in the PR above. 

Given it was single-state (ie. just enabling colors) and colors being by default enabled, removing it is backwards compatible.

**Comment by costasd** [comment]
> @costasd thanks for your suggestions. I'm wondering, in which case would a notification want colors? I think: never. 🤷🏼‍♂️ So the current `--no-colors` option would be good for the local CLI and a hard coded solution where `color.NoColor = false` is applied when it comes to the notification output? Maybe something like that?

hmm, I think you're right, especially given these colors we're talking about are ANSI codes. It's not that our current notifications really parse them.

I'll see if I can think of anything more flexible, otherwise I'll do a different PR to disable colors in notifications, after I configure some notifications myself :)
