### ISSUE TITLE
Standardize IPv6 Format

### ISSUE THREAD

**Issue by captncraig** [StackExchange/dnscontrol#25]
If I make a AAAA record: `AAAA("@","2001:0db8:85a3:0000:0000:8a2e:0370:7334"),` I can create it in gcloud no problem.

I do always get a modification though: `MODIFY AAAA example5555qwerty.com: (2001:db8:85a3::8a2e:370:7334 300) -> (2001:0db8:85a3:0000:0000:8a2e:0370:7334 300)`

Because gcloud stores and returns it in the minified format. I propose as part of the validation/normalization phase, we minimize all ipv6 addresses. That will become our "standard" format. If any provider has issue with that, we will handle it in the provider itself.

**Comment by tlimoncelli** [comment]
I believe that if we minified the IPv6 addresses at the validation/normalization step,  then future API calls will do the right thing. It is just dumb luck, but I think it will work.

Can someone with a domain on gcloud test to see if c15c9487f6150769ce1ee69aad28835761e91213 fixes the problem?

**Comment by tlimoncelli** [comment]
Fixed in 6a80f71d667ff4bad6ab576c3ba7c4ca7ab9d46d
