### ISSUE TITLE
Should providers be case preserving?

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#250]
Some providers are case-preserving, others are not.  We ignore the issue.

For example, this test would fail for BIND, ROUTE53 (and I haven't tried others)

integrationTest/integration_test.go

```
+               // Case preserving
+               tc("Empty"),
+               tc("Create an A record", a("foo", "1.1.1.1")),
+               tc("Upcase", a("FOO", "1.2.3.4")),
+               tc("Downcase", a("foo", "1.2.3.4")),
+               tc("Upcase2", a("FOO", "1.2.3.4")),
```

We could:

* Ignore this issue. Who uses upper case in dns anyway?
* Downcase all labels at the provider and in dnsconfig.js
* Add this test, add a capability to designate not  preserved, preserved, preserved but our code is broken

**Comment by pmoroney** [comment]
My vote is to downcase all labels. Should we be doing that when we convert unicode domains to ascii?

Name.com accepts any case, but returns only lowercase ascii domains.

**Comment by captncraig** [comment]
I agree. A case change should never generate a correction imo. 

The only exception I can see is maybe we want to enforce all lower case labels, and actively change them to match if a provider has preserved an upper case varriant. I could see that leading to irreconcilable differences though, if a provider "accepts" a case change and doesn't actually change it internally.

So I vote lower case on both ends, and write tests to make sure we are. I think the diff code can take care of it without making other code work around it.

**Comment by captncraig** [comment]
The only way I can think of for a provider to really screw that up is if they require the exact same casing again to make a change. 

So if you create a record at `Foo`, an update to `foo` would fail or something. I'd consider that a provider bug. I'm not actually sure how we could test that consistently if we started doing case insensitive matching.

**Comment by haraldkoch** [comment]
The DNS is officially case-insensitive; however, there's a discussion, with references, about case _**preservation**_ in the DNS in RFC 4343 (https://tools.ietf.org/html/rfc4343).

**Comment by tlimoncelli** [comment]
Ok, I'm convinced that we should downcase the label and the targets (when they are hosts, of course).

dnscontrol is an opinionated system and I would consider "we downcase everything / dns should be  all lowercase... for languages that have such a concept" to be one of those opinions.  We should downcase labels/targets in dnsconfig.js and use case insensitive comparisons in our diff'ing code.  (Most of that is all true already... I just want to codify it in the documentation.)

**Comment by TomOnTime** [comment]
First cut of implementing this is https://github.com/StackExchange/dnscontrol/pull/253

**Comment by tlimoncelli** [comment]
This is now implemented. Thanks for all the suggestions!
