### ISSUE TITLE
Support RR() in dnsconfig.js

### ISSUE THREAD

**Issue by thorduri** [StackExchange/dnscontrol#252]
Relating to #91 

It would be very useful if `dnscontrol` supported a _I know what I'm doing_ function in it's DSL.

I currently have a very hack-ish implementation of an `RR()` function, that takes a literal `RR`, 
parsable by [`dns.NewRR()`](https://godoc.org/github.com/miekg/dns#NewRR) that then populates a `RecordConfig` prior to passing the result down to a provider.

Essentially it is short circuiting [`func (rc *RecordConfig) ToRR() dns.RR { ... }`](https://github.com/StackExchange/dnscontrol/blob/eafc18a77e77376ab353bd242932ae9082441596/models/dns.go#L161) allowing an operator to pass something similar to:

```
var REG_NONE = NewRegistrar('none','NONE');
var PROVIDER = NewDnsProvider("gcloud", "GCLOUD");

D('example.com', REG_NONE, DnsProvider(PROVIDER),

  RR('rr.example.com.  300 IN TXT "very long string that the operator has verified will work with all providers registered")
);
```

Currently it only verifies that the shortname, and fqdn of the RR matches the domain context, other then that it completely depends on the `dns` package for validation of the RR.

Is this something `dnscontrol` should support ?

**Comment by thorduri** [comment]
I've tested a single case with three providers: `bind`, `google` and `route53`.  The objective of the entire exercise was to allow for `TXT` records on `dkim` with large keys (> 1024).

This however might be generally useful for RRs that `dnscontrol` does not directly support but are parsable by `dns.NewRR()` -- how useful that is in the long run is up for debate.

**Comment by tlimoncelli** [comment]
My concern is that not all providers can take a generic rType.  This would have to be a "capability" that providers opt in to, so that if someone switches DNS Provider to one that doesn't support it, dnscontrol can warn early on.

**Comment by tlimoncelli** [comment]
(So... yes, please continue with this PR.)

**Comment by captncraig** [comment]
I guess I'm still confused why current functionality is inadequate.  We should support very long TXT records if they are valid. I get uncomfortable when we start adding workarounds to vaguely specified problems. Can you provide a config that fails or a specific zone file you are unable to generate with the  dnscontrol?

**Comment by jeanpaulgalea** [comment]
@captncraig The following `TXT` record is accepted by dnscontrol, but as @tlimoncelli said, it's not split up in chunks of max 255 chars.

The following is a 2048 bit DKIM key loaded in dnscontrol:
```
TXT("google._domainkey", "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnKZogtjOlHoeY8iZ5o5brlPOsj/a2Q9Bopu1kHxlxrdw7tZVL9FzUMngiIYGrl8dbP7Rvk7TLMoxHxVkRZPBtIpsKIab/gOUoPLQVYbrAmzyguHYBwAApi3H/pvjUsK8+XF0dKY17AR96lokAPqvfBaUb+DSx8zNw2hrYWYVqvCtnxHUGEUhT1bTlEZBptH3jJdQ/qm/HROSj3WQn55D8lyQMO8hHml0r15sNYSg8nInFmOhl2JmbsFKy+RoMTwbkk0/meRvcEFWLHkr4MSgbnie6OpQvM4Y51+kO6DUVr3rwjrdVO9wpFt+n/hdQ92TNif17RMJtE5AGaQ6BN3yJQIDAQAB;")
```

NSD throws an error when we try to load the zone as generated by the "BIND" provider. The TXT record is rendered as follows:
```
IN TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnKZogtjOlHoeY8iZ5o5brlPOsj/a2Q9Bopu1kHxlxrdw7tZVL9FzUMngiIYGrl8dbP7Rvk7TLMoxHxVkRZPBtIpsKIab/gOUoPLQVYbrAmzyguHYBwAApi3H/pvjUsK8+XF0dKY17AR96lokAPqvfBaUb+DSx8zNw2hrYWYVqvCtnxHUGEUhT1bTlEZBptH3jJdQ/qm/HROSj3WQn55D8lyQMO8hHml0r15sNYSg8nInFmOhl2JmbsFKy+RoMTwbkk0/meRvcEFWLHkr4MSgbnie6OpQvM4Y51+kO6DUVr3rwjrdVO9wpFt+n/hdQ92TNif17RMJtE5AGaQ6BN3yJQIDAQAB;"
``` 
However, NSD accepts the record/zone if it is mangled likewise:
```
IN TXT ( "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnKZogtjOlHoeY8iZ5o5brlPOsj/a2Q9Bopu1kHxlxrdw7tZVL9FzUMngiIYGrl8dbP7Rvk7TLMoxHxVkRZPBtIpsKIab/gOUoPLQVYbrAmzyguHYBwAApi3H/pvjUsK8+XF0dKY17AR96lokAPqvfBaUb+DSx8zNw2hrYWYVqvCtnxHUGEUhT1bTlEZBptH3j" "JdQ/qm/HROSj3WQn55D8lyQMO8hHml0r15sNYSg8nInFmOhl2JmbsFKy+RoMTwbkk0/meRvcEFWLHkr4MSgbnie6OpQvM4Y51+kO6DUVr3rwjrdVO9wpFt+n/hdQ92TNif17RMJtE5AGaQ6BN3yJQIDAQAB;" )
``` 

This [page](https://kb.isc.org/article/AA-00356/0/Can-I-have-a-TXT-or-SPF-record-longer-than-255-characters.html) expands further on the issue.

@thorduri  and I ran into similar issues with GLOUD, where the API returned [invalidValue](https://cloud.google.com/dns/troubleshooting#invalidvalue)

I believe we can provide you with these examples later next week;

1) API calls which dnscontrol issues toward GCLOUD & ROUTE53 with the above `TXT` record.

2) API calls modified by us to get GCLOUD & ROUTE53 to accept our `TXT` record.

As a side note, I was a bit surprised that no one else had run into this issue yet. [G-Suite](https://support.google.com/a/answer/174126) defaults to 2048-bit DKIM keys, though it's possible to manually select 1024 (which normally gets you a TXT <255 chars).

**Comment by tlimoncelli** [comment]
The root problem here is that we need to provide a way to have multiple strings in a TXT record. Why don't we fix that?

I've created an issue to discuss doing just that:

* TXT() should support multiple strings https://github.com/StackExchange/dnscontrol/issues/260

**Comment by tlimoncelli** [comment]
Closing this, since #260 is the right way to fix this.
