### ISSUE TITLE
Support provider: INWX

### ISSUE THREAD

**Issue by axel-rutz** [StackExchange/dnscontrol#254]
Internetworx is a berlin-located provider with good API support:

- https://www.inwx.de/en/offer/api
- https://github.com/andrexus/goinwx

**Comment by axel-rutz** [comment]
I'm not firm at coding go but can provide testing.

**Comment by tlimoncelli** [comment]
Hopefully we can find a volunteer.

By the way... we've made it very easy to add providers.  In fact, many people have created a provider as their first Go program.
https://everythingsysadmin.com/2017/08/go-get-up-to-speed.html

If you are interested, I'd be willing to mentor you here or in private email.

**Comment by tlimoncelli** [comment]
I've noted this  in 2e61c835110911a34810678b1ca94807a45ca04d.  If someone starts working on this, please re-open this issue.  See https://stackexchange.github.io/dnscontrol/provider-list

**Comment by svenpeter42** [comment]
I've started working on inwx support.

**Comment by patschi** [comment]
Thanks to @svenpeter42 this can now be closed I guess, @tlimoncelli? (Because it's listed under "Providers" in the docs otherwise)

**Comment by svenpeter42** [comment]
I think the issue is already closed but maybe I forgot to remove INWX from the list of requested providers, I can take a look later this week.

**Comment by tlimoncelli** [comment]
I forgot tot remove the provider-request tag.  Should be all good now.

I'm having a busy week but I hope to do a new release next week.  Sadly the website docs are based on master, not the latest release.
