### ISSUE TITLE
dnscontrol push ends with an error when the --report option is not used

### ISSUE THREAD

**Issue by riku22** [StackExchange/dnscontrol#2559]
Hello.

When the `--report` option is not used, `dnscontrol push` displays the following error and exits with exit code 1.

`open : no such file or directory`

Is dnscontrol trying to write something to a file even though it doesn't need to output a report?

P.S: I started getting this error after updating dnscontrol to 4.4.0.
Also, I have confirmed that if I specify an appropriate file for `--report`, it ends normally.

Sincerely.

**Comment by imlonghao** [comment]
My CI also broken with exit 1 after upgrade to v4.4.0

`open : no such file or directory`

**Comment by biodrone** [comment]
Can confirm this is also happening for me, everything up to `push` works fine, then it errors out even after completing all required updates.
