### ISSUE TITLE
slices.Compact

### ISSUE THREAD

**Issue by Deleplace** [StackExchange/dnscontrol#2564]
Hello, while researching for [this Go proposal](https://github.com/golang/go/issues/62729) I noticed [this code](https://github.com/StackExchange/dnscontrol/blob/fa890063a18fb97470b1b4b47318e016bc2b5b85/pkg/normalize/validate.go#L625):

```
slices.Compact(labels)
```

which probably doesn't behave as intended and should look like this instead:

```
labels = slices.Compact(labels)
```

I have not tried to execute it.

**Comment by tlimoncelli** [comment]
Interestingly enough... there's no need to compact `labels`.  The items in `labels` come from map keys, which are by definition unique.

That said... this is an opportunity to clean up some of the code.  Thanks for pointing this out!

**Comment by Deleplace** [comment]
You may consider [golang.org/x/exp/maps.Keys](https://pkg.go.dev/golang.org/x/exp/maps#Keys), which is handy.

For other interesting reasons, `map.Keys` is not yet part of the stdlib.
