### ISSUE TITLE
TransIP test domain about to expire

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#2578]
Hey @blackshadev

Please renew the domain dnscontrol.zone.

The (test) domain 'dnscontrol.zone' will expire on October 30. I suspect that with this the DNSControl Bring-Your-Own-Secrets for TransIP will no longer work.

Thanks
Tom

CC: @cafferata

**Comment by blackshadev** [comment]
I am not the domain holder of dnscontrol.zone
I think it is @cafferata.

Also I will be on honeymoon from today until the 18th. So I won't be able to reply much in that time.

**Comment by tlimoncelli** [comment]
Hi there!

Sorry for interrupting your honeymoon!  May your marriage bring you much happiness!   (Now stop reading email and enjoy yourselves!)

**Comment by tlimoncelli** [comment]
@cafferata : Sorry... I forgot who has registered it.  Would you mind renewing the domain?

Does TransIP has the ability to maintain a domain that isn't registered? (google dns, route53, and others do).  That would save $ and not require any renewal "paper"work each year.

Tom

**Comment by cafferata** [comment]
> Sorry... I forgot who has registered it. 

No problem, you previously stated that you did not want to use the domein `dnscontrol.zone` for documentation.

> https://github.com/StackExchange/dnscontrol/pull/1809#issuecomment-1325623247:
> The URL should be https://docs.dnscontrol.org/. I'd like to keep everything in one domain.

That is why a cancellation has been requested.

> Does TransIP has the ability to maintain a domain that isn't registered?

No unfortunately not.

> Would you mind renewing the domain?

I have registered a cheaper (€ 0,49 versus € 43,50) domain `dnscontrol.nl`. So by changing de GitHub environment variable `TRANSIP_DOMAIN` you're ready for next year(s).

```diff
-TRANSIP_DOMAIN: 'dnscontrol.zone'
+TRANSIP_DOMAIN: 'dnscontrol.nl'
```

**Comment by cafferata** [comment]
Hi @tlimoncelli! 👋 Were you successful in changing the domain name? If not, I'd love to hear how I can help.

**Comment by tlimoncelli** [comment]
Yup!  Thanks for registering it.  We're all set up, and TransIP is now back in the list of automatically tested providers.

Thanks!
Tom

**Comment by cafferata** [comment]
@tlimoncelli thanks for this feedback. Don't forget to close the GitHub issue. ☺️
