### ISSUE TITLE
error with convertzone build

### ISSUE THREAD

**Issue by MattTunny** [StackExchange/dnscontrol#258]
Hey guys,

I'm still new at Go, I can build the main dnscontrol no problems but when i try build ./cmd/convertzone it fails.

following doco: https://github.com/StackExchange/dnscontrol/blob/master/cmd/convertzone/README.md

```
$ cd cmd/convertzone
$ go build
$ cp convertzone ~/bin/.
```

give me this:
```
main.go:27:2: cannot find package "github.com/miekg/dns" in any of:
        /usr/local/go/src/github.com/miekg/dns (from $GOROOT)
        /Users/matthew.tunny/go/src/github.com/miekg/dns (from $GOPATH)
main.go:28:2: cannot find package "github.com/miekg/dns/dnsutil" in any of:
        /usr/local/go/src/github.com/miekg/dns/dnsutil (from $GOROOT)
        /Users/matthew.tunny/go/src/github.com/miekg/dns/dnsutil (from $GOPATH)
main.go:29:2: cannot find package "github.com/pkg/errors" in any of:
        /usr/local/go/src/github.com/pkg/errors (from $GOROOT)
        /Users/matthew.tunny/go/src/github.com/pkg/errors (from $GOPATH)
```

its probably something i'm doing wrong?

**Comment by MattTunny** [comment]
found the issue: https://golang.org/doc/code.html

i was working from my normal github directory, had to be in
`/Users/matthew.tunny/go/src/github.com/StackExchange/dnscontrol/cmd/convertzone`

**Comment by captncraig** [comment]
Yeah, the convertzone utility should not be separate like that anymore. We refactored the main cli, and we mean to move it into the main dnscontrol as a sub-command, but haven't gotten around to it yet. See #204
