### ISSUE TITLE
GCORE TXT spf double quoted

### ISSUE THREAD

**Issue by WladyX** [StackExchange/dnscontrol#2591]
**Describe the bug**
GCORE provide has a problem with double quoting the TXT for spf

**To Reproduce**
```
	SPF_BUILDER({
		label: "@",
		overflow: "_spf%d",
		raw: "_rawspf",
		ttl: "5m",
		parts: [
			"v=spf1",
			"ip4:xxx.xxx.xxx.xxx", // ny-mail*
			"~all"
		]
	}),
```
produces:
```
❯ dig TXT mydomain.com @ns1.gcorelabs.net. +short
"\"v=spf1 ip4:xxx.xxx.xxx.xxx ~all\""
```
**Expected behavior**
SPF should be:
"v=spf1 ip4:xxx.xxx.xxx.xxx ~all"
for desec works expected

**DNS Provider**
GCORE

**Comment by tlimoncelli** [comment]
Hi @xddxdd please take a look.

**Comment by xddxdd** [comment]
Please try the fix from my PR: https://github.com/StackExchange/dnscontrol/pull/2592

**Comment by WladyX** [comment]
I use the docker image, I am not familiar with github (actions) that much, i presume no image was build for your PR, right?
Any easy ways to test your PR, like a container/already built binary? 
Thank you for your support,
Vlad

**Comment by tlimoncelli** [comment]
@WladyX the change was merged, so the best way to test it would be to build from master:

You'll need Go and Git installed on your machine:

```
git clone https://github.com/StackExchange/dnscontrol.git
cd dnscontrol
go build
```

You will now have a file called "dnscontrol" in your current directory.

**Comment by WladyX** [comment]
@tlimoncelli & @xddxdd Thank you both for the super fast support and pointers!
Tested and works as expected.
Closing!
