### ISSUE TITLE
CLOUDFLARE PAGE_RULE no-op changes

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#2597]
NOTE: Have a general question?  You'll get a better response on the [dnscontrol-discuss](https://groups.google.com/g/dnscontrol-discuss) email list!

**Describe the bug**
The CLOUDFLARE provider sometimes rewrites pagerules needlessly.

**To Reproduce**

```
******************** Domain: stackexchange.com
2 corrections (cloudflare_main)
#1: ± MODIFY stackexchange.com PAGE_RULE (https://meta.beer.stackexchange.com/*,https://alcohol.meta.stackexchange.com/$1,8,302 ttl=1) -> (https://meta.beer.stackexchange.com/*,https://alcohol.meta.stackexchange.com/$1,9,302 ttl=1) id=243c42b3617407a38e7e992169e48733
#2: ± MODIFY stackexchange.com PAGE_RULE (https://meta.photography.stackexchange.com/*,https://photo.meta.stackexchange.com/$1,9,302 ttl=1) -> (https://meta.photography.stackexchange.com/*,https://photo.meta.stackexchange.com/$1,8,302 ttl=1) id=321ec15c54844bfab33e76423b535ed0
```

**Expected behavior**
The priority of these two rules was reversed for no reason. 

**DNS Provider**
 - CLOUDFLARE

**Additional context**
I suspect it could be:
* that `preprocessConfig()` is not respecting the priorities.
* that we are dependent on the order of a map's keys
* its just a fluke and won't happen again

CC @blackshadev (is this about ordering?) and @tresni (cloudflare maintainer)

**Comment by blackshadev** [comment]
It shouldn't be due to ordering, as it should leave most records except some (A, MX, CNAME) alone.

Have you tried by disabling the reordering, we introduced a flag to disable it right? That way you could know if it was caused by an unwanted side effect from the reordering

**Comment by tlimoncelli** [comment]
@blackshadev Good points.  Using `--disableordering` doesn't change anything. (which is good)

Another data point: It isn't flapping back and forth.

Hopefully it was a fluke. I'll watch it for the next week or two.

**Comment by tlimoncelli** [comment]
I haven't seen this happen again.  Closing for now.

Thanks for all the suggestions!
