### ISSUE TITLE
TXT() should support multiple strings

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#260]
TXT records can have multiple strings, each 255 len max.

Use cases:

```
TXT(label, "string-longer-than-255")    // Split every 255 bytes
TXT(label, "string255")
TXT(label, "string255", "string255", ...)  
```

Suggestions:

* We will need a capability for "multiple txt strings" and "splits long txt strings automatically"
* We'll need integration tests for both capabilities
* Our datastructures don't support the last case (multiple strings) but it should be easy to add to RecordConfig and helpers.js

Related issues:

* Multiple strings in RR value (from convertzone) cause parse failure https://github.com/StackExchange/dnscontrol/issues/91
* Support RR() in dnsconfig.js https://github.com/StackExchange/dnscontrol/issues/252

**Comment by rlustin** [comment]
I’m quite interested in this feature. Unfortunately I can’t use this tool without it…

Can I try to implement it @tlimoncelli?

I don’t know the codebase… where should I look in the code?

**Comment by tlimoncelli** [comment]
We  have a doc that walks you through the process: https://stackexchange.github.io/dnscontrol/adding-new-rtypes

My advice is that you extend TXT() to also accept a list  of strings:

```
TXT("label", "string"),  //  Old style
TXT("label", ["st",  "ri",  "ng", "s"]),   // New style
```

(TXT() is defined in  `dnscontrol/pkg/js/helpers.js`)

There is a struct called models.RecordConfig that stores a DNS rtype.  Currently the TXT string is stored in .Target.   I would add a field that stores the strings individually:

```
       TxtStrings    []string          `json:"-"`  // TXT
```

For backwards compatibility, I would join the strings and store them in .Target but ALSO store the  separate strings in .TxtStrings.   Each provider that actually supports multiple strings, would then  be modified to  ignore .Target and instead use  the data in .TxtStrings.

We can also add a "capability" that marks which providers support multiple strings.  We could output an error or warning if multiple strings are used by a provider that doesn't support it. (that kind of check  is in  `pkg/normalize/validate.go`

Please ask if you have any questions. I'd be glad to help!

**Comment by tlimoncelli** [comment]
Hey!  I  have some time today to work on this  a bit.  I don't  want to step on your toes, @rlustin.  If you've started,  could you  share your git branch?  Maybe we can collaborate a bit.

**Comment by tlimoncelli** [comment]
My intention was to learn enough Javascript to add it to helpers.js but I ended up doing the rest too. (Sorry if I took the fun parts.)

https://github.com/StackExchange/dnscontrol/pull/289

I think this is fairly complete for BIND. I'm not sure which DNS service providers also support TXT records with  multiple strings.

**Comment by tlimoncelli** [comment]
P.S. @rlustin Which provider are you using?

**Comment by rlustin** [comment]
Hey @tlimoncelli! Thanks for the detailed explanations. That’s well documented!

I haven’t had time to start… But I’m glad you’re almost done on this feature.
What can I do to help you? (if nothing, no worries, I’ll contribute on another feature)

P.S.: I’m mainly on Route 53. It supports TXT records with multiple strings.

**Comment by tlimoncelli** [comment]
Awesome!  Glad to help.

Could you test the branch and see what it would take to make the R53
provider support this?  It is probably a matter of looking at the API docs
and figuring out how to send all the strings.
-- 
Sent from Gmail Mobile

**Comment by rlustin** [comment]
@tlimoncelli I’ve just tested your branch, just adding `CanUseTXTMulti` capability to Route 53. It works well out of the box. The concatenated strings in`Target` field suits well with this provider API.

**Comment by tlimoncelli** [comment]
Ok. I'll give that a shot. 

(I'm  delaying merging this branch until I get  back to  work on Jan 3).

**Comment by tlimoncelli** [comment]
Hi @rlustin !  I'm testing Route53 with multiple txt strings in this branch: https://github.com/StackExchange/dnscontrol/tree/r53_txtmulti

Could you test it a bit before we merge it?   I'd like to know it works  in the real world.

@captncraig: I think I figured out why it works.  When I added support for TXTMulti, I updated dns.go's ToRR() function to do the right thing with TXT records.  Therefore, when route53Provider.go calls MergeToTarget(), the .Target becomes a string like:

       `"one" "two"  "three"`

(all three strings in one string... quoted correctly)

**Comment by rlustin** [comment]
@tlimoncelli your branch works well with Route53. 👌

Thanks!

**Comment by tlimoncelli** [comment]
Great!  I've merged it.

May you have many TXT records and many strings in the coming new year!

**Comment by rlustin** [comment]
Thanks 😄

**Comment by tlimoncelli** [comment]
Sadly this change broke a bunch of other providers.  I've reverted the change.

I'm working on fixing this in https://github.com/StackExchange/dnscontrol/tree/master_broken

**Comment by tlimoncelli** [comment]
I found and fixed problem. Here's the complete PR: https://github.com/StackExchange/dnscontrol/pull/293

The changes since the first (failed) release:

     git diff 534aef372924b8b03265c8df0ca15da9e1079f27  master_broken_mini

@captncraig and @rlustin: Please take another look.

**Comment by rlustin** [comment]
PR #293 works well with TXTMulti on Route53. I haven’t tested it with other providers.

**Comment by tlimoncelli** [comment]
It passes all our integration tests.  I'm declaring this complete!
