### ISSUE TITLE
INWX: Still does not work with more than a couple domains

### ISSUE THREAD

**Issue by schwarmco** [StackExchange/dnscontrol#2604]
Re-Opening https://github.com/StackExchange/dnscontrol/issues/2512

The provided hack with max-integer pagination doesn't work as the INWX API runs in a 504 Gateway Timeout (which is the main reason, developers implement pagination in the first place ;-) )

Like suggested before, the `fetchNameserverDomains`:
https://github.com/StackExchange/dnscontrol/blob/e859f535cd24612b24f0b302188a7fc3b3c18a10/providers/inwx/inwxProvider.go#L397-L411

 should walk the pagination recursively like here for example:
https://github.com/StackExchange/dnscontrol/blob/08afef7f7c2c34674525f729f1b41edb06aa1667/providers/dnsimple/dnsimpleProvider.go#L596-L614

**Comment by tlimoncelli** [comment]
CC @patschi

I just shipped v4.6.0 before I saw this.  I'll gladly ship a v4.6.1 with this fix.
