### ISSUE TITLE
PORKBUN: issues with nameserver for .DE domains when used as registrar

### ISSUE THREAD

**Issue by stefanwascoding** [StackExchange/dnscontrol#2623]
**Describe the bug**
When using Porkbun as a registrar, their default nameservers reported for .DE domains differ from the expected result, leading DNSControl to try to change them, but on the next run, they are still not the expected ones.

```
% dnscontrol push --domains example.de
******************** Domain: example.de
1 correction (porkbun)
#1: Update nameservers curitiba.ns.porkbun.com.,fortaleza.ns.porkbun.com.,maceio.ns.porkbun.com.,salvador.ns.porkbun.com. -> curitiba.ns.porkbun.com,fortaleza.ns.porkbun.com,maceio.ns.porkbun.com,salvador.ns.porkbun.com
SUCCESS!
Done. 1 corrections.
%  dnscontrol preview --domains example.de
******************** Domain: example.de
1 correction (porkbun)
#1: Update nameservers curitiba.ns.porkbun.com.,fortaleza.ns.porkbun.com.,maceio.ns.porkbun.com.,salvador.ns.porkbun.com. -> curitiba.ns.porkbun.com,fortaleza.ns.porkbun.com,maceio.ns.porkbun.com,salvador.ns.porkbun.com
Done. 1 corrections.
```

**To Reproduce**
1. Have a .DE domain & DNSControl settings for it that use Porkbun as registrar.
2. `dnscontrol push`
3. See that it updates the nameservers
4. `dnscontrol preview`
5. See that it would try to update nameservers again.

**Expected behavior**
For .DE domains to be handled without issue, when using Porkbun as Registrar (which should work, thanks to https://github.com/StackExchange/dnscontrol/pull/2542).

**DNS Provider & Registrar**
 - Porkbun

**Additional context**
I tried this with 4 different .DE domains I recently moved to Porkbun, all of them show the same issue. The non-.DE domains do not.
My current workaround is to not use `NewRegistrar("porkbun")` for the .DE domains.

When querying the Porkbun API directly for the nameservers, the responses differ for .DE and other TLDs (at least those I've tried):

.DE:
```
%  curl --silent -H "Content-type: application/json" 'https://porkbun.com/api/json/v3/domain/getNs/example.de' -d"{
  \"apikey\": \"${PORKBUN_API_KEY}\",
  \"secretapikey\": \"${PORKBUN_SECRET_KEY}\"
}"
{"status":"SUCCESS","ns":["curitiba.ns.porkbun.com.","fortaleza.ns.porkbun.com.","maceio.ns.porkbun.com.","salvador.ns.porkbun.com."]}%
```
Note the `.` at the end of each of those servers.

Some other TLD:
```
%  curl --silent -H "Content-type: application/json" 'https://porkbun.com/api/json/v3/domain/getNs/example.com' -d"{
  \"apikey\": \"${PORKBUN_API_KEY}\",
  \"secretapikey\": \"${PORKBUN_SECRET_KEY}\"
}"
{"status":"SUCCESS","ns":["curitiba.ns.porkbun.com","fortaleza.ns.porkbun.com","maceio.ns.porkbun.com","salvador.ns.porkbun.com"]}%
```
_No_ `.` at the end of each of those servers.

Even if I manually change the nameservers in the Porkbun Web UI to not include those `.`, they reappear immediately (so basically the same behaviour as using DNSControl). 

**Questions (I have)**
1. Considering that .DE returns FQDNs and other domain's do not ... is it even an issue with .DE domains? https://docs.dnscontrol.org/language-reference/domain-modifiers/nameserver seems to indicate that the trailing `.` is the correct way to go.
2. Should DNSControl handle both responses?
3. Is that even an issue for DNSControl, or should I contact Porkbun's support?  If so, does anyone have a technical contact there? Otherwise I would probably contact the support, and point them to this issue.

**Comment by tlimoncelli** [comment]
CC @imlonghao (maintainer of the porkbun provider)

**Comment by tlimoncelli** [comment]
Those nameservers are stored in `DomainConfig.Nameservers` without the trailing dot (`.`).

It is up to the provider code to do the right thing... removing or adding the dot as required.  For example, when receiving the list of nameservers from the API, if the API includes the trailing dot, the code should remove the dot before storing the value in `DomainConfig.Nameservers`.  When changing the nameservers via the API, the code should add the dot (if needed).

I'm surprised that a provider API would do different things for .DE domains.... but every API has surprises.

My suggestion is to update the code to strip the dot when receiving it:

```
strings.TrimSuffix(s, ".")  // Remove the trailing dot only if it exists. This provider seems to add the trailing dot to some domains but not others. The .DE domains seem to always include the dot, others don't.
```

Add the dot by using this function, which returns a []string of all the nameservers, with a trailing dot (TD):

```
models.ToNameserversStripTD(DomainConfig.Nameservers)
```

Hope that helps!

Tom

P.S.  More info here: https://github.com/StackExchange/dnscontrol/issues/491

**Comment by stefanwascoding** [comment]
Response from a Porkbun support engineer:

> DENIC, the registry that manages the .de TLD
has unique requirements for nameservers that differ from almost all
other TLDs which are most likely causing this. Most likely the
developer of DNSControl will need to specifically account for the
unique requirements of .de domains. You can read more about DENIC's
requirements on their nameserver documentation page:
https://www.denic.de/en/domains/de-domains/registration/nameserver-and-nsentry-data

**Comment by tlimoncelli** [comment]
Ah!  Thanks for reaching out to support!  Very useful!

Sounds like this is the right way to handle reading the NS records.
