### ISSUE TITLE
Nameserver selection

### ISSUE THREAD

**Issue by jeanpaulgalea** [StackExchange/dnscontrol#263]
Say we have something like the following:

 ```
DnsProvider(DNS_GCLOUD, 2), DnsProvider(DNS_R53, 2)
```

Meaning, use both GCP DNS and AWS R53 as DNS providers, while limiting each provider to maximum two NS RRs.

How is the nameserver selection performed? Are the first two returned by each provider selected? Is it random? Is there some way to influence this from `dnsconfig.js`?

What I'd like to achieve is to have maximum spread across TLDs.

GCP DNS uses `.com` for all its nameservers, while AWS R53 uses 4 distinct ones; `.com`,`.org`,`.net`,`.co.uk`.

How can we instruct `dnscontrol` to never pick the `.com` from `DNS_R53` ?

Meaning, we don't want to have zones with:

```
NS gcp1.com
NS gcp2.com
NS aws1.com
NS aws2.net
```

But rather:

```
NS gcp1.com
NS gcp2.com
NS aws2.net
NS aws3.org
```

Or:
```
NS gcp1.com
NS gcp2.com
NS aws2.net
NS aws4.co.uk
```

Or:
```
NS gcp1.com
NS gcp2.com
NS aws3.org
NS aws4.co.uk
```

**Comment by tlimoncelli** [comment]
Dnscontrol sorts the NS and picks th first n items.  It’s pretty simple.
If you want something more complex, specify zero and use NAMESERVER()
statements to hardcore what you want.

If you want to be able to specify something else, we’d love a PR.
-- 
Sent from Gmail Mobile

**Comment by jeanpaulgalea** [comment]
Thanks for the quick reply, Tom!

`NAMESERVER()` is a solution but not very practical especially when managing a large amount of zones. Unfortunately DNS providers don't make it easy, for example with GCP DNS, each zone might get a different set of nameservers (as opposed to NS RRs being unique for all zones within one provider).

Will try to see if we can come up with a PR - I'm pretty terrible with JS and not much better in Go, so we'll see how far we get. Would appreciate any suggestions where changes need to be made within the codebase or general thoughts on default selection algorithm and/or `dnsconfig.js` directives. Thanks!

**Comment by tlimoncelli** [comment]
My advice is in two parts:

1. Focus on what the ideal syntax would be.  Don’t worry about JS or Go for
now.  Figure out what you want the end goal to be.

2.  Think for a bit how much value this change would create.  How much
resilience is improved by having one .com and one .net NS?   If your users
are on WiFi, that only has 99.9% uptime.  Trying to achieve 99.999% in that
situation seems like a lot of effort for users that won’t appreciate it.
-- 
Sent from Gmail Mobile

**Comment by tlimoncelli** [comment]
@captncraig suggested that the smallest change that would fix this would be to not take the first n items, but to take items alternating from the front and end of the list. (if the NSs are a, b, c, d, e, f, then the selection would be the first n items in: a, f, b, e, c, d).  That would fix the problem and should be acceptable to all existing users. Therefore it wouldn't require any flags or switches to enable.

**Comment by captncraig** [comment]
Slight clarification on my proposed selection strategy:

1. Sort nameservers for each provider by reversed name. (so tlds get seperated)
2. Take from head and tail alternately until you have enough.

That would be pretty easy to sneak in a sort and a selection modification to [this code](https://github.com/StackExchange/dnscontrol/blob/master/pkg/nameservers/nameservers.go#L37). 

If you wanna make a pr, @jeanpaulgalea we'll probably take it.

**Comment by jeanpaulgalea** [comment]
Thanks for the input guys!

Am I going about this out correctly? (pretty late in my timezone... should really continue this tomorrow ;-)
```
-- list from api
aws1.com.
aws2.co.uk.
aws3.org.
aws4.net.

-- explode on dot and reverse column order
.com.aws1
.uk.co.aws2
.org.aws3
.net.aws4
```
```
-- list from api
gcp1.com.
gcp2.com.
gcp3.com.
gcp4.com.

-- explode on dot and reverse column order
.com.gcp1
.com.gcp2
.com.gcp3
.com.gcp4
```

Merge and sort
```
[a] .com.aws1
[b] .com.gcp1
[c] .com.gcp2
[d] .com.gcp3
[e] .com.gcp4
[f] .net.aws2
[g] .org.aws3
[h] .uk.co.aws4
```

Selection
```
[a] .com.aws1
[h] .uk.co.aws4
[b] .com.gcp1
[g] .org.aws3
```

It seems like it's not as trivial as initially thought, especially since we need to meet N for each `DnsProvider()`... above we have three from AWS and just one from GCP.

I'll have another go at it tomorrow, see if I can come up something better.

**Comment by tlimoncelli** [comment]
Dude, get some sleep.  :-)

Given the observations in https://blog.serverfault.com/2017/01/09/surviving-the-next-dns-attack/ it seems to me that if .com was down, 99% of the DNS servers in the world would swap out to a different NS very quickly.  Having some diversity in your TLDs is all that's required. It doesn't need to be perfect.

That said... if you really want to pursue this...

It looks like you're going to need to extract the data from each provider, process them, then extract the NSs you want.  Sort of like a ETL maneuver.

Extract them all into a list of struct { original, reversed string, source *blah}.  original is the original name. reversed is the ToLower() then reversed string (https://stackoverflow.com/questions/1752414), and source is some way of knowing what the original source was.  Then you can sort on reversed, then extract out the NSs that you want (original), and stop when you've filled each DNS provider's quota.

I highly recommend setting up unit tests.  We're going to have a lot of test cases to verify this all works as expected.

By the way.. I wouldn't explode on dot.  Just reverse the strings.  You'll get the same effect but the code will be more simple.

**Comment by captncraig** [comment]
The good news is, we already handle each dns provider seperately, so there is no merge step. It really is as simple as sorting the provider's list more sensibly before we select the first N to go into the master list.

**Comment by jeanpaulgalea** [comment]
@tlimoncelli agreed that the value of having nameservers on different TLDs is debatable. I primarily opened this ticket to figure out how much work is involved and whether it's something you'd want to have.

Below is working code in PHP (I know...). @captncraig  Is this what you had in mind for this [code](https://github.com/StackExchange/dnscontrol/blob/master/pkg/nameservers/nameservers.go#L37)? (obviously the Go equivalent of it).

It's not perfect, but might be easy enough to patch into that function without too much complexity and it should provide a better mix over picking the first n items.

```
<?php

function cmp($x, $y)
{
	return strcmp(strrev($x), strrev($y));
}

$a = array(
"aws1.com",
"aws2.org",
"aws3.net",
"aws4.co.uk",
"aws5.in",
"aws6.se",
"aws7.de",
"aws8.fr"
);

usort($a, "cmp");

/*
Array
(
    [0] => aws7.de
    [1] => aws6.se
    [2] => aws2.org
    [3] => aws4.co.uk
    [4] => aws1.com
    [5] => aws5.in
    [6] => aws8.fr
    [7] => aws3.net
)
*/
print_r($a);


/*
aws7.de
aws3.net
aws6.se
aws8.fr
*/
$nscount = 4;
for ($i=1; $i<=$nscount; $i++)
{
	if ($i & 1)
	{
		echo array_shift($a) . "\n";
	}
	else
	{
		echo array_pop($a) . "\n";
	}
}
```

**Comment by tlimoncelli** [comment]
Here's a much more simple algorithm:

```
Take all the nameservers from all the providers.   Store them
in a table that is:
index: reversed  normal   provider

table := []struct{ reversed, normal string; provider *models.DNSProviderConfig)

That would  look like this:

0: moc.swa.1sn ns1.aws.com aws
1: moc.swa.2sn ns2.aws.com aws
2: ten.swa.3sn ns3.aws.net aws
3: ten.swa.4sn ns4.aws.net aws
4: moc.duolcg.1sn ns1.gcloud.com gcloud
5: moc.duolcg.2sn ns2.gcloud.com gcloud
6: ten.duolcg.3sn ns3.gcloud.net gcloud
7: ten.duolcg.4sn ns4.gcloud.net gcloud

Now sort by the reversed column:

0: moc.duolcg.1sn ns1.gcloud.com gcloud
1: moc.duolcg.2sn ns2.gcloud.com gcloud
2: moc.swa.1sn ns1.aws.com aws
3: moc.swa.2sn ns2.aws.com aws
4: ten.duolcg.3sn ns3.gcloud.net gcloud
5: ten.duolcg.4sn ns4.gcloud.net gcloud
6: ten.swa.3sn ns3.aws.net aws
7: ten.swa.4sn ns4.aws.net aws

Now iterate over the list in the ping-pong pattern.   Take the first n of each provider.

i.e.  if the statement was:  DnsProvider(DNS_GCLOUD, 2), DnsProvider(DNS_R53, 1)

We would loop like:
  0:  counts[gcloud]++;  if counts[gcloud] < max[gcloud]: take it  TRUE
  7:  counts[aws]++;     if counts[aws] < max[aws]: take it        TRUE
  1:  counts[gcloud]++;  if counts[gcloud] < max[gcloud]: take it  TRUE
  6:  counts[aws]++;     if counts[aws] < max[aws]: take it        FALSE
  2:  counts[aws]++;     if counts[aws] < max[aws]: take it        FALSE
  5:  counts[gcloud]++;  if counts[gcloud] < max[gcloud]: take it  TRUE
  3:  counts[aws]++;     if counts[aws] < max[aws]: take it        FALSE
  4:  counts[gcloud]++;  if counts[gcloud] < max[gcloud]: take it  FALSE

Notice  that as each provider's count hits the max, we stop taking providers from it.

"max" in this case  is dc.DNSProviders[name].
```

**Comment by jeanpaulgalea** [comment]
@tlimoncelli I don't think I'll be spending time on this issue - the way it currently works is "good enough".

If you want to close the issue, please feel free to do so. Thanks!

**Comment by tlimoncelli** [comment]
Sounds good!

"The code with the least amount of bugs is the code you decide not to write."
