### ISSUE TITLE
Typo in 4.6.1 release notes (DNSIMPLE provider was renamed DNSMADEEASY)

### ISSUE THREAD

**Issue by onlyhavecans** [StackExchange/dnscontrol#2636]
The 4.6.1 release notes claim the following:

> The DNSIMPLE provider was renamed DNSMADEEASY to match their company name. Please update your dnsconfig.js files.

and

> DNSIMPLE provider was renamed DNSMADEEASY

DNSimple and DNS Made Easy are two separate companies and providers.
The provider renamed is DNSMADESIMPLE, not DNSIMPLE (hopefully)

**Comment by tlimoncelli** [comment]
Correction was sent in the next release.
