### ISSUE TITLE
NSONE: long TXT record causes "NS1 rejects domain mydomain.com: multiple strings in one txt"

### ISSUE THREAD

**Issue by Steltek** [StackExchange/dnscontrol#2641]
**Describe the bug**
Trying to migrate to dnscontrol so I had it get-zone from NS1 and one of my TXT records (the DKIM key to be exact) is pretty long (> 255 characters):

`        TXT("x._domainkey", "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv2sWy4Sh0FqjrPZBGXVST5lIn1lqad9T0bRM4Af+Y3STMY+5cSg4DItNKBtyYFF31bT+3Hm+uEjgxTlMuwDyv4bUN6r/VikosKoBJyY0c4YkZ1o3sgZTp6HPmEaw+6eEfhUZ6gMbZuuU9RHpJJ/ab6qo/+oJT6IlNqFbZhH3wLCR72yvwFVucclOb8EuI0YPhQS1ZbuAHxIrRuS2vXnPbH2bLdcRpGclMkhnnHQdRkX8gC5+l4d93kLbGgwPJudCaT5Jfaa5OGQzxT8QhTyOivyst9WOwxpNBIAjpNGD2U9p48vj4esDdDivj0WtjhnalJHx7Te5m//2GgKi4eoPIwIDAQAB", TTL(1800))`

dnscontrol does not seem to like this record and complains when I run preview or push:

`2023/11/21 19:44:53 printIR.go:113: ERROR: NS1 rejects domain mydomain.com: multiple strings in one txt
`

**Expected behavior**
NS1 does not seem to have an issue with this record when I enter it via the UI. Updating it via the API also returns no error. The following works without issue:

`curl -X POST -H "X-NSONE-Key: $NSO" https://api.nsone.net/v1/zones/mydomain.com/y._domainkey.mydomain.com/TXT -d '{"zone": "mydomain.com","domain": "y._domainkey.mydomain.com","type": "TXT", "answers": [{"answer": ["v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv2sWy4Sh0FqjrPZBGXVST5lIn1lqad9T0bRM4Af+Y3STMY+5cSg4DItNKBtyYFF31bT+3Hm+uEjgxTlMuwDyv4bUN6r/VikosKoBJyY0c4YkZ1o3sgZTp6HPmEaw+6eEfhUZ6gMbZuuU9RHpJJ/ab6qo/+oJT6IlNqFbZhH3wLCR72yvwFVucclOb8EuI0YPhQS1ZbuAHxIrRuS2vXnPbH2bLdcRpGclMkhnnHQdRkX8gC5+l4d93kLbGgwPJudCaT5Jfaa5OGQzxT8QhTyOivyst9WOwxpNBIAjpNGD2U9p48vj4esDdDivj0WtjhnalJHx7Te5m//2GgKi4eoPIwIDAQAB"]}]}'`

dnscontrol should accept this record.

**DNS Provider**
 - NSONE (ns1.com)

**Comment by costasd** [comment]
thank you, will take a look!

**Comment by costasd** [comment]
@Steltek I think I've found the issue. Would you mind adding also the dnscontrol version you've been experiencing this with, just to ensure I can reproduce it?

**Comment by Steltek** [comment]
> @Steltek I think I've found the issue. Would you mind adding also the dnscontrol version you've been experiencing this with, just to ensure I can reproduce it?

My bad for not including that. I'm running it through docker:

`dnscontrol "4.7.0" ("1d590a4b0478b7e03016f55a0321b7c5eaefcfeb") built 20 Nov 23 19:25 UTC`

**Comment by jhmckimm** [comment]
Also experiencing this with the Cloudflare DNS provider on `4.7.0`. My workaround for now is using `4.6.0`.

**Comment by tlimoncelli** [comment]
Hey folks!

Thank you for finding and reporting these issues!   (and fixing them!)

(Please remember that 4.7.0 is a pre-release, not an official release.  4.7.0 has a lot of changes to the TXT record handling and that could introduce a lot of bugs.  4.7.0 was announced as a "pre-release" to help find bugs.  4.7.1 (or later) will be a "real" release.  Thank you for suffering through finding and fixing these bugs. It's really helpful!)

**Comment by Steltek** [comment]
> > (Please remember that 4.7.0 is a pre-release, not an official release.
> 
> [...] I also definitely wouldn't be pointing `latest` to a pre-release version.

That is how I ended up with the stated pre-release version as the documentation merely states to use this:

`docker run --rm -it -v "$(pwd):/dns"  ghcr.io/stackexchange/dnscontrol preview`
_Source: https://docs.dnscontrol.org/getting-started/getting-started#docker_

I can confirm that the issue does not occur when I change the command to 

`docker run --rm -it -v "$(pwd):/dns"  ghcr.io/stackexchange/dnscontrol:4.6.1 preview`

**Comment by tlimoncelli** [comment]
Yeah, this was the first time I did a pre-release and I didn't realize all the downstream effects it would have.  My apologies.

Next time I'll put "beta" in the tag.  I'm not entirely sure how to get the container registry to not mark it as "latest" but I'll see what I can do.

**Comment by tlimoncelli** [comment]
@costasd: I don't have a test account on NS1.  Can you tell me if v4.7.2 runs all the integration tests cleanly?

**Comment by Steltek** [comment]
> @costasd: I don't have a test account on NS1. Can you tell me if v4.7.2 runs all the integration tests cleanly?

I don't know about integration tests, but running this works without the error message reported in this issue:
` docker run --rm -it -v "$(pwd):/dns"  ghcr.io/stackexchange/dnscontrol:4.7.2 preview
`

**Comment by costasd** [comment]
Apologies, was unreachable last week.

Integration tests pass on 4.7.2!

**Comment by tlimoncelli** [comment]
yay!  glad it's working now!
