### ISSUE TITLE
Support for Gandi LiveDNS API

### ISSUE THREAD

**Issue by drazzib** [StackExchange/dnscontrol#266]
Hi!

Since 2015, Gandi has launched a new _LiveDNS_ service which is based on a new [RESTful HTTP API](http://doc.livedns.gandi.net/). This new platform is production ready since december 2016 and will deprecate existing services in the long term.

From my understanding, current Gandi provider in **dnscontrol** uses the [older API, XMLRPC based](http://doc.rpc.gandi.net/overview.html), since it's depends on [gandi-api](https://github.com/prasmussen/gandi-api) project which, AFAIK, doesn't provide expected "livedns" endpoint.

New _LiveDNS_ platform has more features plus new gifts planned (automatic zone signing, new records including ALIAS, etc.)

It's REST based, so it should not be too much of a headache to implement

Regards,

**Comment by tlimoncelli** [comment]
Yes, the new API is different enough that we should consider this a new provider (GANDI2).  As we do with all new provider requests, we request someone  step  up  to volunteer to write the provider.

Do you know of any go libraries that implement the API?

**Comment by captncraig** [comment]
Closing issue, but can still be found on https://stackexchange.github.io/dnscontrol/provider-list. If anyone starts working on it, you can re-open this issue.

**Comment by drazzib** [comment]
Hi @tlimoncelli & @captncraig !

AFAIK, there is no go library that implement this new Gandi LiveDNS API.
So let's reopen this ticket once someone put enough effort to develop for this new API.

Regards,

**Comment by captncraig** [comment]
Is there any official deadline on if/when they will be depricating the older api?

**Comment by drazzib** [comment]
@captncraig AFAIK, there is no official mid-term statement from Gandi on deprecation / removal of XMLRPC API.
