### ISSUE TITLE
TRANSIP tests breaking

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#2670]
Tests were reactivated but I see a few tests are failing.  I did some basic triage but couldn't isolate the problem.

I've disabled the tests.  To re-activate them, set TRANSIP_DOMAIN to dnscontrol.nl in GHA.

```
$ cd ~/git/dnscontrol/integrationTest
$ go test  -provider TRANSIP -start 15 -end 15
--- FAIL: TestDNSProviders (2.54s)
    --- FAIL: TestDNSProviders/dnscontrol.nl (2.53s)
        --- FAIL: TestDNSProviders/dnscontrol.nl/15:MX:Record_pointing_to_@ (0.92s)
            integration_test.go:252: A hostname for a CNAME, NS, MX or SRV record was not found (external hostnames need a trailing dot, eg. "example.com."): foo 300 MX 8 dnscontrol.nl.
FAIL
exit status 1
FAIL	github.com/StackExchange/dnscontrol/v4/integrationTest	4.330s
$ 
```

CC @blackshadev @cafferata

**Comment by cafferata** [comment]
@tlimoncelli thanks for the mention. I'll leave this one to @blackshadev.

_P.S. There is a similar issue about failing integration tests: https://github.com/StackExchange/dnscontrol/issues/2330. Maybe it would be good to close one of the two issues?_

**Comment by blackshadev** [comment]
> oh wow! I forgot about #2330. Yes, let's keep that one and close this one.
> 
> If you'd like to pair on this, I could be available for a video conference / screen share session. (Even during the holidays)

If issues continue I would like that very much. But as far as I can see now, all tests were fixed more easily than I initially thought. When I started I also found my drive again. So it wasn't that bad at all ;)
