### ISSUE TITLE
CI/CD: Release changelog sections

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#2672]
I noticed that in the [v4.6.2](https://github.com/StackExchange/dnscontrol/releases/tag/v4.6.2) release changelog the "Other changes and improvements" section contains 50% of the "documentation" pull requests. Does it make sense to cut the changelog further into more/new sections?

I thought of:

```diff
Breaking changes:
Major features:
Provider specific changes:
Other changes and improvements:
Deprecation warnings:
+Documentation:
+CI/CD:
+Dependencies:
```

**Documentation**
I don't think this one needs any additional explanation.

**CI/CD:**
All work around GitHub Actions/Goreleaser.
Commits/pull requests like: https://github.com/StackExchange/dnscontrol/commit/51104ce775913aed6f9c8e69fd1973f7fe145c42

**Dependencies**
Commits/pull requests like: https://github.com/StackExchange/dnscontrol/commit/a653499655fe27d04e87782ffb40c5d565fa90d7 https://github.com/StackExchange/dnscontrol/commit/919b19eac3cb7a4554ce6655bf06c99da105f08e

With this I hope that the "Other changes and improvements" provides better insight into what actually changes within the DNSControl binary instead of the peripheral issues surrounding it. Of course I would like to prepare the different regex in a pull request. I would like to hear whether this is desired.

## Before

<details>
    <summary>Collapsed for a better issue overview.</summary>

### Major features:

* [37e2103](https://github.com/StackExchange/dnscontrol/commit/37e21030a21089b8989786caa0792fb7f349582a)\: NEW PROVIDER: Azure Private DNS Zones ([#2626](https://github.com/StackExchange/dnscontrol/pull/2626)) ([@matthewmgamble](https://github.com/matthewmgamble))

### Provider-specific changes:

* [fd413a9](https://github.com/StackExchange/dnscontrol/commit/fd413a9b08e578b7c8749e3b8895d162d5cf4f7d)\: AZURE_PRIVATE_DNS: GoReleaser provider-specific changelog regexp ([#2661](https://github.com/StackExchange/dnscontrol/pull/2661)) ([@cafferata](https://github.com/cafferata))
* [bf9e48d](https://github.com/StackExchange/dnscontrol/commit/bf9e48d06f522dfa8cd3449d71499f369a39838a)\: CLOUDFLARE: Update docs WRT domain creation ([#2648](https://github.com/StackExchange/dnscontrol/pull/2648)) ([@shodges-vermeer](https://github.com/shodges-vermeer))
* [d3112f5](https://github.com/StackExchange/dnscontrol/commit/d3112f53df84eb360539bf3c1cf0e272bfedbf01)\: HEXONET: Update GO-SDK dependency version from 3.5.5 to 3.5.6 ([#2667](https://github.com/StackExchange/dnscontrol/pull/2667)) ([@AsifNawaz-cnic](https://github.com/AsifNawaz-cnic))
* [1470144](https://github.com/StackExchange/dnscontrol/commit/1470144c29140cc5e930735c4bc642a5889a8e33)\: NS1: Downgrade ns1-go to 2.7.11 ([#2642](https://github.com/StackExchange/dnscontrol/pull/2642)) ([@costasd](https://github.com/costasd))
* [69fb3b2](https://github.com/StackExchange/dnscontrol/commit/69fb3b26d3f53bd1ebc9cc3034337f04c7c27c6b)\: OVH: Allow ovh provider to connect to other endpoints than EU ([#2625](https://github.com/StackExchange/dnscontrol/issues/2625)) ([#2651](https://github.com/StackExchange/dnscontrol/pull/2651)) ([@masterzen](https://github.com/masterzen))
* [e783d70](https://github.com/StackExchange/dnscontrol/commit/e783d7024cd62e29c46f4019e26d793e24c79e84)\: ROUTE53: Allow R53_ALIAS records to enable target health evaluation ([#2649](https://github.com/StackExchange/dnscontrol/pull/2649)) ([@jonathanbouvier](https://github.com/jonathanbouvier))
* [74a9e5e](https://github.com/StackExchange/dnscontrol/commit/74a9e5e8706085d810886033431405611361181d)\: ROUTE53: add R53_EVALUATE_TARGET_HEALTH to documentation summary ([#2659](https://github.com/StackExchange/dnscontrol/pull/2659)) ([@jonathanbouvier](https://github.com/jonathanbouvier))
* [88f007c](https://github.com/StackExchange/dnscontrol/commit/88f007cd1dca4587e8fffefc1c4e53da948a5bd8)\: ROUTE53: fix parameter type for R53_EVALUATE_TARGET_HEALTH ([#2658](https://github.com/StackExchange/dnscontrol/pull/2658)) ([@jonathanbouvier](https://github.com/jonathanbouvier))

### Other changes and improvements:

* [919b19e](https://github.com/StackExchange/dnscontrol/commit/919b19eac3cb7a4554ce6655bf06c99da105f08e)\: Build(deps): Bump github.com/go-jose/go-jose/v3 from 3.0.0 to 3.0.1 ([#2646](https://github.com/StackExchange/dnscontrol/pull/2646)) ([@dependabot](https://github.com/dependabot))
* [a653499](https://github.com/StackExchange/dnscontrol/commit/a653499655fe27d04e87782ffb40c5d565fa90d7)\: CHORE: Update deps ([#2668](https://github.com/StackExchange/dnscontrol/pull/2668)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [51104ce](https://github.com/StackExchange/dnscontrol/commit/51104ce775913aed6f9c8e69fd1973f7fe145c42)\: CICD: Use GHA concurrency groups to prevent tests from clobbering each other ([#2654](https://github.com/StackExchange/dnscontrol/pull/2654)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [c7065e6](https://github.com/StackExchange/dnscontrol/commit/c7065e67943e00ac412cc9adb6cc21fe7b1c9a60)\: DOCS: Expand integration tests explanation ([#2645](https://github.com/StackExchange/dnscontrol/pull/2645)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [a1e70c9](https://github.com/StackExchange/dnscontrol/commit/a1e70c93b9e995e27261812df251ba10b160201f)\: DOCS: Fix `R53_` broken links ([#2669](https://github.com/StackExchange/dnscontrol/pull/2669)) ([@cafferata](https://github.com/cafferata))
* [bc22690](https://github.com/StackExchange/dnscontrol/commit/bc22690fc1514f89edf1ba15019a982e18d73fe8)\: DOCS: Fixed providers with "contributor support" table. ([#2660](https://github.com/StackExchange/dnscontrol/pull/2660)) ([@cafferata](https://github.com/cafferata))
* [31cd4e1](https://github.com/StackExchange/dnscontrol/commit/31cd4e10a8903d3fc261f98cf41bf44955bdd914)\: DOCS: Fixed the broken provider `ClouDNS` link in the providers table ([#2663](https://github.com/StackExchange/dnscontrol/pull/2663)) ([@cafferata](https://github.com/cafferata))
* [9397eed](https://github.com/StackExchange/dnscontrol/commit/9397eed84b1e66fc2f35c5ce38d5979a770417ee)\: DOCS: Fixed the maintainer of provider `OPENSRS` ([#2662](https://github.com/StackExchange/dnscontrol/pull/2662)) ([@cafferata](https://github.com/cafferata))
* [b5010e7](https://github.com/StackExchange/dnscontrol/commit/b5010e7d9ca060029c4c5235a3476fcfc6e29e17)\: DOCS: Warn against common integration test mistake ([#2653](https://github.com/StackExchange/dnscontrol/pull/2653)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [4fc88aa](https://github.com/StackExchange/dnscontrol/commit/4fc88aa2dcd55bdc7f93d08b917bcd7810fe259e)\: RType AAAA: Add integration test for AAAA. ([#2647](https://github.com/StackExchange/dnscontrol/pull/2647)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [2ca9c84](https://github.com/StackExchange/dnscontrol/commit/2ca9c84dbea8069829191d82f2e5218863fd07c4)\: Unhide shell-completion flag ([#2640](https://github.com/StackExchange/dnscontrol/pull/2640)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [5b93f94](https://github.com/StackExchange/dnscontrol/commit/5b93f94ad64c88b4e53e2e31da05fab7826f00ff)\: Update docs and move Azure Private DNS to the "community support" list ([#2657](https://github.com/StackExchange/dnscontrol/pull/2657)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [df93135](https://github.com/StackExchange/dnscontrol/commit/df9313598dc8d293ea6cc76c6bfb8b773132bc2b)\: Update generated files for v4.6.2 ([@tlimoncelli](https://github.com/tlimoncelli))

</details>

## After

<details>
    <summary>Collapsed for a better issue overview.</summary>

### Major features:

* [37e2103](https://github.com/StackExchange/dnscontrol/commit/37e21030a21089b8989786caa0792fb7f349582a)\: NEW PROVIDER: Azure Private DNS Zones ([#2626](https://github.com/StackExchange/dnscontrol/pull/2626)) ([@matthewmgamble](https://github.com/matthewmgamble))

### Provider-specific changes:

* [bf9e48d](https://github.com/StackExchange/dnscontrol/commit/bf9e48d06f522dfa8cd3449d71499f369a39838a)\: CLOUDFLARE: Update docs WRT domain creation ([#2648](https://github.com/StackExchange/dnscontrol/pull/2648)) ([@shodges-vermeer](https://github.com/shodges-vermeer))
* [d3112f5](https://github.com/StackExchange/dnscontrol/commit/d3112f53df84eb360539bf3c1cf0e272bfedbf01)\: HEXONET: Update GO-SDK dependency version from 3.5.5 to 3.5.6 ([#2667](https://github.com/StackExchange/dnscontrol/pull/2667)) ([@AsifNawaz-cnic](https://github.com/AsifNawaz-cnic))
* [1470144](https://github.com/StackExchange/dnscontrol/commit/1470144c29140cc5e930735c4bc642a5889a8e33)\: NS1: Downgrade ns1-go to 2.7.11 ([#2642](https://github.com/StackExchange/dnscontrol/pull/2642)) ([@costasd](https://github.com/costasd))
* [69fb3b2](https://github.com/StackExchange/dnscontrol/commit/69fb3b26d3f53bd1ebc9cc3034337f04c7c27c6b)\: OVH: Allow ovh provider to connect to other endpoints than EU ([#2625](https://github.com/StackExchange/dnscontrol/issues/2625)) ([#2651](https://github.com/StackExchange/dnscontrol/pull/2651)) ([@masterzen](https://github.com/masterzen))
* [e783d70](https://github.com/StackExchange/dnscontrol/commit/e783d7024cd62e29c46f4019e26d793e24c79e84)\: ROUTE53: Allow R53_ALIAS records to enable target health evaluation ([#2649](https://github.com/StackExchange/dnscontrol/pull/2649)) ([@jonathanbouvier](https://github.com/jonathanbouvier))
* [74a9e5e](https://github.com/StackExchange/dnscontrol/commit/74a9e5e8706085d810886033431405611361181d)\: ROUTE53: add R53_EVALUATE_TARGET_HEALTH to documentation summary ([#2659](https://github.com/StackExchange/dnscontrol/pull/2659)) ([@jonathanbouvier](https://github.com/jonathanbouvier))
* [88f007c](https://github.com/StackExchange/dnscontrol/commit/88f007cd1dca4587e8fffefc1c4e53da948a5bd8)\: ROUTE53: fix parameter type for R53_EVALUATE_TARGET_HEALTH ([#2658](https://github.com/StackExchange/dnscontrol/pull/2658)) ([@jonathanbouvier](https://github.com/jonathanbouvier))

### Other changes and improvements:

* [4fc88aa](https://github.com/StackExchange/dnscontrol/commit/4fc88aa2dcd55bdc7f93d08b917bcd7810fe259e)\: RType AAAA: Add integration test for AAAA. ([#2647](https://github.com/StackExchange/dnscontrol/pull/2647)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [2ca9c84](https://github.com/StackExchange/dnscontrol/commit/2ca9c84dbea8069829191d82f2e5218863fd07c4)\: Unhide shell-completion flag ([#2640](https://github.com/StackExchange/dnscontrol/pull/2640)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [df93135](https://github.com/StackExchange/dnscontrol/commit/df9313598dc8d293ea6cc76c6bfb8b773132bc2b)\: Update generated files for v4.6.2 ([@tlimoncelli](https://github.com/tlimoncelli))

### Documentation:

* [c7065e6](https://github.com/StackExchange/dnscontrol/commit/c7065e67943e00ac412cc9adb6cc21fe7b1c9a60)\: DOCS: Expand integration tests explanation ([#2645](https://github.com/StackExchange/dnscontrol/pull/2645)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [a1e70c9](https://github.com/StackExchange/dnscontrol/commit/a1e70c93b9e995e27261812df251ba10b160201f)\: DOCS: Fix `R53_` broken links ([#2669](https://github.com/StackExchange/dnscontrol/pull/2669)) ([@cafferata](https://github.com/cafferata))
* [bc22690](https://github.com/StackExchange/dnscontrol/commit/bc22690fc1514f89edf1ba15019a982e18d73fe8)\: DOCS: Fixed providers with "contributor support" table. ([#2660](https://github.com/StackExchange/dnscontrol/pull/2660)) ([@cafferata](https://github.com/cafferata))
* [31cd4e1](https://github.com/StackExchange/dnscontrol/commit/31cd4e10a8903d3fc261f98cf41bf44955bdd914)\: DOCS: Fixed the broken provider `ClouDNS` link in the providers table ([#2663](https://github.com/StackExchange/dnscontrol/pull/2663)) ([@cafferata](https://github.com/cafferata))
* [9397eed](https://github.com/StackExchange/dnscontrol/commit/9397eed84b1e66fc2f35c5ce38d5979a770417ee)\: DOCS: Fixed the maintainer of provider `OPENSRS` ([#2662](https://github.com/StackExchange/dnscontrol/pull/2662)) ([@cafferata](https://github.com/cafferata))
* [b5010e7](https://github.com/StackExchange/dnscontrol/commit/b5010e7d9ca060029c4c5235a3476fcfc6e29e17)\: DOCS: Warn against common integration test mistake ([#2653](https://github.com/StackExchange/dnscontrol/pull/2653)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [5b93f94](https://github.com/StackExchange/dnscontrol/commit/5b93f94ad64c88b4e53e2e31da05fab7826f00ff)\: Update docs and move Azure Private DNS to the "community support" list ([#2657](https://github.com/StackExchange/dnscontrol/pull/2657)) ([@tlimoncelli](https://github.com/tlimoncelli))

### CI/CD:

* [51104ce](https://github.com/StackExchange/dnscontrol/commit/51104ce775913aed6f9c8e69fd1973f7fe145c42)\: CICD: Use GHA concurrency groups to prevent tests from clobbering each other ([#2654](https://github.com/StackExchange/dnscontrol/pull/2654)) ([@tlimoncelli](https://github.com/tlimoncelli))
* [fd413a9](https://github.com/StackExchange/dnscontrol/commit/fd413a9b08e578b7c8749e3b8895d162d5cf4f7d)\: AZURE_PRIVATE_DNS: GoReleaser provider-specific changelog regexp ([#2661](https://github.com/StackExchange/dnscontrol/pull/2661)) ([@cafferata](https://github.com/cafferata))

### Dependencies:

* [919b19e](https://github.com/StackExchange/dnscontrol/commit/919b19eac3cb7a4554ce6655bf06c99da105f08e)\: Build(deps): Bump github.com/go-jose/go-jose/v3 from 3.0.0 to 3.0.1 ([#2646](https://github.com/StackExchange/dnscontrol/pull/2646)) ([@dependabot](https://github.com/dependabot))
* [a653499](https://github.com/StackExchange/dnscontrol/commit/a653499655fe27d04e87782ffb40c5d565fa90d7)\: CHORE: Update deps ([#2668](https://github.com/StackExchange/dnscontrol/pull/2668)) ([@tlimoncelli](https://github.com/tlimoncelli))

</details>

**Comment by tlimoncelli** [comment]
Sounds good!

The template for PRs should tell people how to format their subject line so that GoReleaser makes a better first draft.

**Comment by Aartsie** [comment]
Sounds good, much easier to read!

**Comment by cafferata** [comment]
Thanks for the suggestion! I've described the release changelog section in the GitHub pull request template. 👍 See GitHub pull request including (external) regex tests 🤓 I have no experience with Go testing frameworks and didn't want to make the GoReleaser changelog sections pull request larger by setting up a testing framework. 🤷‍♂️
