### ISSUE TITLE
AKAMAIEDGEDNS: AKAMAICDN records unable to be added/modified

### ISSUE THREAD

**Issue by hallorans-nca** [StackExchange/dnscontrol#2680]
**Describe the bug**
The ability to update / add the AkAMAICDN record type stopped working with dnscontrol 4.1.1

**To Reproduce**
(In the output, I've anonymized the domain and edge hostname)
1. Add the following to a zone hosted on Akamai
```
AKAMAICDN('test-a','le2.testedge.edgekey.net',TTL(20)),
AKAMAICDN('test-b','le2.testedge.edgekey.net.',TTL(20)),
```
2. Push the zone to Akamai

You will get

```
#1: + CREATE AKAMAICDN test-a.testedge.com.au le2.testedge.edgekey.net.testedge.com.au ttl=20
FAILURE! recordset creation failed. error: Invalid Operation: [hostname 'le2.testedge.edgekey.net.testedge.com.au' is not allowed for AKAMAICDN]
#2: + CREATE AKAMAICDN test-b.testedge.com.au le2.testedge.edgekey.net. ttl=20
FAILURE! recordset creation failed. error: Invalid Operation: [hostname 'le2.testedge.edgekey.net.' is not allowed for AKAMAICDN]
```

**Expected behavior**
If you do the above with 4.1.0, the following will be returned

```
#1: + CREATE AKAMAICDN test-a.testedge.com.au le2.testedge.edgekey.net ttl=20
SUCCESS!
#2: + CREATE AKAMAICDN test-b.testedge.com.au le2.testedge.edgekey.net. ttl=20
FAILURE! recordset creation failed. error: Invalid Operation: [hostname 'le2.testedge.edgekey.net.' is not allowed for AKAMAICDN]
```
The FAILURE! for 2 here is expected, as the record data is an edge hostname (edge hostnames are not allowed to end in a . )

**DNS Provider**
AKAMAIEDGEDNS

**Additional context**
The change #2421 seems to have caused the issue.
In the function CanonicalizeTargets, the code is treating AkAMAICDN as having a potential shortname.
I think the AKAMAICDN should be treated more like a TXT/ALIAS record

**Comment by tlimoncelli** [comment]
CC @svernick (maintainer of the Akamai provider)

**Comment by svernick** [comment]
Sorry for the problem and thanks for the excellent information.  I'll look into this as quickly as I can.
