### ISSUE TITLE
NS1 Provider TXT records

### ISSUE THREAD

**Issue by bashgeek** [StackExchange/dnscontrol#269]
Hi there,
just tested an implementation - so far so good - but ran into issues with the NS1 implementation when it comes to TXT records. I tested a fairly simple SPF "v=spf1 mx -all", which gets set but ends up being `IN	TXT	"v=spf1" "mx" "-all"`, which is obviously is a wrong format. I tested R53 and GCLOUD as other providers, which seem to work fine.

Thanks!

**Comment by tlimoncelli** [comment]
That's odd (and certainly a bug).  Could you do a test for me?  Can  you use the NS1 web UI  to  enter the string  as you want it, then see if dnscontrol tries to  change it?

**Comment by tlimoncelli** [comment]
Can you test to see if https://github.com/StackExchange/dnscontrol/pull/270 fixes this? I don't have a test account on NS1

CC: @captncraig

**Comment by bashgeek** [comment]
Wow, that what I call a fast reaction. Appreciated!

Merged your PR #270 and using `dnscontrol 0.2.3 ("b0477b090b070f847e49800e1b2252ed4af29a37") built 17 Nov 17 11:40 CST` and tested the following scenarios:

`D('moo.cow', REG_NONE, DnsProvider(DNS_NS1, 2),
	DefaultTTL('1d'),
	TXT('test1', 'v=spf1 mx -all')
)`

Still adds a wrong formatted record:
`$ dig txt test1.moo.cow @dns1.p01.nsone.net`
`test1.moo.cow.		86400	IN	TXT	"v=spf1" "mx" "-all"`

However, when I create a test record in the NS1 interface:
`$ dig txt test2.moo.cow @dns1.p01.nsone.net`
`test2.moo.cow.		86400	IN	TXT	"v=spf1 mx -all"`
And put it into the config:
`TXT('test2', 'v=spf1 mx -all')`

It does NOT try to correct, so it seems to be fine for dnscontrol - which it actually is. Just the adding/saving process to NS1 seems to be causing the issues.

If you need any more testing, just let me know, happy to help!

Cheers,
Daniel

**Comment by tlimoncelli** [comment]
That was a lucky guess.  This is one of the community-supported providers, so the full fix really needs to come from someone with NS1 access.

I'm surprised at the results of the PR.  The code fixes the process that creates new records but doesn't touch the diffing/correction code.  I honestly expected the results of your tests to be reversed (i.e. new records work, dnscontrol tries to 'correct' things that are correct).

I noticed that we don't have an integration tests for TXT records at all.  I've added them to the PR. 

Here's how you can run the integration tests yourself. It will test all the functionality of a provider.

NOTE: This removes all the records from the domain. Don't use it on a production domain.

```
export NS1_DOMAIN="example.com"    # destructive test
export NS1_TOKEN="secret_token"
cd integrationTest
go test -v -verbose -provider NS1
```

**Comment by bashgeek** [comment]
Well, I've to correct my post from before.. Your changes in #270 do indeed fix the issue and work, I was just using a wrong binary for these tests.

`test9.moo.cow.		300	IN	TXT	"v=spf1 mx -all"`

Looks correct now! Thanks!
