### ISSUE TITLE
GANDI: add Registrar support

### ISSUE THREAD

**Issue by philhug** [StackExchange/dnscontrol#271]
Currently GANDI support is only available for DNS zones and not to create new domains/update nameservers.

Any else interested in this?
http://doc.rpc.gandi.net/domain/usage.html#update-a-domain

Or should we wait for a new REST api?

**Comment by captncraig** [comment]
Looks like there is already an issue for this (#87)

**Comment by captncraig** [comment]
But yes,  they do have a new api, and we should gradually move to that
