### ISSUE TITLE
OpenSRS: Add Registrar and DSP support

### ISSUE THREAD

**Issue by philhug** [StackExchange/dnscontrol#272]
Tucows/OpenSRS is one of the largest DNS registrars.
Anyone interested?
I can submit a PR for basic communication and Registrar support.
Should the client be hosted externally? There doesn't seem to exist one yet.

http://domains.opensrs.guide/docs/construction-of-the-post-data

**Comment by TomOnTime** [comment]
Does OpenSRS offer DNS hosting? (i.e. port 53 service?)  I couldn't find it on their website, but I may not have looked hard enough.

**Comment by philhug** [comment]
@TomOnTime yes, they do

**Comment by tIimonceIIi** [comment]
Who cares. This is useless garbage. I'm done with this.

**Comment by tlimoncelli** [comment]
WTF?  I didn't write that.

**Comment by tresni** [comment]
@tlimoncelli this still shows up as a "Requested Provider".  I'm guessing because the tag is still there and/or the website hasn't been regenerated in a while?
