### ISSUE TITLE
dnscontrol should not crash on unknown DNS record types

### ISSUE THREAD

**Issue by philhug** [StackExchange/dnscontrol#273]
This is supported on Cloudflare and when they exist, the following error occurs and dnscontrol aborts:
Unimplemented rtype SPF

Expected behaviour:
1) ignore unknown records
2) delete unknown records
3) abort synchronisation (current behaviour)

Same issue for LOC records.

**Comment by tlimoncelli** [comment]
It is my understanding that the SPF retype (99) is obsolete and TXT records
should be used instead:

https://stackoverflow.com/a/13971793/71978
-- 
Sent from Gmail Mobile

**Comment by philhug** [comment]
I agree. In that case deleting them from cloudflare zone would be the best solution IMO.

**Comment by tlimoncelli** [comment]
I believe it deleres SPF  records now.

LOC records should be easy to support.  https://stackexchange.github.io/dnscontrol/adding-new-rtypes makes it easy.

**Comment by philhug** [comment]
ok, I renamed the issue accordingly.

**Comment by tlimoncelli** [comment]
I'm curious about LOC records.  They were proposed in 1996 and never got traction. Do you know any provider that supports them?  Do you actively use them?

**Comment by philhug** [comment]
the records are supported by cloudflare. I'm not using them.

**Comment by tlimoncelli** [comment]
Crashing when unrecognized records appear is how the system was designed.  The system should crash with an error message that explains why.

We're focusing on features that have direct production needs, not chasing every provider feature. If someone needs a record type supported, we encourage them to add the feature and submit a PR. We make it pretty easy to do so.

We do have some ideas about supporting the ability to ignore certain labels, which will be a decent workaround for this.

I'm going to close this issue. We can reopen it in the future if needed.
