### ISSUE TITLE
pkg.go.dev - release v4.8.0

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#2765]
On [pkg.go.dev (StackExchange/dnscontrol)](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v4?tab=versions) a release [v4.8.0](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v4@v4.8.0) exists, meanwhile there is no [4.8.0](https://github.com/StackExchange/dnscontrol/releases/tag/v4.8.0) release on GitHub. 🤷🏼‍♂️

Versions in this module: `v4`
* **[v4.8.0](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v4@v4.8.0) Dec 13, 2023**
* [v4.7.4](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v4@v4.7.4) Jan 4, 2024
* [v4.7.3](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v4@v4.7.3) Dec 13, 2023
* [v4.7.2](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v4@v4.7.2) Dec 4, 2023
* [v4.7.1-beta](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v4@v4.7.1-beta) Nov 30, 2023
* [v4.7.0](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v4@v4.7.0) Nov 20, 2023

![Screenshot 2024-01-05 at 15 06 11](https://github.com/StackExchange/dnscontrol/assets/1150425/528ba87c-e9a9-424a-a2b9-6d8246c6808d)

Considering the date `Dec 13, 2023` I suspect something went wrong with the v4.7.3 release. Anyway, would you mind removing the non-existent 4.8.0 release from pkg.go.dev? 🙏

**Comment by tlimoncelli** [comment]
I'd gladly remove it.  Sadly I don't see any into on the website about how to have it removed.  Any advice?

**Comment by cafferata** [comment]
> Sadly I don't see any into on the website about how to have it removed. Any advice?

Oof! I read up on the pkg.go.dev [documentation](https://pkg.go.dev/about#removing-a-package) website and found this cumbersome method.

> ## Removing a package
> 
> If you would like to hide versions of a module on pkg.go.dev, as well as from the `go` command, you should retract them. Retracting a module version involves adding a `retract` directive to your go.mod file and publishing a new version. See the Go blog post [New module changes in Go 1.16](https://go.dev/blog/go116-module-changes#module-retraction) and the [modules reference](https://go.dev/ref/mod#go-mod-file-retract) for details.
> 
> Note that it is possible to retract the latest version of a module; the modules reference link above includes an example. Also note that published versions cannot be reused or modified, and this includes retracted versions.
> 
> If you cannot publish a new version with retractions because the source code repository or domain name is no longer accessible, or if you want to hide documentation for all current and future versions, you can [file a request](https://go.dev/s/pkgsite-package-removal) for the pkgsite team to hide your package documentation from pkg.go.dev. Note that the package will continue to be available via `go get` or `go install` unless its module is retracted.

**Comment by tlimoncelli** [comment]
Thanks for finding that!  

I've created https://github.com/StackExchange/dnscontrol/pull/2768

**Comment by tlimoncelli** [comment]
For my own notes: This is similar to https://github.com/StackExchange/dnscontrol/issues/2468
