### ISSUE TITLE
"dnscontrol verison" should report that git hash

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#2766]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
"dnscontrol version" should include a githash.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by cafferata** [comment]
Can you explain why? We have semantic versions for this, right?

**Comment by tlimoncelli** [comment]
@juliusrickert wrote:

> In general, I think these are great changes.
> Removing the build time helps with reproducible builds too.
> But I think a commit hash could come in handy for debugging purposes, but an abbreviated version should suffice (think issue reports).

The more I think about this the more I'm ok with how it is.  In the 6+years of the project's history nobody has reported a  bug that couldn't be solved without that information.

(Though, we should add the word "version" to be like go, git, gh, etc).

**Comment by cafferata** [comment]
> (Though, we should add the word "version" to be like go, git, gh, etc).

GitHub pull request https://github.com/StackExchange/dnscontrol/pull/2769 is ready.

> The more I think about this the more I'm ok with how it is.

Okay, then I think this GitHub issue can be closed.
