### ISSUE TITLE
Load API Key from Variable

### ISSUE THREAD

**Issue by jacobleonw** [StackExchange/dnscontrol#278]
Hi,

I've been migrating to dnscontrol and it would be useful if I could use an environment variables for the API credentials in creds.json

```
{
  "cloudflare": {
    "apiuser": "env.CLOUDFLARE_EMAIL",
    "apikey": "env.CLOUDFLARE_API_KEY"
  }
}
```

**Comment by tlimoncelli** [comment]
Good news!  It isn't well documented, but you can use "$" as the first character and it will look up the env variable.

        "apiuser": "$CLOUDFLARE_EMAIL",

**Comment by jacobleonw** [comment]
Thanks @tlimoncelli - I'm glad you said that it wasn't well documented, because I spent a good 20 minutes searching for it!

**Comment by tlimoncelli** [comment]
Fixed:
https://github.com/StackExchange/dnscontrol/commit/95fb79dfccb81bb387125bc0e47836d2e4a6794c
