### ISSUE TITLE
DOCS: Language reference - Domain modifiers - NS1_URLFWD

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#2815]
The DNSControl language reference for the domain modifier [`NS1_URLFWD`](https://docs.dnscontrol.org/language-reference/domain-modifiers/service-provider-specific/ns1/ns1_urlfwd) (_for provider [NS1](https://docs.dnscontrol.org/service-providers/providers/ns1)_) needs documentation. Who can help with this? 🙏 

The current page shows:

> **NS1_URLFWD**
>
> Documentation needed.

**Comment by costasd** [comment]
Hi, I'll try to push something for this, been in my todo list for quite a while.
