### ISSUE TITLE
CICD: GoReleaser changelog install/update

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#2819]
What do you think of the idea of always including the DNSControl install and update commands in the GitHub release notes (by [GoReleaser > Release > Footer](https://goreleaser.com/customization/release/?h=footer))?

_Inspiration comes from [JetBrains/qodana-cli](https://github.com/JetBrains/qodana-cli/releases/tag/v2023.3.1)._

**Comment by tlimoncelli** [comment]
Good idea!  It would be nice to include the deprecation warnings too.

**Comment by cafferata** [comment]
GitHub pull request https://github.com/StackExchange/dnscontrol/pull/2853 is ready (for review) 👌

**Comment by cafferata** [comment]
I think this [GitHub release 4.9.0](https://github.com/StackExchange/dnscontrol/releases/tag/v4.9.0) detail is great! What do you think @tlimoncelli? Feedback? Suggestions? Any further additions?

**Comment by tlimoncelli** [comment]
I agree.  Having the deprecation warnings and the installation tips automatically included is a big win.  Saves me tons of time!
