### ISSUE TITLE
`-debugjson`

### ISSUE THREAD

**Issue by jeanpaulgalea** [StackExchange/dnscontrol#282]
Hi,

I ran into this [page](https://github.com/StackExchange/dnscontrol/blob/master/docs/unittests.md) but recent versions of `dnscontrol` don't support these arguments.

A search for "debugjson" in the repo only found one match - the same unittests.md file.

Am I missing something or does this page need to be updated?

Thanks

**Comment by tlimoncelli** [comment]
Ah!  Thanks for reporting that.

That's the old style flag that should have been updated a while ago.  I've fixed it just now (3f4cc3c0259c05e4b3a14038c66fdfbf0be72079)

The correct command is:

    dnscontrol print-ir --out foo.json --pretty

(--pretty is optional but... I like to keep it classy :-) )

Tom

**Comment by jeanpaulgalea** [comment]
Awesome, thanks @tlimoncelli !
