### ISSUE TITLE
Removing CloudFlare CAA records

### ISSUE THREAD

**Issue by ddrght12345** [StackExchange/dnscontrol#283]
Since DNSControl does not allow you to set CAA records for CloudFlare, it should not attempt to delete them either.

Why CF's CAA support is still in "Beta", and no API access is beyond me, but since I can now add CAA records via their online panel, anytime I run `dnscontrol preview` it prompts me to delete all my CAA records.

```
#3: DELETE record: my-domain.com CAA 1 0 iodef "mailto:email" (id=12345678901234567890123456789012)
#4: DELETE record: my-domain.com CAA 1 0 issue "amazon.com" (id=12345678901234567890123456789012)
#5: DELETE record: my-domain.com CAA 1 0 issue "comodoca.com" (id=12345678901234567890123456789012)
#6: DELETE record: my-domain.com CAA 1 0 issue "digicert.com" (id=12345678901234567890123456789012)
#7: DELETE record: my-domain.com CAA 1 0 issue "globalsign.com" (id=12345678901234567890123456789012)
#8: DELETE record: my-domain.com CAA 1 0 issue "letsencrypt.org" (id=12345678901234567890123456789012)
```

Perhaps there is a generic enough way to add in, if DNSControl doesnt support a given record type, then just skip over it. No add, delete, edit, ect.

---- ------------------------------------------
Side note: I havent attempted this myself, but since I am in the beta, and I can add CAA records, then maybe they can be added via the API now?
If this is the case, then I dont see why DNSControl should continue to restrict CAA records for CF. Maybe even just add a small disclaimer about being in their beta is required for it to work?
---- ------------------------------------------
EDIT:  (I really wasnt expecting this to work, but thought I would try it, since it's easy enough to check.)
Added `providers.CanUseCAA` to the CF provider.

DNSControl didnt like it, lol
```
#3: MODIFY CAA my-domain.com: (0  "0 iodef "mailto:email"" ttl=1) -> (0 iodef "mailto:email" ttl=1)
#4: MODIFY CAA my-domain.com: (0  "0 issue "amazon.com"" ttl=1) -> (0 issue "amazon.com" ttl=1)
#5: MODIFY CAA my-domain.com: (0  "0 issue "comodoca.com"" ttl=1) -> (0 issue "comodoca.com" ttl=1)
#6: MODIFY CAA my-domain.com: (0  "0 issue "digicert.com"" ttl=1) -> (0 issue "digicert.com" ttl=1)
#7: MODIFY CAA my-domain.com: (0  "0 issue "globalsign.com"" ttl=1) -> (0 issue "globalsign.com" ttl=1)
#8: MODIFY CAA my-domain.com: (0  "0 issue "letsencrypt.org"" ttl=1) -> (0 issue "letsencrypt.org" ttl=1)
```
```
#3: MODIFY CAA my-domain: (0  "0 iodef "mailto:email"" ttl=1) -> (0 iodef "mailto:email" ttl=1)
FAILURE! [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
#4: MODIFY CAA my-domain: (0  "0 issue "amazon.com"" ttl=1) -> (0 issue "amazon.com" ttl=1)
FAILURE! [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
#5: MODIFY CAA my-domain: (0  "0 issue "comodoca.com"" ttl=1) -> (0 issue "comodoca.com" ttl=1)
FAILURE! [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
#6: MODIFY CAA my-domain: (0  "0 issue "digicert.com"" ttl=1) -> (0 issue "digicert.com" ttl=1)
FAILURE! [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
#7: MODIFY CAA my-domain: (0  "0 issue "globalsign.com"" ttl=1) -> (0 issue "globalsign.com" ttl=1)
FAILURE! [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
#8: MODIFY CAA my-domain: (0  "0 issue "letsencrypt.org"" ttl=1) -> (0 issue "letsencrypt.org" ttl=1)
FAILURE! [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
```

**Comment by tlimoncelli** [comment]
We do have a plan to restructure things a bit to make it easier to ignore records.   Currently we have 2 bandaids, neither are ver satisfactory.

Please try using [NO_PURGE](https://stackexchange.github.io/dnscontrol/js#NO_PURGE)  as a work-around.

Of  course, the best solution would  be to add support for CAA records.   Since you are in a beta that has access to  that feature, would you be  interested in trying to fix that?  We have very detailed instructions on how to do it, and most of the work in [Creating new DNS Resource Types](https://stackexchange.github.io/dnscontrol/adding-new-rtypes) is already done for you (Step 2 and 7 need the most attention.)

**Comment by ddrght12345** [comment]
Well, I can attempt it. I havent done anything in Go, so I would likely need assistance with this.
I'll attempt it this weekend and see if I can jump straight into solving this without stressing the brain too much.

**Comment by captncraig** [comment]
In this case though, if cloudflare is going to support them, we should just add support for managing them. What happens if a user not in the beta tries to add CAA? 

I will try and schedule some time to make it work properly. How do you get into the test group?

**Comment by captncraig** [comment]
We shouldn't need to add a new record type. Just add the CanUseCAA flag to cloudflare, and make the tests pass.

**Comment by ddrght12345** [comment]
Ahh. You would be much faster than I would. Lol.
I just submitted a ticket to their support listing which CAs I planned on adding. I have to at least leave their three CAs (comodoca, digi, and globalsign).
There is a blog post floating around here somewhere for it. I'll try to find it real quick

**Comment by tlimoncelli** [comment]
Since you are new to Go, I'd be willing to mentor you. (We've had good experience with this https://everythingsysadmin.com/2017/08/go-get-up-to-speed.html).

**Comment by geek1011** [comment]
Also, I suggest reading the whole go documentation (if you learn by reading and examples, like me) and gobyexample, it's very useful and not too hard to understand. I read it when I first started with go earlier this year. It took me about 14h, and taught me a lot of things. I can also help you with go if you want.

**Comment by tlimoncelli** [comment]
I made some progress here: https://github.com/StackExchange/dnscontrol/pull/285

The problem is that I'm getting an error when the API is used to add an CAA record.  The problem is either (a) the code isn't implementing the API properly wrt adding records, or (b) my account doesn't have CAA enabled.

I get errors like:

```
=== RUN   TestDNSProviders/dnscontroltest-cf.com/1:_CAA_record
--- FAIL: TestDNSProviders (0.92s)
    --- FAIL: TestDNSProviders/dnscontroltest-cf.com (0.55s)
    	integration_test.go:389: Skipping TLSA Tests because provider does not support them
        --- PASS: TestDNSProviders/dnscontroltest-cf.com/0:_Empty (0.28s)
        --- FAIL: TestDNSProviders/dnscontroltest-cf.com/1:_CAA_record (0.27s)
        	integration_test.go:132: CREATE record: @ CAA 1 0 issue "letsencrypt.org"
        	integration_test.go:136: [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
```

If you'd like to try this, check out:

```
git fetch origin
git checkout -b tlim_cloudflarecaa origin/tlim_cloudflarecaa
go install
cd integrationTest
go test -v -verbose -provider CLOUDFLAREAPI
```

**Comment by ddrght12345** [comment]
I get the same error. Deleting is the only modification (if you really want to call it a modification) that works

**Comment by tlimoncelli** [comment]
Since you were part of the beta, could you talk with their support people about this?

Here's the JSON being sent:

```
 {"name":"@","type":"CAA","content":"0 issue \"letsencrypt.org\"","ttl":1,"priority":0,"data":null}
```

Here's the error:

```
 [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
```

Error code 1004 is "Cannot find a valid zone".

**Comment by ddrght12345** [comment]
I have opened a support ticket. Lets see how soon they respond.

**Comment by ddrght12345** [comment]
Ok.
The long story short, after a (painful) talk with support, it turns out an extra data field needs to be sent.
I tested this with my own scripts, and the following array works.
```php
[
    'type'=>"CAA",
    'name'=>'domain.com',
    'content'=>'',
    'ttl'=>1,
    'data'=>[
        'tag'=>'issue',
        'value'=>'godaddy.com',
        'flags'=>0,
    ],
]
```

**Comment by tlimoncelli** [comment]
Well, it may have been a long and painful talk, but you got the exact info needed to fix this problem. (and it was something I would NEVER have guessed!)

This PR should fully support CAA on cloudflare:

https://github.com/StackExchange/dnscontrol/pull/285

Let  me know  if it works for you.

**Comment by ddrght12345** [comment]
You are a beautiful human being.
Everything works as I would expect. Can create, update, and delete CAA records successfully
+1

**Comment by tlimoncelli** [comment]
Consider it a holiday gift. :-)

Tom
