### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by ajh0912** [StackExchange/dnscontrol#2838]
**Describe the bug**
There are multiple broken links on https://docs.dnscontrol.org/ pages.

**To Reproduce**
Visit: https://docs.dnscontrol.org/
Click on: [SPF Optimizer](https://github.com/StackExchange/dnscontrol/blob/main/documentation/functions/record/SPF_BUILDER.md) link.

Visit: https://docs.dnscontrol.org/advanced-features/code-tricks
Click on: [CAA Builder](https://github.com/StackExchange/dnscontrol/blob/main/documentation/functions/record/CAA_BUILDER.md) link.
Click on: [DMARC Builder](https://github.com/StackExchange/dnscontrol/blob/main/documentation/functions/record/DMARC_BUILDER.md) link.
Click on: [M365_BUILDER](https://github.com/StackExchange/dnscontrol/blob/main/documentation/functions/record/M365_BUILDER.md) link.
Click on: [SPF Optimizer](https://github.com/StackExchange/dnscontrol/blob/main/documentation/functions/record/SPF_BUILDER.md) link.

(not limited to the above)

**Expected behavior**
The expected GitBook page should load.

**Actual behavior**
GitHub: '404 - page not found' on the source .md file.

**Comment by cafferata** [comment]
@ajh0912 thanks again for reporting. GitHub pull request https://github.com/StackExchange/dnscontrol/pull/2839 will fixes these broken documentation URLs. 🚀
