### ISSUE TITLE
New warnings in CI/CD runs

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#2841]
**Describe the bug**
All builds are reporting the same annotation over and over:

`No files were found with the provided path: $TEST_RESULTS. No artifacts will be uploaded."

I think it started with https://github.com/StackExchange/dnscontrol/pull/2831

**To Reproduce**
1. https://github.com/StackExchange/dnscontrol/actions/runs/7906927364
2. https://github.com/StackExchange/dnscontrol/actions/runs/7877142313

**Expected behavior**

**DNS Provider**
 - FILL IN

**Additional context**

**Comment by cafferata** [comment]
I indeed missed these warnings:
_https://github.com/StackExchange/dnscontrol/actions/runs/7775150527_
