### ISSUE TITLE
Cannot find Reverse Zones for /25 (other sizes maybe as well)

### ISSUE THREAD

**Issue by misilot** [StackExchange/dnscontrol#2844]
**Describe the bug**
dnscontrol will keep creating zones in R53 without it ever matching on them.

**To Reproduce**
1. Create new Reverse Zone in config
2. dnscontrol --push
3. See: Adding zone for 0/25.100.25.10.in-addr.arpa to route 53 account
4. Run it again  see
5. Adding zone for 0/25.100.25.10.in-addr.arpa to route 53 account
6. Check AWS, and see that you have multiple new reverse zones.

**Expected behavior**
I would expect it to be created once, and allow me to add new PTR records to the reverse zone.

**DNS Provider**
 - AWS

**Additional context**
Example configuration

```
D(REV('10.25.100.0/25'), NO_REGISTRAR,
    DnsProvider(AWS)
);

```

**Comment by tlimoncelli** [comment]
CC @tresni (maintainer of the route53 provider)

**Comment by tlimoncelli** [comment]
Does this happen with other domains?  (i.e. non-reverse lookup domains)

**Comment by misilot** [comment]
So I couldn't get it to create a new zone for a random domain, since I am thinking it is looking for a matching domain,

This is actually the full error

> Adding zone for 0/25.100.25.10.in-addr.arpa to route 53 account
> ERROR: ERROR: Domain 0/25.100.25.10.in-addr.arpa not found in your route 53 account

**Comment by misilot** [comment]
If I do the following, I get the same result:

```
D('0/25.100.25.10.in-addr.arpa', NO_REGISTRAR,
    DnsProvider(AWS)
);
```

```
Adding zone for 0/25.100.25.10.in-addr.arpa to route 53 account
ERROR: ERROR: Domain 0/25.100.25.10.in-addr.arpa not found in your route 53 account
```

**Comment by misilot** [comment]
I wonder if it is because this is what AWS is showing? `0&#x2F;25.100.25.10.in-addr.arpa` 

I am wondering if AWS needs to be 0-25.100.25.10.in-addr.arpa instead, but not finding any helpful documentation or examples from AWS yet.

**Comment by misilot** [comment]
From: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html?icmpid=docs_console_unmapped#domain-name-format-hosted-zones

> If the domain name includes any characters other than a to z, 0 to 9, - (hyphen), or _ (underscore), Route 53 API actions return the characters as escape codes. This is true whether you specify the characters as characters or as escape codes when you create the entity. The Route 53 console displays the characters as characters, not as escape codes.

I wonder if this is what is happening?
