### ISSUE TITLE
Creating r53 dns provider: NoCredentialProviders: no valid providers in chain. Deprecated. 	

### ISSUE THREAD

**Issue by winteraz** [StackExchange/dnscontrol#286]
Why do I get this error?  Config files below(domain/ip and credential values are masked)
dnsconfig.js

```
var REG_NONE = NewRegistrar('none', 'NONE');    // No registrar.
var r53 = NewDnsProvider("r53", "ROUTE53")

D("example1.com", REG_NONE, DnsProvider(r53),
  A("@", "11.11.11.11"),
  A("www", "11.11.11.11")
)

D("w-example2.com", REG_NONE, DnsProvider(r53),
  A("@", "11.11.11.1")
)
```

Creds.json

```
{
  "r53_ACCOUNTNAME": {
    "KeyId": "xxxxx",
    "SecretKey": "xxxxxxxxx"
  }
}
```

``Creating r53 dns provider: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Creating r53 dns provider: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors``

**Comment by winteraz** [comment]
I should note that I double checked the AWS key and secret credentials and they are valid.

**Comment by winteraz** [comment]
I've tried both global credentials and role based (i.e. using IAM) and none of them work.

**Comment by winteraz** [comment]
It works if environment variables are used. However I believe this is still a bug b/c the credentials file is the recommended method.

**Comment by tlimoncelli** [comment]
I'm having trouble reproducing this bug. We  have r53 in our creds.json.

- Do you have other providers with creds in creds.json?  Do they work?
- Does your KeyId/SecretKey have special chars that need to be escaped?
- What is the output of: `jq <creds.json .r53_ACCOUNTNAME`

The (redacted) output of jq for us is:

```
{
  "KeyId": "xxxxxxx",
  "SecretKey": "yyyyyyyyy"
}
```

**Comment by winteraz** [comment]
> Do you have other providers with creds in creds.json? Do they work?

No. Only one set of r53 credentails

> Does your KeyId/SecretKey have special chars that need to be escaped?

No. I had one such SecretKey but then I generated another one which doesn't require escaping and the result is same.

> What is the output of: jq <creds.json .r53_ACCOUNTNAME

_Some characters were replaced with XXX._
$ jq <creds.json .r53_ACCOUNTNAME
{
  "KeyId": "AKIAJBO5XXXXXXXXXX",
  "SecretKey": "R7lblrsa0OevhRs2FZDk1reXXXXXXXXX"
}

**Comment by tlimoncelli** [comment]
I was finally able to reproduce this problem.  I introduced a typo into my creds.json file so that the primary key didn't  match the first parameter in NewDnsProvider().

It should look something like this:

dnscontrol.js:

```
var R53 = NewDnsProvider('r53_ACCOUNTNAME', 'ROUTE53');
```

creds.json:

```
{
  "r53_ACCOUNTNAME": {
    "KeyId": "xxxxx",
    "SecretKey": "xxxxxxxxx"
  }
}
```

**Comment by tlimoncelli** [comment]
Please re-open this ticket if you have further problems.
