### ISSUE TITLE
Load records from zone file

### ISSUE THREAD

**Issue by xtexChooser** [StackExchange/dnscontrol#2862]
Add the ability to load DNS records from a local zone file, this would be useful for migrating from self-hosted DNS servers.

**Comment by xtexChooser** [comment]
ops sorry, just found `get-zones`

**Comment by cafferata** [comment]
Could you tell me why you didn't find the `get-zones` function in the first time? Was there something unclear? 😊

**Comment by xtexChooser** [comment]
First time I did not find way to specify the path of zone file. I found I have to place zone files under `zones/` and name them with their domain name to use `get-zones` to load.
