### ISSUE TITLE
Add DNAME support

### ISSUE THREAD

**Issue by xtexChooser** [StackExchange/dnscontrol#2880]
DNAME records are used to delegate the whole DNS hierarchy to another zone.

Currently DNSControl does not support them but they are useful sometimes.

**Comment by tlimoncelli** [comment]
Marking this as "needs volunteer".  This is a good starter project for someone looking to gain experience with Go or DNSControl. See https://docs.dnscontrol.org/developer-info/adding-new-rtypes
