### ISSUE TITLE
GANDI: domain.eu and domain.org unknown

### ISSUE THREAD

**Issue by flowolf** [StackExchange/dnscontrol#2909]
**Describe the bug**
initial query with `get-zones` does not work for some of my domains. 
```
dnscontrol -v get-zones --format=js gandi - <domain>.org
failed GetZone gzr: StatusCode: 404 ; Err: 404: Unknown domain
```
this worked for .com, .at, .net, .cloud. but does not work for .eu and .org.

the `--format` option has no effect on the error.

**To Reproduce**
1. set up the API for GANDI
2. run `dnscontrol -v get-zones --format=js gandi - <yourdomain>.org`
3. run `dnscontrol -v get-zones --format=js gandi - <yourdomain>.eu`
4. see 404 errors.

**Expected behavior**
I would expect the standard output with the current DNS records.

**DNS Provider**
 - GANDI_V5
 
**Additional context**
DNSControl version 4.8.2 and 4.9.0

the domains in question were bought at the same time as the .com and .net variant.

**Comment by tlimoncelli** [comment]
Closing old idle issue.  Please feel free to re-open if needed.
