### ISSUE TITLE
AKAMAIEDGEDNS: new maintainer

### ISSUE THREAD

**Issue by svernick** [StackExchange/dnscontrol#2939]
AKAMAIEDGEDNS has a new maintainer: cdornin  (Chris Dornin)

**Comment by cafferata** [comment]
Thanks @svernick for this feedback. Out of interest, what is the reason you are transferring the maintainer role? Have you stopped using DNSControl/Akamai Edge DNS?

@cdornin would you like to confirm your new maintainer role? ☺️

**Comment by svernick** [comment]
My last day at Akamai is May 17.  Chris Dornin is taking over my DnsControl duties.

Our group developed and maintains the Akamai Edge DNS provider.   We don’t use it ourselves, except to test it.  We provide it for use by Akamai’s customers.


From: Jeffrey Cafferata ***@***.***>
Reply-To: StackExchange/dnscontrol ***@***.***>
Date: Wednesday, May 8, 2024 at 2:25 AM
To: StackExchange/dnscontrol ***@***.***>
Cc: "Vernick, Steve" ***@***.***>, Mention ***@***.***>
Subject: Re: [StackExchange/dnscontrol] AKAMAIEDGEDNS: new maintainer (Issue #2939)


Thanks @svernick<https://urldefense.com/v3/__https:/github.com/svernick__;!!GjvTz_vk!Tn0NuKWwNfCyM2_jMXqLgVvA5mNjSS5-HzCGJSidYK4xFnedh8_cLm81T-Cj4kUEN-b-9Xdml0Hx5s3-rrS_UKY$> for this feedback. Out of interest, what is the reason you are transferring the maintainer role? Have you stopped using DNSControl/Akamai Edge DNS?

@cdornin would you like to confirm your new maintainer role? ☺️

**Comment by cafferata** [comment]
Thank you for your explanation and thank you again for the good transfer within Akamai Edge DNS.
