### ISSUE TITLE
Cloudflare api for SVCB HTTPS and DNSKEY record

### ISSUE THREAD

**Issue by lolifamily** [StackExchange/dnscontrol#2964]
support cloudflare api for SVCB HTTPS and DNSKEY record please

**Comment by cafferata** [comment]
_Ping @tresni, the maintainer of the provider._

**Comment by tlimoncelli** [comment]
Hi @lolifamily !

Thanks for looking into this.

Could you split the JSON5 support into a separate PR please?  We prefer to have 1 major feature per PR.

Thanks!
