### ISSUE TITLE
require json5 file?

### ISSUE THREAD

**Issue by lolifamily** [StackExchange/dnscontrol#2965]
**Is your feature request related to a problem? Please describe.**
I want to require json5 file

**Describe the solution you'd like**
unexpected token :

**Describe alternatives you've considered**
change to json suffix can fix

**Comment by cafferata** [comment]
Thanks for your feature request.

_I didn't know JSON5. Number of sources I consulted:_
- https://json5.org
- https://github.com/json5/json5

**Comment by tlimoncelli** [comment]
Could you supply a sample json5 file we can test against?

**Comment by tlimoncelli** [comment]
Would you consider submitting a PR?

The JS interpreter we use is `github.com/xddxdd/ottoext`.   If it supports JSON5, this is easy.  Modify `pkg/js/js.go` (there is a function called "require") to handle this as a special case.

If otto doesn't support JSON5, you'll have more work to do.  Perhaps convert JSON5 to JSON and handle it that way.

**Comment by lolifamily** [comment]
> Would you consider submitting a PR?
> 
> The JS interpreter we use is `github.com/xddxdd/ottoext`. If it supports JSON5, this is easy. Modify `pkg/js/js.go` (there is a function called "require") to handle this as a special case.
> 
> If otto doesn't support JSON5, you'll have more work to do. Perhaps convert JSON5 to JSON and handle it that way.

I didn't use any JSON5 feature except commenting, and that works with extension json

**Comment by lolifamily** [comment]
however, modern IDE would warn using comments in json, so supporting json5 would be a great idea, only support that extension is ok.

**Comment by tlimoncelli** [comment]
Feature added!  Enjoy!
