### ISSUE TITLE
DOCS: Domain modifiers code examples

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#2967]
What do we expect from the [Domain Modifiers](https://docs.dnscontrol.org/language-reference/domain-modifiers) code examples? Is a [Top Level Functions](https://docs.dnscontrol.org/language-reference/top-level-functions) [`D()`](https://docs.dnscontrol.org/language-reference/top-level-functions/d) included here or not? Currently they are used interchangeably.

**Without `D()`**

Domain modifier: [`CAA_BUILDER()`](https://docs.dnscontrol.org/language-reference/domain-modifiers/caa_builder)

```javascript
CAA_BUILDER({
  label: "@",
  iodef: "mailto:test@example.com",
  iodef_critical: true,
  issue: [
    "letsencrypt.org",
    "comodoca.com",
  ],
  issuewild: "none",
})
```

Domain modifier: [`SSHFP()`](https://docs.dnscontrol.org/language-reference/domain-modifiers/sshfp)

```javascript
IGNORE(labelSpec, typeSpec, targetSpec):
IGNORE(labelSpec, typeSpec):
IGNORE(labelSpec):
```

**With `D()`**

Domain modifier: [`A()`](https://docs.dnscontrol.org/language-reference/domain-modifiers/a)

```javascript
D("example.com", REG_MY_PROVIDER, DnsProvider(DSP_MY_PROVIDER),
  A("@", "1.2.3.4"),
  A("foo", "2.3.4.5"),
  A("test.foo", IP("1.2.3.4"), TTL(5000)),
  A("*", "1.2.3.4", {foo: 42}),
END);
```

**Comment by tlimoncelli** [comment]
I think it is more friendly to beginners if we include the `D()` every time.   One of my complaints about the Python docs is that they don't give context and new people (like I was years ago :-) ) get confused.

Likewise, the "record modifiers" examples should include `D(... A(...  record_modifier ))`

**Comment by cafferata** [comment]
The scope has just been determined:

1. `documentation/language-reference/domain-modifiers/CAA_BUILDER.md`
2. `documentation/language-reference/domain-modifiers/DMARC_BUILDER.md`
3. `documentation/language-reference/domain-modifiers/IGNORE.md`
4. `documentation/language-reference/domain-modifiers/M365_BUILDER.md`
5. `documentation/language-reference/domain-modifiers/SSHFP.md`
