### ISSUE TITLE
miss makezero in slice init

### ISSUE THREAD

**Issue by alingse** [StackExchange/dnscontrol#2981]
NOTE: Have a general question?  You'll get a better response on the [dnscontrol-discuss](https://groups.google.com/g/dnscontrol-discuss) email list!

**Describe the bug**

I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.

see issues https://github.com/alingse/go-linter-runner/issues/1

and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9242994368/job/25426542378

```
====================================================================================================
append to slice `mzn` with non-zero initialized length at https://github.com/StackExchange/dnscontrol/blob/main/providers/gcloud/gcloudProvider.go#L482:10
====================================================================================================
```

the `mzn := make([]*gdns.ManagedZonePrivateVisibilityConfigNetwork, len(g.Networks))` should be `mzn := make([]*gdns.ManagedZonePrivateVisibilityConfigNetwork, 0, len(g.Networks))`

**To Reproduce**

**Expected behavior**

**DNS Provider**
 - FILL IN

**Additional context**

**Comment by tlimoncelli** [comment]
Thanks for the report!
Fixing in https://github.com/StackExchange/dnscontrol/pull/2982
