### ISSUE TITLE
Notifications via Shoutrrr

### ISSUE THREAD

**Issue by kytta** [StackExchange/dnscontrol#2994]
**Is your feature request related to a problem? Please describe.**
Currently, there is a limited number of notification types. Adding a new one is simple, but each notification type would require their own configuration parameters. Sometimes it's a token, sometimes it's a URL, sometimes it's both.

**Describe the solution you'd like**
We could consider using [Shoutrrr](https://containrrr.dev/shoutrrr/v0.8/), which is a Go library for notifications. Unlike the current solution, it uses a single URL for a notification type, and this URL encodes all information needed, be it tokens or other metadata. It supports all current notification types natively except for Bonfire, but since it also has webhook support, Bonfire is also easy to implement.

**Describe alternatives you've considered**
An obvious alternative would be to implement all notification types from scratch

**Additional context**
N/A

**Comment by tlimoncelli** [comment]
Hi there!

Shoutrrr sounds great!  Would you be interested in sending a PR? I'd be glad to assist.

Tom

**Comment by kytta** [comment]
> Would you be interested in sending a PR? I'd be glad to assist.

Yes! I don't have much experience with Go, but one always has to start somewhere :)

**Comment by hmoffatt** [comment]
Hey @kytta want to try out this on my PR?
