### ISSUE TITLE
ERROR: ERROR: failed parsing domain list from porkbun: json: cannot unmarshal number into Go struct field domainListRecord.domains.securityLock of type string

### ISSUE THREAD

**Issue by Sylonin** [StackExchange/dnscontrol#3016]
**Describe the bug**

Using `preview` with the porkbun provider  is broken and results in any of my domains:

```
ERROR: ERROR: failed parsing domain list from porkbun: json: cannot unmarshal number into Go struct field domainListRecord.domains.securityLock of type string
```

**DNS Provider**
 - porkbun

**Comment by tlimoncelli** [comment]
CC @imlonghao

**Comment by imlonghao** [comment]
Please use v4.11.0 at this time while I'm preparing a fix for this.

(I'm having trouble with integration test due to rate limit)
