### ISSUE TITLE
Porkbun URL forwarding

### ISSUE THREAD

**Issue by viharm** [StackExchange/dnscontrol#3020]
**Is your feature request related to a problem? Please describe.**
Does not support "URL" for Porkbun

**Describe the solution you'd like**
Porkbun API supports the URL Forwarding functionality.

**Describe alternatives you've considered**
Set URL forwarding on the web interface, then add lines for ALIAS & CNAME pointing to Porkbun's servers.

**Additional context**
N.A.

**Comment by cafferata** [comment]
cc @imlonghao, the maintainer of the Prokbun provider.

**Comment by imlonghao** [comment]
I'm doubting how many users use their API for URL forwarding.

The API endpoint for "Domain Delete URL Forward" on the docs is incorrect, shows `https://api.porkbun.com/api/json/v3/domain/addUrlForward/DOMAIN/RECORD ID` but the correct one should be `https://api.porkbun.com/api/json/v3/domain/deleteUrlForward/DOMAIN/RECORD ID` which is undocumented.

:|

**Comment by ajh0912** [comment]
I contacted their support, they've fixed [Domain Delete URL Forward](https://porkbun.com/api/json/v3/documentation#Domain%20Delete%20URL%20Forward) now.
