### ISSUE TITLE
[4.12.3] Unsupported record type CLOUDFLAREAPI_SINGLE_REDIRECT

### ISSUE THREAD

**Issue by pro-sumer** [StackExchange/dnscontrol#3039]
**Describe the bug**

```
2024/07/09 08:36:37 ERROR: unsupported record type (CLOUDFLAREAPI_SINGLE_REDIRECT) domain=DOMAIN.TLD name=NAME
2024/07/09 08:36:37 ERROR: checkTargets: Unimplemented record type (CLOUDFLAREAPI_SINGLE_REDIRECT) domain=DOMAIN.TLD name=NAME
```

**To Reproduce**
1. Install DNSControl 4.12.3
2. Add `{ manage_single_redirects: true }` to the DNS provider options
3. Add a `CF_SINGLE_REDIRECT` rule (see example below)

```
 CF_SINGLE_REDIRECT(NAME', 302, '(starts_with(http.request.uri.path, "/users") and http.host eq "DOMAIN.TLD")', 'concat("https://social.DOMAIN.TLD", http.request.uri.path)'),
```

**Expected behavior**
Cloudflare single/dynamic rule set up correctly.

**DNS Provider**
`cloudflare`

**Comment by tlimoncelli** [comment]
dang!  it worked in the test environment!!! :-)

But seriously... I'll take a look this morning..
