### ISSUE TITLE
[4.12.4] CF_SINGLE_REDIRECT name not applied

### ISSUE THREAD

**Issue by pro-sumer** [StackExchange/dnscontrol#3049]
**Describe the bug**
Name **name** in CF_SINGLE_REDIRECT(**name**, **code,** **when**, **then**) is not used; name of rule in Cloudflare dashboard is "code=**code** when=**when** then=**then**" instead.

**To Reproduce**
1. Install DNSControl 4.12.4
2. Add `{ manage_single_redirects: true }` to the DNS provider options
3. Add a `CF_SINGLE_REDIRECT` rule (see example above)

**Expected behavior**
Name **name** is used.

**DNS Provider**
 - `cloudflare`

**Additional context**
N/A

**Comment by tlimoncelli** [comment]
Geez... another problem not caught in the integration test. Sorry!

I think there's confusion in the code on how CloudflareSingleRedirectConfig.SRDisplay is used.

FYI: I'm traveling and won't be able to get to this until next week.

**Comment by tlimoncelli** [comment]
Hi @pro-sumer!  Please take a look at the `tlim_b3049_cfname` branch.

This code is cleaner and greatly improves the names for redirects that appear in the Cloudflare control panel. It also fixes the bug you reported :)
