### ISSUE TITLE
Service Provider Specific domain-modifiers not appearing on website

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#3053]
**Describe the bug**
Modifiers like CF_STATIC_REDIRECT and AKAMAICDN are not appearing on the website's navivation.

**To Reproduce**

What it looks like on the website:

![screencapture_2024-07-18_11 31 47](https://github.com/user-attachments/assets/4e441ea9-daaa-48c8-b8e1-ce081fbfb5e2)

There are many more in SUMMARY.md:

![screencapture_2024-07-18_11 32 17](https://github.com/user-attachments/assets/96751555-35a2-4d57-916f-23b20b1e0f5b)

**Expected behavior**
All the missing items should appear.

**DNS Provider**
 - n/a

**Additional context**

CC @cafferata

**Comment by cafferata** [comment]
I can confirm the problem. The GitBook sync is no longer running. Why is still unknown. The error message:
> "The latest synchronization timed out."

I'm reporting this issue to Gitbook support.

![Screenshot 2024-08-05 at 09 09 28](https://github.com/user-attachments/assets/3df29205-90b4-42a7-a28c-0585653a562c)

_<https://app.gitbook.com/o/a20fYtKYj8URvopj6H8Q/s/WrmraLixHOl1dTf6kvlX/~/gitsync/status>_

_<https://app.gitbook.com/o/a20fYtKYj8URvopj6H8Q/s/WrmraLixHOl1dTf6kvlX/~/gitsync/progress>_

**Comment by cafferata** [comment]
> I'm reporting this issue to Gitbook support.

Done!

> The GitHub sync does not work anymore, the last successful sync was 17 days ago. The [GitBook GitHub sync](https://app.gitbook.com/o/a20fYtKYj8URvopj6H8Q/s/WrmraLixHOl1dTf6kvlX/~/gitsync/progress) interface shows me this error message: "The latest synchronization timed out." Could you tell me what's going wrong? I've applied multiple times the GitHub sync configurations without any success.

**Comment by cafferata** [comment]
Fixed by GitBook support:

1. https://docs.dnscontrol.org/language-reference/domain-modifiers/service-provider-specific/cloudflare-dns/cf_single_redirect
2. https://docs.dnscontrol.org/language-reference/domain-modifiers/service-provider-specific/akamai-edge-dns/akamaicdn

**Comment by tlimoncelli** [comment]
yay!
