### ISSUE TITLE
NS1: URFLWD is deprecated

### ISSUE THREAD

**Issue by costasd** [StackExchange/dnscontrol#3076]
While working on #2815, I found out that the URLFWD record type (what we call `NS1_URLFWD` in dnscontrol) is being deprecated by IBM/NSONE.

Essentially, the current status is:
* No docs anymore, just a hint that this is going to be replaced by a new "REDIRECT" type [source](https://www.ibm.com/docs/en/ns1-connect?topic=answers-reference-dns-record-types#guide_to_dns_record_types__title__27)
* No way to configure (=add new/edit existing) them through the portal
* API still works, but can stop accepting the record anytime

I'm tempted to just remove all relevant code from the provider and replace with a message for any people still using it, but maybe warrants a deprecation notice in the next release and removal in next++. Not sure though, it's probably not that many people using it, but that's just a hunch.

Any opinions?

**Comment by tlimoncelli** [comment]
There are a couple ways to do this:
1. Announce NS1_URLFWD is going away in the docs, have it print a warning, and remove the code when the API disappears.
2. Add code so that NS1_URLFWD generates a REDIRECT in addition and stop updating URLFWD.

The first is probably less work.  I'm ok with either.

**Comment by costasd** [comment]
Thanks. Given that REDIRECT isn't live yet nor fully documented, I will go with the first option. #3078 adds this warning and there's #3075 open for the docs

**Comment by tlimoncelli** [comment]
Sounds good!
