### ISSUE TITLE
New registrar: Porkbun

### ISSUE THREAD

**Issue by Kernald** [StackExchange/dnscontrol#3087]
**Is your feature request related to a problem? Please describe.**
Being able to manage name servers for a domain registered with Porkbun would be nice.

**Describe the solution you'd like**
Implement Porkbun, which already is supported as a DNS provider, as a registrar

**Describe alternatives you've considered**

**Additional context**
I'm not 100% sure what the pre-requisites are for such a feature to even be possible, but it looks like their API should cover it: https://porkbun.com/api/json/v3/documentation#Domain%20Update%20Name%20Servers

**Comment by imlonghao** [comment]
Already supported. #2542

**Comment by Kernald** [comment]
My bad - that's what I get for reading the documentation on my phone I guess. Apologies for the noise.

**Comment by tlimoncelli** [comment]
No worries!  Happens to me all the time!
