### ISSUE TITLE
bind default_soa seems to be ignored

### ISSUE THREAD

**Issue by chicks-net** [StackExchange/dnscontrol#3109]
**Describe the bug**
`default_soa` does not seem to effect the resulting file.

**To Reproduce**

1. Install dnscontrol on macOS with brew.
1. Follow the tutorial at https://docs.dnscontrol.org/getting-started/getting-started
1. Merge in the example config from https://docs.dnscontrol.org/provider/bind

End up with a `dnsconfig.js` that looks like:

```
var REG_NONE = NewRegistrar("none");
var DNS_BIND = NewDnsProvider("bind", {
        "default_soa": {
                "master": "va0.fini.net.",
                "mbox": "support.fini.net.",
                "refresh": 1200, // 20 minutes
                "retry": 600, // 10 minutes
                "expire": 604800, // 1 week
                "minttl": 3600, // 1 hour
        },
        "default_ns": [
                "va0.fini.net.",
                "va1.fini.net.",
                "va2.fini.net.",
                "va3.fini.net."
        ]
});

D("example.com", REG_NONE, DnsProvider(DNS_BIND),
    A("@", "10.11.12.13"),
END);
```

Yet the resulting zone file `zones/example.com.zone`:

```
$TTL 300
; generated with dnscontrol 2024-09-05T19:27:02-07:00
@                IN SOA   DEFAULT_NOT_SET. DEFAULT_NOT_SET. 2024090602 3600 600 604800 1440
                 IN NS    va0.fini.net.
                 IN NS    va1.fini.net.
                 IN NS    va2.fini.net.
                 IN NS    va3.fini.net.
                 IN A     10.11.12.13
```

still indicates the defaults for SOA aren't set.  The `default_ns` did take effect.

`dnscontrol` says there is nothing else to update:

```% dnscontrol preview
******************** Domain: example.com
Done. 0 corrections.
```

**Expected behavior**
SOA to get updated also.

**DNS Provider**
 - BIND

**Additional context**
```
% dnscontrol version
DNSControl version 4.13.0
```

installed with brew on MacOS.

**Comment by chicks-net** [comment]
I created a new domain and it did get the SOA info.  So the question becomes: how should we set the SOA on an existing domain?

**Comment by tlimoncelli** [comment]
Yes, the `default_soa` only affects a domain when it is completely new and has no SOA record at all. Once the SOA record exists, the `default_soa` values are ignored. This is explained https://docs.dnscontrol.org/provider/bind though it could probably be more clear. If you have suggestions for new wording I'd appreciate it!

To update the SOA, use the SOA() feature.  https://docs.dnscontrol.org/language-reference/domain-modifiers/soa

**Comment by chicks-net** [comment]
First, I'd like to say that the docs are excellent and strongly encouraged me to try out `dnscontrol`.  I had read that part of https://docs.dnscontrol.org/provider/bind before starting an issue, but I missed this nuance.

I wanted to wait for a new day to give this a fresh look.  I can see how I might have misread it now.  Here is a suggested rewrite of the bullet point that seems to be central to this:

> ## Meta configuration
> This provider accepts some optional metadata in the `NewDnsProvider()` call.
> 
> * `default_soa`: If no SOA record exists in a zone file, one will be created based on the values specified here.  Use `SOA()` to update existing zone files.
>
> * `default_ns`: Inject these NS records into the zone.

I can turn this into a PR if you desire.

**Comment by tlimoncelli** [comment]
CC @cafferata 

That's a great rewrite!  Yes, please send a PR!

One suggestion:  After "Inject these NS records into the zone." add "Use this when NS() is insufficient."

Tom

**Comment by chicks-net** [comment]
I've started the PR.  #3111  I think that is what we discussed, but I'm happy to tweak further.
