### ISSUE TITLE
IGNORE doesn't work with providers that don't set RecordConfig.Name

### ISSUE THREAD

**Issue by masterzen** [StackExchange/dnscontrol#312]
I just discovered that some (most?) providers never sets `RecordConfig.Name` for existing record, unlike what I did in the OVH provider (coincidentally I'm only testing with this provider).

Unfortunately, the #300 PR adding the IGNORE directive just test on the `Name`, not the `NameFQDN`. I'm going to push a bug fix ASAP for this issue.

But a quick question, shouldn't all provider fill the `Name` field along with the `NameFQDN` field?
The comment in https://github.com/StackExchange/dnscontrol/blob/master/models/dns.go#L61 as I read it seems to imply it should always exist.

**Comment by masterzen** [comment]
This is fixed with PR #313 .

**Comment by tlimoncelli** [comment]
Part of the refactoring done last month was to eliminate the .Name field and replace it with getters/setters.  Has this fixed this issue? (or made it worse?)

**Comment by masterzen** [comment]
@tlimoncelli 

The refactor changed nothing to this issue. I fixed this issue so that the code uses `NameFQDN` instead of `Name` (see commit b7c6efaa53933a3f1b26d63ed55a4a51b4b921d3).

So, you can either close this issue, or I can rewrite the `IGNORE` feature to use the `GetLabel` getter (this would remove a `TrimDomainName` call per label if that matters).

**Comment by TomOnTime** [comment]
Please rewrite it to use GetLabel(). Eventually we'd like to unexport .Name and .Target entirely.

**Comment by tlimoncelli** [comment]
anything left to do?

**Comment by masterzen** [comment]
@tlimoncelli no, you can close this issue.
