### ISSUE TITLE
Cloudflare batch updates

### ISSUE THREAD

**Issue by wdhdev** [StackExchange/dnscontrol#3123]
**Is your feature request related to a problem? Please describe.**
Sending a separate API request for every record change can be a lot of requests.

**Describe the solution you'd like**
Use the new batch update endpoint Cloudflare introduced in their new blog post: https://blog.cloudflare.com/batched-dns-changes/

**Describe alternatives you've considered**
N/A

**Additional context**
Free users of Cloudflare are limited to 200 record changes in one batch request, however users on paid plans have a limit of 3,500.

**Comment by cafferata** [comment]
_Ping @tresni, the maintainer of Cloudflare provider._

**Comment by tlimoncelli** [comment]
Thank you for letting us know about this new CF feature.

Sadly I'm going to reject this feature request. The CF provider is pretty old and inflexible, which makes this difficult to implement.  Most "push" updates are very small, and batching won't help much.

However if we ever rewrite this provider from scratch (something we've considered from time to time), we'll consider doing batch updates.
