### ISSUE TITLE
CLOUDNS: API error messages leak credentials

### ISSUE THREAD

**Issue by hmoffatt** [StackExchange/dnscontrol#3124]
**Describe the bug**
If a CLOUDNS API error occurs, the credentials are leaked. This is because the credentials are passed in the query part of the URL, and the whole URL is printed in the error.

**To Reproduce**
Seen while debugging ClouDNS changes, but it would occur if you had the credentials wrong.

**Expected behavior**
Credentials should not be leaked in the error text.

**DNS Provider**
 - ClouDNS

**Additional context**

**Comment by cafferata** [comment]
_Ping @pragmaton, the maintainer of the ClouDNS provider._

**Comment by hmoffatt** [comment]
I think the simplest change is not to print the URL - change is in the referenced PR. Otherwise a sanitized URL could be printed, if this is desired.

**Comment by cafferata** [comment]
@hmoffatt, can this issue be closed with https://github.com/StackExchange/dnscontrol/pull/3126? Or are there other ideas/implementations besides https://github.com/StackExchange/dnscontrol/pull/3126 that would require this GitHub issue to be kept open?
