### ISSUE TITLE
Fix ppush/oldpush docs

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#3133]
NOTE: Have a general question?  You'll get a better response on the [dnscontrol-discuss](https://groups.google.com/g/dnscontrol-discuss) email list!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**DNS Provider**
 - FILL IN

**Additional context**

**Comment by cafferata** [comment]
Addition to https://github.com/StackExchange/dnscontrol/pull/3132

**Comment by cafferata** [comment]
Fixed by https://github.com/StackExchange/dnscontrol/pull/3144.

Replaced by https://github.com/StackExchange/dnscontrol/issues/3142 https://github.com/StackExchange/dnscontrol/pull/3145
