### ISSUE TITLE
PorkBun always wants to update nameservers for any domain

### ISSUE THREAD

**Issue by rknightuk** [StackExchange/dnscontrol#3163]
**Describe the bug**

For reference, this seems to be identical to https://github.com/StackExchange/dnscontrol/issues/2623 but it's not limited to specific domains.

With the following config, on first run it will add these name servers to Porkbun but if I run `dnscontrol preview` again it will say it wants to update the name servers with `Update nameservers coco.bunny.net,kiki.bunny.net -> coco.bunny.net,coco.bunny.net,kiki.bunny.net,kiki.bunny.net`

```
D("example.me", REG_PORKBUN
	, DnsProvider(DSP_BUNNY)
	, DefaultTTL(600)
	, NAMESERVER("kiki.bunny.net.")
  	, NAMESERVER("coco.bunny.net.")
)
```

**To Reproduce**

(Copied from https://github.com/StackExchange/dnscontrol/issues/2623 because it's the same)

1. Have a domain & DNSControl settings for it that use Porkbun as registrar (this happens for me on `.me` and `.net` domains)
2. `dnscontrol push`
3. See that it updates the nameservers
4. `dnscontrol preview`
5. See that it would try to update nameservers again.

**Expected behavior**

It shouldn't try to update nameservers again. 

[This comment](https://github.com/StackExchange/dnscontrol/issues/2623#issuecomment-1811197902) suggests the provider needs to updated to handle missing `.` on the API and [this PR](https://github.com/StackExchange/dnscontrol/pull/2624) appears to fix it.

**DNS Provider**
 - Porkbun.

**Additional context**
Running 4.14.0 on MacOS 15.0.1/Sequoia

**Comment by cafferata** [comment]
Ping @imlonghao, the maintainer of Porkbun provider.

**Comment by rknightuk** [comment]
>  it will generate by DnsProvider(DSP_BUNNY)

Thank you, I didn't even think of that 🤦‍♂️ Sorry to have bothered you.
