### ISSUE TITLE
ORACLE: inconsistent behavior for "trailing dot on nameserver"

### ISSUE THREAD

**Issue by fabienmazieres** [StackExchange/dnscontrol#3164]
**Describe the bug**

I need trailing dot removed: https://github.com/StackExchange/dnscontrol/issues/3089
@kallsyms needs them on: https://github.com/StackExchange/dnscontrol/pull/3151

Using `main` or `v1.14.0`, I get this error:

```
WARN: In v4.15 --cmode will default to "concurrent". Please test and report any bugs ASAP. In v4.16 or later, "legacy" will go away. See https://docs.dnscontrol.org/commands/preview-push
******************** Domain: example.co.uk
ERROR: ERROR: error while getting Nameservers for zone="example.co.uk" with provider="oracle": provider code leaves trailing dot on nameserver
Done. 0 corrections.
```

Using v1.13.0, all fine:

```
******************** Domain: example.co.uk
Done. 0 corrections.
```

**To Reproduce**

```
go install github.com/StackExchange/dnscontrol/v4@main
dnscontrol preview
```

works for @kallsyms , error for @fabienmazieres 

```
go install github.com/StackExchange/dnscontrol/v4@v4.13.0
dnscontrol preview
```

error for @kallsyms , works for @fabienmazieres

Note: I have actually build both providers separately to make it easier to test with either one or the other:
```
cd <GOPATH>\pkg\mod\github.com\!stack!exchange\dnscontrol\v4@v4.13.0
go build -o <GOPATH>\bin\dnscontrol.v4.13.0.exe
cd ..\v4@v4.14.0\
go build -o <GOPATH>\bin\dnscontrol.v4.14.0.exe
```

**Expected behavior**

behavior should be consistent.

**DNS Provider**

 - ORACLE

**Additional context**

I get the same behavior on my machine (Windows) and on a GitHub runner (Ubuntu) so I do not think it is linked to the OS, except if @kallsyms is using Mac?
Could it be linked to the Oracle config?
Can we have a variable used to control whether to use or the other function?
This may need to be set at a global level to apply to all domains, or at a domain level

**Comment by fabienmazieres** [comment]
We had our config migrated to Oracle from another provider (Dyn) after it was bought by Oracle, so yes it is possible.

How could I make flag available in the domain config to flip on or off the logic?
For example a flag in the config file
```
D("example.co.uk", REG_NONE, DnsProvider(DSP_ORACLE),
  ORACLE_REMOVE_TRAILING_DOT,
 [...]
```

would change behavior in the provider code:
```
	if o.OracleRemoveTrailingDot {
		return models.ToNameservers(nss)
	} else {
		return models.ToNameserversStripTD(nss)
	}
```

I was thinking something like NO_PURGE but the code around that seems deep into the weeds rather than managed at provider level, so I could not find an example how to read this property in the provider code directly.

if you can give me a lead @tlimoncelli, I do not mind working on a code change

**Comment by tlimoncelli** [comment]
Hi there!

I'd be glad to help!

Before we code, let's see if we can avoid code:
* Are dots required/not-required for new domains?  Maybe that's the default.
* For domains that are "the other way", does deleting and re-creating the nameservers fix the problem?
* Have you opened a support case with Oracle? Maybe this is a known issue and they have a solution.

**Comment by fabienmazieres** [comment]
> Are dots required/not-required for new domains? Maybe that's the default.

I cannot test new domains right now but I will check once I get a few more permission in OCI from our admins.

> For domains that are "the other way", does deleting and re-creating the nameservers fix the problem?

We have prod domains, if they are affected I would not want to touch them anyway.
NS Records for Oracle servers themselves appear to be locked and cannot be touched in the UI, I am pretty sure API will bounce me off too.

> Have you opened a support case with Oracle? Maybe this is a known issue and they have a solution.

Working on this, will update when I have feedback.

**Comment by tlimoncelli** [comment]
By the way... adding a `ORACLE_REMOVE_TRAILING_DOT` feature would be relatively easy. It is very similar to `NO_PURGE`, as you mentioned.

- In helpers.js: Add ORACLE_REMOVE_TRAILING_DOT similar to NO_PURGE.
- In models/domains.go:DomainConfig: Add a field called OracleRemoveDot bool
- In the code that needs to remove the dot, you can access d.OracleRemoveDot.

**Comment by fabienmazieres** [comment]
Oracle support not helpful, basically they won't touch integration with 3rd party tools and referred me to Account Management and Customer Success departments to get more custom help on this topic.

I had started to work on the solution mention, I think I got the last part wrong as I accessed it on the provider rather than domain.
I will push a draft PR shortly so we can discuss further.

Thanks @tlimoncelli !

**Comment by fabienmazieres** [comment]
#3170 is in draft with the code as advised, I think I got the code right but test fails:

```
=== RUN   TestDNSProviders
=== RUN   TestDNSProviders/example.co.uk
    integration_test.go:132: Failed getting nameservers provider code leaves trailing dot on nameserver
--- FAIL: TestDNSProviders (2.80s)
    --- FAIL: TestDNSProviders/example.co.uk (0.50s)
=== RUN   TestDualProviders
    integration_test.go:132: Failed getting nameservers provider code leaves trailing dot on nameserver
--- FAIL: TestDualProviders (0.38s)
=== RUN   TestNameserverDots
    integration_test.go:132: Failed getting nameservers provider code leaves trailing dot on nameserver
--- FAIL: TestNameserverDots (0.30s)
```

How can I pass this parameters to the tests?

**Comment by fabienmazieres** [comment]
Could I propose an alternative?

function `GetNameservers`:
```TypeScript
	nssNoStrip, err := models.ToNameservers(nss)

	if err != nil {
		nssStrip, err := models.ToNameserversStripTD(nss)
		if err != nil {
			return nil, fmt.Errorf("Could not determine if trailing dots should be stripped or not...")
		}

		return nssStrip, nil
	}

	return nssNoStrip, nil
```
This way it can handle both dynamically... makes more sense?

**Comment by tlimoncelli** [comment]
I'm ok with the alternative.

Is the problem when reading or writing?  That is, is the problem that during a preview some zones include a trailing dots and others don't?  Or is the problem that when updating the domain sometimes the API expects DNSControl to include the trailing dot and othertimes it doesn't?

If this is a problem with reading... I'm good with the dynamic solution.

**Comment by fabienmazieres** [comment]
@kallsyms ,
Could you please help me test the code from #3170.
This should automatically strip NS when needed.
For me it looks like but I would appreciate if you can have a go and see if it works for your too.
Thanks!

**Comment by tlimoncelli** [comment]
When you test the code, please also test a "push" that changes a nameserver for a domain. Thanks!

**Comment by tlimoncelli** [comment]
(Tip: Configure your code editor to run goimports (instead of gofmt) and those problems go away)

**Comment by tlimoncelli** [comment]
What's the decision?  Use the automatic version?  (and remove the code for ORACLE_REMOVE_TRAILING_DOT ?)

**Comment by fabienmazieres** [comment]
> What's the decision? Use the automatic version? (and remove the code for ORACLE_REMOVE_TRAILING_DOT ?)

I am waiting for Nick's tests after the missing `fmt` was added but I believe it should work for both of us.
If it does, I clean the code of `ORACLE_REMOVE_TRAILING_DOT ` and then you can merge.

**Comment by fabienmazieres** [comment]
@tlimoncelli branch cleaned, ready to merge
