### ISSUE TITLE
CAA_CRITICAL sets wrong flag into CAA record

### ISSUE THREAD

**Issue by ismaelperal** [StackExchange/dnscontrol#318]
According to RFC [6844](https://tools.ietf.org/html/rfc6844#section-5.1): Bit 0, Issuer Critical Flag:  If the value is set to '1', the  critical flag is asserted and the property MUST be understood if the CAA record is to be correctly processed by a certificate issuer. Where bit 0 match with the decimal value "128"

**Comment by tlimoncelli** [comment]
Fixed.
