### ISSUE TITLE
Porkbun does not support CAA records

### ISSUE THREAD

**Issue by ducksauz** [StackExchange/dnscontrol#3199]
**Describe the bug**
Porkbun provider does not support CAA records. It is marked as `Unimplemented`. Provider code comment says "CAA record for base domain is pinning to a fixed set once configure". However, Porkbun's API supports CAA records just fine for both the domain apex and subdomains.

```
2024/11/10 20:14:01 1 Validation errors:
2024/11/10 20:14:01 ERROR: domain example.com uses CAA records, but DNS provider type PORKBUN does not support them exiting due to validation errors
```

**To Reproduce**

1. Have CAA records for your domain
2. `dnscontrol preview`
3. See error

**Expected behavior**
CAA records get created or updated

**DNS Provider**
 - PORKBUN

**Additional context**
I was able to directly call the Porkbun API and create CAA records.

**Comment by imlonghao** [comment]
Yeah, few months ago, no matter how I change it, it just keeps it that way.

I will file a PR to make it to `providers.Can()`
