### ISSUE TITLE
Add CNR to automated tests

### ISSUE THREAD

**Issue by AsifNawaz-cnic** [StackExchange/dnscontrol#3204]
I would like to volunteer to maintain credentials and an account for CNR to enable automated testing. The account is an OT&E account and does not involve any real-time costs.  

I acknowledge and agree to the following rules:  
- The account/credentials will only access the test domain `dnscontroltest-cnr.com`.  
- I will ensure timely renewal of the test domain and monitor associated notifications if needed.  
- I will not use company resources or credentials without proper permission.  

The credentials have already been securely forwarded to Timo via https://transfer.secretoverflow.com/u/tlimoncelli.  

Please let me know if any additional steps are required.

**Comment by tlimoncelli** [comment]
Thanks! I'll get to this by Friday.

**Comment by AsifNawaz-cnic** [comment]
> Thanks! I'll get to this by Friday.

Great, much appreciated!

**Comment by tlimoncelli** [comment]
All set up and tested! https://github.com/StackExchange/dnscontrol/actions/runs/12208339671/job/34061587748
