### ISSUE TITLE
Major refactoring complete. Please test with your provider.

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#323]
Hey folks!

I've reworked and greatly simplified a lot of code.  The integration test work for all the providers that I could test.  However I don't have test accounts on all the providers.  Therefore, I'd appreciate it if everyone could try the latest code and let me know if your integration tests run cleanly.

In particular...

* digital ocean @Deraen
* dnsimple @aeden
* Linode @koesie10
* namecheap @captncraig
* ns1 @captncraig
* OVH @masterzen
* Vultr @geek1011

Thanks!
Tom

**Comment by aeden** [comment]
This is already on master?

**Comment by masterzen** [comment]
@aeden I assume @tlimoncelli is referring to this commit de4455942bf38dc6b49e03b56748b00be5c062cf which is in master.

**Comment by tlimoncelli** [comment]
Yes, the master branch.

**Comment by masterzen** [comment]
@tlimoncelli all integration tests pass for the OVH provider.

**Comment by Deraen** [comment]
@tlimoncelli integration tests pass for Digitalocean

**Comment by onlyhavecans** [comment]
This issue is new post refactor https://github.com/StackExchange/dnscontrol/issues/324
I am testing on behalf of DNSimple

**Comment by tlimoncelli** [comment]
Update...

- [X] digital ocean @Deraen
- [ ] dnsimple @aeden
- [ ] Linode @koesie10
- [ ] namecheap @captncraig
- [ ] ns1 @captncraig
- [X] OVH @masterzen
- [ ] Vultr @geek1011

**Comment by TomOnTime** [comment]
Friendly ping to @koesie10 , @captncraig , @geek1011

**Comment by geek1011** [comment]
@TomOnTime sorry, missed the notification. I get too many notifications from GitHub so I usually miss important ones. I'll test this sometime today or tomorrow.

**Comment by TomOnTime** [comment]
@geek1011 no worries!  (and no rush)

**Comment by geek1011** [comment]
Works for my config. Will test a few other edge cases later.

**Comment by tlimoncelli** [comment]
@geek1011 FYI: I've updated the [integration test documentation](https://github.com/StackExchange/dnscontrol/blob/master/integrationTest/readme.md) recently.

**Comment by geek1011** [comment]
@tlimoncelli Looks great!

**Comment by tIimonceIIi** [comment]
@geek1011 Who cares. Nobody asked your opinion.

**Comment by TomOnTime** [comment]
WTF?  I didn't write that.
