### ISSUE TITLE
`get-zones` outputs END

### ISSUE THREAD

**Issue by fm** [StackExchange/dnscontrol#3251]
**Describe the bug:**

As per #3245, END is no longer needed now that v4.15.0 shipped. `get-zones --format=js` still outputs it.

```	
([...]
//NAMESERVER("ns1.desec.io."),
//NAMESERVER("ns2.desec.org."),
END);

```

If I understand the code correctly, we just need to amend line 279:
https://github.com/StackExchange/dnscontrol/blob/43579505fff36fa7d42cfab7ba788bc16fa38384/commands/getZones.go#L272-L280

**Comment by tlimoncelli** [comment]
Thanks for catching that!  I've removed it.
