### ISSUE TITLE
A Name.com TXT entry produces quoted value

### ISSUE THREAD

**Issue by tkurki** [StackExchange/dnscontrol#3259]
**Describe the bug**
[This configuration](https://github.com/SignalK/dns/blob/main/dnsconfig.js#L21-L23) produces a quoted TXT record value:
<img width="968" alt="image" src="https://github.com/user-attachments/assets/1b09664c-0b7b-49f3-a2a1-16a6535546b1" />

If I manually remove the quotes in name.com UI subsequent `push` operations do nothing .

**To Reproduce**
See linked repo.

Log of 2 push runs: 
```
CONCURRENTLY gathering 0 zone(s)
SERIALLY gathering 1 zone(s)
Serially Gathering: "signalk.org"
******************** Domain: signalk.org
1 correction (name.com)
#1: + CREATE TXT _atproto.signalk.org "did=did:plc:b6o3a5sifu6lp7if47yabyvp" ttl=300
SUCCESS!
Done. 1 corrections.

====> THE VALUE APPEARS QUOTED. MANUALLY REMOVED QUOTES FROM THE VALUE HERE <====

signalk/dns(main|✔) %   ./run.sh push
CONCURRENTLY gathering 0 zone(s)
SERIALLY gathering 1 zone(s)
Serially Gathering: "signalk.org"
******************** Domain: signalk.org
Done. 0 corrections.

```
**Expected behavior**
The value is created without quotes. All push operations effect changes so that the actual dns is like the donscontrol configuration.

**DNS Provider**
 - name.com

**Additional context**
The record is for Bluesky.social domain verification.

**Comment by tlimoncelli** [comment]
This sounds a lot like https://docs.dnscontrol.org/developer-info/testing-txt-records 

The bad news is that the NAMEDOTCOM provider doesn't have a maintainer at this time.

The good news is that while writing some tips about how to debug this on your own, I think I found the bug.

Can you build https://github.com/StackExchange/dnscontrol/pull/3260 and see if that fixes the problem?

**Comment by tkurki** [comment]
If you tell me how 😁 - pointers?

**Comment by tlimoncelli** [comment]
hi @tkurki !  Glad to help.  I put the instructions in https://github.com/StackExchange/dnscontrol/pull/3260#issuecomment-2549290654
