### ISSUE TITLE
New patch release to fix ALIAS record type for Route 53 provider

### ISSUE THREAD

**Issue by koenrh** [StackExchange/dnscontrol#334]
Would you mind cutting a new (patch) release that includes the fix (https://github.com/StackExchange/dnscontrol/pull/311) for the ALIAS record type for the Route 53 provider? This would allow anyone to use this new record type with 'dnscontrol'. Thank you!

**Comment by tlimoncelli** [comment]
@captncraig  Any last PRs to include before we do another release?

**Comment by captncraig** [comment]
No, probably better to do now. And then we can do a major release with the new certificate things.

**Comment by tlimoncelli** [comment]
Done.

**Comment by koenrh** [comment]
Thank you!
