### ISSUE TITLE
Current master always set records as apex records

### ISSUE THREAD

**Issue by masterzen** [StackExchange/dnscontrol#341]
This issue prevents any record modifications (only apex records can be modified), worst it can rewrite all records to apex records.

As discovered in #339, when running dnscontrol, dnscontrol always wants to modify all zone records.

This is because all records coming from `dnsconfig.js` after a call to `DomainConfig.PunyCode()` have no `Label` nor `LabelFQDN` anymore. I think all providers call `PunyCode`.

This is because `PunyCode` rebuilds the `Label` from the `LabelFQDN` which itself has never been set (it used to be set in [`NormalizeAndValidateConfig`]( https://github.com/StackExchange/dnscontrol/blob/master/pkg/normalize/validate.go#L324).

**Comment by masterzen** [comment]
Note: this issue is now fixed in master thanks to PR #342.

**Comment by tlimoncelli** [comment]
+1
