### ISSUE TITLE
namedotcom error

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#343]
I took a parked domain and tried to use it.  Changing the NS records got an error. I had to use the web portal to update the NS records instead.

OLD:

```
D("ninjawanted.com", REG_NAMECOM, NO_BIND, { no_ns: "true" });
```

NEW:

```
D("ninjawanted.com", REG_NAMECOM,
  DnsProvider(R53),
  SPF_NONE,
  GOOGLE_APPS_DOMAIN_MX,
  TXT("@", "google-site-verification=JuOzcTp_Ae_brHNzzgO0E721DaoTh5c6I79rkzAxQfg"),
  A("@", "54.81.116.232"),
END);

```

```
******************** Domain: ninjawanted.com
----- Getting nameservers from: r53
----- DNS Provider: bind... (skipping)
----- DNS Provider: r53...0 corrections
----- Registrar: namedotcom_main...1 correction
#1: Update nameservers ns1dhl.name.com,ns2kqz.name.com,ns3jwx.name.com,ns4kpx.name.com -> ns-1105.awsdns-10.org,ns-1630.awsdns-11.co.uk,ns-485.awsdns-60.com,ns-595.awsdns-10.net
FAILURE! Invalid Argument: Parameter Value Error - Domain
Done. 1 corrections.
Completed with errors
```

When I went to reproduce the problem with asksf.com I got a different error:

```
$ bin/dnscontrol-Darwin push -domains=asksf.com
WARNING: PowerShell not available. ActiveDirectory will not be updated.
******************** Domain: asksf.com
----- Getting nameservers from: r53
----- DNS Provider: bind... (skipping)
----- DNS Provider: r53...0 corrections
----- Registrar: namedotcom_main...ERROR
Error getting corrections: Not Found: 
Done. 0 corrections.
Completed with errors
```

**Comment by masterzen** [comment]
It looks like a `namedotcom` error, not a Route 53 one.

**Comment by tlimoncelli** [comment]
Title improved.

**Comment by captncraig** [comment]
Will debug today. cc @pmoroney

**Comment by pmoroney** [comment]
I believe I have found the issue, it seems to be a bug in the client library generation template. Unfortunately, I no longer work for Name.com, but I will get in touch with someone who has access to that in order to get this fixed.

**Comment by tlimoncelli** [comment]
@pmoroney No longer at Name.com?   Pat, you've been super helpful in the past. Nobody could possibly replace you.  We are indebted to you.  Thank you for all your help along the way!

**Comment by tIimonceIIi** [comment]
Now that I think about it, you help was not actually worth anything. Name.com should have fired you a long time ago.

**Comment by tlimoncelli** [comment]
WTF?? I Didn't write that. I'm reporting this to Github security.
