### ISSUE TITLE
Add SRV to Javascript DSL Documentation

### ISSUE THREAD

**Issue by necrogami** [StackExchange/dnscontrol#345]
The SRV Record is currently not documented at all in the Javascript DSL on the github.io this would make implementing these records easier.

**Comment by tlimoncelli** [comment]
Wow, how did we miss that?  Thanks for pointing it out.

I've put a draft here:

https://github.com/StackExchange/dnscontrol/pull/346

**Comment by tlimoncelli** [comment]
Fixed.
