### ISSUE TITLE
SOA RR Missing

### ISSUE THREAD

**Issue by necrogami** [StackExchange/dnscontrol#352]
You can generate a SOA record via the provider for Bind however it is currently not documented.

**Comment by necrogami** [comment]
actually it appears that you cannot generate a SOA directly. This feels off as an SOA record is actually a resource record and should be the same of the likes of A, AAAA, PTR and NS however the only way to generate an SOA record for bind is using the bind default_soa option which i feel is off. 

Also bind file's dont generate an $ORIGIN line like they do a $TTL line.

**Comment by tlimoncelli** [comment]
Yes, the SOA record needs some love.   All the API-driven providers auto-generate the SOA, so they don't need it. BIND needs an SOA record, so we just take it from the existing zone file but will populate it with the default_soa values if it isn't found.  If you are interested in adding an `SOA()` function, [there are instructions here](https://stackexchange.github.io/dnscontrol/adding-new-rtypes) for adding new record types.

However let's first take a step back and ask, "What problem are you trying to solve?"   I'd like to understand how the current functionality is negatively affecting your DNS operations.

Similarly for not generating the $ORIGIN... BIND defaults $ORIGIN to be the name of the zone, which is specified outside the file as part of the named.conf file.  What problem would be solved by generating the $ORIGIN line in the file?

**Comment by necrogami** [comment]
The system i'm building won't have filenames for the dnsconfig.js file It's being auto generated and i don't like having to set the SOA details in the bind config when it's a resource record not a bind specific record. Also setting the $ORIGIN is considered best practice from everything i've seen no you don't need it but when setting other values like SOA nameserver and email it can pull the value from the $ORIGIN i will look into generating the SOA record.

**Comment by tlimoncelli** [comment]
$ORIGIN doesn't default to the filename. It defaults to the zone name.

For example if you have a zonefile named "default.zone" and use it multiple times, BIND does the right thing:

````
  zone "mydomain.com"    {    type master;   file "zones/master/default.zone";  };
  zone "otherdomain.com" {    type master;   file "zones/master/default.zone";  };
  zone "yourdomain.com"  {    type master;   file "zones/master/default.zone";  };
```

With a $ORIGIN in the file, that won't work.  I'd rather keep the flexibility that is gained by leaving it out.

**Comment by tlimoncelli** [comment]
Like I said, I'll gladly accept a PR that adds an SOA() function but I'd like to know what technical problem you are trying to solve. "it's a best practice" is an issue, but I'd like to understand how the lack of SOA stuff is effecting you.

**Comment by tlimoncelli** [comment]
By the way... you can include that info in a var or repeat it each time:

Include it in "var DNS_BIND"...

```
var DNS_BIND = NewDnsProvider("bind", "BIND", {
  default_soa: {
    master: "ns3.serverfault.com.",
    mbox: "sysadmin.stackoverflow.com.",
    refresh: 3600,    retry: 600,    expire: 604800,    minttl: 1440,
  },
  default_ns: [    "ns1.serverfault.com.",    "ns2.serverfault.com.",   "ns3.serverfault.com.",   "ns4.serverfault.com." ],
});

D("domain.com", REG_FOO, DNS_BIND,
  A("foo", "1.2.3.4"),
  A("bar", "2.2.2.2")
)
```

Or include it in each domain definition...

```
D('domain.com', REG_FOO,
  NewDnsProvider("bind", "BIND", {
  default_soa: {
    master: "ns3.serverfault.com.",
    mbox: "sysadmin.stackoverflow.com.",
    refresh: 3600,   retry: 600,   expire: 604800,   minttl: 1440,
  },
  default_ns: [
    "ns1.serverfault.com.",   "ns2.serverfault.com.",    "ns3.serverfault.com.",    "ns4.serverfault.com.",  ],
  }),
  A("foo", "1.2.3.4"),
  A("bar", "2.2.2.2")
}
```

**Comment by tlimoncelli** [comment]
With the changes in https://github.com/StackExchange/dnscontrol/pull/652 and others, this is sufficiently remediated.
