### ISSUE TITLE
dynamically creating dnsconfig.js?

### ISSUE THREAD

**Issue by computersrmyfriends** [StackExchange/dnscontrol#354]
HI,
Do you have any suggestions on how I can dynamically create the dnsconfig.js since its not a json?

Right now, according to your docs, I need to manually create a dnsconfig.js by hand right?

I can use nodejs or python for this. but how do I dynamically control this? I mean is there no standard way? Please suggest.

or even if I can dynamically pass the domain name and record names as arguments to "dnscontrol push", it would help. Please let me know which way I can try.

Thank you!

**Comment by tlimoncelli** [comment]
It is easy to dynamically generate the middle of the file, but not the beginning or end.

A very simple system:

Create a file called dnsconfig.js.head which includes the opening definitions, etc. and a dnsconfig.js.tail that contains anything you want at the end (this may be empty).  Then dynamically generate the middle as dnsconfig.js.data.    To run dnscontrol, concatenate those files:

```
$ vim dnsconfig.js.head
$ vim dnsconfig.js.tail
$ generate_my_stuff >dnsconfig.js.data
$ cat dnsconfig.js.head dnsconfig.js.data dnsconfig.js.tail >dnsconfig.js
$ dnscontrol push
```

Of course, you should store these files in Git and automate this in a Makefile or your CI system.  The point being that the hand-created stuff should go in the head and tail files.

You could use this whether you want to generate all your domains, or if you want to generate a different domain each time.

**Comment by captncraig** [comment]
Alternatively, there is an intermediate json format that may be suitable for input to dnscontrol. It can accept (or create) that if you look at the various flags the preview command takes.

**Comment by LTGIV** [comment]
FWIW, @computersrmyfriends, this is how I do it via Bash-script: https://thad.getterman.org/2017/12/11/dnscontrol-compiler

**Comment by wavded** [comment]
@captncraig is this intermediate JSON format documented anywhere?

**Comment by wavded** [comment]
@tlimoncelli currently we have configuration loaded into a database and we wanted to generate the DNS entries from that.  If the DSL could pull in JSON files we possibly could just use the JavaScript DSL, but doesn't seem like it supports that.  But maybe there is a better way we haven't thought of yet?

**Comment by tlimoncelli** [comment]
Ah, I see.  In that situation I think it would be easier to generate the dnsconfig.js than the JSON file.  The example in https://github.com/StackExchange/dnscontrol/issues/354#issuecomment-380563881 is exactly what you need to do.  (The .head and .tail files might be empty).

**Comment by tlimoncelli** [comment]
Is this ready to be closed?

**Comment by tlimoncelli** [comment]
Not hearing a response, I'm assuming this is resolved. Please re-open the issue if you need further assistance.
