### ISSUE TITLE
Specific domain issue with flattener test tool

### ISSUE THREAD

**Issue by balabanov** [StackExchange/dnscontrol#360]
#### Steps to reproduce:

* Open https://stackexchange.github.io/dnscontrol/flattener/index.html
* Enter domain name `balabanov.co` and press Lookup

#### Actual result:

Console error `flattener.js:1412 Uncaught (in promise) Error: In included spf: In included spf: In included spf: In included spf: Unsupported spf part`.

Full log attached [stackexchange.github.io-1525329775853.log](https://github.com/StackExchange/dnscontrol/files/1969829/stackexchange.github.io-1525329775853.log)

#### Expected result:

Valid output, the domain has a valid SPF record

**Comment by tlimoncelli** [comment]
I really dislike having code that works around people's broken SPF records.  Ignoring extra whitespace isn't so bad, but it becomes a slippery-slope.  Eventually we have exponentially increasing number of edge cases and tests to manage.

**Comment by captncraig** [comment]
Kinda agree with Tom that it is a slippery slope. Leave it up to him if we merge that or not.

**Comment by captncraig** [comment]
I actually merged it since I updated the html version from another unrelated issue that I wanted to get out anyway. Cheers.

**Comment by tlimoncelli** [comment]
I agree with the merge.  This seems innocuous and at the minimum we shouldn't crash.
