### ISSUE TITLE
convertzone produces deprecated NAMESERVER entries

### ISSUE THREAD

**Issue by frazor** [StackExchange/dnscontrol#362]
It seems convertzone still generates NAMESERVER entries with two fields:
`  NAMESERVER("@", "ns.fluffy.clouds", TTL(3600)),`

But like referenced in another issue ( https://github.com/StackExchange/dnscontrol/issues/348 ) NAMESERVER only accepts one field now.

```
$ dnscontrol preview
Executing javascript in dnsconfig.js: NAMESERVER only accepts one argument for name.
$ 
```

This is a paraphrasing of my ingoing bind file:
```
$ORIGIN .
$TTL 3600 ; 1 hour
fluffy.clouds IN SOA ns.fluffy.clouds. <snip>
    NS ns.fluffy.clouds.
<snip>
```

The domain name is obviously a fake one, but I've taken care to reproduce other syntax according to my files.

I've opened cmd/convertzone/main.go up, but to be honest I'm not qualified to make a change in that code that would fix my problem. Would appreciate any help in the matter.

**Comment by tlimoncelli** [comment]
Yup. Definitely a bug.

NOTE TO SELF: We really need to make a test harness so that bugs like this get noticed, fixed, and stay fixed.
