### ISSUE TITLE
Determine corrections in parallel

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#38]
dnscontrol is slow when there are many domains because they are processed sequentially.  It should be possible to gather all the information related to what corrections are needed in parallel.  (Updates should be done serially, at least initially.)

**Comment by captncraig** [comment]
Will also require making sure individual providers do not write to console out of order. We would want to collect the results in order and print them appropriately.

**Comment by captncraig** [comment]
I intend to add a `Logger` to the domain config that the provider gets. It can `Warn` and `Debug` on that logger without writing to `log` or console directly. Then we can run each domain in parallel, and even providers within a domain, by giving each provider a different logger that saves messages. Then print them in order as they finish.
