### ISSUE TITLE
AWS Token is alway blank - this is required in some AWS use cases

### ISSUE THREAD

**Issue by shleeable** [StackExchange/dnscontrol#381]
The third token param is always blank by default. but I need to be able to change it to work with my codebuild workflow.

https://github.com/StackExchange/dnscontrol/blob/921fa9849001d42494b23feadbe069d1dd46d916/providers/route53/route53Provider.go#L46

Can you please support the optional token value in creds.json for AWS

as per https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#NewStaticCredentials

**Comment by ashleyhull-versent** [comment]
https://github.com/StackExchange/dnscontrol/pull/386

**Comment by ashleyhull-versent** [comment]
hey team, I've forked dnscontrol to fix this bug... but I'd love to get back onto master.

Please pass the token down with the other variables.

`keyID, secretKey, tokenID := m["KeyId"], m["SecretKey"], m["Token"]`

**Comment by tlimoncelli** [comment]
Fixed by https://github.com/StackExchange/dnscontrol/pull/401
