### ISSUE TITLE
How to override global default TTL on provider level

### ISSUE THREAD

**Issue by papakai** [StackExchange/dnscontrol#383]
I recognized that dnscontrol sets TTL to 300 if not provided. Our backend system would set it to 3600.
I know there are different possibilities to add a default ttl in dnsconfig.js, but imo it would be more useful if we could set a default ttl configuration fallback within the provider module itself so that in case no TTL is given, it takes that one provided in the provider module instead of the global defined one. This would drop out the need to explicitely configure it in configuration file - so existing domain names will definitely benefit of this. In case a customer forgets about adding that special Default  TTL in his configuration, existing domains using the backend system default TTL of 3600 will be updated to 300 and would again need to updated to 3600. Also it makes the dnsconfig file more compact if it could be left out there and it would synchronize the settings with our backend system settings.

I hope you could follow me. Is it possible to get this realized in the provider module itself? if yes how?

TIA!
Kai

**Comment by captncraig** [comment]
I think if you do `DEFAULTS( DefaultTTL(3600));` at the top of your file, it will apply that to all domains.

**Comment by captncraig** [comment]
Oh, you mean different ttls for different providers? I don't think that's something I've considered yet.

**Comment by captncraig** [comment]
At one point it did behave this way. If a record made it all the way to the provider without a ttl, it was up to the provider to specify the default. For some reason we moved that logic into the central validation / normalization pass for consistency. I think it may have been too difficult to communicate that convention and provider authors kept missing it and getting confused. 

If a provider has special restrictions or quirks about ttls (some have minimums or maximums or whatever), the specific driver is free to change records at the last minute to make them make sense. I'm just not quite clear what behaviour on the provider side is causing problems with the default ttl of 300. Is it that all existing records need to be updated to 300? Can you not create records with a specific ttl, so it needs a two-step create then update? 

You can do a global default ttl in your dns config with `DEFAULTS( DefaultTTL(3600));`, but I do not believe that can be done on a provider-by-provider basis. It is probably best not to have different ttls in different places if using multiple dns providers.

**Comment by papakai** [comment]
Hmm... thought about `DEFAULTS(DefaultTTL(3600))`... this would set it globally in config file also for other potential dns providers in use. Is it somehow possible to set it as DNS provider configuration? So through `NewDnsProvider( name, type, meta )`?

**Comment by tlimoncelli** [comment]
(sorry for the radio silence)

Because dnsconfig.js is javascript, you could write a function that does the right thing depending on provider.  Other than that, I think `DEFAULTS(DefaultTTL(3600))` is the best bet here.

Let's zoom out a bit: What are you trying to achieve?

**Comment by pkorovin** [comment]
I noticed that DEFAULTS(DefaultTTL(3600)) doesn't apply to bind provider generated SOA record, which is always set to TTL=300. Is it possible to fix this behaviour?

**Comment by tlimoncelli** [comment]
@pkorovin Could you file a separate issue about that?  (preferably with an example that demonstrates the bug, plz)

**Comment by pkorovin** [comment]
@tlimoncelli Sure, here it is: #802

**Comment by tlimoncelli** [comment]
Not hearing any disagreement, I'm closing this issue, Please re-open if needed.
