### ISSUE TITLE
Gandi LiveDNS: handling access to domains from an organization/person

### ISSUE THREAD

**Issue by vincentbernat** [StackExchange/dnscontrol#391]
Hey!

Gandi Live DNS API has the notion of sharing ID to be able to modify a domain attached to an organization. It is quite unknown how it should work. The [documentation](http://doc.livedns.gandi.net/#work-with-zones) says:

> Note: You can only associate domains and zones that share the same organization or, "sharing space". Therefore, If you want to create a new zone and attach it to a domain that is in an organization (ie. not your personal account), you must create the zone with the same SHARING_ID of the domain.
>
> Unfortunately, there is no API that returns the SHARING_ID.To find the SHARING_ID, you must use the v5 website and navigate to the dashboard of the organization that owns the domain. The sharing_id will be in the URL and will immediateliy follow /dashboard/.
>
> You then need add the SHARING_ID to the URL when you send the POST command.

First consequence, from the documentation, it doesn't seem possible to automatically get this sharing ID. It has to be provided by the user. However, some had success without providing it when the zone is created for the first time by dnscontrol. It is unknown if this works when the first zone attached to a domain is created in the web interface, then modified by dnscontrol.

Second consequence, when a domain is attached to another account a user has rights to modify, the documentation doesn't state it's possible for a user to modify the domain. It has been verified a user can read the records of the domain through the `/domain` endpoints, but the provided links to inspect the zone by UUID through the `/zone` endpoints are not reacheable (for reading or writing). Adding a sharing ID doesn't affect this behavior.

From this point, I gave up investigating this issue. It was easier to just generate an API key for the owner of the domain and use this key directly. If people have more insights on how it should work, please report here.

See #304 for initial discussions around this.

**Comment by tlimoncelli** [comment]
@vincentbernat Are you able to do everything you need at this point, or are you blocked?

**Comment by vincentbernat** [comment]
No, everything works for me. Thanks for your concern! :)

**Comment by tlimoncelli** [comment]
In that case, I think we should document that people can create the API keys as you did. Can you suggest some text and/or submit a PR?  Thanks!

**Comment by tlimoncelli** [comment]
ok!
