### ISSUE TITLE
I suggest to create home brew formula for dnscontrol and convertzone binary files

### ISSUE THREAD

**Issue by harobed** [StackExchange/dnscontrol#396]
Hi,

I suggest to create [home brew formula](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md) for `dnscontrol` and [`convertzone`](https://github.com/StackExchange/dnscontrol/tree/master/cmd/convertzone) binary files.

Best regards,
Stéphane

**Comment by captncraig** [comment]
I had this thought recently as well. Very soon, the convertzone will not be a seperate binary, but a subcommand. I will look into seeing how to package for homebrew at some point when I get time. 

Unless you would like to volunteer to take the lead on this?

**Comment by murarisumit** [comment]
@captncraig If it is still open I would like to pick it up, haven't created a brew formula before. 
I like this tool, so want to volunteer for this.

**Comment by captncraig** [comment]
go for it!

**Comment by murarisumit** [comment]
@captncraig dnscontrol brew is done. We can close it now.

**Comment by tlimoncelli** [comment]
Thanks!
