### ISSUE TITLE
Cloudflare Page Rules for forcing HTTPS

### ISSUE THREAD

**Issue by Southclaws** [StackExchange/dnscontrol#405]
Hi, moved all my domains to this tool recently, absolutely loving it, great work!

One thing I'd like to automate is [Cloudflare page rules for forcing HTTPS](https://support.cloudflare.com/hc/en-us/articles/200170536-How-do-I-redirect-all-visitors-to-HTTPS-SSL-) - reason being, I have a site that doesn't work for users on HTTP, redirecting at the server level [isn't possible](https://support.cloudflare.com/hc/en-us/articles/115000219871-Why-does-Flexible-SSL-cause-a-redirect-loop-) so it must be configured at the Cloudflare level.

Is there a way to do this with `CF_TEMP_REDIRECT`? It implies that it can be used to set arbitrary Cloudflare "Page Rules" but so far I've only used it to create a basic URL redirect. Can I use it to create a redirect from `http://*.site.com/*` to `https://*.site.com/*`?

**Comment by tlimoncelli** [comment]
There isn't but it should be easy to add.  Look at the code for CF_TEMP_REDIRECT and do something similar. It will require changes to the JS and Go code.

**Comment by Southclaws** [comment]
Thanks, I'll take a look and see if I can figure something out and make a PR!

**Comment by tlimoncelli** [comment]
I'm pretty sure that https://github.com/StackExchange/dnscontrol/issues/433 fixed this.  Please confirm?

**Comment by tlimoncelli** [comment]
Yes, this was fixed. Closing. (Please re-open if you find an issue.)

```
$ grep -ri cloudflare_universalssl pkg/js/helpers.js providers/cloudflare/cloudflareProvider.go docs/_providers/cloudflare.md
pkg/js/helpers.js:var CF_UNIVERSALSSL_OFF = { cloudflare_universalssl: 'off' };
pkg/js/helpers.js:var CF_UNIVERSALSSL_ON = { cloudflare_universalssl: 'on' };
providers/cloudflare/cloudflareProvider.go:	metaUniversalSSL  = "cloudflare_universalssl"
docs/_providers/cloudflare.md:   * `cloudflare_universalssl` (unset to keep untouched; otherwise "on, or "off")
docs/_providers/cloudflare.md:var CF_UNIVERSALSSL_OFF = { cloudflare_universalssl: 'off' };
docs/_providers/cloudflare.md:var CF_UNIVERSALSSL_ON = { cloudflare_universalssl: 'on' };
```
