### ISSUE TITLE
SRC value does not contain 4 fields

### ISSUE THREAD

**Issue by mapperr** [StackExchange/dnscontrol#408]
Hi guys,

I'm getting a strange error when trying to preview my domain on DNSimple.
I suppose the "SRC" is a typo, meant to be "SRV".

The thing is it seems DNSimple does not return the priority number (or maybe dnscontrol does not detect it).

Here is the error:

```
docker run --rm -it -v $(pwd)/dnsconfig.js:/dns/dnsconfig.js -v $(pwd)/creds.json:/dns/creds.json stackexchange/dnscontrol dnscontrol preview
******************** Domain: xxxxxxxxx.xx
----- Getting nameservers from: dnsimple
----- DNS Provider: dnsimple...panic: unparsable record received from dnsimple: SRC value does not contain 4 fields: ("1 443 sipdir.online.lync.com.")

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/dnsimple.(*DnsimpleApi).GetDomainCorrections(0xc4202b2f60, 0xc4204cd2c0, 0x8, 0xc4204cd200, 0x1, 0x0, 0x0)
        /go/src/github.com/StackExchange/dnscontrol/providers/dnsimple/dnsimpleProvider.go:95 +0x1246
github.com/StackExchange/dnscontrol/commands.run(0xe89d84, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe882c6, 0xa, 0x0, ...)
        /go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:129 +0x3d7
github.com/StackExchange/dnscontrol/commands.Preview(0xe89d84, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe882c6, 0xa, 0x0, ...)
        /go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:81 +0x74
github.com/StackExchange/dnscontrol/commands.glob..func4.1(0xc420230160, 0x0, 0xc420230160)
        /go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x4e
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0xcd5180, 0xc420136040, 0xc420230160, 0x0, 0xc42019a9c0)
        /go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0xe85a34, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xeae3ec, 0x4e, 0x0, ...)
        /go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:165 +0x4bb
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc4201ba1c0, 0xc42000c060, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:259 +0x740
github.com/StackExchange/dnscontrol/commands.Run(0xc42022c060, 0x5e, 0xc091f2)
        /go/src/github.com/StackExchange/dnscontrol/commands/commands.go:50 +0x18a
main.main()
        /go/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34
```

**Comment by tlimoncelli** [comment]
CC: @aeden

**Comment by aeden** [comment]
We return the priority in its own attribute (for legacy reasons) so the adapter should use that.

**Comment by aeden** [comment]
@tlimoncelli can you assign this to me please.

**Comment by tlimoncelli** [comment]
Odd... Github won't let me assign it to anyone.  Please consider it assigned to you while I figure out why Github is acting weird.

**Comment by tlimoncelli** [comment]
@aeden Two things: 1) if my big global change last spring broke this, I apologize.  2) Does the integration test run clean?  If it doesn't catch this bug please let me know because I'd like to enhance the tests to catch this kind of thing.

**Comment by onlyhavecans** [comment]
@tlimoncelli I was asked to look into this @aeden. If you can also ping me on issues with the dnsimple provider I would be happy to help.

I compiled master as is (without the additional SRV case) and was not able to replicate this issue against my domains with SRV records. Could this have been fixed elsewhere in the last two weeks?
I also tested the latest docker image and could not replicate.

I don't see any tests for this provider at the moment but if you can point out what you believe to be the exemplar tests I can implement some.

@mapperr What version are you running? Can you provide the line from your configuration?

**Comment by onlyhavecans** [comment]
Perfect! I think I found the bug and am going to fix. I had some bad data in my personal test domain

**Comment by tlimoncelli** [comment]
Thanks, @onlyhavecans!  We appreciate the contribution!

**Comment by tlimoncelli** [comment]
Glad to hear it's working!  Thanks @onlyhavecans!
