### ISSUE TITLE
Provider request: Oracle Cloud Infrastructure

### ISSUE THREAD

**Issue by Marcus-James-Adams** [StackExchange/dnscontrol#419]
More info at https://cloud.oracle.com/en_US/edge/dns/faq

**Comment by tlimoncelli** [comment]
We've noted your request for this provider!  
 
As an open source project, we are glad to accept PRs that add new
providers. We encourage you to try adding this provider yourself.  The
process is well-documented here:
https://stackexchange.github.io/dnscontrol/writing-providers

Many people have reported that adding a provider was their first
experience writing Go.

**Comment by tlimoncelli** [comment]
FYI: Now that it is tagged "provider-request", we close the issue.   I know that's a bit confusing, but it will remain on the "requested provider" list where people can find it.
