### ISSUE TITLE
Support for Azure DNS

### ISSUE THREAD

**Issue by xt0rted** [StackExchange/dnscontrol#42]
The docs are at https://docs.microsoft.com/en-us/azure/dns/ and there's a GO SDK which looks to have DNS support at [Azure/azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go)

I don't have the time right now to try adding this in, but if someone else does I can help test it out.

**Comment by captncraig** [comment]
Azure should be very similar in api style to route 53 and google cloud. One issue in the past has been lack of support for fully modifying apex NS records (https://feedback.azure.com/forums/217313-networking/suggestions/17222627-allow-modifying-ns-records-in-apex-of-dns-zone), but that is not a hard blocker. Just prevented us from using it in a dual-dns-host setup.

**Comment by tlimoncelli** [comment]
FYI: The NS record issue is fixed.

**Comment by tlimoncelli** [comment]
I've added this to the [list of requests](https://stackexchange.github.io/dnscontrol/provider-list). If someone would like to volunteer to implement this, please re-open this issue. 

Advice on how to write a provider is documented [here](https://stackexchange.github.io/dnscontrol/writing-providers). Also, speak up in this issue and someone will get back to you asap.

**Comment by vatsalyagoel** [comment]
can the provider-request label be removed from this?
