### ISSUE TITLE
Provider request: Alibaba cloud 

### ISSUE THREAD

**Issue by Marcus-James-Adams** [StackExchange/dnscontrol#420]
More information at
https://www.alibabacloud.com/help/product/34269.htm?spm=a3c0i.228936.1218286.3.2054221eXUxW1G

**Comment by tlimoncelli** [comment]
Thank you for requesting this provider!

I've tagged this issue as a provider-request.  It will (soon) be listed as a "requested provider" on the provider list web page: 
https://stackexchange.github.io/dnscontrol/provider-list

I will now close the issue.  I know that's a bit confusing, but it will remain on the "requested provider" list.

If someone would like to volunteer to implement this, please re-open this issue and add the tag `has-pr`.

We encourage you to try adding this provider yourself.  We've tried to
make the process as friendly as possible.  Many people have reported
that adding a provider was their first experience writing Go.  The
process is documented here:
https://stackexchange.github.io/dnscontrol/writing-providers
If you need assistance, please speak up in this issue and someone will get back to you ASAP.
