### ISSUE TITLE
Proper capitalization

### ISSUE THREAD

**Issue by nikolay** [StackExchange/dnscontrol#428]
It's Cloudflare (not CloudFlare) and DigitalOcean (not Digitalocean).

**Comment by tlimoncelli** [comment]
True!  Good catch!

Would you like to submit a PR?

**Comment by nikolay** [comment]
I will, thank you!

**Comment by nikolay** [comment]
@tlimoncelli Here it is: https://github.com/StackExchange/dnscontrol/pull/429

**Comment by BenoitKnecht** [comment]
#429 has been merged, and it's part of the v2.9 release, so I guess this issue can be closed now.

**Comment by tlimoncelli** [comment]
Good catch. Thanks!
