### ISSUE TITLE
Support more than one label on SPF_BUILDER

### ISSUE THREAD

**Issue by virtualroot** [StackExchange/dnscontrol#432]
This might be very handy

```
    SPF_BUILDER({
      labels: ['dev', 'production', 'staging'],
        parts: [
            'v=spf1',
            'include:mailgun.org',
            'include:spf.mailjet.com',
            '-all'
        ]
    }),
```

**Comment by tlimoncelli** [comment]
How would this work?  Would they all point to the same "overflow" records?

**Comment by virtualroot** [comment]
I thought a simple [iteration over label](https://git.io/fhtxi) would be enough, but I found out that overflow, if defined, only works for `@` label.

I think after the first SPF record all of them should include the same "overflow" records.

**Comment by tlimoncelli** [comment]
CC: @captncraig

**Comment by tlimoncelli** [comment]
This is stale. I'm closing this. Please re-open if needed. Thanks!
