### ISSUE TITLE
[Cloudflare] Add CF_ALWAYS_HTTPS_ON function

### ISSUE THREAD

**Issue by virtualroot** [StackExchange/dnscontrol#433]
[Always Use HTTPS](https://api.cloudflare.com/#zone-settings-get-always-use-https-setting) is a Cloudflare feature disabled by default that makes all requests for URLs that use "HTTP" redirect to the equivalent "HTTPS" URL with a 301. 

We use `CF_REDIRECT` to achieve that same behavior, it would be great to bring something like `CF_ALWAYS_HTTPS_ON`, where we can serve the same functionality and at the same time save one precious page rule.

**Comment by tlimoncelli** [comment]
Sounds good!  Would you like to attempt a PR?

**Comment by virtualroot** [comment]
I'll give it a try as soon as I get some free time in my hands.

**Comment by DrMurx** [comment]
Isn't this a duplicate of #405?

**Comment by captncraig** [comment]
Technically, yes it is. I'll close this one. Good catch. That doesn't prevent you (or anyone else) from attempting a pr on it though @virtualroot
