### ISSUE TITLE
Option to return non-zero when preview detects changes

### ISSUE THREAD

**Issue by miguelbernadi** [StackExchange/dnscontrol#437]
We are migrating to DNSControl and we would like to have a way to detect when there are differences between the current Zone and the one defined in DNSControl. This is, at least for now, to detect manual modifications done during interventions that would not be reflected in the configuration.

My idea would be to add a flag to `dnscontrol preview` so it returns a non-zero code when there are corrections detected.

Is this something desirable/acceptable? Is there already a way to have this workflow? What I'm currently doing is parsing the output of the tool to identify if there are changes to be done but a return-code approach would be much cleaner, in my opinion.

**Comment by tlimoncelli** [comment]
That's a great idea.  In fact, it should be how preview works, no flag needed.  

Would you consider making a PR?

**Comment by miguelbernadi** [comment]
I'll try to add that.
