### ISSUE TITLE
Report if changes were made using exit codes

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#447]
CC: miguelbernadi

There is a desire to be able to report back whether changes happened using an exit code.  To retain backwards compatibility, this needs to be activated using a flag.

My proposal is to model the flag after Puppet's `--detailed-exitcodes` flag:

```
* --detailed-exitcodes:
  Provide transaction information via exit codes. If this is enabled, an exit
  code of '2' means there were changes, an exit code of '4' means there were
  failures during the transaction, and an exit code of '6' means there were both
  changes and failures.
```

In other words, the 2^1 bit means "changes" and the 2^3 bit means "failure". Yeah binary!!

I think this flag should apply to `preview` and `push`.  In the case of `preview`, the flag indicates changes would be made.

**Comment by miguelbernadi** [comment]
I like the `--expect-no-changes` approach as flag for `preview`.

**Comment by tlimoncelli** [comment]
I agree with @captncraig 's analysis.  `--expect-no-changes` works for me too!

**Comment by miguelbernadi** [comment]
Then I'll try to add the flag sometime this week and open a PR for it.

**Comment by miguelbernadi** [comment]
PR is up for discussion.
