### ISSUE TITLE
Nameserver not found error Cloudflare

### ISSUE THREAD

**Issue by jr-RXcode** [StackExchange/dnscontrol#457]
Trying out dnscontrol for the first time and everything was going good until one of our domains started to produce the following message 
 
----- Getting nameservers from: cloudflare
Nameservers for mydomain not found in cloudflare account

Why do the rest of my cloudflare zones work except for one. How can I enable additional logging to troubleshoot what's going on using the -v flag does not produce any additional information.

**Comment by tlimoncelli** [comment]
Are you using the NAMESERVER() function?  Check the spelling of the NS hosts.

Can you post a (redacted) copy of the D() statement?

**Comment by jr-RXcode** [comment]
I feel so dumb... it was a typo in the domain name. Basically the error was saying that the domain was not found. 

Thanks for the quick response though. I will mark this issue as close

**Comment by tlimoncelli** [comment]
No problem!  You aren't the first person to mis-type a domain name :-)
