### ISSUE TITLE
README is a bit stale

### ISSUE THREAD

**Issue by noloader** [StackExchange/dnscontrol#458]
It looks like OpenSRS was provided with [GH #275](https://github.com/StackExchange/dnscontrol/pull/275) but the README does not list OpenSRS as a supported platform.

Hat tip for OpenSRS support.

I'd love to see a feature that fetches my current IP from somewhere like `https://ifconfig.me/` and then push updates as required. That would cut-out the dynamic DNS middlemen.

**Comment by tlimoncelli** [comment]
Hmm... I wonder how we missed that.  Anyway... I've started a PR here: https://github.com/StackExchange/dnscontrol/pull/459

**Comment by tlimoncelli** [comment]
Hey @philhug could you take a look at this?

I started a branch (https://github.com/StackExchange/dnscontrol/tree/opensrs2) which fixes some of the documentation but I'd like you to take over and finish this.

**Comment by philhug** [comment]
Ok, will do.
