### ISSUE TITLE
Duplicate records should be caught during validation

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#466]
The validation code should make sure that there are no duplicate records.

This will avoid finding them much later, when all we can do is panic, such as this one from https://github.com/StackExchange/dnscontrol/issues/464:

```
panic: DUPLICATE D_RECORD FOUND: {bitnest.co.uk NS} ns1.digitalocean.com. ttl=300
```

This is something that could be easily added to `pkg/normalize/validate.go:NormalizeAndValidateConfig()`

**Comment by TomOnTime** [comment]
Fixed in 98232b0933deca551bf6bffb39763b3aee115cff
