### ISSUE TITLE
Stumbling when attempting to follow the documentation

### ISSUE THREAD

**Issue by chines** [StackExchange/dnscontrol#47]
This project seems like an AMAZING solution for a common problem and one that is definitely affecting me @ work.  I'm not the best programmer and have no experience with Go, though, and having some trouble following the documentation.

From the provided examples, when attempting to do a basic update to a Route53 zone:

```
[root@dflgnvweby0 a]# cat dnscontrol.js 
var registrar = NewRegistrar("name.com", "NAMEDOTCOM");
var route53 = NewDnsProvider("route53", "ROUTE53");


D("aws.thig.com", registrar, DnsProvider(route53),
    A("image101", "10.9.1.101"),
    A("image102", "10.9.1.102")
);

[root@dflgnvweby0 a]# cat providers.js
{
  "route53":{
    "KeyId": ";sdklfja;sdfjasdlfjasldfj",
    "SecretKey": "not_anything_real"
  }
}
{
  "name.com":{
    "apikey": "yourApiKeyFromName.com-klasjdkljasdlk235235235235",
    "apiuser": "yourUsername"
  }
}
[root@dflgnvweby0 a]# ./dnscontrol-Linux -js dnscontrol.js -creds providers.js preview
2017/03/17 08:52:56 main.go:117: Error creating registrars: Registrar name.com not listed in -providers file.
[root@dflgnvweby0 a]# 
[root@dflgnvweby0 a]# ./dnscontrol-Linux -js dnscontrol.js -providers providers.js preview
2017/03/17 08:54:56 main.go:113: error loading provider configurations: While reading provider credentials file creds.json: open creds.json: no such file or directory
```

Some other questions:

D
What is the default location for dnsconfig.js and providers.json (I've tried same folder, GOPATH, some other various folders, it only seems to work when I provide the arguments -js and -creds??)
What is creds.json?  is that the same as providers.json?  What would be in one as opposed to the other?

Would it be possible to have some more working real world examples?

Thanks again in advance, I'm really looking forward to using this tool...

**Comment by mhenderson-so** [comment]
Hey @chines 

First thing I noticed in your providers.js is that your javascript isn't well formed. If you throw it into http://jsonlint.com/ you'll find a few errors. It should really read:

```
{
	"route53": {
		"KeyId": ";sdklfja;sdfjasdlfjasldfj",
		"SecretKey": "not_anything_real"
	},
	"name.com": {
		"apikey": "yourApiKeyFromName.com-klasjdkljasdlk235235235235",
		"apiuser": "yourUsername"
	}
}
```

I'd start by getting your providers.json file corrected, and see if your problems persist.

The default location for your dnsconfig.js and providers.json file is in your current working directory - i.e. if you don't specify an explicit location, it will look where you are right now (not where the binary lives). So if you're in `~/mydns/` when you run `dnscontrol`, then that's where it's going to look.

`creds.json` is the same as `providers.json` as far as I'm aware. We use `creds.json` internally at Stack - the I hadn't actually seen `providers.json` until I read the documentation on the project, so I'll need to defer to @captncraig on that one I'm afraid.
