### ISSUE TITLE
Question: R53_ALIAS with dual DNS

### ISSUE THREAD

**Issue by sajal** [StackExchange/dnscontrol#470]
I want to use `ALIAS` with dual DNS providers, where one of them is Route 53 and the other supports `ALIAS` natively.

The target of `ALIAS` is another record in the same zone.

If I use `R53_ALIAS`, it would fail with the non-route53 provider, if I use `ALIAS` it would fail for route 53.

Is there a way to define conditional records? Such that to only apply a certain record only for a particular provider?

**Comment by tlimoncelli** [comment]
That's an interesting problem. Sadly right now we don't have any kind of conditional records.

Our general philosophy is that pseudo-types like ALIAS should be generic enough that each provider can do the right thing.  This way if you change providers it should always work.

Our concern is that if ALIAS accepted a ZONE_ID(), then it would work when switching to R53, but could break when switching away from R53.

We figured that if you are making a big change, like moving to a new provider, having to change R53_ALIAS() to ALIAS() wouldn't be a hardship. In fact, it would force you to think about each R53_ALIAS(), and decide what to do for the new provider.

However we've gotten enough requests for this that we can't ignore it.  If someone were to send us a PR, we'd accept it.

If you are looking for a temporary workaround, remember that the dnsconfig.js file is javascript. I think you could do something like:

```
if (1) {
  var MYPROVIDER=R53
  var MYALIAS=R53_ALIAS
} else {
  var MYPROVIDER=CLOUDFLARE
  var MYALIAS=ALIAS
}

D()...
...
   MYALIAS('one', 'two', ZONE_ID())
```

**Comment by tlimoncelli** [comment]
Idle for 1 year.  Please reopen if this is still an issue.
