### ISSUE TITLE
SPF_BUILDER should support redirect

### ISSUE THREAD

**Issue by silverl** [StackExchange/dnscontrol#472]
I'm following the examples in the docs to use SPF_BUILDER instead of my previous method of string concat. We passed the 10 lookup limit, and I'm trying to unroll some things. Obvious case for SPF_BUILDER.

I noticed your example uses Hubspot. We also use Hubspot. However, the SPF host they gave us is `5113190.spf08.hubspotemail.net`, whereas yours is `450622.spf05.hubspotemail.net`.

`5113190.spf08.hubspotemail.net` resolves thusly:

```
$ dig 5113190.spf08.hubspotemail.net txt

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> 5113190.spf08.hubspotemail.net txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38345
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;5113190.spf08.hubspotemail.net.        IN      TXT

;; ANSWER SECTION:
5113190.spf08.hubspotemail.net. 1799 IN TXT     "v=spf1 redirect=_aspf.spf08.hubspotemail.net"

;; Query time: 38 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon May 13 12:14:50 DST 2019
;; MSG SIZE  rcvd: 116
```

This produced the validation error:
```
ERROR: In included spf: Unsupported spf part redirect=_aspf.spf08.hubspotemail.net
```

I could put `_aspf.spf08.hubspotemail.net` in my SPF, but there are obvious risks. I have no idea if Hubspot will ever change this.

This is preventing adoption of SPF_BUILDER.

**Comment by tlimoncelli** [comment]
Yeah, we only supported what we needed for our own record so far :-)

Would you be interested in working on this?  This seems like an easy one.  From an implementation standpoint,  `redirect` can be handled like `include` except it has to be the last item in the record.

CC: @captncraig

**Comment by silverl** [comment]
Wish I could take it up. I gave the same response to someone on my own OSS project this morning :)

**Comment by tlimoncelli** [comment]
@silverl I've implemented a minimal implementation. It only implements the situation where `redirect:` is the last item in the SPF record.  Does that suit your needs?  

See the PR https://github.com/StackExchange/dnscontrol/pull/506

**Comment by silverl** [comment]
I believe that should work nicely, thank you!

**Comment by silverl** [comment]
I'm trying to test this out with both the docker image on our build server (did a fresh docker pull and removed the old image) and also Go on my local workstation. Pretty sure I've got things right, but I'm still hitting the same issue in `dnscontrol check`.

```
2 Validation errors:
ERROR: In included spf: Unsupported spf part redirect=_aspf.spf08.hubspotemail.net
ERROR: In included spf: Unsupported spf part redirect=_aspf.spf08.hubspotemail.net
Exiting due to validation errors
```

Yes, I have it twice in the same config file.

**Comment by tlimoncelli** [comment]
Hmmm... are you sure you're getting commit 2d9d93653b37448b0e5efe38dc10c7e55096533f or later? That seems like the error you would get with the old release.

**Comment by silverl** [comment]
I did an update with `go get -u`. Also using the latest docker image that was built within an hour of your merge to master.

**Comment by tlimoncelli** [comment]
does `git log` show something like:

```
commit 2d9d93653b37448b0e5efe38dc10c7e55096533f (HEAD -> master, origin/master, origin/HEAD)
Author: Tom Limoncelli <tlimoncelli@stackexchange.com>
Date:   Wed Jun 19 18:46:56 2019 +0100

    SPF Optimizer: Add "redirect:" support (#506)
    
    FYI: The support is very minimal. It only supports redirect if it is the last item in an SPF record. At that point, it is equivalent to include.
    
    * In SFP, treat redirect like a special include.
    * Document SPF redirect: limited implementation.
```

**Comment by silverl** [comment]
I just built it on Windows using the build.ps1 script from latest master. Your commit is in the git log. I am still getting the validation errors.

**Comment by silverl** [comment]
I found a similar string to `Unsupported spf part` inside a file called `flattener.js`, which seems to be part of some web-based validator API. Is it possible the code to validate the SPF has been moved out of Go and into some kind of self-hosted web service?

**Comment by tlimoncelli** [comment]
OOH!  It's `redirect=` and I implemented `redirect:`

When I google "spf redirect" I see examples of each.  Which should we support?  Both?

**Comment by tlimoncelli** [comment]
`flatterner.js` is transpiled from go to javascript to make the web version.  The JS might be out of date, but not for long.

**Comment by silverl** [comment]
Oho! I guess I'd be checking the RFP on that one.

**Comment by silverl** [comment]
https://tools.ietf.org/html/rfc7208#section-6.1

**Comment by tlimoncelli** [comment]
You are absolutely correct, sir!  I'll prepare a PR.

**Comment by tlimoncelli** [comment]
Fixed in https://github.com/StackExchange/dnscontrol/pull/507

**Comment by silverl** [comment]
@tlimoncelli The latest change worked! Thank you!

**Comment by tlimoncelli** [comment]
@silverl Thank you for reporting this!
