### ISSUE TITLE
TTL for SPF_BUILDER?

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#475]
Thanks for this very helpful tool! I'm currently working on getting dnscontrol implemented in my private IT environment, including CI.

While I was able to cover all my needs so far, I wasn't able to find any way how to specify a custom TTL for generated SPF records using `SPF_BUILDER`. Is there any way to do so?

**Comment by tlimoncelli** [comment]
Hi there!

SPF_BUILDER generates records with no TTL, thus the default TTL is used.

**Comment by patschi** [comment]
Thanks for the reply! Yes, I'm aware that the default TTL is used here as well, however I'd like to use a custom TTL for the SPF record.

I'd guess that this must be added to `SPF_BUILDER` in `pkg/js/helpers.js` somehow...

**Comment by tlimoncelli** [comment]
Yes, helpers.js is a big part of it.  helpers.js generates a data structure that contains everything needed by the Go code to generate the records.  The Go code will need to take the TTL and add it as appropriate.

The info in [steps to add a new rType](https://stackexchange.github.io/dnscontrol/adding-new-rtypes) might be helpful. 

Tom

**Comment by patschi** [comment]
Thanks a lot for the hint! Apparently I was on the correct way to get this solved, however I wasn't aware about this specific detail as stated in your linked documentation:
```
FYI: If you change pkg/js/helpers.js, run go generate to update pkg/js/static.go.
```

So at first all changes I've done were basically without any effect...

**Comment by tlimoncelli** [comment]
Ah.   Yes, that can be confusing. There's a `-dev` flag that always reads from the file.  We should mention that in the doc.

**Comment by patschi** [comment]
Even if it's not related to this issue: Wouldn't make it more sense to simply trigger `go generate` during the build process? (when build/build.go is run?)

**Comment by tlimoncelli** [comment]
@captncraig ^^^

**Comment by patschi** [comment]
Just to add: For example see my PRs #476 and #478. In both cases I had to commit the `static.go` file as well, so that changes take effect code-wise, however this now ends up in a merge conflict as the content can't be merged automatically. Doing this as part of the build process might allow to get rid of this limitation.
