### ISSUE TITLE
Easier Getting Started guide

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#48]
It dawned on me that boostrapping with dnscontrol would be a lot easier if we provided a walk-through that first only used the BIND provider (making the creds.json file much easier to create). Then it would walk through adding an API-based provider. 

Along the way it should include ways to check your json file.  Suggestion: jq or run the built-in checked in Python:

    echo '{"json":"obj", }' | python -m json.tool

**Comment by captncraig** [comment]
Yeah, bind is probably a good bet since anyone can run it. There is the small problem of bind being disabled by default when the providers run though.

**Comment by fbjerggaard** [comment]
Is it possible to get a MWE of a basic BIND setup? I don't see anywhere what to put in the creds file (or how to create it) and I get an error when trying to create the BIND files:

`./dnscontrol-Linux -providers BIND preview
main.go:121: Error creating dsps: DNSServiceProvider BIND not listed in -providers file
`

dnsconfig.js:

    var localns = NewDnsProvider ("BIND", "BIND")
    D("example.com", DnsProvider(localns),
            A("@", "1.1.2.3")
    )

**Comment by captncraig** [comment]
unfortunately you need to have `{"BIND":{}}` in `creds.json`. Maybe we can relax that shortly. Working on making a smaller example in the docs.

**Comment by fbjerggaard** [comment]
Thanks @captncraig - unfortunately I still get the error that bind is not listed in -providers file even though I add `-providers all` to the commandline like above - any idea what might be wrong?
I am running the release version and not the newest code from github if that has anything to say.

**Comment by captncraig** [comment]
It will be case sensitive. From your dnsconfig.js I would expect your creds.json to be exactly: 

```
{"BIND":{}}
```

That branch linked above should make that unnecessary once merged.

**Comment by fbjerggaard** [comment]
Cool. Thanks @captncraig - The documentation for the BIND config could really use some love as it is right now, but it seems like your branch should do the job just fine :)

**Comment by BrandonPotter** [comment]
If I could add one more lesson learned, in my setup I needed to manage records on a provider but didn't have or need a compatible registrar.

It was a pretty deep dive to find the noneRegistrar provider... would imagine a lot of folks would be in this same boat, so maybe an example for that in getting started?
