### ISSUE TITLE
GetNameservers() is inconsistent wrt "trailing dot" across providers

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#491]
You are probably reading this issue because of a warning told you to read this.

The warning is to help us find and fix an inconsistency in the code.  Some providers store a nameserver with a trailing dot, others don't.  Currently the code strips out the dot.  We would prefer if all providers act the same.

More specifically: The problem is with `models.DomainConfig.Nameservers`.  Some providers store a `FQDN` others store a `FQDN + "."` (known as a "trailing dot").

This inconsistency means that later code must deal with having (or not having) the trailing dot.  In fact, in `pkg/nameservers/nameservers.go` the dot is stripped out to compensate for all future code. However this covers up the inconsistency.  That's kind of messy and we'd prefer to clean this up.  (@tlimoncelli is to blame for this inconsistency as he wrote the original code; now he's trying to fix it.)

What we would prefer is if all providers simply stored the FQDN without the dot.

Plan:

* Before 3.0: The trailing dot is silently removed.
* Starting with 3.0: The trailing dot will be removed, but a warning that includes a link to this issue will be printed.
* Eventually: dnscontrol will error out if the trailing dot exists.

If you've seen the warning message, please consider sending a PR for your provider.

A checkbox in this list means the provider code has been checked and fixed:

- [x] `ACTIVEDIRECTORY_PS` @tlimoncelli
- [x] `AZURE_DNS` @vatsalyagoel
- [ ] `BIND` @tlimoncelli
- [x] `CLOUDNS` @pragmaton
- [X] `CLOUDFLAREAPI` @tlimoncelli
- [x] `DIGITALOCEAN` @Deraen
- [x] `DNSIMPLE` @aeden
- [x] `EXOSCALE` @pierre-emmanuelJ
- [X] `GANDI_V5` @TomOnTime
- [X] `GCLOUD` @tlimoncelli
- [ ] `HEXONET` @papakai
- [ ] `INTERNETBS` @pragmaton
- [ ] `LINODE` @koesie10
- [ ] `NAMECHEAP` @captncraig
- [X] `NAMEDOTCOM` @tlimoncelli
- [ ] `NS1` @captncraig
- [X] `ROUTE53` @tlimoncelli
- [x] `OCTODNS` @TomOnTime
- [ ] `OPENSRS` @pierre-emmanuelJ
- [x] `OVH` @masterzen
- [ ] `SOFTLAYER`@jamielennox
- [ ] `VULTR` @geek1011

There's no rush on this.  The warning in 3.0 will be very tiny.

# How to fix:

*Step 1: Does the provider need to change?*

Run "dnscontrol preview" on a configuration that uses the provider.

Do you see this warning?

```
Warning: provider gcloud could be improved. See https://github.com/StackExchange/dnscontrol/issues/491 (DetermineNameservers::sstatic.net::ns-cloud-e1.googledomains.com.)
```

No?  The provider does not exhibit the problem.  Congrats! Please post a comment here so we can update the checklist.

Yes?  Please continue to Step 2.

*Step 2: Fix the GetNameservers()*

Find the provider's `GetNameservers()` function. (Be careful about the case. At least one provider also has a `GetNameServers` method.)

Usually this function builds up a list of nameserver names (strings) then converts them to a `[]models.Nameserver`, sometimes using `models.StringsToNameservers`.  Instead, we want it to end with one of these two statements:

```
    return models.ToNameservers(nss)
OR
    return models.ToNameserversStripTD(nss)
```

where "nss" is a `[]strings` where each string is the FQDN of a name server.

Call ToNameservers if the FQDNs *do not end* with a trailing dot.

Call ToNameserversStripTD if the FQDNs *do end* with a trailing dot.  The dot will be stripped.

Why use these functions?  (1) they will warn us if the provider's protocol ever changes to include (or not include) the trailing dot.  (2) once all providers use these functions, it will be easier to change the definition of models.Namservers.

In most cases the change will be to change:

```
OLD:
  return models.StringsToNameservers(nss), nil
NEW:
  return models.ToNameservers(nss)
```

*Step 3: Update GetRegistrarCorrections*

The code for `GetRegistrarCorrections()` was expecting the nameservers to have a trailing dot.  Adjust the code to assume no trailing dot.

If the provider is not a Registrar, no changes will be required.

*Step 4: Test*

Run the integration tests (See [Writing new DNS providers](writing-providers).)

Run "dnscontrol preview" on a configuration that uses this provider.
Look for messages such as:
"provider code leaves trailing dot on nameserver"
or
"provider code already removed nameserver trailing dot".

Once all tests pass, send a PR.

Any questions? Please post a comment!  I look forward to hearing from you!

**Comment by captncraig** [comment]
We should remove the odd nameserver struct and just move to a list of strings. And take care of this at the same time.

**Comment by tlimoncelli** [comment]
Working on this here: https://github.com/StackExchange/dnscontrol/pull/655

**Comment by tlimoncelli** [comment]
I played around with this all day.  The more I looked at it, the more confused I got. I'll take another look tomorrow.

**Comment by tlimoncelli** [comment]
After a nights rest I had a much better idea of what to do.  I've merged to master some code that prints the warnings and directs people to this issue.  It also fixes many providers.

**Comment by vatsalyagoel** [comment]
Tested Azure DNS with your changes. It can be marked as complete

**Comment by masterzen** [comment]
Tested OVH and it works. I can submit a PR to migrate to `models.ToNameservers` if needed.

**Comment by tlimoncelli** [comment]
> Tested Azure DNS with your changes. It can be marked as complete

Done.  Thanks!

**Comment by tlimoncelli** [comment]
@masterzen:
> Tested OVH and it works. I can submit a PR to migrate to `models.ToNameservers` if needed.

A PR would be great.

**Comment by masterzen** [comment]
@tlimoncelli I just published the PR #679.

**Comment by pragmaton** [comment]
ClouDNS - done in https://github.com/StackExchange/dnscontrol/pull/681
INTERNETBS - GetNameservers not implemented

**Comment by tlimoncelli** [comment]
Enough providers have implemented this that I'll consider it "done".   Providers are encouraged to continue with updates.

**Comment by willpower232** [comment]
```Warning: provider hetzner could be improved. See https://github.com/StackExchange/dnscontrol/issues/491 (DetermineNameservers (mydomain.com) (hydrogen.ns.hetzner.com.))```

I found this on 3.28.0 and 3.31.2 so I guess their API changed otherwise I would have noticed this during #2259 maybe.

Should I endeavour to follow the earlier steps?

**Comment by tlimoncelli** [comment]
> `Warning: provider hetzner could be improved. See https://github.com/StackExchange/dnscontrol/issues/491 (DetermineNameservers (mydomain.com) (hydrogen.ns.hetzner.com.))`
> 
> I found this on 3.28.0 and 3.31.2 so I guess their API changed otherwise I would have noticed this during #2259 maybe.
> 
> Should I endeavour to follow the earlier steps?

Sure!  I suspect following the instructions in Step 2 will fix it.
