### ISSUE TITLE
Initial push for AWS Route53 provider could invoke CREATE instead of UPSERT operation

### ISSUE THREAD

**Issue by karolkania** [StackExchange/dnscontrol#493]
This applies to this line in particular: https://github.com/StackExchange/dnscontrol/blob/b3e35b56a22f81cc8f42adb9071fa4f28b4a1502/providers/route53/route53Provider.go#L245

When I was trying to push ~800 records for a single domain to AWS R53 in a single batch, I hit the following:
>FAILURE! InvalidChangeBatch: [Number of records limit of 1000 exceeded.]

There's an undocumented limit (at least I was unable to find it) for this.

What I did encounter though is this thread that could explain more: https://forums.aws.amazon.com/thread.jspa?threadID=237911

tl;dr
> CREATE and DELETE would always add 1 for each ResourceRecord element in the request towards the limit; [...] using UPSERT, you would need to double new records [doing the math]

In other words with UPSERT we can process maximum of 500 records for a single domain in a single push -- that's what I did as a workaround with a simple cut&paste in the text editor.

Would consider it a minor enhancement that would allow us to increase the current limit of 500 (which is still a lot for a single domain) records to 1000 records (rarely seen truth be told).

Perhaps a simple warning message could appear if there are >500 entries for a domain could help for future reference (plus some docs update).

**Comment by tlimoncelli** [comment]
A warning would be useful, as would splitting the request into batches of 500.

**Comment by tlimoncelli** [comment]
Would you be interested in volunteering to fix this?

**Comment by captncraig** [comment]
Should be fixed in #509. For simplicity's sake, I just applied upserts in batches of 500. Identifying creates vs upserts would be quite a bit more logic to optimize what I assume is a fairly rare situation where we are adding many records at once.

**Comment by tlimoncelli** [comment]
Is this issue ready to be closed?
