### ISSUE TITLE
Idea: "FAKE-CNAME"

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#495]
(Before I'm starting describing my idea: I'm bad at giving things names.)

**Situation**
Let's assume we have following records:
```
A('admin', '1.2.3.4'),
AAAA('admin', '(use your imagination to think of an IPv6)'),
```

Additionally, we have following CNAME record:
```
CNAME('user', 'admin'),
```

So, the usual CNAME is easy to understand: We use the same records with `user.domain.tld` just like `admin.domain.tld`. However a CNAME is in place and will be returned back from the DNS provider.

**Idea**
What's about the idea of implementing something like `SMART_CNAME()`. Using this function we simply duplicate the records from the target on dnscontrol-side and populate it to the provider - getting rid of the CNAME on the DNS-provider-end.

So, for example:
```
SMART_CNAME('user', 'admin'),
```
causes following records to be created on dnscontrol-side:
```
A('dev', '1.2.3.4'),
AAAA('dev', '(use your imagination to think of an IPv6)'),
```

From a technical standpoint that should work out fine, and bring the same result as a real CNAME. However it has the advantage that no additional DNS query might be necessary for the user.

Furthermore: This should only work as part of same domain, or in other words: as long as there's no dot in the end of the target.

Does this make any sense in the practise? Or more a worse than a good idea? Any thoughts?

**Comment by tlimoncelli** [comment]
What problem would this solve?  If it is one of optimization (one fewer DNS query) then that's done already on the server side.

Here's an example: The QUESTION section shows the request is for A records.  The ANSWER section lists the CNAME record, plus any additional records required to get the A record.

```
$ dig www.limoncelli.com a

; <<>> DiG 9.10.6 <<>> www.limoncelli.com a
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30339
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.limoncelli.com.		IN	A

;; ANSWER SECTION:
www.limoncelli.com.	21237	IN	CNAME	limoncelli.com.
limoncelli.com.		21237	IN	A	174.136.107.197

;; Query time: 0 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri May 24 05:59:37 EDT 2019
;; MSG SIZE  rcvd: 77
```

Sadly some bad guys stuff the response with bad data. For example, the A record for Google, but point it at them.  Therefore clients must be very careful to accept only records that the sender is responsible for.  You can read more about it here: https://tools.ietf.org/html/rfc5452

**Comment by patschi** [comment]
Ah, understood! I thought resolving CNAMEs requires additional requests from the client (even the ANSWER section contains both records). Thanks for letting me know! :)
