### ISSUE TITLE
Not possible to use get-certs without OCSP stapling

### ISSUE THREAD

**Issue by reshippie** [StackExchange/dnscontrol#497]
Not all TLS environments can, or wish to, support OCSP stapling, but all Let's Encrypt certificates generated by `get-certs` have that as a requirement.    It is a configurable option in the `github.com/xenolf/lego/acme/` package for both generating new certificates and renewing existing ones, but the `get-cert` code has it hardcoded as a strict requirement, not an option.  

https://github.com/reshippie/dnscontrol

**Comment by captncraig** [comment]
Interesting, we recently did a whole run around to automatically fetch and serve staples on our load balancers. I assumed that flag was hard coded for all LE certs no matter what. If that option really works I will make it an option you can set on a per-cert basis, but requiring staple will remain the default.

**Comment by captncraig** [comment]
Since this bit us hard in production today, I made this option in #502. The default is false. You can set `"must_staple": true` in certs.json to enable it per-cert.

**Comment by captncraig** [comment]
So thanks for pointing out this option works.
