### ISSUE TITLE
Large version jump

### ISSUE THREAD

**Issue by jloh** [StackExchange/dnscontrol#501]
Not sure if this is intended but all the previous releases were `v0.x.x` but this latest release is `v2.9`, dropping the leading zero. Not sure if this is intended?

**Comment by tlimoncelli** [comment]
I should have pointed this out in the release notes.

* The leading "0." was a mistake a made a long time ago and I'd been meaning to correct it.
* There is a comment in one commit about a 3.0 release. That's in error.

My general plan is:
1.x was the python version. 2.x was the go version.  I'm holding 3.x for when we overhaul the provider interface to be more modular.
