### ISSUE TITLE
ERROR: Exact duplicate record found for R53_ALIAS in Version 2.9

### ISSUE THREAD

**Issue by loosi** [StackExchange/dnscontrol#504]
We previously used R53_ZONE for dual-stack. 
R53_ALIAS('$NAME$', 'A','.,...elb.amazonaws.com.', R53_ZONE('adasdwer34r')),
R53_ALIAS('$NAME$', 'AAAA','.,...elb.amazonaws.com.', R53_ZONE('adasdwer34r'))

using the latest Version this now fails with "ERROR: Exact duplicate record found"
Is there any way to use both A and AAAA records with R53_Alias for now?

**Comment by tlimoncelli** [comment]
I'm pretty sure that's a bug.  I moved that check to be earlier in the process and must have botched it.

Can you make a minimal config that reproduces the problem?

**Comment by loosi** [comment]
Well those two lines above are more or less the config to reproduce the bug. I can't really add anything else without disclosing internal AWS stuff. Everything else are internal Domains or even AWS ZoneID.

````
var REG_BO = NewRegistrar('none', 'NONE');
require("macros.js");
DEFAULTS(DefaultTTL("1d"), DnsProvider(R53), {'ns_ttl': '3600'});
require('zones.conf.d/foobar.js');
````
File foobar.js
````
D("daba.net", REG_BO,
R53_ALIAS('$NAME$', 'A','.,...elb.amazonaws.com.', R53_ZONE('adasdwer34r')),
R53_ALIAS('$NAME$', 'AAAA','.,...elb.amazonaws.com.', R53_ZONE('adasdwer34r'))
)
```

**Comment by tlimoncelli** [comment]
I found the problem and created https://github.com/StackExchange/dnscontrol/pull/505.

Does that fix the problem?

**Comment by loosi** [comment]
I'll test that this weekend

**Comment by tlimoncelli** [comment]
PS I merged it into master. You can test it there.

**Comment by loosi** [comment]
Fix in master works. No error now on deploying r53_alias with dual stack. Thx :)

**Comment by tlimoncelli** [comment]
Thanks for pointing this out so that it could be fixed!
