### ISSUE TITLE
Route53 provider  limit exceeded

### ISSUE THREAD

**Issue by diegoroccia** [StackExchange/dnscontrol#508]
I'm using the R53 provider and migrating my existing zones, but I'm hitting the 1000 records limit from AWS

```FAILURE! InvalidChangeBatch: [Number of records limit of 1000 exceeded.]
	status code: 400, request id: dd6eab21-9761-11e9-a6ff-ff51040595ae
----- Registrar: none...0 corrections
Done. 1 corrections.
```

Is there a way to configure the batch size or a workaround to the problem? I saw there is another issue opened https://github.com/StackExchange/dnscontrol/issues/493 but that would not solve it for good

**Comment by captncraig** [comment]
#509 should address this. I guess we hadn't really encountered such massive zones in our prior usage of r53. Thanks!
