### ISSUE TITLE
AWS Certificate Manager DNS validation records trigger label underscore warning

### ISSUE THREAD

**Issue by essh** [StackExchange/dnscontrol#519]
AWS Certificate Manager DNS record labels start with an underscore (as per https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-validate-dns.html) and trigger the label underscore warning similar to the following:

`WARNING: label _X1.example.com contains an underscore`

**Comment by tlimoncelli** [comment]
Is there a regular expression that we could add to the whitelist that would cover this situation? (There is a whitelist of patterns that we don't output a warning for)

**Comment by essh** [comment]
I’m not sure if there is a generic regex that would catch this since as per the documentation _X1 is actually a long random string like “ _3639ac514e785e898d2646601fa951d5”.

It looks like these are always CNAME records that have a value of “_x2.acm-validations.aws” where x2 is also a long random string. A possible fix would need to consider values and allow CNAMEs with a value that ends in “acm-validations.aws” which is a more complicated fix than the existing whitelist.

**Comment by tlimoncelli** [comment]
How about:

No warning if:
1. The .Name starts with `_`
2. and... The .Type is "CNAME"
3. and... the .Target ends with `acm-validations.aws`

**Comment by essh** [comment]
This logic looks like it will cover what I've seen in practice.

**Comment by tlimoncelli** [comment]
How's this?  https://github.com/StackExchange/dnscontrol/pull/661

**Comment by tlimoncelli** [comment]
#661 fixed it.  Yay!
