### ISSUE TITLE
subdomain delegation

### ISSUE THREAD

**Issue by liljenstolpe** [StackExchange/dnscontrol#535]
I need to create/manage both example.com and foo.example.com using dnscontrol.  Hexonet is the registrar, and a combination of GCloud and R53 as the servers, if that makes any difference.

Doing a D(example.com...) and D(foo.example.com...) isn't going to work, as I have no idea what nameserver addresses will be used for foo.example.com to fill out the NS records.  

Is there anyway to get the NS records from one domain referenced in another domain definition?  Maybe a "DELIGATE" object?

Christopher

**Comment by captncraig** [comment]
You're going to need to manually add an NS record in the parent zone delegating to the child zone. We do something like this:

```
D("example.com", ..., DnsProvider(R53),
   NS("foo", "ns1.gcloudblah.blah."),
   NS("foo", "ns2.gcloudblah.blah."),
   ...
)

D("foo.example.com", ... , DnsProvider(GCLOUD)....)
```

You should be able to find the appropriate nameservers for the child zone by looking in the web console for whatever provider is handling `foo`. I don't think it makes too much sense to extend the auto-discovery of nameservers into subdomain delegation, as it is a bit of a corner case. 

Does something like that work for you?

**Comment by liljenstolpe** [comment]
Actually, that's not going to necessarily work if the parent is also being run by dnscontrol.  I can't fill in the NS records for the deligation, until I've run dnscontrol push once.  So, every time where there might be an NS record change for the deligated subdomain, I have to run dnscontrol, collect the NS records, and manually populate them into the D() and re-run.    It's doable, but a bit annoying (and harder to pipeline in a CI/CD chain).

**Comment by captncraig** [comment]
Correct. How many domains are you doing this for? Are they changing often? Realistically, with those providers the nameservers are not going to change after domain creation. Create the subdomain once, copy the ns records and its done.

They also have features like delegation sets so you can be sure to use the same nameservers for all domains, but I am not very familiar with those.

To get metadata like that from a separate domain is something we don't really have any existing paradigms for. Its kinda annoying here, but I'm not sure the pain of a once manual import of ns records is worth implementing a pretty major feature for.

**Comment by liljenstolpe** [comment]
Ok, I'll look at the delegation sets.  The subdomains do come and go with reasonable regularity.  Ny thinking was that once you get the NS records (which you have to to feed the registrar), you could then fill that data in (i.e. replace a placeholder) in the delegating zone.  

Christopher

**Comment by tlimoncelli** [comment]
Can we close this issue?
