### ISSUE TITLE
DigitalOcean not purging existing nameservers

### ISSUE THREAD

**Issue by glennjacobs** [StackExchange/dnscontrol#537]
If I have the following domain as below, the new nameservers get added but the original nameserver records that DigitalOcean pre-populate remain, which is not desired.

```
D('example.com', REG_NONE, DnsProvider(DNS_DIGITALOCEAN),
    NAMESERVER("ns1.xxxxxx.com."),
    NAMESERVER("ns2.xxxxxx.com."),
    NAMESERVER("ns3.xxxxxx.com."),

    A('@', '2.1.1.1')
);
```

How can I ensure the original DigitalOcean nameserver records are removed?

**Comment by captncraig** [comment]
I'm not sure I understand the use case here. What role is DigitalOcean playing if you are not using their nameservers?

Be that as it may, `DnsProvider(DNS_DIGITALOCEAN)` implies that you want to use DO as a dns provider, and DnsControl will auto-discover the nameservers from that, combine them with your manually entered nameservers, and make sure all of those are set up with the appropriate NS records. 

See [this doc](https://stackexchange.github.io/dnscontrol/nameservers) gives a more in depth overview of nameserver management.

If you really want to remove DO's nameservers, you can use  `DnsProvider(DNS_DIGITALOCEAN, 0)` to disable the discovered records.

**Comment by glennjacobs** [comment]
@captncraig thanks for the quick response :-)

The use case is white label (or vanity) DNS servers. So our name servers aren't actually the default DO name servers, even though they point to the same IP. You can see how we've done it here https://www.digitalocean.com/community/tutorials/how-to-create-vanity-or-branded-nameservers-with-digitalocean-cloud-servers

I tried `DnsProvider(DNS_DIGITALOCEAN, 0)` from your suggestion, but it didn't seem to make any difference.

```
var REG_NONE = NewRegistrar('none', 'NONE');
var DNS_DIGITALOCEAN = NewDnsProvider('digitalocean', 'DIGITALOCEAN');

DnsProvider(DNS_DIGITALOCEAN, 0);
```

**Comment by glennjacobs** [comment]
When I say no difference, no changes were made when running `dnscontrol push`. I'm going to guess from the code (I don't program in GoLang, but can try workout what is going on), that by setting the name server count to 0, it's also going to ignore our custom name servers?

**Comment by ad8-bdl** [comment]
I'm seeing the same thing, but using DO's nameservers - the result is duplicate NS records in DO.
Repro:
- starting with a "blank canvas" at DO (i.e. example.net does not exist), and the following config:
`example.net.js`:
```
var REG_NONE = NewRegistrar('none', 'NONE');
var DNS_DIGITALOCEAN = NewDnsProvider("digitalocean", "DIGITALOCEAN");

D("example.net", REG_NONE, DnsProvider(DNS_DIGITALOCEAN),
	NAMESERVER('ns1.digitalocean.com.'),
	NAMESERVER('ns2.digitalocean.com.'),
	NAMESERVER('ns3.digitalocean.com.'),
    A('@', '10.20.30.40')
);
```
```
% docker run --rm -it -v  $(pwd)/example.net.js:/dns/dnsconfig.js:ro -v $(pwd)/creds-do.json:/dns/creds.json:ro stackexchange/dnscontrol dnscontrol preview
******************** Domain: example.net
----- Getting nameservers from: digitalocean
----- DNS Provider: digitalocean...7 corrections
#1: CREATE NS example.net ns1.digitalocean.com. ttl=300
#2: CREATE NS example.net ns2.digitalocean.com. ttl=300
#3: CREATE NS example.net ns3.digitalocean.com. ttl=300
#4: CREATE A example.net 10.20.30.40 ttl=300
#5: MODIFY NS example.net: (ns3.digitalocean.com. ttl=1800) -> (ns3.digitalocean.com. ttl=300), DO ID: 76070895
#6: MODIFY NS example.net: (ns2.digitalocean.com. ttl=1800) -> (ns2.digitalocean.com. ttl=300), DO ID: 76070894
#7: MODIFY NS example.net: (ns1.digitalocean.com. ttl=1800) -> (ns1.digitalocean.com. ttl=300), DO ID: 76070893
----- Registrar: none...0 corrections
Done. 7 corrections.
```

`push`ing results in two copies of each NS record on DO, with the same TTL (300). A subsequent `preview` reports `----- DNS Provider: digitalocean...0 corrections`.

**Comment by captncraig** [comment]
@ad8-bdl This is expected. In the normal case, you should not need to specify Nameserver records at all. Dnscontrol will discover them and take care of managing ns records and registrars and so forth.

Either remove the redundant nameserver records, or use `DnsProvider(DNS_DIGITALOCEAN,0)`
