### ISSUE TITLE
convertzone produces redundant NAMESERVER entries

### ISSUE THREAD

**Issue by ad8-bdl** [StackExchange/dnscontrol#539]
`convertzone` emits extraneous NAMESERVER entries:

Given the following zone file:
```
$TTL 86400
@	IN	SOA	ns1.linode.com. hostmaster.example.net. 2019070884 14400 14400 1209600 86400
@		NS	ns1.linode.com.
@		NS	ns2.linode.com.
@		NS	ns3.linode.com.
@		NS	ns4.linode.com.
@		NS	ns5.linode.com.
@			A	10.2.3.4
```

`convertzone` produces the following:
```
% ~/src/misc/dnscontrol/cmd/convertzone/convertzone example.net ./example.zone 
D("example.net", REG_FILL_IN, DnsProvider(DNS_FILL_IN),
	NAMESERVER('ns1.linode.com.', TTL(86400)),
	NAMESERVER('ns2.linode.com.', TTL(86400)),
	NAMESERVER('ns3.linode.com.', TTL(86400)),
	NAMESERVER('ns4.linode.com.', TTL(86400)),
	NAMESERVER('ns5.linode.com.', TTL(86400)),
	A('@', '10.2.3.4', TTL(86400))
)
```

I suggest that convertzone should not include the NAMESERVER entries; or ideally only include them if they do not exist in the DnsProvider (which could be inferred from the SOA record, or provided via a new command line argument).

(also ref. #176  re. NAMESERVER TTL() arguments)

**Comment by tlimoncelli** [comment]
Hi @ad8-bdl !  Could you please check if this bug exists with the new "dnscontrol get-zones" feature?  That feature will replace convertzone soon.

**Comment by ad8-bdl** [comment]
I tested the bind, Linode and DigitalOcean providers.

1. BIND using the zone file from the OP: includes NAMESERVER entries, as expected

```
dnscontrol% ./dnscontrol get-zones --format=dsl - BIND all                            
var - = NewDnsProvider("-", "BIND");
D("example.net", REG_CHANGEME,
	DnsProvider(-),
	SOA('@', ns1.linode.com. hostmaster.example.net. 2019070884 14400 14400 1209600 86400, TTL(86400)),
	NAMESERVER('ns1.linode.com.', TTL(86400)),
	NAMESERVER('ns2.linode.com.', TTL(86400)),
	NAMESERVER('ns3.linode.com.', TTL(86400)),
	NAMESERVER('ns4.linode.com.', TTL(86400)),
	NAMESERVER('ns5.linode.com.', TTL(86400)),
	A('@', '10.2.3.4', TTL(86400))
)
```

2. LINODE provider doesn't yet support `get-zones`

```
% ./dnscontrol get-zones --format dsl linode LINODE mydomain.com
not implemented
```

3. DIGITALOCEAN: includes superfluous NAMESERVER entries, see below

```
./dnscontrol get-zones --format dsl digitalocean DIGITALOCEAN mydomain.com
var digitalocean = NewDnsProvider("digitalocean", "DIGITALOCEAN");
D("mydomain.com", REG_CHANGEME,
    DnsProvider(digitalocean),
    NAMESERVER('ns1.digitalocean.com.', TTL(7200)),
    NAMESERVER('ns2.digitalocean.com.', TTL(7200)),
    NAMESERVER('ns3.digitalocean.com.', TTL(7200)),
...
```
(note also the invalid TTL argument to each NAMESERVER())

**Comment by tlimoncelli** [comment]
Ah, I'll remove the TTL() stuff.  I'm not sure how to fix the superfluous NAMESERVER entries.  What's an algorithm that would spot NAMESERVER() entries to ignore?

**Comment by tlimoncelli** [comment]
Working on this in https://github.com/StackExchange/dnscontrol/pull/658

**Comment by tlimoncelli** [comment]
How's this?

OLD:

```
$ dnscontrol get-zones --format dsl DIGITALOCEAN DIGITALOCEAN dnscontrol-do.com
var DIGITALOCEAN = NewDnsProvider("DIGITALOCEAN", "DIGITALOCEAN");
D("dnscontrol-do.com", REG_CHANGEME,
	DnsProvider(DIGITALOCEAN),
	NAMESERVER('ns1.digitalocean.com.', TTL(300)),
	NAMESERVER('ns2.digitalocean.com.', TTL(300)),
	NAMESERVER('ns3.digitalocean.com.', TTL(300)),
	NAMESERVER('ns1.example.com.', TTL(300)),
	NAMESERVER('ns2.example.com.', TTL(300))
)
$
$
```

NEW:

```
$ dnscontrol get-zones --format dsl DIGITALOCEAN DIGITALOCEAN dnscontrol-do.com
var DIGITALOCEAN = NewDnsProvider("DIGITALOCEAN", "DIGITALOCEAN");
D("dnscontrol-do.com", REG_CHANGEME,
	DnsProvider(DIGITALOCEAN),
	NAMESERVER('ns1.digitalocean.com.'),
	NAMESERVER('ns2.digitalocean.com.'),
	NAMESERVER('ns3.digitalocean.com.'),
	NAMESERVER('ns1.example.com.'),
	NAMESERVER('ns2.example.com.')
)
$
$
```

**Comment by ad8-bdl** [comment]
> What's an algorithm that would spot NAMESERVER() entries to ignore?

AIUI, it's going to be dependant on the Provider - e.g. providers that have default nameservers defined should filter them from get-zones, on the expectation they'll be added back in via the D().

From what I can tell from looking at the interface, it seems that GetZoneRecords should remove anything returned by GetNameservers?

**Comment by tlimoncelli** [comment]
I appreciate your input and suggestions. 

I agree it is going to be provider-dependent.  Therefore, I'm going to consider this "works as designed". (after https://github.com/StackExchange/dnscontrol/pull/658 is merged)

`dnscontrol get-zones --format=dsl` does not produce the perfect dnscontrol.js code. It is documented as creating "a good first draft."  People can delete extra NAMESERVER() lines easily. They might even appreciate seeing what their nameservers are.

If a provider wants to hide NAMESERVERS(), it can do that.  NAMEDOTCOM already does something like that... turning the gobbledygook names that are generated back into the default names that appear in the web portal.
