### ISSUE TITLE
Route53 unable to authenticate

### ISSUE THREAD

**Issue by willpower232** [StackExchange/dnscontrol#548]
I may be misunderstanding something, being new to dnscontrol, but I am unable to authenticate against Route53 when using either `r53` or `r53_main` and I get the following error message (AWS access key redacted)

![image](https://user-images.githubusercontent.com/1619102/64485840-31a08a00-d21d-11e9-95ae-f0900644bb9f.png)

I seem to remember from other software development that AWS updated their authorization header requirements at some point so was dnscontrol updated for that?

I am using version 2.9 of dnscontrol on Linux downloaded from the releases page.

P.S. is there a difference between `r53` and `r53_main`? README.md and the documentation website contain one or the other but don't say which should be used

**Comment by tlimoncelli** [comment]
`r53` and `r53_main` are just a name you assign to a particular set of credentials.  If you have only one set of credentials, just using one is fine.   In some companies you might have multiple AWS accounts, each with their on credentials, and certain domains managed under each account.

You assign a set of credentials a name in creds.json, then use that name later in dnsconfig.js:

```
var R53 = NewDnsProvider("r53", "ROUTE53");
```

In the above example, "ROUTE53" refers to the module name.  The "r53" is a name that you pick. When dnscontrol needs credentials, it will read creds.json and lookup "r53".

Some examples are on: https://stackexchange.github.io/dnscontrol/providers/route53

Once you figure out the issue, I'd love to update `https://stackexchange.github.io/dnscontrol/providers/route53` with the error message (redacted, of course), what the problem was, and the solution.

Tom

**Comment by willpower232** [comment]
I missed the part where the SDK is used so obviously its going to work for everyone.

My issue turned out to be a stray space between the key and the `"` in the JSON file, inspired by (https://github.com/aws/aws-sdk-go/issues/289).

I'm now getting the error `Check your credentials, your not authorized to perform actions on Route 53 AWS Service`.

Aside from the `you(')r(e)` typo, do you have an example IAM policy for all the required permissions?

**Comment by captncraig** [comment]
Our test account just uses `AmazonRoute53FullAccess`. You could experiment with less than that, but it does need full control over resource record sets.

**Comment by tlimoncelli** [comment]
FYI: 3.0 will have a "dnscontrol getzone" command which will be very useful for debugging authentication without having to go through a lot of setup.  Maybe we should have it be extra verbose in the error messages to help find whitespace, etc.

**Comment by willpower232** [comment]
@captncraig thanks for that, for anyone else interested I'm currently having great success with the following policy

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "route53:CreateHostedZone",
                "route53:GetHostedZone",
                "route53:ListHostedZones",
                "route53:ChangeResourceRecordSets",
                "route53:ListResourceRecordSets",
                "route53:UpdateHostedZoneComment"
            ],
            "Resource": "*"
        }
    ]
}
```

@tlimoncelli sounds great thank you, I'll remember that, do you want this left open as a reminder?

**Comment by tlimoncelli** [comment]
Thanks for the research!

Rather than leaving this bug open, would you please submit a PR that adds this to [docs/_providers/route53.md](https://github.com/StackExchange/dnscontrol/blob/master/docs/_providers/route53.md) ?

**Comment by willpower232** [comment]
Can do, I was referring to you adding extra verbosity for the leaving openness :-P

**Comment by tlimoncelli** [comment]
Is this ready to be closed?

**Comment by willpower232** [comment]
If you don't need a reminder about making "dnscontrol getzone" be extra verbose in the error messages, or you've since decided against it, then sure :-)

**Comment by tlimoncelli** [comment]
I've separated that out as https://github.com/StackExchange/dnscontrol/issues/609 so that it doesn't get lost.

**Comment by willpower232** [comment]
No worries, thanks for all your help
