### ISSUE TITLE
Default creds file name (docs mismatch)

### ISSUE THREAD

**Issue by BrandonPotter** [StackExchange/dnscontrol#55]
In `dnscontrol-Linux` version: `dnscontrol 0.1.0 (c52ff67386750e96138fe78f0631d757f928f452) built 14 Mar 17 00:32 UTC` (current latest compiled release)

Everything in the utility (help text etc) defaults to `creds.json`, documentation indicates `providers.json` is default. https://github.com/StackExchange/dnscontrol/blob/master/docs/getting-started.md

**Comment by captncraig** [comment]
Fixed in a branch I should be merging shortly. Thanks.

**Comment by tlimoncelli** [comment]
Maybe it hasn't been merged yet, but I see docs/getting-started.md has the old filename.  The integrationTest directory, of course, still uses providers.json since that is a different thing.

```
$ grep -ri providers.j *
docs/getting-started.md:The second file is a json document to hold your api credentials. By default we use `providers.json`:
integrationTest/integration_test.go:	jsons, err := config.LoadProviderConfigs("providers.json")
integrationTest/readme.md:`providers.json` should have an object for each provider type under test. This is identical to the json expected in creds.json for dnscontrol, except it also has a "domain" field specified for the domain to test. The domain does not even need to be registered for most providers. Note that `providers.json` expects environment variables to be specified with the relevant info.

```

**Comment by BrandonPotter** [comment]
Saw it updated in the bind branch

**Comment by captncraig** [comment]
Merged into master.
