### ISSUE TITLE
Repeating CAA Changes

### ISSUE THREAD

**Issue by loosi** [StackExchange/dnscontrol#552]
Weird manual push problem with AWS Route53 (not found in our CI). 
RUN #1
```
#1: MODIFY CAA foo.net: (0 issuewild "letsencrypt.org" ttl=86400) -> (0 issue "letsencrypt.org" ttl=86400)
MODIFY CAA foo.net: (0 issue "letsencrypt.org" ttl=86400) -> (0 issuewild "letsencrypt.org" ttl=86400)
```
RUN #2 
```
#1: MODIFY CAA foo.net: (0 issuewild "letsencrypt.org" ttl=86400) -> (0 issue "letsencrypt.org" ttl=86400)
MODIFY CAA foo.net: (0 issue "letsencrypt.org" ttl=86400) -> (0 issuewild "letsencrypt.org" ttl=86400)
```

And that goes on and on and on with every manual run. Strangely its not happening in our CI, though it's the same docker image and the same repo. Could that be an API timing-order problem?
There are no changes to the CAA records in AWS.
I tested it on a mostly blank Domain
```
D("foo.net", REG_NONE,
	 A('@', RedirectIP4),
        AAAA('@', RedirectIP6),
        A('www', RedirectIP4),
	AAAA('www', RedirectIP6)
	CAA_BUILDER({
          label: "@",
          iodef: "mailto:webmaster@foo.net",
          iodef_critical: true,
          issue: [
            "letsencrypt.org",
            "amazon.com",
          ],
          issuewild: [
             "letsencrypt.org",
          ]
});
)
```
Any ideas? It's preventing me from going on with letsencrypt (found 1 pending corrections...)
Thanks

**Comment by captncraig** [comment]
That is definitely a problem. Looks like the diff algorithm is not matching the records properly. I will try to repro.

**Comment by captncraig** [comment]
I'm pretty sure #553 fixes. Can you confirm?

I still can't explain why it passes in your CI but not locally. My guess is that R53 is not returning records in consistent order, and you just happened to observe a run that lined up properly.

**Comment by loosi** [comment]
#553 fixes it locallly. Thanks - that fast blazingly fast. 
Still no clue why it's local only. Maybe our CI is slower..maybe a different route and different response. For most records the order doesn't matter at all, so I guess not many people see those errors. 

Still,
thanks

**Comment by captncraig** [comment]
I'm actually amazed this hasn't been a bigger issue before now. I guess caa is one of the only records where it is typical to have multiple records with the same target (letsencrypt.org for you) that have differences in other fields.
