### ISSUE TITLE
Add provider specific entries=

### ISSUE THREAD

**Issue by JoyceBabu** [StackExchange/dnscontrol#554]
I have a DKIM TXT record that is over 255 characters. Route53 and Google Cloud DNS requires the record to be split into multiple strings, but CloudFlare does not support multiple strings for TXT records.

I tried adding a separate D('mydomain.com', REG_NONE ...);, for cloudflare, but it is failing with error

> Executing javascript in dnsconfig.js: mydomain.com is declared more than once

Is it possible to conditionally add records depending on the provider with dnscontrol?

**PS:** Sorry, I know this is a support question. I tried [asking this on SO](https://stackoverflow.com/questions/58411589/how-to-add-provider-specific-entries-using-dnscontrol), but received no response there.

**Comment by captncraig** [comment]
Hmmm. Are you hosting the same domain on all 3 providers? Are all of them authoritative? 

I would probably advise cloudflare is not suitable for your setup if you need this dkim. They also don't really play nice with other dns providers. It doesn't seem like a great idea to have inconsistent dns records across multiple providers. Sounds like a good way to really confuse resolvers. 

Can you elaborate a little more on why you want to do this?

**Comment by JoyceBabu** [comment]
Yes, I was planning on using CloudFlare and Google Cloud DNS as authoritative nameservers.

In my case, DKIM was not important so I ended up removing the record from all 3 providers.

Last week, the site was down with error

> Service Unavailable - DNS failure

Akamai support said it was due to a DNS error, and that the edge server was not able to resolve the origin hostname. I was using CloudFlare's nameservers for the site. So, I thought of adding Google Cloud CDN to the authoritative nameservers.

**Comment by captncraig** [comment]
You're gonna run into more issues trying to use cloudflare like that. They check the registered nameservers and will assume your domain is misconfigured when they find the gcloud nameservers there.

When you have multiple nameservers and they return different combinations of things to different clients, things become really unpredictable and hard to debug. I don't think conditional records are a good workaround to providers not supporting features.

**Comment by JoyceBabu** [comment]
Thank you for the advice. It makes more sense to have all records synchronized or drop the provider completely.
