### ISSUE TITLE
Does dnscontrol support Cloudflare Load Balancer?

### ISSUE THREAD

**Issue by lukelyp** [StackExchange/dnscontrol#568]
Hi,

I was wondering does dnscontrol support Cloudflare DNS Load Balancer? I didn't see in the repo.

Thanks.

**Comment by tlimoncelli** [comment]
Not at this time.  We'd be glad to accept a PR that adds such a feature.

(I'm closing this issue but feel free to re-open it if you want to discuss this further)

**Comment by lukelyp** [comment]
Thanks.
