### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by ntwb** [StackExchange/dnscontrol#569]
The last release was ~ 6 months at the end of May

> https://github.com/StackExchange/dnscontrol/releases

Any chance on pushing out a new release?

I'm using Homebrew to install DNSControl and even though I'm about to go install with Go, I'd expect a few others who use Homebrew would enjoy the latest features.

I was trying to debug why #534 wasn't working for me...

**Comment by tlimoncelli** [comment]
Wow, I can't believe its been so long! I'll add it to my todo list.

**Comment by tlimoncelli** [comment]
Release 2.10.0 pushed via 88769d51b7910c459d939e33d1156a5c41303f75
