### ISSUE TITLE
Deprecate Old Gandi Provider

### ISSUE THREAD

**Issue by captncraig** [StackExchange/dnscontrol#573]
#572 is a new and improved gandi provider. Once merged, it will implement a `GANDI_V5` provider type.

When the other gandi types are used, we should print a deprication warning that those providers will go away at the next major release, and they should migrate usages to the new provider.

**Comment by tlimoncelli** [comment]
Working on this in https://github.com/StackExchange/dnscontrol/tree/gandi2

**Comment by tlimoncelli** [comment]
Deprecated in https://github.com/StackExchange/dnscontrol/commit/f6ce421fdd2306fc778fd13b1346781542d6f864

Use of GANDI or GANDI-LIVEDNS reports a warning.
