### ISSUE TITLE
Major Refactoring of DnsProvider Interface

### ISSUE THREAD

**Issue by captncraig** [StackExchange/dnscontrol#576]
Currently convertzone only works with certain providers. We would like it to work with all providers, and become part of dnscontrol as a “getzone” subcommand. This has been requested by many people.

The current provider interface is monolithic, and only provides a “GetCorrections” function.
Our plan is to separate this into “Get Existing Records” and “Determine needed Corrections” functions that can be used independently for different functionality. 

The main thing this will enable is a single, unified “convert zone” command that will work for any provider, and ease migration to dnscontrol greatly for more complicated zones.

Technically what will happen is providers change from providing 2 big functions and will instead provide 5 more granular functions.

```
// DNSProvider is an interface for DNS Provider plug-ins.
type DNSProvider interface {
  GetNameservers(domain string) ([]*Nameserver, error)
  GetDomainCorrections(dc *DomainConfig) ([]*Correction, error)
}

// DNSProvider will replace DNSProvider in 3.0.
// NOTE: This is a draft and will change during implementation.
type DNSProvider interface {
 GetNameservers(domain string) ([]*Nameserver, error)
 GetZoneRecords(domain string) (Records, error)
 PrepFoundRecords(recs Records) Records
 PrepDesiredRecords(dc *DomainConfig)
 GenerateDomainCorrections(dc *DomainConfig, existing Records) ([]*Correction, error)
}
```

**Comment by tlimoncelli** [comment]
I was able to achieve the same goal without a major refactoring.  I simply added `GetZoneRecords(domain string) (Records, error)` to `DNSProvider`, then added a function to each provider that reported "not implemented".  I then made a few different providers work. The others can do the conversion at their own pace.
