### ISSUE TITLE
Softlayer DNS for TXT always tries to modify and fails

### ISSUE THREAD

**Issue by saurabhguptag** [StackExchange/dnscontrol#583]
I see there is a bug for TXT records for soflayer DNS, Once the following config is push, dnscontrol always recognise that there is change in the record.

`   
    TXT("XYZ", "ABC", TTL(300)),
    TXT("XYZ1", "ABC1", TTL(300)),
`   

following is preview 

`
----- DNS Provider: softlayer...2 corrections
#1: MODIFY TXT xyz.testcbz.com: ( ttl=300) -> ("ABC" ttl=300)
#2: MODIFY TXT xyz1.testcbz.com: ( ttl=300) -> ("ABC1" ttl=300)
----- Registrar: none...0 corrections
`

following is the output when trying to push

`
----- DNS Provider: softlayer...2 corrections
#1: MODIFY TXT xyz.testcbz.com: ( ttl=300) -> ("ABC" ttl=300)
FAILURE! didn't find changes when I expect some
#2: MODIFY TXT xyz1.testcbz.com: ( ttl=300) -> ("ABC1" ttl=300)
FAILURE! didn't find changes when I expect some
----- Registrar: none...0 corrections
`

using docker version at latest version.

**Comment by tlimoncelli** [comment]
Can @jamielennox please take a look?

**Comment by saurabhguptag** [comment]
Is there any expected timeline for this?

**Comment by tlimoncelli** [comment]
FYI: I don't have a test account on Softlayer.   @jamielennox maintains this provider.

**Comment by jamielennox** [comment]
eek - sorry. It's probably been 18 months since I left that job and haven't had access since. I'm surprised (unless it's a softlayer bug - in which case i'm not surprised) that this is something that has only started being a problem now.

**Comment by saurabhguptag** [comment]
I have done the fix could check and merge ?

https://github.com/StackExchange/dnscontrol/pull/659

**Comment by tlimoncelli** [comment]
@saurabhguptag Thanks for the bug fix.  I'll merge that soon.
