### ISSUE TITLE
Digitalocean CAA Records

### ISSUE THREAD

**Issue by georgejipa** [StackExchange/dnscontrol#588]
They have support for CAA records: https://www.digitalocean.com/docs/networking/dns/how-to/create-caa-records/

> ERROR: Domain [redacted].com uses CAA records, but DNS provider type DIGITALOCEAN does not support them

**Comment by tlimoncelli** [comment]
@Deraen maintains that provider.  Your thoughts?

**Comment by Deraen** [comment]
The implementation is simple, but currently Digitalocean doesn't support empty CAA value, like `;` in the integrations tests.

**Comment by Deraen** [comment]
Related #542 #370 (another DO API problem)
https://github.com/StackExchange/dnscontrol/compare/master...Deraen:feature/do-caa

I looked into asking their support about this, and found that I already sent them question June 2018. They said engineering team was taking a closer look, but doesn't look like they changed anything.

**Comment by Deraen** [comment]
https://www.digitalocean.com/docs/networking/dns/how-to/create-caa-records/

> DigitalOcean DNS does not support the following CAA standard features:
> Blocking anyone from issuing certificates by sending a semicolon (;) in the value

**Comment by tlimoncelli** [comment]
We've got this question a few times.

I think it would be useful for `docs/_providers/digitalocean.md` to explain why CAA is not supported, and list the bugid that is filed with DO, as well as the link that @Deraen included.

Could you submit a PR?

**Comment by georgejipa** [comment]
Thank you, @Deraen @tlimoncelli!
