### ISSUE TITLE
TXT records and empty strings.

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#598]
We made a special case for Cloudflare in https://github.com/StackExchange/dnscontrol/pull/597

We should investigate whether this is a bug in our cloudflare code (which should be fixed), or if their API doesn't support an empty string (in which case we should file a feature request and log the bugid here).

**Comment by onlyhavecans** [comment]
Hello @tlimoncelli 
I am trying to upgrade the DNSimple api client per #619 but I am also hitting this new test as a roadblock.

We (DNSimple) perform some validation on incoming requests and an empty or null string isn't valid for a TXT record per [RFC 1035](https://tools.ietf.org/html/rfc1035)

```
3.3.14. TXT RDATA format
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    /                   TXT-DATA                    /
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
where:
TXT-DATA        One or more <character-string>s.
```

what do you feel the best way of moving forward on this is?

**Comment by tlimoncelli** [comment]
Ah, I think I misunderstood https://github.com/StackExchange/dnscontrol/pull/559 which was saying that it should be possible to delete a TXT record with an empty string, but I took it one step further and tried to make sure that creating them worked also.

I thought it was weird that someone would want an empty string.  Thank you for citing the RFC and educating me.

Here's what I propose:

* Users should be blocked from creating a TXT with an empty string
* Providers should not crash if an empty TXT string is received.

Sadly the current integration test framework can't test these situations.  However, we can at least add some validation code to detect and report empty strings.

I'm going to rename this issue.

**Comment by aeden** [comment]
@tlimoncelli you are correct, a 0 length string is allowed by the RFC (I was the one who thought it wasn't, but I am wrong). Now, is there a use-case for it? I've never seen one. I'm in favor of 1 or 2 mostly because I think there will be providers who will not care to enforce the RFC.

**Comment by onlyhavecans** [comment]
@tlimoncelli Do you have any movement on this decision?
We are unable to make this change to our validators immediately as it may have impacts we need to carefully review.

If you do not have any strong feelings either way I would like to extend the "cloudflare exception" so that I can get our contribution #619 and #628 in as soon as possible.

**Comment by tlimoncelli** [comment]
I pick... "2. Anarchy: Let users set an empty string, if a provider doesn't accept it, we don't care."

If this turns out to be a bad decision, we can always switch to 1 or 3, especially if we can implement a capability like "CanHaveEmptyTxt" (or a shorter name).

**Comment by onlyhavecans** [comment]
Thanks so much for the feedback. I see the PR is merged that removes the test for now so I will get the other tasks done.

**Comment by tlimoncelli** [comment]
I believe this is ready to be closed. Please re-open if needed.
