### ISSUE TITLE
FR: Control registry lock

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#600]
It would be awesome if DNSControl could control DNS registry lock (at least for providers that support this).

Obviously we'd prefer to do this first with name.com since that's what I use :-)

Suggested syntax:

```
D("example.com", ...
   TRANSFERLOCK(true),
   ...
```

**Comment by captncraig** [comment]
That's a pretty cool idea. What if it enforced a lock by default unless you add `ALLOW_TRANSFER`? Maybe that is a little too much invisible magic, but maybe it would be a nice safety feature?

**Comment by tlimoncelli** [comment]
Now that you mention it... I think we want 3 settings: "don't touch", "set to lock", "set to unlock".  The default should be "don't touch".   The DEFAULTS() keyword can be used to if you want something different.

**Comment by tlimoncelli** [comment]
No plans to make this happen.  Closing.
