### ISSUE TITLE
Azure Piplines commit status broken

### ISSUE THREAD

**Issue by pgaskin** [StackExchange/dnscontrol#602]
It needs to be re-linked to the org/repo, as it broke when switching from dev.azure.com/dnscontrol/DnsControl to stackoverflowoss.visualstudio.com/StackOSS.

In addition, the README badge is outdated.

Also see #595.

**Comment by geek1011** [comment]
@devblackops?

**Comment by geek1011** [comment]
@devblackops?

**Comment by geek1011** [comment]
@devblackops @tlimoncelli @captncraig?

**Comment by pgaskin** [comment]
@tlimoncelli?

**Comment by tlimoncelli** [comment]
@MaxHorstmann Ready to be closed?

**Comment by pgaskin** [comment]
The README badge still needs to be updated. Also, are you planning run the pipeline on the master branch too?

**Comment by MaxHorstmann** [comment]
> The README badge still needs to be updated. Also, are you planning run the pipeline on the master branch too?

Yes and yes. :-) How's this? https://github.com/StackExchange/dnscontrol/pull/933 

@pgaskin @tlimoncelli
