### ISSUE TITLE
Add support for NS1

### ISSUE THREAD

**Issue by ChrisMcKee** [StackExchange/dnscontrol#62]
Just wanted to add this to the Dyn requst, as another common T2 provider.

* https://ns1.com/pricing#managed has a free tier
* https://ns1.com/integrations lots of integrations
* Full api support and https://github.com/ns1 own libraries

**Comment by captncraig** [comment]
Good news! I already did this: #63. 

Just gotta finish up a few details and merged it.

**Comment by ChrisMcKee** [comment]
YEY! 👍 
Now do I tell the ops guy he can have his wet dream of 'enterprise' dns or keep pushing till I get Route 53 with its pretty traffic flow UI 🚀 
Thanks though, thats frickin awesome. I'll close the ticket :)
