### ISSUE TITLE
Upgrade to latest github.com/hexonet/go-sdk

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#621]
We are using github.com/hexonet/go-sdk  version v1.2.1 and should upgrade to v2.2.3+incompatible or newer.

Steps would be something like:

1.  Fork and upgrade

```
git checkout master
git checkout -b hexoupgrade
go get -u github.com/hexonet/go-sdk
```

2. Run the integration test

See: https://github.com/StackExchange/dnscontrol/tree/master/integrationTest

3. If it works, we're done.

```
go mod vendor
git add vendor
git commit vendor
git push
```

(then make a PR and send it to me)

**Comment by murarisumit** [comment]
hi @tlimoncelli, can i pick it up ?

**Comment by tlimoncelli** [comment]
Sure!

>

**Comment by murarisumit** [comment]
Hey sorry, i deleted my above comment, forgot you would have received in email. Actually i can only test it with digitalocean provider not with others, as I have nameservers over there.

So wouldn't be able to test it for all providers !

**Comment by teknogeek** [comment]
I was trying to import `dnscontrol/v2` with go modules and was getting blocked by the bad `hexonet-sdk` version, so I made a fix for this. See #662

**Comment by tlimoncelli** [comment]
Thanks @teknogeek for fixing this!
