### ISSUE TITLE
More providers should implement "get-zones" 

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#628]
Commit 87ad01d194ddc05950e79382c838d348e11d3db2 added a new subcommand called "get-zones" which replaces the (mostly broken) convertzone command.  It is a stand-alone command that allows users to download zone records from a provider. It is useful for bootstrapping your dnsconfig.js configuration.

This subcommand works for any provider that implements a new function called `GetZoneRecords`.  I've added such a function to all providers that simply outputs "not implemented".  I'm asking that all providers replace this function with one that actually does the required task.  Initially I've implemented it for BIND, GANDI_V5, and @captncraig wrote one for CLOUDFLAREAPI.

The functional is fairly easy to implement since the code exists in `GetZoneCorrections()`.  One simply (?) extracts out that code into a separate function.

- [x] **ACTIVEDIRECTORY_PS @tlimoncelli
- [x] **AZURE_DNS @vatsalyagoel
- [X] **BIND @tlimoncelli
- [X] **CLOUDFLAREAPI @captncraig
- [x] CLOUDNS @pragmaton
- [x] DIGITALOCEAN @Deraen
- [x] DNSIMPLE @aeden
- [ ] EXOSCALE @pierre-emmanuelJ 
- [X] GANDI_V5  @tlimoncelli
- [x] **GCLOUD  @tlimoncelli
- [ ] HEXONET @papakai
- [ ] INTERNETBS @pragmaton
- [ ] LINODE @koesie10
- [ ] NAMECHEAP @captncraig
- [x] **NAMEDOTCOM  @tlimoncelli
- [ ] NS1 @captncraig
- [ ] OCTODNS @tlimoncelli
- [ ] OPENSRS @philhug 
- [x] OVH @masterzen
- [x] **ROUTE53  @tlimoncelli
- [ ] SOFTLAYER @jamielennox 
- [x] VULTR @geek1011

We'll consider this bug complete when both of these statements are true:

* At least 50% of all providers implement this feature
* 100% of the providers labeled `**` implement this feature

This feature blocks the 3.0 release.

**Comment by aeden** [comment]
@tlimoncelli for DNSimple I'm going to ask @onlyhavecans to implement it.

**Comment by papakai** [comment]
@tlimoncelli for HEXONET I'll dive into the review in mid of march. As I am very busy, I can't handle it earlier.

**Comment by tlimoncelli** [comment]
> @tlimoncelli for HEXONET I'll dive into the review in mid of march. As I am very busy, I can't handle it earlier.

Sounds good!

**Comment by geek1011** [comment]
I'll probably get to this sometime before March, but not in the next week.

**Comment by masterzen** [comment]
@tlimoncelli I've finally implemented `GetZoneRecords` for ovh in the #666 PR (sorry for the delay). Feel free to review and merge it if you think it is ready.

Thanks !

**Comment by tlimoncelli** [comment]
With OVH support get-zones, we are at 50% and can consider this ready for 3.0!   Thanks to @masterzen for putting us over the finish line!

**Comment by pragmaton** [comment]
Done in https://github.com/StackExchange/dnscontrol/pull/681

**Comment by pragmaton** [comment]
INTERNETBS - only Registrar for now and I don't have any plans to implement any DNS Provider functions.

**Comment by tlimoncelli** [comment]
Enough providers have implemented this that I'll consider it "done".   Providers are encouraged to continue with updates.
