### ISSUE TITLE
Cloudflare's get-zones implementation should include "orange cloud"

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#629]
`dnscontrol get-zones --format=dsl cred CLOUDFLAREAPI example.com` does not output any indication of `CF_PROXY_ON`, `CF_PROXY_OFF`, or `CF_PROXY_FULL`.

Quoting @captncraig 

> Cloudflare uses metadata for the "orange cloud" proxy configuration. Right now the existing function to get records does not recreate that, but instead the driver queries the "original" record field to learn what it needs to know. It gets worse, because the "read-only" side of things doesn't really know whether to use "on" or "full" (I don't even remember which does what anymore). But maybe using "on" is an ok default for get-zone for records that are already enabled? GetZoneRecords could maybe add "on" to records it finds need it? Assuming GetZoneRecords creates the proper metadata, the dsl printer should probably output it.

**Comment by tlimoncelli** [comment]
Related: https://github.com/StackExchange/dnscontrol/issues/674

**Comment by tlimoncelli** [comment]
Would love your feedback, @mrtristan

**Comment by tlimoncelli** [comment]
@mrtristan Better late than never... https://github.com/StackExchange/dnscontrol/issues/629 should add this feature.

**Comment by mrtristan** [comment]
@tlimoncelli i think you mean https://github.com/StackExchange/dnscontrol/pull/952

i'll check it out, thanks!

**Comment by tlimoncelli** [comment]
Correct. The fix is in https://github.com/StackExchange/dnscontrol/pull/952

**Comment by tlimoncelli** [comment]
I've merged the change. (sorry if I'm a bit impatient... trying to get this and 1 other change in so I can do a release). If there are bugs, please let me know.
