### ISSUE TITLE
get-zones doesn't handle TTLs very well

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#630]
Not sure if this is fixed but I don't want to lose the info, so I'm quoting it here.

Quoting @captncraig:

> TTLs are always horrible. Cloudflare uses 1 as a default and my dsl output was littered with TTL(1). I first changed the cloudflare code to replace 1 with 300, but then noticed the default is configurable. So I kinda went with the reverse of another convention we have used: "If GetZoneRecords gives you a 0 ttl, use the default value.". Is that sensible? Its in the PR above.

**Comment by tlimoncelli** [comment]
I can confirm this issue.  I don't think the --ttl flag is connected to the pretty. Possibly dsl too.

**Comment by tlimoncelli** [comment]
Working on this in https://github.com/StackExchange/dnscontrol/pull/654

**Comment by captncraig** [comment]
I think for the most part there isn't much to do here. The majority of
providers have a very simple ttl model that translates directly to the DNS
control model.

It is just for things like cloudflare that have magic values.and things
that we would need to do anything special. Basically if we do any special
ttl conversions in the driver, do the opposite for get-zones.

**Comment by tlimoncelli** [comment]
Do cloudflare zones have more reasonable output with https://github.com/StackExchange/dnscontrol/pull/657 ?
