### ISSUE TITLE
ALIAS support for Azure DNS

### ISSUE THREAD

**Issue by vatsalyagoel** [StackExchange/dnscontrol#634]
I wanted to engage in some discussion before I went ahead an implemented this feature.

Azure supports Alias Records as a configuration in the following record types as stated [here](https://docs.microsoft.com/en-us/azure/dns/dns-alias):
* A
* AAAA
* CNAME

We have previous provisions to implement custom record types as done previously in R53_ALIAS. I thought of implementing it similar to that however ran into some roadblocks. Firstly, Route 53 has a single Alias Record Type whereas Azure DNS has 3. The second issue is that Azure Alias Records can point to a specific azure resource as a resource path or to a different record in the same zone for e.g.

```http
PUT https://management.azure.com/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/dnsZones/zone1/A/record1?api-version=2018-05-01
```

```json
{
  "properties": {
    "metadata": {
      "key1": "value1"
    },
    "TTL": 3600,
    "targetResource": {
      "id": "/subscriptions/726f8cd6-6459-4db4-8e6d-2cd2716904e2/resourceGroups/test/providers/Microsoft.Network/trafficManagerProfiles/testpp2"
    }
  }
}
```

This means we would have to bypass the validation checks for the alias records as they aren't standard DNS Records. 

I was thinking of implementing something similar to how we've done it for Cloudflare as the "Orange Cloud" is an amendment to the standard record while maintaining original functionality. 

The other solution is to register 3 different record types:

* AZURE_ALIAS_A
* AZURE_ALIAS_AAAA
* AZURE_ALIAS_CNAME

Then implement a fully custom validation state by just using the response from the rest API.

This could also cause issues in get-zone command.

@tlimoncelli @captncraig Do you think it should be implemented in DNS Control?

**Comment by tlimoncelli** [comment]
I think it is best to implement the three record types: AZURE_ALIAS_A/AZURE_ALIAS_AAAA/AZURE_ALIAS_CNAME.

Ideally we'd have one generic "ALIAS" record that would Do The Right Thing for each provider, but reality makes that impossible.  A universal ALIAS would be useful when moving from one provider to another.  However, if you are using an Azure resource path, we can assume moving to another provider will mean changing away from Azure resource paths too.  If we ever did implement a universal ALIAS it would only be what's common among all providers... which isn't very useful.  I'm told that Terraform faced the same challenge and decided that portability isn't possible, so it is better to make provider-specific controls.

As far as the get-zones command, it should work for `--format=tsv` and `--format=dsl`.  For `--format=pretty` it should output the record as best as it can, but commented out.  I believe that code is already there, please let me know if it doesn't work for you.

Tom
