### ISSUE TITLE
Abide by Digital Ocean's rate limit

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#636]
I consistently get a 429 http code during integration testing.

            integration_test.go:145: GET https://api.digitalocean.com/v2/domains/dnscontrol-do.com/records: 429 Too many requests

Go has a number of rate limiting modules.  However I think it would be easier to detect the 429 http response, pause, and retry.  In theory such requests should always be re-tryable. (I hope!)

**Comment by tlimoncelli** [comment]
CC @Deraen

**Comment by tlimoncelli** [comment]
CC @Deraen @mikenz @pgaskin 

I'm working on adding rate limiting to the Digital Ocean provider and I see something I don't understand.  Maybe one of you has more info?

When a 429 statuscode is received, DO adds the header `Ratelimit-Reset` which contains the Unix time when the rate limit counter should reset.  In theory you can sleep until that time and the next request should go through.

However the time I'm getting is in the past!

For example, I got this time: 1604779129

I ran this command:

```
$ export TZ=UTC ; date -u ; date --date=@1604784171
Sat Nov  7 21:47:55 UTC 2020
Sat Nov  7 21:22:51 UTC 2020
```

If I do a simple exponential back off everything is fine. That said, I feel like if DO is going to give us this extra information we should use it.

My draft PR is https://github.com/StackExchange/dnscontrol/pull/934

**Comment by tlimoncelli** [comment]
Sample output:

```
=== RUN   TestDNSProviders/dnscontrol-do.com/Post_cleanup:Empty#08
    integration_test.go:180: DELETE TXT foo.dnscontrol-do.com "with space at end  " ttl=300, DO ID: 120553142
2020/11/08 04:58:26 Rate limit exceeded. Ratelimit-Reset is 1604828759 2020-11-08 09:45:59 +0000 UTC
2020/11/08 04:58:26 TIME now:   2020-11-08 09:58:26.771305 +0000 UTC
2020/11/08 04:58:26 TIME reset: 2020-11-08 09:45:59 +0000 UTC
2020/11/08 04:58:26 TIME dur:   -12m27.771304s
2020/11/08 04:58:26 Using exponential backoff instead: 5s seconds
=== RUN   TestDNSProviders/dnscontrol-do.com/10:empty_TXT:TXT_with_empty_str
    integration_test.go:180: CREATE TXT foo1.dnscontrol-do.com "" ttl=300
=== RUN   TestDNSProviders/dnscontrol-do.com/Post_cleanup:Empty#09
```

**Comment by Deraen** [comment]
https://developers.digitalocean.com/documentation/v2/#rate-limit

The field is not about when the whole rate limit resets, for a single request:

> RateLimit-Reset: This represents the time when the oldest request will expire. The value is given in Unix epoch time. See below for more information about how request limits expire.

**Comment by tlimoncelli** [comment]
Oh duh. I was confusing it with the `Retry-After` header that other systems (not DigitalOcean) support.

I guess the only solution is an exponential back-off.

**Comment by tlimoncelli** [comment]
Done!
