### ISSUE TITLE
Invalid integration test 49

### ISSUE THREAD

**Issue by masterzen** [StackExchange/dnscontrol#667]
Hi,

While working on #628 for the OVH provider, I noticed that an integration test for OVH weren't passing anymore, namely the SSHFP 49:

https://github.com/StackExchange/dnscontrol/blob/c98b9221709ade929b83cee9328e41c283ae8c02/integrationTest/integration_test.go#L476-L477

This models a fingerprint method change from SHA-1 to SHA-256. 
OVH errors on it, because the fingerprint is not a SHA-256 fingerprint (the size of the fingerprint is not 64 bytes).

I believe this test is not needed, as if we succeed the following test in the test suite:
https://github.com/StackExchange/dnscontrol/blob/c98b9221709ade929b83cee9328e41c283ae8c02/integrationTest/integration_test.go#L478-L479
then that implies we succeeded in changing the fingerprint method.

What do you think ?

**Comment by tlimoncelli** [comment]
(I don't know much about the SSHFP rtype so please correct me here)

What I hear you saying is that if the method changes, the fingerprint changes too. Therefore a test for just the method changing doesn't make sense.  The test should change the method and the fingerprint.

If I've understood the situation correctly, would you submit a PR?

**Comment by masterzen** [comment]
@tlimoncelli yes you got it right. 

There are only 2 fingerprint methods defined so far: SHA-1 and SHA-256. They produces results of different size, so a SHA-1 fingerprint can not be used as a SHA-256 fingerprint (the reverse also holds).

Yes, I'll submit a PR ASAP.

**Comment by tlimoncelli** [comment]
Merged.  Thanks for the PR!
