### ISSUE TITLE
Support Route53 as a registrar

### ISSUE THREAD

**Issue by ddrght12345** [StackExchange/dnscontrol#68]
`Error creating registrars: Registrar type ROUTE53 not declared.`
Self explanatory?
We just recently moved to r53, so this would be nice.

Since I have been wanted to learn Go, this may be a good chance for me, but Im not sure when I would be able to start this, in case someone else is capable of doing this faster/before I can start learning

**Comment by captncraig** [comment]
Hey, this should be pretty easy to implement at this point, we have just never had the need for it. It is really as simple as implementing a single function on the [route53Provider](https://github.com/StackExchange/dnscontrol/blob/master/providers/route53/route53Provider.go#L18) type to set the nameservers appropriately. 

Just implement `GetRegistrarCorrections(dc *models.DomainConfig) ([]*models.Correction, error)` and register it appropriately, and it should work. See the [namecheap](https://github.com/StackExchange/dnscontrol/blob/master/providers/namecheap/namecheap.go#L32) implementation for an easy reference.

I could do it, but if you would like the opportunity to learn and contribute it is all yours.

**Comment by ddrght12345** [comment]
Oh. Fantastic!
Then I may try to tackle this, after all. 
Thanks for the reference

**Comment by captncraig** [comment]
closed via #155
