### ISSUE TITLE
Example.org zonefile per Tom's request

### ISSUE THREAD

**Issue by philpennock** [StackExchange/dnscontrol#685]
This is redacted from spodhuis.org, with some records added from a couple of other domains to round out the example.

Nothing in this is a stress-test.  It's all real records.  It's just ... varied.

[example.org.zone.txt](https://github.com/StackExchange/dnscontrol/files/4302801/example.org.zone.txt)

**Comment by philpennock** [comment]
I don't normally include `RP` in zones which handle email, I added it here to round out the example.  My stance is "any domain which does not send or receive email, and declares such, needs to make available contact information and RP is the way to do it".

**Comment by tlimoncelli** [comment]
I commented out some of the lines and integrated it into https://github.com/StackExchange/dnscontrol/pull/688

I found and fixed a TON of bugs by going `zonefile -> js -> zonefile` with these commands:

```
dnscontrol get-zone --format=js -out=foo.jsf bind BIND example.org
dnscontrol preview --config foo.js
```

I hope to merge that PR soon.  Would appreciate feedback!

**Comment by tlimoncelli** [comment]
Merged and seems to be working well. Thanks!
