### ISSUE TITLE
Issues with the documentation for `require()`

### ISSUE THREAD

**Issue by pjeby** [StackExchange/dnscontrol#686]
The current documentation compares the `require()` function to that of node.js, even though it is almost (but not quite) utterly unlike it: it does not use the same path resolution rules, does not consider extensions optional, doesn't run each module in a separate namespace, doesn't look up modules globally, ...  really comparing it doesn't make sense at all.

I would suggest changing the documentation to something like this:

> `require(...)` loads the specified JavaScript or JSON file, allowing to split your configuration across multiple files.
> 
> If the supplied `path` string ends with `.js`, the file is interpreted as JavaScript code, almost as though its contents had been included in the currently-executing file.  If  the path string ends with `.json`, `require()` returns the `JSON.parse()` of the file's contents.
> 
> If the path string begins with a `.`, it is interpreted relative to the currently-loading file (which may not be the file where the `require()` statement is, if called within a function), otherwise it is interpreted relative to the program's working directory at the time of the call.

This would let users understand how the function actually behaves, without them wondering why e.g. `module.exports` doesn't work, or why `./` is module-relative rather than package-relative, etc.

Indeed, it might be better to rename the function to something like `include()` instead, (leaving `require` as a deprecated alias) because by analogy it is *much* closer to PHP's `include()` function than it is to node's `require()`.  (After all, the reason node.js calls it "require" is because it's a declarative statement saying the file is needed, and so should be loaded if it hasn't already been loaded.)

In contrast, dnscontrol's require is actually an imperative command to load the file and execute the code or parse the data from it.  (So if two files both `require("./tools.js")`, for example, then it will be loaded twice, whereas in node.js it would only be loaded once.)

**Comment by tlimoncelli** [comment]
This is a great bug report because not only did you supply replacement text, but I learned a bit about Node (something I haven't used).

How's this for an update: https://github.com/StackExchange/dnscontrol/pull/690

As far as renaming the command, I'd be open to a PR!

**Comment by pjeby** [comment]
LGTM.  As far as changing the command, I kind of think it perhaps should be replaced by having a readFile or getFileContents() or some such, since basically both functions of `require()` can be emulated in JS if you just had a way to read a file.  At least, require (or include) could be explained in terms of eval(readFile(path)) and JSON.parse(readFile(path)) at that point.  (Also, a readFile() function would have many more uses than just reading JSON and JS code.)

All that being said, I'm starting to lean towards just using node.js to begin with, and just passing an IR tree to dnscontrol anyway, so reading files of whatever type, using node modules and API and what-have-you, would be a done deal without dnscontrol having to support them.  (Indeed, I rather wish you could pass stdin as the `--ir` option for that very reason, as then I wouldn't need to create temporary files to run dnscontrol on the output of another program on Windows.)

As it happens, I have been finding dnscontrol's DSL rather awkward for higher-order programming dealing with large sets of domains that need to mix and match lots of components.  For example, I recently coded a hack that lets me declare that a domain has its mail sent by a particular mailserver or sender, and then only at the *end* of the entire script, generating SPF records only after *all* the mailservers for the domain are known.

Within the current DSL framework, this is a hassle because there's no way for a function to say, "and come back once this domain is fully configured".  Indeed, the builtin DSL has no way to reference domains at all, so I first had to make a wrapper API that hangs onto the domains at creation.

Between that issue and issues with regression testing , I now use a "canonicalized"  form of the IR to do regression tests when refactoring, using a short `jq` script to turn the list of domains into an object mapping names to domains, and record names to mappings of record types to record lists, with all mapping keys sorted.  This lets me diff IR for semantics without caring what order domains were originally defined in, or what order records were defined in (except those that are of the same type and key).  Before I did that, using the IR to do regression testing for refactoring was a pain, because the IR changed dramatically for very minor changes to my code, despite there not being any semantic difference.  And with ~100 CloudFlare domains, using the preview function to do regression testing was insanely slow.

Anyway, what I'm kind of getting to in my somewhat roundabout way, is that I wonder if perhaps some future release should just focus more on IR handling, perhaps with a more "semantic" IR schema.  There are a great many programming languages and other tools for generating JSON, so maybe maintaining and expanding a JS engine to generate JSON isn't in the sweet spot for dnscontrol in the long run?  Especially considering that the ES5 dialect understood by Otto is now a bit... "quaint" by modern JS standards.  ;-)  (i.e., it's more than 5 years obsolete)

But that's less a call for removing the JS engine, and more a suggestion that perhaps 1) cleaning up the IR a bit (so that two files with the same semantics are also structurally comparable) and 2) documenting it as a spec, while 3) allowing it to come frm stdin, would give your users an escape hatch from the limitations of your JS interpreter.

Really, the main thing stopping me from just flat out abandoning your DSL to roll my own in jq and/or node.js, is the fact the IR isn't declared to be stable.  (Though on reflection, it kind of has to be, because otherwise it's not just the JS parts you'd need to rewrite.)

Anyway, I'll give some thought to future PRs related to these matters.  ;-)  (And again, #690 LGTM.)

**Comment by tlimoncelli** [comment]
Wow!  I must say you take the language design of this project a lot more seriously than I do.  My goal is to keep it simple and shift most of the work to the Go part of the project.  

The things you are doing a very sophisticated... beyond what I had intended for dnscontrol.  Have you considered Terraform?  It has a lot richer programability.

**Comment by pjeby** [comment]
I'd heard the *name* Terraform, but not what it did.  I'll have to investigate further.  A quick glance does makes it look like it might be the sort of thing I'm currently doing with my wrapper for your DSL, though, but for more things.  So yeah, that might be worth looking into, especially if it lets me provision things besides DNS.  Thanks for the suggestion.

I'm going to go ahead and close this issue - (I'm actually not sure why it didn't close at my last comment, as I'd intended.  Maybe I hit the wrong button.)
