### ISSUE TITLE
Inconsistent counting?

### ISSUE THREAD

**Issue by willpower232** [StackExchange/dnscontrol#697]
> ----- DNS Provider: digitalocean...2 corrections
>#1: DELETE CNAME delta.example.com server.example.com. ttl=43200, DO ID: 12345678
>SUCCESS!
>#2: DELETE CNAME uniform.example.com server.example.com. ttl=43200, DO ID: 87654321
>SUCCESS!
>----- DNS Provider: r53...1 correction
>#1: 
>DELETE CNAME delta.example.com server.example.com. ttl=43200
>DELETE CNAME uniform.example.com server.example.com. ttl=43200
>
>SUCCESS!

Not a major issue I know and doesn't seem to cause an actual problem but presumably this is down to how each provider handles things?

**Comment by captncraig** [comment]
Yes, it is really the number of unique operations that need to be performed. Different providers have different levels of "atomicity" for how many changes you can make at once. 

With r53 we can submit batches of changes to do everything at once. It is a bit safer that way. With Digital Ocean the best granularity is deleting individual records one at a time.

**Comment by willpower232** [comment]
Thanks for confirming
