### ISSUE TITLE
No help topic for 'get-zones'

### ISSUE THREAD

**Issue by willpower232** [StackExchange/dnscontrol#698]
Re #613 every example I run from https://stackexchange.github.io/dnscontrol/get-zones to try using the `get-zones` command returns `No help topic for 'get-zones'`. I'm trying with Route 53 and DigitalOcean which are ticked as having this feature on the providers list.

Version: dnscontrol 2.11.0 ("4712e5e4459d7c80df57f5a87a85e8aa4fdf0bd5") built 14 Feb 20 15:51 GMT

Also https://stackexchange.github.io/dnscontrol/check-creds is referred to by https://stackexchange.github.io/dnscontrol/providers/gcloud, is that a typo and incorrect page?

**Comment by tlimoncelli** [comment]
Are you on the latest `master`?  The docs, sadly, are ahead of the releases.

What's the exact command you are running?

**Comment by willpower232** [comment]
> The docs, sadly, are ahead of the releases

Ah my bad, I thought I had the dates in the right order
