### ISSUE TITLE
Doesn't build: go.mod still uses /v2

### ISSUE THREAD

**Issue by mholt** [StackExchange/dnscontrol#713]
The latest release is 3.0 but the go.mod still uses the /v2 suffix, breaking semantic import versioning: https://github.com/StackExchange/dnscontrol/blob/2a44a89d1bb0d802de62069e96b5ec86194e53b6/go.mod

```
require github.com/StackExchange/dnscontrol/v2: version "v3.0.0" invalid: module contains a go.mod file, so major version must be compatible: should be v2, not v3
```

It should be updated to use /v3. Builds are currently broken.

**Comment by tlimoncelli** [comment]
Hi there!

First I want to apologize for breaking the build.  This is our first time I've bumped the "major version" since Go's modules were introduced.  Tons to learn!

Oddly enough, it builds for me either way.  I'd love help reproducing your error message so I can learn more about modules.

That said, here's the fix: https://github.com/StackExchange/dnscontrol/pull/716/files

**Comment by mholt** [comment]
Hey Tom, no worries -- the fix looks good!

To reproduce the issue, I think you can just run:

```
$ go get github.com/StackExchange/dnscontrol/v3 
go get github.com/StackExchange/dnscontrol/v3: module github.com/StackExchange/dnscontrol@upgrade found (v0.2.8), but does not contain package github.com/StackExchange/dnscontrol/v3
```

Because the v3.0.0 tag has a mismatched module name (ending in /v2), the Go module proxy does not recognize it (I think). So, it tries the latest valid tag in the 1.x and pre-1.x range, which is v0.2.8. The next tag after that was v2.9, which requires a module name ending in /v2.

In any case, thanks for the fix! I went through similar head-scratching when trying to figure out how to version Caddy properly... the transition was definitely a bit bumpy for us too.

**Comment by tlimoncelli** [comment]
Thanks for helping me find and fix it!    (P.S. I'm a big fan of Caddy!)

**Comment by mholt** [comment]
@tlimoncelli That's neat, glad to hear it!

I do have some questions related to that, as I want to make wider use of this library in Caddy. I'll open a new issue.
