### ISSUE TITLE
Provider request: Netlify

### ISSUE THREAD

**Issue by FiloSottile** [StackExchange/dnscontrol#714]
Netlify offers managed DNS for arbitrary zones.

There is an API, although the docs and Go client support are pending in a PR: netlify/open-api#207

**Comment by brentybh** [comment]
Really need this

**Comment by tlimoncelli** [comment]
I'd love to get a volunteer to write the code for this.

Our [Step-by-Step Guide](https://stackexchange.github.io/dnscontrol/writing-providers) makes it pretty easy.  You basically write (1) a function to authenticate, (2) a function to download all the records for a zone, (3) a function that does an add/change/delete.  DNScontrol does all the rest.  Many of our providers were written by people that are new to Go.

Tom

**Comment by kmutahar** [comment]
Adding onto this while netlify/open-api#207 has been close a similar PR was made and merged netlify/open-api#211 

In-case any one is interested and to revive this issue.
