### ISSUE TITLE
Provider request: Hetzner

### ISSUE THREAD

**Issue by hebbet** [StackExchange/dnscontrol#715]
Hetzner released a new dns-service with api support.

https://dns.hetzner.com/api-docs/

**Comment by ramlev** [comment]
Please prioritize this :)

**Comment by tlimoncelli** [comment]
As an open source project, we gladly accept code.  As the project owner, I'll gladly coach you through writing the provider (you'll be surprised at how easy it is).

**Comment by ramlev** [comment]
I have looked into one of the providers, and looks do'able, even though i dont haev any GO experience.

**Comment by tlimoncelli** [comment]
Yes, I understand.

P.S. I'm still willing to coach.  We have a pretty good track record with people writing providers as their first Go experience.  [link](https://everythingsysadmin.com/2017/08/go-get-up-to-speed.html)

**Comment by das7pad** [comment]
I gave this a spin and opened https://github.com/StackExchange/dnscontrol/pull/904.
