### ISSUE TITLE
Avoiding bloat by separating the DNS provider implementations

### ISSUE THREAD

**Issue by mholt** [StackExchange/dnscontrol#717]
Long post, sorry!

**Summary:** Would you be open to moving the DNS provider implementations into separate repos or at least separate Go modules? (Preferably repos.)

----

[Caddy](https://caddyserver.com) uses DNS provider APIs to solve the ACME DNS challenge. Currently, we use [lego's _many_ DNS provider implementations](https://github.com/go-acme/lego/tree/master/providers/dns).

Unfortunately, merely importing lego's core adds about 20 MB to the compiled binary, significantly slows down build times, and adds about 1000+ lines to go.sum which means that there are _hundreds_ of dependencies which could easily break a fresh `go build` or `go get`, for example if one of them has a Go module that is misconfigured (which we now know is easy to do!).

If all providers are actually used or referenced in the main package, a total of about 40 MB is added to the binary. And it will just keep growing, along with the other problems I mentioned.

Anyway, I tried without success to convince the maintainers to move them out of the repo or into separate Go modules... also, those implementations are much simpler: they only implement a very narrow interface of, basically, `Present()` and `CleanUp()` methods -- specifically for solving the ACME challenges.

We want to be able to do more with DNS APIs than just set and clear a TXT record. For example, [my dynamicdns side project](https://github.com/mholt/caddy-dynamicdns/) is a Caddy app that keeps 'A'/'AAAA' records pointed at the server's dynamic IP address. I'm using dnscontrol for this.

I'd actually like to use dnscontrol for everything, including solving ACME challenges, rather than using two different libs. I am preparing to fork lego and maintain a separate code base and all DNS provider implementations if necessary, to accomplish our goals. One of them is to avoid build+binary bloat, by having the DNS provider implementations as separate modules or repos.

Another goal would be to add more DNS providers than dnscontrol currently supports. Lego currently supports 60 or 70+... but it's more work to add them to dnscontrol than to lego because dnscontrol does more stuff, but I think it'll be well worth it to have the single, unified, and generalized interface that dnscontrol exports rather than something more narrow like lego's.

Again, I'm willing to fork libraries as needed to achieve this goal, since I think the payoff will be well worth it in the long run. (I have other reasons I need to fork lego though, too. I would just rather fork one library than two.) My lego fork would probably make use of dnscontrol as well, and I think with enough momentum we might even be able to make them the mainline development for Go + DNS APIs + ACME abilities.

**Comment by tlimoncelli** [comment]
Do you mean the API interface code or the individual items in providers/* ?

If you look at the dnscontrol "get-certs" subcommand, you'll see that we solved the problem by using dnscontrol for the updates.  Have you looked at how we did that?

**Comment by mholt** [comment]
> Do you mean the API interface code or the individual items in providers/* ?

Yeah, I mean the providers here: https://github.com/StackExchange/dnscontrol/tree/master/providers -- can we consider moving them to separate repos? (I know it's a lot of tedium up front, I'm willing to help!)

> If you look at the dnscontrol "get-certs" subcommand, you'll see that we solved the problem by using dnscontrol for the updates. Have you looked at how we did that?

Yep, although I will be using the DNS providers in this repo, I won't be using the pkg/acme package in this repo.

I'm mostly interested in reducing the size of [go.mod](https://github.com/StackExchange/dnscontrol/blob/master/go.mod) (and the associated go.sum). This will reduce bloat both of builds and development environments, while also decoupling any breaking upstreams as much as possible.

**Comment by tlimoncelli** [comment]
TBH my life is kind of exploding right now.  I can't think of big changes like this right now. Maybe after the pandemic.

**Comment by mholt** [comment]
@tlimoncelli No worries, not a huge priority to consider! If I get around to it first, it'll probably be a fork which won't be a blocker, and we can always discuss it later. Take care!

**Comment by tlimoncelli** [comment]
sure!  I'll probably understand it better once I see the fork.

Be well!
