### ISSUE TITLE
Route53 get-zones doesn't convert aliases correctly

### ISSUE THREAD

**Issue by truthdoug** [StackExchange/dnscontrol#720]
I ran get-zones on a route53 domain and I have one Route53 alias record. The output produced by get-zones is

    R53_ALIAS('api.dougtest, 'testserver.mydomain.com. atype=CNAME zone_id=Z2XMPVPIGE8OH3'),

When I preview, I get this error:

    Executing javascript in dnsconfig.js: R53_ALIAS record requires 3 arguments (name, type, target). Only 2 were supplied 

Changing to this fixed it:

    R53_ALIAS('api.dougtest', 'CNAME', 'testserver.mydomain.com.'),

**Comment by tlimoncelli** [comment]
I don't have any R53 zones that use aliases. Can you try this?

https://github.com/StackExchange/dnscontrol/pull/721

**Comment by truthdoug** [comment]
Yes, that works!
