### ISSUE TITLE
SSHFP support for Google Cloud DNS

### ISSUE THREAD

**Issue by decke** [StackExchange/dnscontrol#726]
Google Cloud DNS integration seems to not support SSHFP records yet. `dnscontrol get-zones` did properly generate the SSHFP entries but `dnscontrol preview` fails with them with the error message:

```
1 Validation errors:
ERROR: Domain XXX uses SSHFP records, but DNS provider type GCLOUD does not support them
```

Technically Google Cloud DNS does properly support SSHFP via their web interface and on their DNS servers.

**Comment by tlimoncelli** [comment]
Good catch!  Thank you for reporting that!

I've updated GCLOUD's profile.

Tom

**Comment by decke** [comment]
Thanks, works like a charm!
