### ISSUE TITLE
Private keys are world-readable

### ISSUE THREAD

**Issue by mholt** [StackExchange/dnscontrol#728]
Feel free to correct me if I'm wrong (definitely not a Linux guru) -- but I believe these permissions:

https://github.com/StackExchange/dnscontrol/blob/5416c16fa1acabfd280d4adfeb6f2cde68c19b3a/pkg/acme/directoryStorage.go#L37-L39

allow any user on the system to read the files if they know the filepath (which are deterministic), including the private key.

[In CertMagic we use 0600](https://github.com/caddyserver/certmagic/blob/0643091dc5705651fdc4c6b72043b5ffc521217e/filestorage.go#L50) -- could dnscontrol do the same? Probably not a huge deal in practice, but it _seems_ easy enough to change a couple of digits for some better peace of mind. 🤷

**Comment by tlimoncelli** [comment]
Agreed. Fixing.
