### ISSUE TITLE
Support passing the intermediate JSON as a command line parameter?

### ISSUE THREAD

**Issue by evaryont** [StackExchange/dnscontrol#73]
So I already have my own internal project that generates DNS zones using a DSL in Ruby. It outputs bind files currently, but I heard about DnsControl and thought I might be able to reuse it's providers support.

**Comment by captncraig** [comment]
Ha. We had something like that at one point, and sort of ripped it out because we never used it. It would be fairly easy to implement, you just bypass the whole js interpreting step. Can do.

**Comment by evaryont** [comment]
The only concern I have at the moment is that the intermediate JSON is undocumented outside of the code. Though it'd be trivial to generate a .js file that exercises the various functions and read the output of `-debugrawjson`.

**Comment by captncraig** [comment]
Yeah, we parse it into [this struct type](https://godoc.org/github.com/StackExchange/dnscontrol/models#DNSConfig). The generated js route is also viable, but I like it a little less. The actual front-end should be fairly insignificant.

**Comment by tlimoncelli** [comment]
FYI: @evaryont 
A recent commit changes the json field "priority" to "mxpreference".  This may be a breaking change for you.  This is to make all the optional field names consistent with the RFCs and prefixed by the rtype they relate to.  The result is better support for SRV and (some day) CAA, DS, and other records.

**Comment by evaryont** [comment]
Thanks for the heads up! I guess this is the part where I recommend creating a CHANGELOG. :)
