### ISSUE TITLE
Updates for deSEC

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#730]
CC: @D3luxee @nils-wisiol @Knight1 @peterthomassen

Hi folks!  When I approved PR https://github.com/StackExchange/dnscontrol/pull/725 I forgot to check the items listed in `docs/writing-providers.md`. These should be easy to fix.

1. In `docs/writing-providers.md` near "Pick a similar provider as your base".  Please add this provider to the list for `incremental-label` or `incremental-label-type` as appropriate.  I think it is the former.

2. In `docs/provider-list.md` in `Providers with "contributor support"` please add DESEC and the maintainer's name.

3. Add the maintainer's name to `OWNERS`

Thanks!

**Comment by D3luxee** [comment]
Hi @tlimoncelli,
i've created another pull request which should resolve the issues you mentioned.

**Comment by Alixerid** [comment]
Thanks for adding deSEC!
I tried to use release v3.0.0 with deSEC but then realized that. despite the [current docs](https://stackexchange.github.io/dnscontrol/providers/desec) being updated already, the latest release doesn't include the deSEC provider yet. Is there any chance for another release soon? Thanks!

**Comment by tlimoncelli** [comment]
I'll be doing a release soon.  In the meanwhile "go install" from the master branch should give you the binary you need.

**Comment by tlimoncelli** [comment]
A new release has shipped!
