### ISSUE TITLE
Can't create domain in deSEC

### ISSUE THREAD

**Issue by dereulenspiegel** [StackExchange/dnscontrol#732]
Hello :)

I just tried this tool together with the new deSEC provider. My config looks like this
```
var REG_NAMECHEAP = NewRegistrar("namecheap","NAMECHEAP");
var deSEC = NewDnsProvider('desec', 'DESEC');

D("my.domain", REG_NAMECHEAP, DnsProvider(deSEC),
  A("@","1.2.3.4", TTL(60))
);
```

The domain is already bought and registered at namecheap. My impression is that this code should create this domain in deSEC and add an A record. But instead I get the following error:
```
******************** Domain: my.domain
----- Getting nameservers from: desec
----- DNS Provider: desec...ERROR
Error getting corrections: Error fetching records from deSEC for domain my.domain: Not found.
Done. 0 corrections.
Completed with errors
```
So it seems it authentication is not a problem and it correctly retrieves the information that this domain, currently does not exist in deSEC. But why is this an error?

Thanks in advance :)

**Comment by D3luxee** [comment]
Just run `./dnscontrol create-domains` this is a separate command and will not automatically happen.

**Comment by dereulenspiegel** [comment]
Thank you, I must have missed that. Sorry for not reading the documentation throughly enough.

**Comment by tlimoncelli** [comment]
> Thank you, I must have missed that. Sorry for not reading the documentation thoroughly enough.

Could you suggest where we could be more clear?  (or, to be more plain... where did you look, because I'd like to put a note there)

When someone says "I couldn't find the answer" I treat it like a bug and want to improve the findability. :)

**Comment by dereulenspiegel** [comment]
I followed the Getting started guide (https://stackexchange.github.io/dnscontrol/getting-started) with the modification that I used my correct registrar und correct dns provider directly.
Probably there needs to be a comment explaining that you need to run `create-domains` when using a "real" dns provider.
