### ISSUE TITLE
Route53 Always Create/Modify NS records

### ISSUE THREAD

**Issue by joshbartley** [StackExchange/dnscontrol#741]
Using `get-zones` with the Route53 provider produces a dnsconfig.js containing `NAMESERVER('NS-111.AWSDNS-11.COM.'),`

Taking the generated dnsconfig.js into `dnscontrol preview` creates an output of

`
CREATE NS domain.com ns-111.awsdns-11.org. ttl=3600
CREATE NS domain.com ns-111.awsdns-11.co.uk. ttl=3600   
MODIFY NS domain.com: (ns-111.awsdns-11.co.uk. ttl=300) -> (ns-111.awsdns-11.co.uk. ttl=3600)  
MODIFY NS domain.com: (ns-111.awsdns-11.org. ttl=300) -> (ns-111.awsdns-11.org. ttl=3600) 

Which can't be resolved because the NS can't be applied to the bare domain.

If you also happen to drop one of the Route53 servers out of your configuration, dnscontrol forces it back in because AWS reports it even though Route53 isn't listed as the registar for the domain.

**Comment by tlimoncelli** [comment]
Interesting!  What happens if you comment out the NAMESERVER() statements before running `dnscontrol preview`?   If there are no NAMESERVER() statements it should do the right thing.

**Comment by joshbartley** [comment]
That does clear up the corrections and it lists 0 now. I need to try to drop one of the nameservers out of the Route53 console again to see if having the NAMESERVER() records in there was causing the issue or not.

**Comment by tlimoncelli** [comment]
The goal of "get-zones" is to create a decent first draft, not a perfect dnsconfig.js.  99% of the time one should comment out the NAMESERVER() statements.  Maybe we should just generate them commented out so that people can uncomment them if needed.
