### ISSUE TITLE
ClouDNS still listed as requested provider

### ISSUE THREAD

**Issue by marcolussetti** [StackExchange/dnscontrol#742]
Hi! Just noticed that ClouDNS is still showing up as a "requested provider" on https://stackexchange.github.io/dnscontrol/provider-list from PR #114 despite having been implemented in PR #578 

Took a look through https://github.com/StackExchange/dnscontrol/blob/master/docs/provider-list.md but only saw a reference to:
```
<ul id='requests'>

</ul>
```

Haven't managed to locate where that's configured yet. I might take a closer look tomorrow but figured I'd raise it as someone might figure that out far quicker than I :)

**Comment by marcolussetti** [comment]
I suspect in the end this might just need the label `provider-request` removed from #114 or something like that.

**Comment by tlimoncelli** [comment]
Fixed. Thanks for pointing that out.  I've also updated the docs to remind me to remove that label.
