### ISSUE TITLE
Support the DS record type

### ISSUE THREAD

**Issue by haraldkoch** [StackExchange/dnscontrol#75]
Issues I see up front:

1) not all DNS providers support all record types.

2) The object model (e.g. RecordConfig) doesn't have fields for the extra data; it only understands Priority (for MX and SRV records). I'm not convinced you can treat the entire record as opaque data; some DNS providers want text strings instead of protocol numbers for the 'algorithm' and 'digest type' fields of a DS record, for example.

**Comment by captncraig** [comment]
Yeah, we have an open issue #56 to support SRV records that is impacted by this too. Our general philosophy is that the RecordConfig should define a standard format for records, whatever that is, and it is up to the providers to adapt that to their own needs. We generally prefer to split fields into their own things, but if fields are not there, it likely means we don't support that record type **yet**. 

We will be adding top level fields for weight and port for SRV records, for example.

Your first point is a bit trickier. Generally we have been handling that by assuming all providers can handle all record types, and making it the responsibility of the provider implementation to print a warning or error if it must skip records it can't handle. 

This will all get more complicated as we move into more specialized custom things like ALIAS records, that have much less consistent adoption.

**Comment by captncraig** [comment]
And DNSSec is a whole other beast that is going to take some effort to work in. API support for DNS providers and registrars is all pretty spotty at best.

**Comment by haraldkoch** [comment]
@captncraig - I wouldn't want to tackle all of DNSSec in this tool, but DS records are a requirement for zone delegation. I have BIND automatic signing turned on for the rest of dnssec, but I still need to place DS records in my zone files, as well as configuring them into registars that support doing so.

Because of the RecordConfig fields, is it worth splitting this issue into separate issues for each record type?

**Comment by captncraig** [comment]
Yes, we should make a seperate issue for each record type we wish to support. DS records are probably a domain level thing for the registrar to deal with. Probably would add a list of `DSRecord` structs to the domain, and have the registrar add them. And DNS providers that support dnssec can fill it like we do with nameservers. I think only one of the registrars we currently support have any api for DS records at all though :(

**Comment by haraldkoch** [comment]
Ugh. DS records are complicated because they're a property of a zone, but they need to be added to the parent zone (just like NS records). Which means that to delegate from a zone that I control to another zone, I'd expect to write something like:

```
D("cfrq.net", registrar, DnsProvider(bind),
 ...
  DS("chk", 17314, 8, 1, "0B2D95FC3693F5C880CD2CDCF14BFBCF9FBD8274"),
  NS("chk", "ns1.cfrq.net"),
...
);
```

in order to publish the DS records for 'chk.cfrq.net' into the 'cfrq.net' zonefile.

But for domains hosted directly by a registrar, the DS record would need to be a property of the domain itself, like the "default_ns" property in the BIND registrar.

**Comment by captncraig** [comment]
ug indeed. For something like bind that is signed by you, yeah, you can add DS records, probably like you say. 

Most cloud providers though, it would be signed by them and they only give you a DS record to add, so there is some element of automatic detection needed as well.

We do a similar thing for nameservers, where we do an initial pass asking each dns provider what nameservers they want to use. We could do a similar thing for DS.

**Comment by captncraig** [comment]
What registrar do you use?

**Comment by captncraig** [comment]
Gandi is the only registrar we support that seems to have any adequate support for registering DS with the tld.

**Comment by haraldkoch** [comment]
@captncraig there are different answers depending on what you're looking for:

- I host my own domains; I'm attempting to use the "BIND" registrar in `dnscontrol` to build my zone files, but there's functionality missing.
- I have some zones hosted by Digital Ocean via their API and an ansible module. Digital Ocean does not support DS records (or SSHFP records).
- my domain registrar is Hover.com, but I don't use their domain hosting service. Hover does not have an API for domain management (there's a five-year old request for one, though), so that part is moot.

**Comment by pmoroney** [comment]
There is an IETF draft defining an API for 3rd party DNS services to create DS records, https://tools.ietf.org/html/draft-ietf-regext-dnsoperator-to-rrr-protocol-03
Unfortunately I do not know of any registrars that have implemented it publicly. The one I work for, name.com, hasn't yet.

**Comment by captncraig** [comment]
@pmoroney any word on if/when name.com will implement *any* kind of api for updating DS records? We'd certainly love to try it if possible, but it only seems to be available via the clicky interface.

**Comment by pmoroney** [comment]
I just created a ticket for that. I am not sure how long it will take to get to it, but hopefully we will have something before too long.

**Comment by tlimoncelli** [comment]
As part of adding support for SRV, we've added the support to help other record types be added:

* there is now a way to mark a provider as supporting/not supporting a record type.
* any "special case" code is handled better.

Since DS needs to be added to the parent domain, it reminds me of the difference between NS() and NAMESERVER().  NS() adds a record to the domain, that's it.  NAMESERVER(), on the other hand, is very smart and inserts the records in the parent domain (kind of... it really uses the provider's API to set "name servers" for the domain). 

We could have DS() and Dsomethingelse() where the latter uses the provider's API to update the parent domain.

Are there any providers that have special support for DS records?

**Comment by haraldkoch** [comment]
It appears that other than BIND, I don't have access to any providers with API support for DS records.
