### ISSUE TITLE
DNSSEC synchronization

### ISSUE THREAD

**Issue by jpbede** [StackExchange/dnscontrol#752]
I'm thinking about a kind of DNSSEC synchronization between DSP and registrar, like dnscontrol already do it with nameservers.

Is this something you would like to have ?

**Comment by tlimoncelli** [comment]
I'm interested but I don't know anything about DNSSEC (except that I read the RFC a zillion years ago when it was first proposed).  I'd be glad to assist, discuss design proposals, etc.!

**Comment by tlimoncelli** [comment]
This is stale. I'm closing this. Please re-open if needed. Thanks!
