### ISSUE TITLE
Add ARM support to Docker image

### ISSUE THREAD

**Issue by avdija** [StackExchange/dnscontrol#756]
stackexchange/dnscontrol docker image will not work on ARM architecture.

**Comment by tlimoncelli** [comment]
Confirmed.

Anyone with ARM access willing to make a PR?

**Comment by klausenbusk** [comment]
Inspiration: https://github.com/thelounge/thelounge-docker/pull/109

**Comment by iaean** [comment]
I also really appreciate, that you think about to provide your fabulous DNS stack to the ARM folks, too. Maybe you do not need access to ARM for [Multi-arch docker][0] builds. Just try to utilize your Github CI. Here is an [excellent paper][1]. For CI stuff it seems sometimes hard to provide PR correctly. But let me know, if there is the possibility for further help...

[0]: https://www.docker.com/blog/multi-arch-images/
[1]: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by cdhunt** [comment]
Artifacts targeting ARM should be published going forward. This includes Docker, RPM, Deb, and tar.gz archives. I would appreciate any testing you can do.

**Comment by tlimoncelli** [comment]
Closing this.  It's been done for a while.
