### ISSUE TITLE
go get currently fails to download dnscontrol

### ISSUE THREAD

**Issue by robotmay** [StackExchange/dnscontrol#757]
Haven't seen any other reference to this so far, but this is currently happening to me on both my CI and my local machine:

```
$ go get github.com/StackExchange/dnscontrol                                                                                   
# github.com/StackExchange/dnscontrol/vendor/github.com/mittwald/go-powerdns
../../../.go/src/github.com/StackExchange/dnscontrol/vendor/github.com/mittwald/go-powerdns/client.go:58:21: cannot use hc (type *"github.com/StackExchange/dnscontrol/vendor/github.com/mittwald/go-powerdns/pdnshttp".Client) as type *"github.com/mittwald/go-powerdns/pdnshttp".Client in argument to zones.New
```

This seems to imply a breaking change upstream but I haven't had a chance to look into it properly yet.

**Comment by tlimoncelli** [comment]
CC: @jpbede 

I'm seeing the same thing for fresh clones.  My existing repo is fine.

**Comment by jpbede** [comment]
I will have a look at this later on.

**Comment by jpbede** [comment]
It seams to me that you have already fixed that @tlimoncelli ?

**Comment by tlimoncelli** [comment]
Nope :-(.  While investigating I spotted a problem with .gitignore and I fixed that.  Sadly I still get the error above if I do `go get github.com/StackExchange/dnscontrol` if I unset GOPATH.

**Comment by tlimoncelli** [comment]
Umm... I'm not sure if I fixed it.

While investigating I spotted a problem with .gitignore and I fixed that. ("zones" was ignored, not "/zones", which lead to part of `github.com/mittwald/go-powerdns` not being vendored.

Does that fix the problem for everyone?

I still get the error if I unset GOPATH but that might be something funny in my environment.

**Comment by jpbede** [comment]
Hmm i can't reproduce it anymore after your `.gitignore and go mod tidy` fix

**Comment by tlimoncelli** [comment]
@robotmay Can you confirm?

**Comment by robotmay** [comment]
@tlimoncelli Still getting it on my local machine. Is there anything I'd need to do to clear a cache of some sort?

**Comment by tlimoncelli** [comment]
Hmm.... the ~/pkg directory is a cache.  You can remove it, but I don't think that's related to this problem.  

What's your GOPATH variable set to?

**Comment by robotmay** [comment]
`~/.go` on this machine. I'll try rerunning my CI tasks too and see what happens there.

-------- Original Message --------

**Comment by robotmay** [comment]
@tlimoncelli, @jpbede Looks to be solved on my CI :+1: Thanks for the quick fix! :smile:
