### ISSUE TITLE
PowerDNS docs

### ISSUE THREAD

**Issue by MAGICCC** [StackExchange/dnscontrol#759]
Hello,

Since PowerDNS got introduced in https://github.com/StackExchange/dnscontrol/pull/748 is it possible to add a doc for it?

Thanks in advance

**Comment by tlimoncelli** [comment]
Sadly the website updater isn't working right now.  You can access the file directly as:

https://github.com/StackExchange/dnscontrol/blob/master/docs/_providers/powerdns.md

(not as pretty, but might get you through until we can fix the website)

**Comment by MAGICCC** [comment]
Oh, well then, thanks!
