### ISSUE TITLE
Support PTR records

### ISSUE THREAD

**Issue by dattas** [StackExchange/dnscontrol#76]
Hello,

It'd be nice to be able to use this tool to also create reverse zones. Reverse zones use PTR records which are basically CNAME records. Can we set this up so that PTR records are like CNAME?

Examples are like:
```
2               IN      PTR     blah1.domain.com.
3               IN      PTR     blah2.domain.com.
4               IN      PTR     blah3.domain.com.
5               IN      PTR     blah4.domain.com.
6               IN      PTR     blah5.domain.com.
```

Currently it generates this error: `ReferenceError: 'PTR' is not defined`

Thanks!

**Comment by tlimoncelli** [comment]
We should probably add PTR() records asap.

**Comment by captncraig** [comment]
Would it make sense to have a mode where we automatically create PTR records for A records?

Option A: everything explicit:
```
D("example.com", myReg, ...,
  A("foo","1.2.3.4"),
  PTR("1.2.3.4.in-addr.arpa", "foo") //not sure if the in-addr.arpa part is necessary.
```

Option B: magic!
```
D("example.com", myReg, ...,
  A("foo","1.2.3.4"),
  AutoPTR, //generates PTRs as above. Essentially reverse of all A/AAAA in the domain.
  PTR("5.5.5.5", "foo.otherdomain.com.")
}
```

**Comment by captncraig** [comment]
Ok, talked to Tom, here's the plan:

1. PTR records will be supported in all domains: `PTR("23","foo.google.com.")`.
2. Add a `REV` function to transform a domain name:
   `D(REV("174.136.107.0/24")...)` is equivalent to `D("107.136.175.in-addr.arpa"...)`
3. Make sure all providers that support PTR can manage them. Once we get BIND passing the test, convertzone should work as intended too.

**Comment by f0** [comment]
@captncraig   any progress on this?

**Comment by tlimoncelli** [comment]
Most of this is done. We just haven't tested it with any providers.  Which provider are you using?  We can test that first.

**Comment by dattas** [comment]
I'm personally using plain zonefiles (bind)

**Comment by bhuntley-cu** [comment]
BIND, CloudDNS and Route53 here, thanks!

**Comment by f0** [comment]
plain bind zonefiles

**Comment by tlimoncelli** [comment]
@bhuntley-cu @f0 @dattas  I've got BIND working.  I'll push that after @captncraig does a code review. If you want to try what's in the branch and give feedback, I'd appreciate it.

@bhuntley-cu By "CloudDNS" do you mean Google CloudDNS?

**Comment by bhuntley-cu** [comment]
@tlimoncelli Yes, sorry. Google CloudDNS

**Comment by tlimoncelli** [comment]
Question for IPv6 users.

Right now you can do:

```
D(REV('2001:db8:302::/48'), REGISTRAR, DnsProvider(BIND),
  PTR("1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0", 'foo.example.com.'),  // 2001:db8:302::1
);
```

The REV() function generates the `.arpa` domain for you, which is pretty cool (I hope you agree). 
 However you have list list a long string for each PTR() name.  That's ugly. Right?

PTR could notice that something is an IP address and do the right thing (magic). Or, we could make a new function called AUTOPTR() (explicit):

```
  PTR("1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0", 'foo.example.com.'),  // manual
  PTR("2001:db8:302::1", 'foo.example.com.'),                          // magic
  AUTOPTR("2001:db8:302::1", 'foo.example.com.'),                      // explicit
```

Would people prefer magic or explicit?

(if you prefer explicit, should the name be AUTOPTR() or something else?)

**Comment by dattas** [comment]
I'd say if we can do magic by default but have either an option or a manual mode would be the way I'd prefer to see it

**Comment by tlimoncelli** [comment]
Ok, the magic was added to PTR() directly. I was able to prove to myself that there is no case where the same string could be interpreted as an IP address and a valid PTR name.  (Since we know the enclosing domain name, we know that ip6.arpa domains should match IPv6 addresses, etc.)

Read the PTR() docs at https://stackexchange.github.io/dnscontrol/js

**Comment by tlimoncelli** [comment]
AWS Route53 users: This now works for Route53.

Actually it always worked.  It turns out the AWS API is generic enough that it "just worked". Or... I'm supremely optimistic.

Please test this and report any problems.

I don't have a good Google CloudDNS test environment right now. Can someone test to see if it happens to work?

**Comment by whs** [comment]
It seems that [Classless in-addr.arpa delegation](https://tools.ietf.org/html/rfc2317) is not supported:

1. If I use `REV('172.20.18.128/27')` it will result in `2017/07/08 13:07:13 main.go:66: Error executing javasscript in (dnsconfig.js): Error: invalid CIDR address: 172.20.18.128/128` (it should returns `128/27.18.20.172.in-addr.arpa`)
2. If I manually add that domain and add magic PTR records (`PTR('172.20.18.137', 'home.whs.dn42.')`) then it returns `ERROR: ERROR: PTR record 172.20.18.137 in wrong IPv4 domain (128/27.18.20.172.in-addr.arpa)` (Yes, it did wrote double `ERROR: `)

**Comment by tlimoncelli** [comment]
Good point. I should have documented this.  I intentionally didn't implement anything related to classless delegations because I wanted to get the basics working first.

Does everyone use the same  format for their classless domains?  IIRC (and I could be wrong) the format ("128/27.18.20.172.in-addr.arpa") is a recommendation but people are free to do it differently.

**Comment by tlimoncelli** [comment]
RFC2317 is now better supported, but not perfect.  Give it a try.

**Comment by tlimoncelli** [comment]
Ok, the latest commit supports RFC2317 if you are using the format recommended in the RFC. It does some very strict validation. @whs please test again.

**Comment by tlimoncelli** [comment]
https://github.com/StackExchange/dnscontrol/pull/149

**Comment by whs** [comment]
Apparently / is the directory separator, and so bind tries to generate a zonefile named `zones/128/27.18.20.172.in-addr.arpa.zone` which will fail.

I think we might have to replace the / in the zone name with something else, maybe an underscore.

**Comment by whs** [comment]
For Google Cloud provider, PTR is not advertised as supported: https://github.com/StackExchange/dnscontrol/blob/autoptr/providers/google/google.go#L18

Other than that it seems to publish the records just fine.

**Comment by tlimoncelli** [comment]
@whs I just pushed commit that (a) changes BIND filenames with "/" to use spaces instead, (b) advertises PTR support for BIND, Route53, and GCP DNS. PTAL

**Comment by whs** [comment]
Works for me on BIND and GCP, thanks!

**Comment by tlimoncelli** [comment]
Declaring this fixed.

It is enabled for R53, GCLOUD and Route53.  Integration tests are in place. Other providers may support PTR records... please open separate issues to have those enabled.
