### ISSUE TITLE
Multiple providers

### ISSUE THREAD

**Issue by karlism** [StackExchange/dnscontrol#773]
Hello,

We need to configure single domain with multiple providers, is that possible with DNSControl?

I've tried suggestion mentioned in https://github.com/StackExchange/dnscontrol/issues/527 but DNSControl comlains about domain being declared more than two times when doing that:
```
$  dnscontrol preview
Executing javascript in dnsconfig.js: Error: example.com is declared more than once
```

**Comment by tlimoncelli** [comment]
Try:

```
D('example.com', REG, DnsProvider('R53'), DnsProvider('GCLOUD'),
   A('@', '1.2.3.4')
)
```

See https://stackexchange.github.io/dnscontrol/examples

**Comment by tlimoncelli** [comment]
I'm going to close this issue but please re-open it if you have any further questions.  (This is one of my favorite features and I'm glad to see someone using it!)

**Comment by karlism** [comment]
@tlimoncelli, thanks for the prompt reply! Your solution works like a charm.
