### ISSUE TITLE
NS1 is failing integration tests

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#779]
Here's what it looks like https://pastebin.com/dDZx50tn

FYI: I don't have a test account with NS1, so I need someone to step up and look into these. I'd be glad to assist remotely!

**Comment by MaxRatmeyer** [comment]
Hi,

I did a little more tinkering and I was able to fix all the issues with NS1 and it's now passing! I think it was just a problem with how the default record builder worked with MX records, so I added a special case in the NS1 provider file in the buildRecord function, similar to how the SRV record was built. 

Here is the test: https://pastebin.com/uT5tFqEw

I'll submit a PR in a bit!

**Comment by tlimoncelli** [comment]
Can we close this issue?

Tom

P.S.  Thank you for stepping up and fixing this issue.  I'm really impressed by your debugging skills!

**Comment by MaxRatmeyer** [comment]
Thank you! Yep, we're good to close it.
