### ISSUE TITLE
Allow import from providers

### ISSUE THREAD

**Issue by dattas** [StackExchange/dnscontrol#78]
It would be nice to be able to create a dnsconfig.js (or maybe a separate file) from the providers. This would allow people to jumpstart their configuration instead of having to manually convert zone files or configurations from their providers.

**Comment by tlimoncelli** [comment]
Most providers can export to a BIND-style DNS zone.  Those can be converted using the "convertzone" utility.

More info about the utility here:
https://github.com/StackExchange/dnscontrol/blob/master/misc/convertzone/README.md

We should probably mention this in the main README.

**Comment by dattas** [comment]
Yup, I missed that completely, there wasn't anything in the README or the documentation. I'd also recommend putting a quick 'how to' on how to get/create a binary for this utility as it isn't as explicit as the main dnscontrol utility.

**Comment by tlimoncelli** [comment]
Working on this in https://github.com/StackExchange/dnscontrol/pull/79

**Comment by captncraig** [comment]
I think it would be real cool to have the ability to do that for all providers. It should be possible with a little work. Currently, we don't return the records from the `GetDomainCorrections` function, but they pretty much all have a `GetRecords` function internally. We could put that on the DnsProvider interface if we wanted to.

**Comment by tlimoncelli** [comment]
The new get-zones command has a --format=dsl mode which does what is described in this issue.  What is being generated is 99% of what someone getting started would need, only small cleanups are required.

get-zones is supported by nearly half the providers (See https://github.com/StackExchange/dnscontrol/issues/628)

Thanks fur the suggestion, @dattas
