### ISSUE TITLE
Azure DNS Provider with >100 Zones

### ISSUE THREAD

**Issue by meowingtons** [StackExchange/dnscontrol#792]
I'm attempting to manage a large (>500 domains) Azure DNS environment with dnscontrol.

When I attempt to manage an Azure DNS zone that isn't in the first page of the Azure API response within an Azure Resource Group, dnscontrol doesn't think the domain exists, even if it already does.

I think this is likely the function that needs to be changed to use an iterator: https://github.com/StackExchange/dnscontrol/blob/42f7568074698956f70b0bef0feff6b7516fdb53/providers/azuredns/azureDnsProvider.go#L75 with a similar fix to https://github.com/StackExchange/dnscontrol/issues/770

**Comment by meowingtons** [comment]
I think I have a working fix for this. I've never written go before, so I'm trying to make sure I didn't do anything dumb and then I'll submit a PR.

**Comment by tlimoncelli** [comment]
Was this fixed in https://github.com/StackExchange/dnscontrol/pull/791 ?

**Comment by meowingtons** [comment]
It was not, the fix is very similar, but getExistingZones needed to be updated.

**Comment by tlimoncelli** [comment]
@run1et do you think you could work similar magic on this issue?

**Comment by run1et** [comment]
@tlimoncelli thank you for mentioning, I will be glad to try

**Comment by run1et** [comment]
"It was not, the fix is very similar, but getExistingZones needed to be updated." -> confirmed. Thinking how to modify ListZones and getZones.

**Comment by run1et** [comment]
I can't create a solution which follows DRY principle. `getExistingZones` returns `zonesIterator.Response` instead the iterator itself (BTW I've got an idea). Initial version:

```golang
func (a *azureDNSProvider) getZones() error {
    a.zones = make(map[string]*adns.Zone)

    ctx, cancel := context.WithTimeout(context.Background(), 6000*time.Second)
    defer cancel()
    zonesIterator, zonesErr := a.zonesClient.ListByResourceGroup(ctx, *a.resourceGroup, to.Int32Ptr(100))
    if zonesErr != nil {
        return zonesErr
    }

    for zonesIterator.NotDone() {
        zonesResult := zonesIterator.Response()
        for _, z := range *zonesResult.Value {
            zone := z
            domain := strings.TrimSuffix(*z.Name, ".")
            a.zones[domain] = &zone
        }
        zonesIterator.NextWithContext(ctx)
    }

    return nil
}

func (a *azureDNSProvider) ListZones() ([]string, error) {
    var zones []string

    ctx, cancel := context.WithTimeout(context.Background(), 6000*time.Second)
    defer cancel()
    zonesIterator, zonesErr := a.zonesClient.ListByResourceGroup(ctx, *a.resourceGroup, to.Int32Ptr(100))
    if zonesErr != nil {
        return nil, zonesErr
    }

    for zonesIterator.NotDone() {
        zonesResult := zonesIterator.Response()
        for _, z := range *zonesResult.Value {
            domain := strings.TrimSuffix(*z.Name, ".")
            zones = append(zones, domain)
        }
        zonesIterator.NextWithContext(ctx)
    }

    return zones, nil
}
```
It works on one zone, trying to test it fore the case then zones qty is >100.

**Comment by run1et** [comment]
Second variant (I don't like it — it changes `getExistingZones` parameters).

```golang
func (a *azureDNSProvider) getExistingZones(ctx context.Context) (*adns.ZoneListResultPage, error) {
    zonesIterator, zonesErr := a.zonesClient.ListByResourceGroup(ctx, *a.resourceGroup, to.Int32Ptr(100))
    if zonesErr != nil {
        return nil, zonesErr
    }
    return &zonesIterator, nil
}

func (a *azureDNSProvider) getZones() error {
    ctx, cancel := context.WithTimeout(context.Background(), 6000*time.Second)
    defer cancel()

    a.zones = make(map[string]*adns.Zone)

    zonesIterator, err := a.getExistingZones(ctx)

    if err != nil {
        return err
    }

    for zonesIterator.NotDone() {
        zonesResult := zonesIterator.Response()
        for _, z := range *zonesResult.Value {
            zone := z
            domain := strings.TrimSuffix(*z.Name, ".")
            a.zones[domain] = &zone
        }
        zonesIterator.NextWithContext(ctx)
    }

    return nil
}

func (a *azureDNSProvider) ListZones() ([]string, error) {
    var zones []string

    ctx, cancel := context.WithTimeout(context.Background(), 6000*time.Second)
    defer cancel()

    zonesIterator, err := a.getExistingZones(ctx)

    if err != nil {
        return nil, err
    }

    for zonesIterator.NotDone() {
        zonesResult := zonesIterator.Response()
        for _, z := range *zonesResult.Value {
            domain := strings.TrimSuffix(*z.Name, ".")
            zones = append(zones, domain)
        }
        zonesIterator.NextWithContext(ctx)
    }

    return zones, nil
}
```

**Comment by tlimoncelli** [comment]
A little bit of repetition is better than a lot of complexity.

**Comment by run1et** [comment]
I will check it in few days and create a PR.

**Comment by run1et** [comment]
Here is a fix: https://github.com/StackExchange/dnscontrol/pull/816

I've tested this fix on my Azure subscription by creating 200 zones. Initial bug-report confirmed.

**Comment by meowingtons** [comment]
I apologize I totally forgot about this. Thanks @run1et. Your fix is better than what I had.

**Comment by run1et** [comment]
Thank you, @meowingtons!
