### ISSUE TITLE
SPF Record Causing Panics Again

### ISSUE THREAD

**Issue by epyonavenger** [StackExchange/dnscontrol#796]
Similar to #446 and #339, seeing issues with SPF records in r53 and gcloud since upgrading to 3.2.0.

Can provide output if it's helpful, but it seems to match what was in those for the most part.

**Comment by patschi** [comment]
There was apparently commit ea328263c746747b205569d0a0ffadbc19447afd after the 3.2.0 release, changing something related to SPF records specific to R53. You could build a custom dnscontrol build based on this commit and re-try?

**Comment by tlimoncelli** [comment]
FYI: The goal of https://github.com/StackExchange/dnscontrol/commit/ea328263c746747b205569d0a0ffadbc19447afd was to translate SPF records to be TXT records (SPF records are deprecated).

**Comment by tlimoncelli** [comment]
I've released v3.3.0.  Can you test again with that release and reply with the result.

**Comment by epyonavenger** [comment]
Will do, just need to set up a test record since we converted the others to TXT to get around the problem.

**Comment by tlimoncelli** [comment]
Does it work now?
