### ISSUE TITLE
BIND provider: Using DefaultTTL() adds a TTL to each record instead of changing $TTL

### ISSUE THREAD

**Issue by dattas** [StackExchange/dnscontrol#80]
Using the BIND provider, if we set `DEFAULTS( DefaultTTL(60000) );` or adding `DefaultTTL(60000),` to the D( I would expect the $TTL to change in the resulting .zone file, instead a TTL is added to each record. This seems like incorrect behavior. $TTL is always 300 (which I believe is being pulled from https://github.com/StackExchange/dnscontrol/blob/master/models/dns.go#L18 )

**Comment by captncraig** [comment]
Hmm. You are correct obviously. DefaultTTL is a javascript only construct at the moment, so it would not be availible when generating zone files.

Three options I see:

1. Pass defaultTTL in json to go backend to reference (put it on DNSConfig struct)
2. Have provider level metadata for bind to specify default ttl for zone files.
3. Infer the most common ttl (the mode) from the records we have. Automatically optimize it to reduce size.

@tlimoncelli ?

**Comment by tlimoncelli** [comment]
All three options seem fine.  1 is the cleanest.  3 would be awesome... just make sure that in the event of a tie, always pick the same item (i suggest the highest TTL value always wins the tie).
