### ISSUE TITLE
Verbose Flag not working?

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#803]
Am I doing something wrong or is the `-v` verbose flag not working as expected?

I'm trying it this way:
```
$ dnscontrol -v preview --domains domain.tld
******************** Domain: domain.tld
----- Getting nameservers from: provider
----- DNS Provider: provider...3 corrections
#1: DELETE TXT domain.tld "BLA" ttl=43200
#2: CREATE MX domain.tld 20 mail.domain.tld. ttl=3600
#3: REFRESH zone domain.tld
----- Registrar: provider...0 corrections
Done. 3 corrections.
```

In this test I must have run through plenty of `Debugf()` with some kind of output, specially because this was a test with `NO_PURGE` which runs through a bunch of debug messages.

The flag should be correct as stated in:
https://github.com/StackExchange/dnscontrol/blob/24b7d0641e0a5c6fbcfc9287f22b4e49975ec021/commands/commands.go#L50-L53

**Comment by tlimoncelli** [comment]
Most of the code doesn't do much with the `-v` flag.  The person that added printer.Debugf() is no longer on the project.   The conversion was never complete. He had some really good ideas (for example, we could do all the domains in concurrently and use printer to coordinate the output so there are no overlaps)
