### ISSUE TITLE
CF_REDIRECT always in "preview" output, nothing actually changed

### ISSUE THREAD

**Issue by svenluijten** [StackExchange/dnscontrol#809]
Say I have the following config:

```js
var REG_NONE = NewRegistrar('none', 'NONE');
var DNS_CLOUDFLARE = NewDnsProvider('cloudflare', 'CLOUDFLAREAPI', {'manage_redirects': true});

D('example.net', REG_NONE, DnsProvider(DNS_CLOUDFLARE),
    CF_PROXY_DEFAULT_ON,
    DefaultTTL('1m'),
    A('@', '1.2.3.4'),
    CNAME('www', '@'),
    CF_REDIRECT('*example.net/*', 'https://example.com', TTL('1m'))
);
```

The output of `dnscontrol preview` will _always_ contain the `example.net` page rule:

```
******************** Domain: example.net
----- Getting nameservers from: cloudflare
----- DNS Provider: cloudflare...1 correction
#1: MODIFY PAGE_RULE example.net: (*example.net/*,https://example.com,1,301 ttl=1) -> (*example.net/*,https://example.com,1,301 ttl=120)
----- Registrar: none...0 corrections
Done. 1 correction.
```

It looks like the `TTL()` and/or `DefaultTTL()` modifiers aren't applied to `CF_REDIRECT` rules, likely because the restrictions in the Cloudflare API?

**Comment by svenluijten** [comment]
Upon closer inspection, this looks like it's due to [the `TTL` being "defaulted" to `1` when _retrieving_ the page rules](https://github.com/StackExchange/dnscontrol/blob/a9f2ab84c8e0db722dec40894059c181dc7ee221/providers/cloudflare/rest.go#L429), but it's trying to set it to `120` because of [this `if`](https://github.com/StackExchange/dnscontrol/blob/a9f2ab84c8e0db722dec40894059c181dc7ee221/providers/cloudflare/cloudflareProvider.go#L346-L348), making the `preview` command _think_ it changed, when it really hasn't.

I'm not super adept at Go, but I'd be comfortable setting up an environment to send in a PR if you guys could give me some pointers if I'm on the right track here, and how I could test my hypothesis 🙂

**Comment by cipriancraciun** [comment]
@svenluijten The `CF_REDIRECT` (and `CF_TEMP_REDIRECT`) are not actual DNS records, but are modeled as such for `dnscontrol`;  therefore there is no TTL for them.

I would assume that `dnscontrol` should always reset the TTL to `1` (or any other constant value), regardless of what the user sets in `DefaultTTL(...)`, `TTL(...)`, or other ways to set defaults at higher levels.

**Comment by svenluijten** [comment]
Agreed, and dnscontrol seems to do just that for now: it just ignores whatever value is given with `TTL()` or `DefaultTTL()`, and instead always defaults to `1` when _retrieving_ the page rules for comparison in `dnscontrol preview` ("old value", or the left side of the `->` in the `preview` output), but defaults to `120` for _setting_ the value ("new value", or the right side of the `->` in the `preview` output).

I reckon it'd just be a case of changing [this line](https://github.com/StackExchange/dnscontrol/blob/a9f2ab84c8e0db722dec40894059c181dc7ee221/providers/cloudflare/cloudflareProvider.go#L347) to `1` instead of `120`, but I don't know what else that change would affect.

**Comment by cipriancraciun** [comment]
The lines you've mentioned, https://github.com/StackExchange/dnscontrol/blob/a9f2ab84c8e0db722dec40894059c181dc7ee221/providers/cloudflare/cloudflareProvider.go#L343-L348, will affect all records.

Thus, I think perhaps after the line https://github.com/StackExchange/dnscontrol/blob/a9f2ab84c8e0db722dec40894059c181dc7ee221/providers/cloudflare/cloudflareProvider.go#L369 of the same file could be added:

~~~~
if rec.Type == "CF_REDIRECT" || rec.Type == "CF_TEMP_REDIRECT" {
    rec.TTL = 1
~~~~

**Comment by tlimoncelli** [comment]
@svenluijten Would you be interested in submitting a PR?
