### ISSUE TITLE
Using "smart" variables

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#811]
It's quite difficult to describe in just a few words, in the subject, what I'm trying to achieve. So I'm going ahead with some further explanation and some kinda-pseudo code here.

Basically I'm trying to use variables or simple definitions to provide specific functionality to domains - let's take email for example. By simply using a flag/variable `MAIL_SUPPORT` (without anything to add, like parameters) I'd like to prepare the domain for email and adding enabled domains to a global variable to process it at a later point (e.g. looping over variable for DMARC report subdomains).

Let's take following example:
```javascript
var MAIL_ENABLED = [];

D('domain.tld', REGISTRAR, DnsProvider(AWESOME_DNS_PROVIDER),
	MAGIC_VARIABLE_OF_RECORDS,
	MAIL_SUPPORT1,
	MAIL_SUPPORT2,
	MAIL_SUPPORT3,
	MAIL_SUPPORT4("domain.tld"),
	MAIL_SUPPORT5
)
```

Here I've tried four different ways somehow achieving my goal. While the last one works, I don't have the `domain` JS object and I'd like to prevent manually adding the domain as a parameter.

So my tests were:
**Test 1**
```javascript
function MAIL_SUPPORT1(domain) {
	console.log("Enabled mail for " + domain.name);
	MAIL_ENABLED.push("test1:" + domain.name);
	return [
		TXT('test1', domain.name + ' is awesome'),
		MX('@', 20, 'mail.domain.tld.', TTL('1h'))
	]
}
```
Result: Variable domain accessible, push works, no records applied.

**Test 2**
```javascript
var MAIL_SUPPORT2 = (function(domain) {
	console.log("Enabled mail for " + domain.name);
	MAIL_ENABLED.push("test2:" + domain.name);
	return [
		TXT('test2', domain.name + ' is awesome'),
		MX('@', 20, 'mail.domain.tld.', TTL('1h'))
	]
})
```
Result: Variable domain accessible, push works, however no records applied.

**Test 3**
```javascript
var MAIL_SUPPORT3 = (function(domain) {
	console.log("Enabled mail for " + domain.name);
	MAIL_ENABLED.push("test3:" + domain.name);
	return [
		TXT('test3', domain.name + ' is awesome'),
		MX('@', 20, 'mail.domain.tld.', TTL('1h'))
	]
})()
```
Result: Variable domain NOT accessible, and therefore JS fails. However records applied, if domain var removed.

**Test 4**
```javascript
function MAIL_SUPPORT4(domain_name) {
	console.log("Enabled mail for " + domain.name);
	MAIL_ENABLED.push("test4:" + domain_name);
	return [
		TXT('test4', domain_name + ' is awesome'),
		MX('@', 20, 'mail.domain.tld.', TTL('1h'))
	]
}
```
Result: Variable domain NOT accessible/existent and manual parameter required. However records applied.

**Test 5**
```javascript
// variable domain accessible, push works, however no records applied as D() not yet populated.
var MAIL_SUPPORT5 = (function(domain) {
	console.log("Enabled mail for " + domain.name);
	MAIL_ENABLED.push("test5:" + domain.name);
	D_EXTEND("domain.tld",
		TXT('test5', domain.name + ' is awesome'),
		MX('@', 20, 'mail.domain.tld.', TTL('1h'))
	);
})
```
Result: This doesn't work at all. Because at the time when `D_EXTEND()` is being called, the `D()` function hasn't yet added the domain to the global `domains` variable of helper.js and therefore is seen as "not defined" in this stage. Furthermore, I believe this is rather a hacky workaround (race condition possible?).

Someone has some clever ideas?

@tlimoncelli Maybe you have a good idea how to handle this scenario, as I might indeed tend to over-complicate this - as we've discussed in my PR recently. You're also allowed to tell me `Shut up and just use "MAIL_SUPPORT4"-variant` :D

**Comment by mikenz** [comment]
A variant on option 4

```
var MAIL_ENABLED = [];

D(domain = 'domain.tld', REGISTRAR, DnsProvider(AWESOME_DNS_PROVIDER),
	MAGIC_VARIABLE_OF_RECORDS,
	MAIL_SUPPORT4(domain)
)

D(domain = 'example.com', REGISTRAR, DnsProvider(AWESOME_DNS_PROVIDER),
	MAGIC_VARIABLE_OF_RECORDS,
	MAIL_SUPPORT4(domain)
)


function MAIL_SUPPORT4(domain_name) {
	console.log("Enabled mail for " + domain_name);
	MAIL_ENABLED.push("test4:" + domain_name);
	return [
		TXT('test4', domain_name + ' is awesome'),
		MX('@', 20, 'mail.domain.tld.', TTL('1h'))
	]
}
```

**Comment by tlimoncelli** [comment]
I'm no Javascript expert.  I do, however, think @mikenz has the right idea because by defining MAIL_ENABLED as a global, functions can append to it later. (At least that's how Python works :-) ).

**Comment by tlimoncelli** [comment]
I'd like to also warn against getting too complex with the Javascript.  A little repetition is better than a lot of complexity. Complexity is like a mortgage that you pay more for every year.

For example, at Stackoverflow we have a number of email related macros that clearly explain to the next person their purpose.  No functions required, just MAGIC_VARIABLE_OF_RECORDS (I like that term) called SPF_NONE, SPF_TYPICAL, SPF_foo where "foo" is special cases that are well-documented.

**Comment by patschi** [comment]
> ...just MAGIC_VARIABLE_OF_RECORDS (I like that term)

Yeah, that's what I'm using now too. But for DMARC reports you need to allow `domainB.tld` to send reports under `domainA.tld` by having `domainB._report.dkim.domainA.tld` (don't remember exact record naming). I don't want to use `*.report...` wildcard, I really like to allow each domain individually.

I have a few domains which are NOT mail-enabled. That's why I'd like to track the domain names which are mail-enabled to only create necessary records that way. So not really complex usecase, I believe.

**Comment by patschi** [comment]
> A variant on option 4

Thanks a lot @mikenz! Works like a charm!

If anyone is interested:
**Domain definition**
```javascript
D(name = 'domain.tld', REG, DnsProvider(DNS),
	MAIL_ENABLED(name),
	...
);
```

**MAIL_ENABLED() function**
```javascript
var MAIL_ENABLED_DOMAINS = [];
function MAIL_ENABLED(name) {
	MAIL_ENABLED_DOMAINS.push(name);
	return [
		MX('@', 20, ADDR_MX1_HOST + '.', TTL('1h')),
		...
	];
}
```

**DMARC magic**
```javascript
console.log("Updating DMARC report subdomains...");
for (i = 0; i < MAIL_ENABLED_DOMAINS.length; i++) {
	var name = MAIL_ENABLED_DOMAINS[i];
	D_EXTEND('dmarc_domain.tld',
		TXT(name + '._report._dmarc', 'v=DMARC1')
	);
}
```
