### ISSUE TITLE
Notifications ignores failure

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#813]
Notifications sometimes fail, especially when getting set up. This makes it difficult to debug new configurations, or notice that an existing configuration has stopped working.

pkg/notifications should be refactored to propagate errors and log them as warnings.

**Comment by rkapoor028** [comment]
Hi @tlimoncelli I reckon notifications to MSteams are failing for us. I have the latest windows package from v3.3.0 https://github.com/StackExchange/dnscontrol/releases/tag/v3.3.0

Do not see any errors when doing .\dnscontrol.exe -v push -notify

I reckon this feature was released today so might be early to start using but wanted to point it out. 

The teams Incoming Webhook works as I can send messages using the same.

**Comment by tlimoncelli** [comment]
Can you try building from master?  There was a bug fix that arrived shortly
after the release. --
Sent from Gmail Mobile
