### ISSUE TITLE
How integrating AUTODNSSEC should work out?

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#814]
I'm just wondering how the implementation of `AUTODNSSEC` should work out for existing providers. I've just implemented it for the OVH provider, however stumbling about sort-of-breaking-change.

So when specifying `AUTODNSSEC` in a `D()` function, everything works as expected: It's retrieving the current state of DNSSEC, making the correction as expected and pushes the changes.

But how should this work out for existing definitions out there? If the change is being merged, everyone not adding `AUTODNSSEC` to their domain definition will get DNSSEC disabled straight away and most likely breaking things. When making `AUTODNSSEC` per default, it might enable DNSSEC for domains where it's not expected to be enabled.

**Comment by tlimoncelli** [comment]
I'm not sure I understand the issue but if I read you correctly...

You are right in that currently legacy domains will have autodnssec disabled if people don't change their dnsconfig.js

A better way would be if AUTODNSSEC has 3 settings: on, off, don't change.   The default is "don't change".

**Comment by tlimoncelli** [comment]
CC: @philpennock

**Comment by philpennock** [comment]
My experience with the provider I added this to was that anyone already using DNSSEC couldn't use DNSControl, because DNSControl complained bitterly about all the extra records which weren't handled, and failed out.  So the logic was "impossible to have been there before, so we can have a simple boolean".

If we now have providers which managed to be DNSSEC-blind, then yes this needs to become a ternary with a default of "don't change".

Was the OVH integration actually DNSSEC-blind before?

**Comment by patschi** [comment]
> Was the OVH integration actually DNSSEC-blind before?

I assume you mean that dnscontrol isn't aware if dnssec is enabled or disabled when being run against OVH? If so, then yes. OVH manages DNSSEC completely in the background - no DNSSEC-related records visible for dnsscontrol.

**Comment by philpennock** [comment]
Ah, there's the difference.  I wrote the provider against "stop breaking in the presence of DNSSEC", not against "blissful ignorance".  I think that OVH is probably doing the right thing here, I wish more providers were like that.

Okay, I think `AUTODNSSEC` needs to be, as @tlimoncelli suggests, a ternary, `{ ignore, off, on }` and the default should be `ignore`.

**Comment by tlimoncelli** [comment]
Looks like we have consensus: we need an "on/off/ignore" mechanism in AUTODNSSEC.

I've opened https://github.com/StackExchange/dnscontrol/issues/847 to record that. I'm closing this issue.

Thanks for all the input!
