### ISSUE TITLE
Provider request: Constellix (DNSMadeEasy)

### ISSUE THREAD

**Issue by SesquipedalianDefenestrator** [StackExchange/dnscontrol#842]
Started taking a whack at this myself with some progress, stalled by carpal tunnel issues so I figured I'd write it up in an Issue to see if someone else wanted to resume (or just get input for when I can do it).

There's a Go library for talking to the API: https://github.com/Backblaze/gostellix

Biggest difficulty is probably handling entries with multiple A records, since that doesn't map super well to Constellix's structure, but maybe it's OK to just punt and not support that for an initial version?

**Comment by tlimoncelli** [comment]
It's worth a try!

**Comment by tlimoncelli** [comment]
I've tagged this issue as a provider-request.  It will (soon) be listed as a "requested provider" on the provider list web page:
https://stackexchange.github.io/dnscontrol/provider-list

If you need assistance, please speak up in this issue and someone will get back to you ASAP.

**Comment by tlimoncelli** [comment]
Thank you for requesting this provider!

I've tagged this issue as a provider-request.  It will (soon) be listed as a    "requested provider" on the provider list web page:
https://docs.dnscontrol.org/service-providers/providers

I will now close the issue.  I know that's a bit confusing, but it will remain  on the "requested provider" list.

If someone would like to volunteer to implement this, please re-open this issue and add the tag `has-pr`.

We encourage you to try adding this provider yourself.  We've tried to make the process as friendly as possible.  Many people have reported that adding a       provider was their first experience writing Go.  The process is documented here:
https://docs.dnscontrol.org/developer-info/writing-providers
If you need assistance, please speak up in this issue and someone will get back to you ASAP.
