### ISSUE TITLE
AUTODNSSEC should have an "ignore" option, which should be the default

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#847]
Rather than on/off, AUTODNSSEC should have 3 settings: on, off, don't change. The default would be "don't change".

See discussion in https://github.com/StackExchange/dnscontrol/issues/814

**Comment by patschi** [comment]
Just for clarifications and bring in my ideas:
**Existing AUTODNSSEC**
- `AUTODNSSEC` should be deprecated, as it's not suitable for many situations and changing the behavior could result in a disaster for existing providers.
- `AUTODNSSEC` should default to `AUTODNSSEC_ON`, as this is basically currently what it does - for backwards-compatibility reasons.

**New AUTODNSSEC**
- Introducing two options might be easier: `AUTODNSSEC_ON` and `AUTODNSSEC_OFF`, which are exactly doing that: Forcing DNSSEC being on/off at supported providers.
- When none of both mentions options are provided, the logic shouldn't be triggered and basically result in "don't change". (This way NO specific `AUTODNSSEC_IGNORE` or whatsoever is required)
