### ISSUE TITLE
TTL issue with Cloudflare

### ISSUE THREAD

**Issue by gallivantor** [StackExchange/dnscontrol#851]
I'm using dnscontrol 3.2.0. I am trying to set things up so I can use dnscontrol to manage my DNS -- I have not yet deployed using it.

So I used the get-zones command to generate a script from my Cloudflare account. My MX records have a TTL of 300 in Cloudflare, and it correctly generated this:

`MX('@', 10, 'xxxxx.com.', TTL(300)),`

However, when I run "dnscontrol preview", it says this:

`#1: MODIFY MX mysite.com: (10 xxxxx.com. ttl=300) -> (10 xxxxx.com. ttl=1)`

Why is it trying to change the TTL to 1 when it is correctly specified as 300 in the script?

**Comment by tlimoncelli** [comment]
Did the behavior change for you vs. pre-3.2.0 releases?

Cloudflare interprets a ttl of 1 to mean "use the default TTL".  The cloudflare default is 300 (as far as I can tell, there is no way to change the default. Therefore 1 == 300.  The provider has a bit of logic to try to do the right thing.

There was recently a change to that logic., but only for redirects. See  ca136992f85d09079f68093267c7f36625fe2ae5

**Comment by tlimoncelli** [comment]
Oh wait.  I think I see the problem.  get-zones doesn't know that you'll be using this with Cloudflare in the future, so it sets the TTL to 300 (I guess 300 isn't the default for the zone?).  Then the provider sees 300 and changes it to "auto-ttl", because it is trying to be smart.

If you let dnscontrol set the TTL to 1, what does the next run of dnscontrol do?

**Comment by gallivantor** [comment]
Ahh thanks, that explains it. My MX entries are explicitly set to TTL 300 in Cloudflare, but because 300 is the default, dnscontrol is trying to set them to "Auto" instead of "300" explicitly.

So running dnscontrol to deploy the changes is technically making a change compared to how they were configured before, but the functionality should be the same.
