### ISSUE TITLE
replace ips based on provider? 

### ISSUE THREAD

**Issue by rbelnap** [StackExchange/dnscontrol#853]
This is not so much of an issue, but more of a support request... Although if there is no way to do it, maybe it could become a feature.  

I have a situation where I want to push public ip addresses to one provider (let's say namecheap) and I want to push a filtered set of ips to another provider (bind) that is used internally.  The idea would be to somewhat implement split horizon dns - just split provider.  

The logic is simple: if pushing to 'bind' provider, map public -> private ip (given a mapping of all public <-> private ips)  

This could be implemented after the zone files are generated, outside of dnscontrol, but then dnscontrol would detect changes every time.  This after generation filtering also wouldn't work for other providers.  Is there an elegant way to achieve this scheme?

**Comment by tlimoncelli** [comment]
That's quite an interesting use-case!  It could be implemented in the code (would require a LOT of testing).  There's an easier way to do it:

You could use some javascript to define the domain one way or the other based on a variable.  Then you can run dnscontrol twice, once with the variable set each way.  You can even use the `--domains` or `--providers` to restrict which domains or providers are included.

How do you set the variable?

    echo 'var DESTINATION = "second";' >picker.js
    cat picker.js dnsconfig.js >generated.js
    dnscontrol --config generated.js

**Comment by tlimoncelli** [comment]
Were you able to find a solution?

**Comment by rbelnap** [comment]
Yes, thanks Tom!  This was the idea I was looking for... it actually works quite nicely, particularly with appropriate `--providers` arguments, and the `_exclude_from_defaults` in creds.json.  Thanks again!
