### ISSUE TITLE
Provider request: Joker.com

### ISSUE THREAD

**Issue by netravnen** [StackExchange/dnscontrol#854]
Links to API docs:

- https://go-acme.github.io/lego/dns/joker/
- https://joker.com/faq/category/39/22-dmapi.html
- https://dmapi.joker.com/
    - https://dmapi.joker.com/docs/
        - https://dmapi.joker.com/docs/DMAPI-ext.txt
        - https://dmapi.joker.com/docs/dmapi-1.2.txt

**Comment by tlimoncelli** [comment]
Thank you for requesting this provider!

I've tagged this issue as a provider-request.  It will (soon) be listed as a    "requested provider" on the provider list web page:
https://docs.dnscontrol.org/service-providers/providers

I will now close the issue.  I know that's a bit confusing, but it will remain  on the "requested provider" list.

If someone would like to volunteer to implement this, please re-open this issue and add the tag `has-pr`.

We encourage you to try adding this provider yourself.  We've tried to make the process as friendly as possible.  Many people have reported that adding a       provider was their first experience writing Go.  The process is documented here:
https://docs.dnscontrol.org/developer-info/writing-providers
If you need assistance, please speak up in this issue and someone will get back to you ASAP.
