### ISSUE TITLE
extend D_EXTEND to handle subdomains

### ISSUE THREAD

**Issue by ad8-bdl** [StackExchange/dnscontrol#858]
I'm finding it beneficial to split out my DNS config to separate files, per sub-domain, using the `require` and `require_glob` functions. These subdomains are not delegated, so I'm using the `D_EXTEND` function to extend the main domain. I then have to manually include the subdomain in every single record, hopefully without typos or other errors.

It would be neat if there were a `D_SUBDOMAIN` function that was the same as `D_EXTEND` but accepted a single additional required argument of a path to be inserted between the RRs and domain name. e.g. something like

    D('example.com', REG_NONE,  DnsProvider(DNS_CLOUDFLARE), ...)

    D_EXTEND('example.com',
      A('x.subdomain', '10.1.1.1')
      A('y.subdomian', '10.1.1.2')
    );

    D_SUBDOMAIN('example.com', 'subdomain',
      A('x', '10.1.1.1')
      A('y', '10.1.1.2')
    );

**Comment by tlimoncelli** [comment]
That's an interesting use-case!

Let me suggest an alternative syntax:

```
D('example.com', REG_NONE,  DnsProvider(DNS_CLOUDFLARE), 
    SUBDOMAIN('subdomain', [
        A('x', '10.1.1.1')
        A('y', '10.1.1.2')
    ])
);
```

That would work on both `D()` and `D_EXTEND()`.

The `SUBDOMAIN()` function could be written in Javascript and included in the dnsconfig.js file.  It would require a bit more Javascript know-how than I have.

**Comment by tlimoncelli** [comment]
Question: Given the domain `.foo.tld` and subdomain `.bar`, what would `CNAME("a", "b")` be the equivalent of:

```
      CNAME("a.bar", "b.bar.foo.tld")
```

or

```
      CNAME("a.bar", "b.foo.tld")
```

**Comment by ad8-bdl** [comment]
Implementing this as a 'Domain Modifier' within a `D` or `D_EXTEND` would work for me. I had a go at implementing this as JS but realised my JS skills are very atrophied, moreover and I decided that this approach was contrary to KISS / YSMFN (https://stackexchange.github.io/dnscontrol/code-tricks). Maybe there's a simpler approach than the hack I was creating.

As to the `CNAME`: I'd expect it to be consistent with existing behaviour: a fully qualified target (ends in `.`) is as-is, anything else is tacked on to "the domain" as it is at the time the CNAME is called. i.e. including the subdomain.

    // goal: CNAME a.bar.foo.tld > b.bar.foo.tld
    D_EXTEND('foo.tld'
        SUBDOMAIN('bar', [
            CNAME("a", "b")
        ])
    );

to be equivalent to:

    D_EXTEND('foo.tld'
        CNAME("a.bar", "b.bar.foo.tld.")
    );

**Comment by tlimoncelli** [comment]
I, too, am concerned about the KISS / YSMFN issues.  That's why I would prefer a JS solution.  Initially it can be a function that people graft into their config. If there is a groundswell of support, we can add it to helpers.js and everyone can benefit. If it turns out to be not good, we haven't added it to the main project.

**Comment by tlimoncelli** [comment]
May I close this issue?

**Comment by ad8-bdl** [comment]
Yep; I'll have a go at a JS helper and if I get anything remotely presentable I'll send a PR.

**Comment by ad8-bdl** [comment]
After poking around helpers.js, it seems the simplest / most elegant approach was to modify D_EXTEND to accept subdomain names; e.g.

    D('foo.tld', REG_NONE,  DnsProvider(DNS_CLOUDFLARE), ...)

    // goal: CNAME a.bar.foo.tld > b.bar.foo.tld
    D_EXTEND('bar.foo.tld'
        CNAME("a", "b")
    );

to be equivalent to:

    D_EXTEND('foo.tld'
        CNAME("a.bar", "b.bar.foo.tld.")
    );

The only niggle I can see to this approach is with CF_REDIRECT, where the name is actually ignored and the page rule "installed" on the apex domain; as such calling CF_REDIRECT from within a D_EXTEND will cause it to be considered 'new' each time. I presume this could/should be fixed in the Cloudflare differ?

**Comment by tlimoncelli** [comment]
Wow!  That is quite elegant!

I like that it automatically finds the domain to extend.  (i.e. extending foo.bar.tld finds bar.tld automatically. The user doesn't have to specify the subdomain).

CF_REDIRECT: Yeah, I'm not sure what to do there.  Maybe disallow them if .subnet is in use?  I can take a look this weekend.

There are some edge-cases I thought of:

    D('foo.tld', ...)
    D('bar.foo.tld', ...)
    D_EXTEND('bar.foo.tld', ...) // Should extend bar.foo.tld; not use "subdomain" mode

    D('foo.tld', ...)
    D_EXTEND('bar.foo.tld', ...) 
    D('bar.foo.tld', ...)    // ERROR!

**Comment by ad8-bdl** [comment]
I believe the PR in #870 does the job for this; I've converted my production config (~240 names across 13 subdomains on Cloudflare, pretty much all plain vanilla A and CNAME records with a couple of CF redirect page rules) to use this new feature and a preview tells me `Done. 0 corrections.`.

I discovered two violations of our naming scheme whilst doing the conversion, so I'm certain this is a worthwhile feature in terms of minimising opportunity to screw up.

**Comment by tlimoncelli** [comment]
Thank you for suggesting this feature and contributing the code to implement it!

> I discovered two violations of our naming scheme whilst doing the conversion, so I'm certain this is a worthwhile feature in terms of minimising opportunity to screw up.

Isn't that wonderful?  I love when Infra-as-Code finds issues like that!

**Comment by tlimoncelli** [comment]
Fixed by https://github.com/StackExchange/dnscontrol/pull/870
