### ISSUE TITLE
inwx - .ro domains preview/push unparsable record

### ISSUE THREAD

**Issue by wararjey** [StackExchange/dnscontrol#860]
Today I started using dnscontrol to set up domains at inwx
I got .de, .eu and .ro domains currently.

The .eu and .de domains work fine.
However, for the .ro domains fail after initial setup when doing a preview or push, I get an unparsable record errror.
Only workaround is to comment out the .ro domain stuff from dnsconfig.js so that dnscontrol can do the other domains:

----- Getting nameservers from: inwx
----- DNS Provider: inwx...panic: INWX: unparsable record received: unknown rtype () when parsing () domain=(redacted)

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/providers/inwx.(*inwxAPI).GetZoneRecords(0xc000120490, 0xc000a75c50, 0xc, 0x0, 0x0, 0x0, 0xc0008458f0, 0x7a9e68)
        src/github.com/StackExchange/dnscontrol/providers/inwx/inwxProvider.go:302 +0x6a8
github.com/StackExchange/dnscontrol/v3/providers/inwx.(*inwxAPI).GetDomainCorrections(0xc000120490, 0xc00018a0c0, 0x4, 0xc00018a000, 0x1, 0x0, 0x0)
        src/github.com/StackExchange/dnscontrol/providers/inwx/inwxProvider.go:212 +0x6f
github.com/StackExchange/dnscontrol/v3/commands.run(0x13af234, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13acbf1, 0xa, 0x0, ...)
        src/github.com/StackExchange/dnscontrol/commands/previewPush.go:135 +0x3da
github.com/StackExchange/dnscontrol/v3/commands.Preview(...)
        src/github.com/StackExchange/dnscontrol/commands/previewPush.go:87
github.com/StackExchange/dnscontrol/v3/commands.glob..func6.1(0xc00040f0c0, 0xb, 0xc)
        src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x9a
github.com/urfave/cli/v2.(*Command).Run(0xc0000d9200, 0xc00040ed80, 0x0, 0x0)
        pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4ed
github.com/urfave/cli/v2.(*App).RunContext(0xc00042e480, 0x15aa980, 0xc000034130, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
        pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
        pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/StackExchange/dnscontrol/v3/commands.Run(0xc00040abe0, 0x14, 0xc00003c118)
        src/github.com/StackExchange/dnscontrol/commands/commands.go:59 +0x247
main.main()
        src/github.com/StackExchange/dnscontrol/main.go:18 +0x45

**Comment by wararjey** [comment]
It seems that inwx created empty ._domainkey. records for each domain I transferred in. Once i deleted those manually in the inwx web interface, I was able to proceed manually. It seems those malformed records led to the crash.

Regards,

**Comment by patschi** [comment]
I've also seen this exact behavior in the past too. This strange records are being added when you enable DNSSEC on INWX and is most likely considered a bug on INWX. I've already raised a ticket with INWX and I'm waiting for a reply now. In the meanwhile simply get rid of those strange records manually and you're fine to go.

Beside that I'm wondering how we should handle unexpected entries (which can't be added through API/user UI) like this. Should we throw a warning and continue instead? @svenpeter42 @tlimoncelli

**Comment by svenpeter42** [comment]
I'm a big fan of failing loudly and early if something unexpected happens. If there are unexpected entries which we know about we could specifically ignore these but just ignoring anything unexpected sounds dangerous.

**Comment by tlimoncelli** [comment]
Short version: I agree. If something unexpected happens, fail. Don't try to fix something that a human should fix.

Longer version:

DNSControl calls `panic()` if it downloads a zone and finds that it contains DNS rtypes it doesn't understand.

There have been many proposals to ignore such records (or in the case of SPF, change them to TXT).  None of these proposals work all the time, and most of them have surprises that require human attention.  Thus, based on the [Compensatory Principle](https://queue.acm.org/detail.cfm?id=3197520) we leave this for humans to do.

Some day I'll make the code exit cleanly with a better error message instead of `panic()` but for now, it panics.

**Comment by tlimoncelli** [comment]
Update: I've been slowing removing the use of `panic()`.   

As of https://github.com/StackExchange/dnscontrol/commit/7db3741bc72462e17b4f099c45a39626d6e1ab3c, when DNSControl detects an unknown record type it will gracefully exit with a (hopefully) useful error message.

Can you verify if inwx works better now?

**Comment by wararjey** [comment]
Thx for getting back. Thing is, I already have activated dnssec for all domains on inwx, so the erroneous records that originally triggered the problem are all gone. I am afraid I cannot verify the fix right now. It probably will be a while until I get new domains...

Regards,

**Comment by patschi** [comment]
> Can you verify if inwx works better now?

I was able to try it with the latest commit as of today. While there's no panic, there's also no error nor warning anymore. The only validation errors coming up are due to TXT key size. But this was never been an issue before, so I'm confused why this error is being thrown now.

```
$ dnscontrol preview
[...]
2020/11/21 00:03:21 printIR.go:88: 22 Validation errors:
2020/11/21 00:03:21 printIR.go:94: ERROR: txt target >255 bytes and AUTOSPLIT not set: label="2018101._domainkey" index=0 len=424 string[:50]="v=DKIM1; k=rsa; t=s; s=email; p=MIIBIjANBgkqhkiG9w..."
2020/11/21 00:03:21 printIR.go:94: ERROR: txt target >255 bytes and AUTOSPLIT not set: label="20201._domainkey" index=0 len=424 string[:50]="v=DKIM1; k=rsa; t=s; s=email; p=MIIBIjANBgkqhkiG9w..."
[...]
2020/11/21 00:03:21 printIR.go:94: ERROR: txt target >255 bytes and AUTOSPLIT not set: label="2018101._domainkey" index=0 len=424 string[:50]="v=DKIM1; k=rsa; t=s; s=email; p=MIIBIjANBgkqhkiG9w..."
2020/11/21 00:03:21 printIR.go:94: ERROR: txt target >255 bytes and AUTOSPLIT not set: label="20201._domainkey" index=0 len=424 string[:50]="v=DKIM1; k=rsa; t=s; s=email; p=MIIBIjANBgkqhkiG9w..."
exiting due to validation errors
```

**Comment by svenpeter42** [comment]
Can you share a minimal dnsconfig.js that results in that error? I've just tried to reproduce it on the OTE system but haven't been able to.

**Comment by patschi** [comment]
There's no special configuration needed. The crash occurs when there're unknown rtypes provided from the INWX API. This can only reproduced when you enable automated DNSSEC on INWX for a specific domain with specific entries:
![image](https://user-images.githubusercontent.com/2029878/99878477-84d1e300-2bfd-11eb-8f2f-c7b40ee9237a.png)

Resulting in:
![image](https://user-images.githubusercontent.com/2029878/99878461-679d1480-2bfd-11eb-8a06-68dbef13f37a.png)

**Comment by svenpeter42** [comment]
Ah, sorry, I should've been more precise: I was curious about the `ERROR: txt target >255 bytes and AUTOSPLIT` error.

**Comment by patschi** [comment]
These are apparently new notices/warnings implemented in 13a13607794e726caabbe432ec8b8228058b6f97, and seems to be unrelated to the DNSSEC setup or this particular issue.

**Comment by tlimoncelli** [comment]
Yes, I did add some validation on the TXT records.  It looks like that's more of a breaking change than I expected.  Maybe I should include in the next release notes that provider maintainers should test their stuff.

**Comment by tlimoncelli** [comment]
I'm documenting this. I'd appreciate your feedback (is it clear?  what is it missing?  where were you confused?)

https://github.com/StackExchange/dnscontrol/pull/957

**Comment by svenpeter42** [comment]
I was just confused because I thought the error messages were somehow related to the original DNSSEC problem in this issue :-)

If I remember correctly INWX auto-splits long TXT records anyway but I think it still makes sense for dnscontrol to enforce the length limit. Otherwise people might be surprised if they switch to another provider which doesn't auto-split but denies overlong TXT records.

**Comment by tlimoncelli** [comment]
> Otherwise people might be surprised if they switch to another provider which doesn't auto-split but denies overlong TXT records.

Exactly.

**Comment by patschi** [comment]
> There's no special configuration needed. The crash occurs when there're unknown rtypes provided from the INWX API. This can only reproduced when you enable automated DNSSEC on INWX for a specific domain with specific entries:
> [...]
> ![image](https://user-images.githubusercontent.com/2029878/99878461-679d1480-2bfd-11eb-8a06-68dbef13f37a.png)

I have finally received an answer from INWX regarding those records. Apparently this specific records are "ENTs" and are intended. Based on my research this means `non-empty terminal` and is related to DNSSEC NSEC - see [RFC8198](https://tools.ietf.org/html/rfc8198#appendix-B) and [NSEC3 RFC5155](https://tools.ietf.org/html/rfc5155#page-43).

Not sure how we should handle this specific scenario, as it seems to be unique to INWX as of now. Ignoring records of type `_$SOMETHING` with empty record type?

**Comment by tlimoncelli** [comment]
FYI: The way dnscontrol handles TXT records is non-optimal.  I'm working on rewriting how that works, see https://github.com/StackExchange/dnscontrol/issues/1052

**Comment by tlimoncelli** [comment]
The new way to handle TXT records is now in `master`.  Is this still a problem?

**Comment by wararjey** [comment]
I recentrly registered a few domains (no .ro domain though) and did experience any problems with switching on DNSSEC.
TXT autosplit seems to work fine, when used according to the reference. Version currently used is 3.7.0.

**Comment by patschi** [comment]
> his specific records are "ENTs" and are intended

I think the core issue here is solved/clarified, so it might be closed I think, @tlimoncelli.

**Comment by tlimoncelli** [comment]
Glad it's working better!

If you do find special issues related to .ro domains, please add them to the docs (https://stackexchange.github.io/dnscontrol/providers/inwx)

Tom
