### ISSUE TITLE
Need NS1 maintainer

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#873]
The maintainer of NS1 is no longer with the project. We need someone to step up to maintain it.

**Comment by costasd** [comment]
Hi @tlimoncelli!

Read the item about NS1 getting dropped in the latest release notes.
> Provider NS1 has no maintainer and is jeopardy of being removed or deactivated if no volunteer steps up soon.

Having done a couple contributions to ns1 already and being a ns1 user with no plans to move out, I'd be happy to help keeping it up to shape.

best,
Costas

**Comment by costasd** [comment]
Sounds good, PR #1403 open! 

Thanks!
