### ISSUE TITLE
convertzone build fails

### ISSUE THREAD

**Issue by anderiv** [StackExchange/dnscontrol#88]
On current `master`, `go build` for convertzone fails with:

```
$ go build
# _/home/erik/src/dnscontrol/misc/convertzone
./main.go:73: cannot use l (type []"github.com/miekg/dns".RR) as type []"github.com/StackExchange/dnscontrol/vendor/github.com/miekg/dns".RR in argument to bind.WriteZoneFile
```

I do have `https://github.com/miekg/dns` and `https://github.com/pkg/errors` installed as required, but I'm afraid I don't grok golang enough to further troubleshoot this.

Thanks for any insight you can provide!

**Comment by captncraig** [comment]
Ah, one thing that is tricky with go apps it you have to check it out to a very specific path. 

To build dnscontrol, you pretty much need to check it out to $GOPATH/src/StackExchange/dnscontrol.

If you wanna work with a fork, just add a second remote to your repo, but leave the working directory as-is.

**Comment by anderiv** [comment]
Ahh, super-secret go knowledge. ;) Thanks @captncraig I'll give it a try.

**Comment by anderiv** [comment]
OK, looks like I'm still stuck. Sorry for boring you with what are likely mundane questions.

```
$ echo $GOPATH
/Users/erik/go
$ pwd
/Users/erik/go/src/StackExchange/dnscontrol/misc/convertzone
$ go build
# StackExchange/dnscontrol/misc/convertzone
./main.go:73: cannot use l (type []"StackExchange/dnscontrol/vendor/github.com/miekg/dns".RR) as type []"github.com/StackExchange/dnscontrol/vendor/github.com/miekg/dns".RR in argument to bind.WriteZoneFile
```

**Comment by captncraig** [comment]
Sorry, I screwed up. $GOPATH/github.com/StackExchange/dnscontrol

**Comment by anderiv** [comment]
Success! Thanks!
