### ISSUE TITLE
SRV records are listed as not defined

### ISSUE THREAD

**Issue by liljenstolpe** [StackExchange/dnscontrol#880]
Running on the latest version (3.3.0) pulled from github releases (this was fine a few months ago the last time I updated).  This is the first time I'm using the pre-built as go builds are currently borked (see my other open ticket).

The only include in my dnsconfig.js file that has SRV records, has the following SRV records...

```
  SRV('_jabber._tcp', 20, 0, 5269, 'xmpp2.hosted.im.'),
  SRV('_jabber._tcp', 10, 0, 5269, 'xmpp1.hosted.im.'),
  SRV('_msrps._tcp', 0, 0, 2855, 'msrprelay.sipthor.net.'),
  SRV('_sip._tcp', 100, 100, 5060, 'proxy.sipthor.net.'),
  SRV('_sip._udp', 100, 100, 5060, 'proxy.sipthor.net.'),
  SRV('_stun._udp', 0, 0, 3478, 'stun2.dns-hosting.info.'),
  SRV('_stun._udp', 0, 0, 3478, 'stun1.dns-hosting.info.'),
  TXT('xcap', 'https://xcap.sipthor.net/xcap-root/'),
  SRV('_xmpp-client._tcp', 20, 0, 5222, 'xmpp2.hosted.im.'),
  SRV('_xmpp-client._tcp', 10, 0, 5222, 'xmpp1.hosted.im.'),
  SRV('_xmpp-server._tcp', 10, 0, 5269, 'xmpp1.hosted.im.'),
  SRV('_xmpp-server._tcp', 20, 0, 5269, 'xmpp2.hosted.im.'),
```

When I run dnscontrol create-domains or push, I get the following error:

```
$ ./dnscontrol push
requiring: domains/<some_fnord_domain>.js
2020/09/30 23:57:46 main.go:56: Error executing javasscript in (dnsconfig.js): Error: ReferenceError: 'SRV' is not defined
```

**Comment by tlimoncelli** [comment]
I think this may be the same as https://github.com/StackExchange/dnscontrol/issues/881

**Comment by tlimoncelli** [comment]
New release posted.  Are you seeing the same problem?

**Comment by tlimoncelli** [comment]
Not receiving any complaints, I'll assume this issue is resolved.  Please re-open the issue if the issue persists.
