### ISSUE TITLE
NAMESERVER_TTL is not defined error in 3.3.30

### ISSUE THREAD

**Issue by liljenstolpe** [StackExchange/dnscontrol#881]
Another issue with 3.3.0

I am getting a NAMESERVER_TTL is not defined error
```
$ ./dnscontrol push
2020/10/01 00:47:19 main.go:56: Error executing javasscript in (dnsconfig.js): ReferenceError: 'NAMESERVER_TTL' is not defined
Cleaning up file based variables
```
Before I got the error the first time, I didn't have a NAMESERVER_TTL defined in defaults (except for .is domains, which requires a > 24h setting).  So the defaults seen above didn't have the NAMESERVER_TTL object.  After the first time the error threw, I added the entry in DEFAULTS as below without any change in behavior.

```
DEFAULTS(
    DnsProvider(dns_r53,2), DnsProvider(dns_gc,2), DnsProvider(dns_hex,1),
    //    DnsProvider(dns_gc,2), DnsProvider(dns_hex,2),
    NAMESERVER_TTL('5m'), DefaultTTL('1m')
);
```

**Comment by tlimoncelli** [comment]
Interesting!  I haven't seen that before.

Some questions:

What git branch / commit are you at?

What's the output of: `dnscontrol version`

What's the output of: `dnscontrol check`

Can you provide a minimal `dnsconfig.js` that demonstrates the problem?

**Comment by tlimoncelli** [comment]
I think we may just have a bad release. I'm also seeing reports like https://github.com/StackExchange/dnscontrol/issues/880

**Comment by tlimoncelli** [comment]
New release posted.  Are you seeing the same problem?

**Comment by tlimoncelli** [comment]
Not receiving any complaints, I'll assume this issue is resolved.  Please re-open the issue if the issue persists.
