### ISSUE TITLE
Unable to "go get" - build fails

### ISSUE THREAD

**Issue by mludvig** [StackExchange/dnscontrol#890]
go version go1.15.2 linux/amd64 on Ubuntu 18.04

```
~ $ go get -v github.com/StackExchange/dnscontrol
github.com/StackExchange/dnscontrol/pkg/acme
github.com/StackExchange/dnscontrol/providers/hexonet
# github.com/StackExchange/dnscontrol/pkg/acme
go/src/github.com/StackExchange/dnscontrol/pkg/acme/acme.go:143:36: not enough arguments in call to client.Certificate.Renew
	have (certificate.Resource, bool, bool)
	want (certificate.Resource, bool, bool, string)
# github.com/StackExchange/dnscontrol/providers/hexonet
go/src/github.com/StackExchange/dnscontrol/providers/hexonet/domains.go:7:41: cannot use map[string]string literal (type map[string]string) as type map[string]interface {} in argument to n.client.Request
go/src/github.com/StackExchange/dnscontrol/providers/hexonet/domains.go:13:41: cannot use map[string]string literal (type map[string]string) as type map[string]interface {} in argument to n.client.Request
go/src/github.com/StackExchange/dnscontrol/providers/hexonet/nameservers.go:44:41: cannot use map[string]string literal (type map[string]string) as type map[string]interface {} in argument to n.client.Request
go/src/github.com/StackExchange/dnscontrol/providers/hexonet/nameservers.go:97:31: cannot use cmd (type map[string]string) as type map[string]interface {} in argument to n.client.Request
go/src/github.com/StackExchange/dnscontrol/providers/hexonet/records.go:175:23: cannot use cmd (type map[string]string) as type map[string]interface {} in argument to n.client.Request
go/src/github.com/StackExchange/dnscontrol/providers/hexonet/records.go:191:23: cannot use cmd (type map[string]string) as type map[string]interface {} in argument to n.client.Request
github.com/StackExchange/dnscontrol/providers/vultr
# github.com/StackExchange/dnscontrol/providers/vultr
go/src/github.com/StackExchange/dnscontrol/providers/vultr/vultrProvider.go:123:103: cannot use r.Priority (type *int) as type int in argument to api.client.DNSRecord.Create
go/src/github.com/StackExchange/dnscontrol/providers/vultr/vultrProvider.go:196:35: cannot convert r.Priority (type *int) to type uint16
go/src/github.com/StackExchange/dnscontrol/providers/vultr/vultrProvider.go:199:50: cannot convert r.Priority (type *int) to type uint16
go/src/github.com/StackExchange/dnscontrol/providers/vultr/vultrProvider.go:245:3: cannot use priority (type int) as type *int in field value
```

Looks like some dependency API has changed?

**Comment by tlimoncelli** [comment]
Yes, we're having a problem with the Hexonet https://github.com/StackExchange/dnscontrol/issues/893 and Vultr https://github.com/StackExchange/dnscontrol/issues/892 providers.  Until those are fixed, please use the instructions in the README.md:

```
To install, simply run

    GO111MODULE=on go get github.com/StackExchange/dnscontrol/v3

To download the source

    go get -d github.com/StackExchange/dnscontrol
```

**Comment by pgaskin** [comment]
Does it work if you run `GO111MODULE=on go get github.com/StackExchange/dnscontrol/v3` instead?

**Comment by pgaskin** [comment]
@tlimoncelli, it might be worth completely deprecating using non-go-module `go get` for installing dnscontrol.

**Comment by tlimoncelli** [comment]
> @tlimoncelli, it might be worth considering completely deprecating using non-go-module go get for installing dnscontrol.

@pgaskin I would like to do that.  I have a limited knowledge of how Go Modules works.  What (aside from fixing #892 and #893) needs to be done?

**Comment by mludvig** [comment]
> is there a reason why you are trying to compile it without go modules?

No good reason other than that it's usually what I do when I need a go software built from source. With `GO111MODULE=on` and `/v3` it builds.

**Comment by pgaskin** [comment]
> @pgaskin I would like to do that. I have a limited knowledge of how Go Modules works. What (aside from fixing #892 and #893) needs to be done?

Nothing but not providing support or fixes for building with old-style plain `go get` (which uses unversioned dependencies). That would make this issue, #892, and #893 invalid.

> No good reason other than that it's usually what I do when I need a go software built from source. With GO111MODULE=on and /v3 it builds.

OK. Note that most newer Go packages (i.e. ones with `go.mod` in the root directory) should be built in this manner rather than plain `go get` (and `GOPATH`), as `go.mod` locks dependency versions and prevents conflicts. If you want access to the source code of a module, you can clone the repository with Git to a folder outside `GOPATH` and work directly inside it. The `/v3` comes from the module name, which can be found in the top line of `go.mod`. To edit the code for a dependency, you can use the `replace` directive in `go.mod`. See [here](https://blog.golang.org/using-go-modules) for more information about this.

Go modules replaces the older `GOPATH` and non-`GO111MODULE` `go get`.

**Comment by pgaskin** [comment]
If you do decide to discontinue supporting old-style builds, I can open a PR to add a warning if `dnscontrol` was built without go modules. It'd also be a good idea to ensure there aren't any leftover instructions for building dnscontrol without go modules.

**Comment by tlimoncelli** [comment]
@pgaskin Yes, let's stop supporting old-style builds.  A PR would be greatly appreciated!

**Comment by pgaskin** [comment]
> A PR would be greatly appreciated!

Done: #902.

**Comment by tlimoncelli** [comment]
Fixed by #902

**Comment by dovidgef** [comment]
The documentation websites quick start page does not contain the readme's updated install instructions.
Please fix this.

**Comment by tlimoncelli** [comment]
> The documentation websites quick start page does not contain the readme's updated install instructions.
> Please fix this.

doh!  I hadn't realized they got out of sync. Thank you for pointing that out!  I'm preparing a PR in https://github.com/StackExchange/dnscontrol/pull/951
