### ISSUE TITLE
Hexonet provider no longer compiles

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#893]
CC: @papakai

Regular `go get github.com/StackExchange/dnscontrol` does not work because of an incompatibility with the provider's module.  Please submit a PR with the newest .  The default module to download for the provider has made incompatible changes.   We are getting many reports about this (https://github.com/StackExchange/dnscontrol/issues/890 is one example).

I can't fix this because I do not have an account on the provider's system.  I need a volunteer to do this.

Generally the fix looks like this:

```
env | grep ^GO
# "unset" any GO* environment variables
unset GOPATH GO15VENDOREXPERIMENT
go get -d github.com/StackExchange/dnscontrol
cd ~/go/src/github.com/StackExchange/dnscontrol/
go test ./...
go get -u github.com/hexonet/go-sdk
go test ./...       # this will fail. Please fix.
# Once that works, try the integration test:
export HEXONET_ENTITY="redacted.tld"
export HEXONET_UID="redacted" 
export HEXONET_PW="redacted"
# Edit providers.json and change "HEXONET "domain" to a domain you can overwrite.
cd integrationTest && go test -v -verbose -provider HEXONET
# Fix problems until all tests pass.
```

---

Here is a demonstration of the `go get` problem:

```
$ go get -v github.com/StackExchange/dnscontrol
github.com/StackExchange/dnscontrol/pkg/acme
github.com/StackExchange/dnscontrol/providers/hexonet
github.com/StackExchange/dnscontrol/providers/vultr
# github.com/StackExchange/dnscontrol/providers/hexonet
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/hexonet/domains.go:7:41: cannot use map[string]string literal (type map[string]string) as type map[string]interface {} in argument to n.client.Request
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/hexonet/domains.go:13:41: cannot use map[string]string literal (type map[string]string) as type map[string]interface {} in argument to n.client.Request
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/hexonet/nameservers.go:44:41: cannot use map[string]string literal (type map[string]string) as type map[string]interface {} in argument to n.client.Request
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/hexonet/nameservers.go:97:31: cannot use cmd (type map[string]string) as type map[string]interface {} in argument to n.client.Request
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/hexonet/records.go:175:23: cannot use cmd (type map[string]string) as type map[string]interface {} in argument to n.client.Request
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/hexonet/records.go:191:23: cannot use cmd (type map[string]string) as type map[string]interface {} in argument to n.client.Request
# github.com/StackExchange/dnscontrol/pkg/acme
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/pkg/acme/acme.go:143:36: not enough arguments in call to client.Certificate.Renew
	have (certificate.Resource, bool, bool)
	want (certificate.Resource, bool, bool, string)
# github.com/StackExchange/dnscontrol/providers/vultr
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/vultr/vultrProvider.go:123:103: cannot use r.Priority (type *int) as type int in argument to api.client.DNSRecord.Create
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/vultr/vultrProvider.go:196:35: cannot convert r.Priority (type *int) to type uint16
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/vultr/vultrProvider.go:199:50: cannot convert r.Priority (type *int) to type uint16
/Users/tlimoncelli/go/src/github.com/StackExchange/dnscontrol/providers/vultr/vultrProvider.go:245:3: cannot use priority (type int) as type *int in field value
```

Here is go-mod-outdated's opinion of what the old and new module releases are:

```
$ go get -u github.com/psampaz/go-mod-outdated
$ go list -mod=mod -u -m -json all | go-mod-outdated -update -direct 
+-----------------------------------+------------------------------------+------------------------------------+--------+------------------+
|              MODULE               |              VERSION               |            NEW VERSION             | DIRECT | VALID TIMESTAMPS |
+-----------------------------------+------------------------------------+------------------------------------+--------+------------------+
...
| github.com/hexonet/go-sdk         | v2.2.3+incompatible                | v3.5.0+incompatible                | true   | true             |
...
+-----------------------------------+------------------------------------+------------------------------------+--------+------------------+
```

**Comment by papakai** [comment]
This PR bumped our version from the previous one to the newer one and has to be seen as origin of this issue.
https://github.com/StackExchange/dnscontrol/pull/662

It is cool to see others to work on the hexonet part and contributing - very appreciated. But yes, when it comes to such kind of issues, it tells me that things were probably not well enough tested.

I can't change the situation, as I am having other priorities assigned. Wouldn't be the easiest idea to switch back to our previous version? @tlimoncelli

**Comment by papakai** [comment]
If possible, could anyone just review the affected code lines into direction of https://github.com/hexonet/go-sdk#sessionless-api-communication. It is probably just about the incoming variable type and therefore quite easy to fix.

**Comment by papakai** [comment]
@tlimoncelli 

> We are getting many reports about this (#890 is one example).

Are that issues reported by hexonet customers or could that be anyone using dnscontrol? That's worth to know for me.

**Comment by tlimoncelli** [comment]
@papakai It affects anyone trying to "go get" the code.

**Comment by tlimoncelli** [comment]
@papakai I made the change to `interface{}` as suggested.  The result is https://github.com/StackExchange/dnscontrol/pull/898

I can compile it.  Can you verify that it works?

**Comment by papakai** [comment]
I don't have to the time to test @tlimoncelli nor a ready to use setup for this. We have a public user for our demo system available that anyone could use: user -> test.user, password -> test.passw0rd
These credentials are known to the public, no worries.

I expect noone has time to dive into tests atm, neither myself nor anyone of you guys. I am also ok to get this merged to just support dnscontrol with a back working compile process. If there are upcoming issues for hexonet then, we have to get them fixed asap. More important is to support dnscontrol in general first.

**Comment by tlimoncelli** [comment]
@papakai Thanks for the tip about the public demo system!  That's awesome!  I can run our full suite of tests now.

All my fixes are in https://github.com/StackExchange/dnscontrol/pull/898. If you could take a look, it would be greatly appreciated!

**Comment by papakai** [comment]
just one note: anyone in the world can use that user, so anyone in the world can add new dnszone and modify / delete existing ones. If that's a problem of your tests, please let me know. I can create an account just for dnscontrol in our OT&E system.

I added my review to your PR! ... and also again in here: Thanks so much for your help... I did not expect that from you guys and had been in worries how I can manage dnscontrol patches in near future. Very very appreciated! Better times will come, I am sure.
