### ISSUE TITLE
Multiple D() entries for internal/external DNS

### ISSUE THREAD

**Issue by liftedkilt** [StackExchange/dnscontrol#903]
We leverage Cloudflare for external DNS, and BIND files for our internal DNS.

The way that I've organized things is:

`main.js`:
```
function getCommon() {
	return [
            CNAME('foo', example.com.'),
         ];
}

require('./external.js');
require('./internal.js');
```

and then in `external.js`:
```            
D(
	'example.com',
	REG_NONE,
	DnsProvider(CLOUDFLARE),
	getCommon(),
        ... // more records that are only external
);
```

in `internal.js`:
```
D(
	'internal_example.com',
	REG_NONE,
	DnsProvider(BIND),
	getCommon(),
        // more records that are only internal
):
```

in order to generate DNS separately for internal and external, I have to prefix all my internal domains with `internal_` in order to have the names be unique.

The only real annoyance is that for some reason if I don't delete the BIND files every time I regenerate, the mbox entry in the SOA record (which is hardcoded to `postmaster.example.com` in my BIND `default_soa` entry gets changed from:

`postmaster.example.com` 
to
`postmaster.example.com.internal_example.com`

Is there a better way I should be doing this? Is that a result of a bug in the BIND provider generation? It would be amazing to have a way to spit out a bind file for example.com containing our internal records as well as using cloudflare for external records without having to break the domain name.

**Comment by tlimoncelli** [comment]
You've raised a couple issues here.

The mbox bug... yeah, that might be hard to fix.  On the bright side, I can assure you that zero people in the world pay attention to the data in the mbox field.  At least nobody since about 1994.  So, it it is invalid I wouldn't worry too much.  If you have a counter example I'd be very interested!

As far as better ways to have 2 domains with similar info.... I think your technique is about as good as one can get.  I have a question: Is the zone `internal_example.com` loaded into ISC BIND as `example.com`?

Tom

**Comment by tlimoncelli** [comment]
Here's a thought.  What if you made a file that could be included twice, but acted differently depending on if this was the internal or external version?

dnsconfig.js:

```
require("example.js");
site = "internal";
require("example.js");
```

example.js:

```
D( "example.com",
    if_external( A("aaa", "1.2.3.4")),
    if_internal( A("aaa", "10.2.3.4")),
    A("bbb", "10.2.3.4"),
    if_internal(
        A("ccc", "10.2.3.4"),
        A("ddd", "10.2.3.4"),
    ),
)   
```

When you write `if_internal()` and `if_external()` you can take advantage of the fact that each item in a `D()` can be a. single item, a list of items, or even an empty list (i.e. `{}`).

In https://github.com/StackExchange/dnscontrol/issues/853 there was a similar suggestion that resulted in:

```
echo 'var DESTINATION = "second";' >picker.js
cat picker.js dnsconfig.js >generated.js
dnscontrol --config generated.js
```

You can also use the `--domains` flag to run the configuration only for certain domains.

We get this question occasionally.  If you come up with a good solution, I'd love a writeup that we could include in the docs.

Tom

**Comment by liftedkilt** [comment]
We actually use both BIND and CoreDNS internally, and I template the configs for them both to read them in as `example.com` (I'm managing ~25 domains like this)

I don't need the mbox field, but named-checkzone throws errors because it's invalid:

```
$ named-checkzone example.com ./internal_example.com.zone
./internal_example.com.zone:3: warning: postmaster.example.com.internal_example.com: bad name (check-names)
```

**Comment by liftedkilt** [comment]
@tlimoncelli If I require a file twice which contains a D() with the same domain name, won't that fail?

```executing dnsconfig.js: Error: File main.js: Error: File internal.js: example.com is declared more than once```

**Comment by tlimoncelli** [comment]
Good point.  You'll have to use the `picker.js` strategy or use `D(prefix + "example.com",` and set prefix to `""` or `"internal_"` as appropriate.

As far as getting `named-checkzone` to pass... that may be more difficult.  I would look at the SOA-related code in in `providers/bind/*.go`.  BIND is the only provider that doesn't auto-generate SOA records therefore all the SOA-related code is there.
