### ISSUE TITLE
Passing variables

### ISSUE THREAD

**Issue by mrtristan** [StackExchange/dnscontrol#907]
I'd like to dynamically run dnscontrol with different providers. My use case _seems_ pretty simple. Cloudflare is my main DNS, i'd like to have Rt53 fully populated and on standby for when cloudflare has their blips as they do.

There does not seem to be a way to either:
- make a variable for all the records and then have two `D()` records for the same domain, one per provider. (not allowed due to domain being same)
- pass a variable saying which to use, and simply run twice to ensure both are fully synchronized.

The first feels like a bigger deal, so opting to ask about if there's any reason the second wouldn't work?

Regarding trying to use the library as-is, I tried including both providers but there doesn't seem to be a way to prevent NS records from cross pollinating, and if i recall correctly, adding `DnsProvider(rt53, 0)` makes it so that dnscontrol wants to strip the NS records that are in my hosted zone.

As a (hopefully) temporary measure, I'm about to resort to writing strings to a json file in CI/CD process and reading that in `dnsconfig` and then simply running twice. seems it will accomplish what I'm looking to do but definitely a little clunky.

**Comment by tlimoncelli** [comment]
I think what you are trying to do is covered by the "Shadow DNS servers" section of https://stackexchange.github.io/dnscontrol/nameservers

Does that help?

If not, you might look at this bug:

https://github.com/StackExchange/dnscontrol/issues/853

**Comment by mrtristan** [comment]
@tlimoncelli  i did try the shadow concept prior to opening the issue. 

in this example specifically:
```
D("example1.com", REG_NAMECOM,
  DnsProvider(DNS_NAMECOM), // Our real DNS server
  DnsProvider(DNS_CLOUDFLARE, 0), // Quietly send a copy of the zone here.
  DnsProvider(DNS_BIND, 0), // And here too!
  A("@", "10.2.3.4")
);
```

my issue with the functionality of the shadow is that it wants to update NS records at the shadow. So in the case of my main/shadow being cloudflare/rt53 having the shadow means that it wants to put jack and kara in route53 and delete the NS records that are there, where i'd rather leave the NS records alone and ready to go so in the event of needing to flip traffic from cloudflare to rt53 all that is good and ready to go.

_however_, it seems that things got a little more complicated in my setup in that i need to run twice either way due to needing to conditionally use alias/rt53_alias based on which provider i'm targeting, and conditionally format TXT records based on which provider i'm targeting to get around length issues (for long DKIM records that go beyond 255 max). so all this forces me away from the shadow concept.

in thinking of your example as "do something outside of the tool and then run the tool" your other example is functionally more or less the same to what i'm doing. With the goal of minimizing complexity and moving parts, i think i would rank the approaches as follows:
1. pass param or have the ability to read arbitrary env vars
2. read config from file
3. generate dnsconfig.js dynamically

thanks again for your time and your work here. much prefer all of this even with the nuanced pain points than managing things manually as i was, and much nicer having such a specialized toolset over using terraform as well.

**Comment by tlimoncelli** [comment]
Thanks for the writeup!

I hadn't realized that the NS records would be deleted that way.  My shadow is BIND, which doesn't do much with NS records.

You might look at https://github.com/StackExchange/dnscontrol/pull/913 which will enable setting variables at the command line.  `dnscontrol preview -v foo=bar` will set foo.  That should let you do conditionals a lot easier.  Please watch that PR.

I'll close this issue for now. Please reopen it if you need.

**Comment by mrtristan** [comment]
@tlimoncelli that PR would be perfect for my needs. thanks
