### ISSUE TITLE
ROUTE53 provider fails with very large updates

### ISSUE THREAD

**Issue by mrtristan** [StackExchange/dnscontrol#908]
```
FAILURE! InvalidChangeBatch: [RDATA character limit of 32000 exceeded.]
        status code: 400
```

i have a 1500 record zone file on cloudflare i'm trying to replicate to RT53, seems there's a character limit on the requests to AWS and they're not batched or at least the batching doesn't factor in the character length.

**Comment by mrtristan** [comment]
since i'm not dealing with a live system i was able to move the records to an array and simply put a `.slice(0,250)` on the list and run a few times, incrementing by 250 each time until i got to the end. clearly this wouldn't be ideal if it was "live"

**Comment by tlimoncelli** [comment]
CC: @maclennann @rileyberton @zwo-bot 

I was able to create a repo.

It's interesting because our integration test tries up to 1200 records and succeeds.  I had to change the test to much bigger (9999 records) to see it fail the way you indicated:

```
$ go test -run TestDNSProviders -v -provider ROUTE53 -start 17 -end 17
=== RUN   TestDNSProviders
=== RUN   TestDNSProviders/dnscontroltest-r53.com
=== RUN   TestDNSProviders/dnscontroltest-r53.com/Clean_Slate:Empty
=== RUN   TestDNSProviders/dnscontroltest-r53.com/17:pager1201:9999_records
    integration_test.go:184: InvalidChangeBatch: [Exceeded limit MAX_RRSETS_BY_ZONE for zone: Z3HTIAEKH5JU4F]
        	status code: 400, request id: 6f75f2c5-335f-4f9c-aae0-dfe420b97785
=== RUN   TestDNSProviders/dnscontroltest-r53.com/Post_cleanup:Empty
--- FAIL: TestDNSProviders (81.03s)
    --- FAIL: TestDNSProviders/dnscontroltest-r53.com (80.59s)
        --- PASS: TestDNSProviders/dnscontroltest-r53.com/Clean_Slate:Empty (0.30s)
        --- FAIL: TestDNSProviders/dnscontroltest-r53.com/17:pager1201:9999_records (29.81s)
        --- PASS: TestDNSProviders/dnscontroltest-r53.com/Post_cleanup:Empty (50.28s)
FAIL
exit status 1
FAIL	github.com/StackExchange/dnscontrol/v3/integrationTest	81.312s
```

Interesting enough, there is code in `providers/route53/route53Provider.go` that seems to be trying to send small batches of updates. Seems like a matter of improving that code should fix this.

Would you be interested in taking a whack at it?

**Comment by mrtristan** [comment]
@tlimoncelli  not sure if that last line was directed at me, i'd certainly attempt it if i was a go guy... :-)

regarding the quantity nuances, most of our records are cnames to load balancers so that could be causing a dramatically larger character account as opposed to 1200 ips if your integration test leans in that direction.

**Comment by rileyberton** [comment]
The default limit for MAX_RRSETS_BY_ZONE is 10000.  (https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-entities-records)

I don't think breaking up into smaller chunks can side step that.

The original report complains of 32K chars in RDATA.  That is a fixed limit:

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests-changeresourcerecordsets

I think the fix here is being more intelligent about the size of the batch (keep track of number of records but also character count).

**Comment by tlimoncelli** [comment]
Thanks for the URL about the limits. We should include that in the code for future reference.

I found this sentence the most interesting: `When the value of the Action element is UPSERT, each character in a Value element is counted twice.`

We don't try to be very sophisticated and determine the RDATA size. We just batch up a small number of records at a time which should be small enough.   When we changed to using UPSERT, we should have cut the limits in half.

**Comment by tlimoncelli** [comment]
I don't think it is a simple matter of reducing the batch size. If I change the batch size  500 -> 10 the error still happens:

Old:

        batchSize := getBatchSize(len(changes), 500)

New:

        batchSize := getBatchSize(len(changes), 10)

Same error.

**Comment by tlimoncelli** [comment]
In all my tests, the error happened on the last batch.  I found that odd considering that the last batch should always be smaller than the others. (If you have 450 records and 100-record batches, the batches should be 100, 100, 100, 5)

I think this means that all the batches are being sent in the same HTTP request.

I don't have time to investigate but if the above is true, at least we've narrowed down the issue.

**Comment by ibeex** [comment]
I think taht getBatchSize 1000 or 10 don't change anything, there should be delay every 1000 records so that [treashold](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests-changeresourcerecordsets) is't trigered
