### ISSUE TITLE
Updating from 3.3.0 to 3.4.2 seems to error

### ISSUE THREAD

**Issue by trobotham** [StackExchange/dnscontrol#910]
I have updated to the latest docker image which is currently 3.4.2 and am now getting a error:

executing dnsconfig.js: Error: File 010-darenet.org.js: TypeError: 'substr' is not a function

If I downgrade back to 3.3.0, it all works fine no errors at all not sure what changed in between, I am happy to help debug if you have questions. everything looks syntactically correct when I run check and preview in 3.3.

**Comment by tlimoncelli** [comment]
Welp, that's a new one!

Is `010-darenet.org.js` a file on your system?  is it a `require()` file?

What's the output of: `dnscontrol check`

**Comment by trobotham** [comment]
it is a require file, and it is a specific file on my system.

> > dnscontrol check
> executing dnsconfig.js: Error: File 010-darenet.org.js: TypeError: 'substr' is not a function

**Comment by tlimoncelli** [comment]
Is `010-darenet.org.js` mentioned in `dnsconfig.js`?

**Comment by trobotham** [comment]
it is under domains which is a require:

dnsconfig.js:

> /*
>    dnsconfig.js: dnscontrol configuration file for DareNET.
> */
> 
> // Providers:
> 
> var REG_NONE = NewRegistrar('none', 'NONE');    // No registrar.
> var ROUTE53 = NewDnsProvider("route53", "ROUTE53");
> 
> //////////////////////////////////////////////////////////////////////////
> 
> // import util files
> require_glob('utils/', false)
> 
> // import dynamic info
> require_glob('dynamic/', false)
> 
> // import individual domain files
> require_glob('domains/', false)

**Comment by tlimoncelli** [comment]
Are you using `D_EXTEND()` by any chance?

**Comment by trobotham** [comment]
yes, I am using it in a few places in that file

**Comment by tlimoncelli** [comment]
That'd odd.  The only place that substr is used is in the D_EXTEND() functions.  Do you think you could repro the error with a small sample?  Something you can share?

**Comment by tlimoncelli** [comment]
Is there a chance that the first parameter to `D_EXTEND()` is not a string?

**Comment by trobotham** [comment]
here is a small snippit of one of the D_EXTENDS that seem to affect it:

> D_EXTEND(domain,
> 	NS('irc', 'ns-1474.awsdns-56.org.'),
> 	NS('irc', 'ns-531.awsdns-02.net.'),
> 	NS('irc', 'ns-72.awsdns-09.com.'),
> 	NS('irc', 'ns-2032.awsdns-62.co.uk.')
> );

**Comment by trobotham** [comment]
also to note, "domain" is a actual variable.

**Comment by tlimoncelli** [comment]
If you change the variable to a literal, or change it to: `D_EXTEND(""+domain,` does the error go away?

**Comment by tlimoncelli** [comment]
PS.   if you are `D_EXTEND`-ing many domains in a loop, consider using a macro like in the "Macro to for repeated records"  example in https://stackexchange.github.io/dnscontrol/examples (which I now realize should be "Macro to repeat records'). That might be easier to maintain.

**Comment by tlimoncelli** [comment]
I'm baffled.

That said... do did notice that while trying to reproduce this issue I made a typo that gave the same error message.

```
var REG = NewRegistrar("bind", "BIND");
var DSP = NewDnsProvider("bind", "BIND");
D('example.com', REG,
   DSP,       /// WRONG!  Should be:  DnsProvider(DSP),
  A("www", "1.2.3.4")
)
```

That might not be related to this problem, but I'm recording it just in case. (and because we should fix that!)

**Comment by tlimoncelli** [comment]
I'm still baffled but... if you comment out all the `D_EXTEND()` statements, does "dnscontrol check" report anything?  I ask because the error message is unclear and I want to narrow down what it is referring to.

**Comment by trobotham** [comment]
if I change domain to a literal, it seems to work, what is even stranger is that it only seems to affect some D_EXTEND blocks and not others.

If I can privately provide you the zone files somewhere (irc?) I can let you test with them.

**Comment by tlimoncelli** [comment]
Sure, send it to tlimoncelli at stack over flow dot com

**Comment by tlimoncelli** [comment]
CC: @patschi 

I have reproduced the bug!

This works:

```
var REG_NONE = NewRegistrar("ThirdParty", "NONE");
var ROUTE53 = NewDnsProvider("r53", "ROUTE53");

D('example.com', REG_NONE,
  DnsProvider(ROUTE53),
  A('@', "1.2.3.4")
);
  
D_EXTEND('example.com',
  A('aaa', "1.2.3.4")
);
  
D_EXTEND('example.com',
  A('bbb', "1.2.3.4")
);
```

However this doesn't work:

```
var REG_NONE = NewRegistrar("ThirdParty", "NONE");
var ROUTE53 = NewDnsProvider("r53", "ROUTE53");

domain = 'example.com';

D(domain, REG_NONE,
  DnsProvider(ROUTE53),
  A('@', "1.2.3.4")
);

D_EXTEND(domain,
  A('aaa', "1.2.3.4")
);

D_EXTEND(domain,
  A('bbb', "1.2.3.4")
);
```

If you comment out the second `D_EXTEND()` it works.

Maybe `_getDomainObject` is mutating something it shouldn't?

**Comment by patschi** [comment]
Based on the [changes between 3.3.0 and 3.4.2](https://github.com/StackExchange/dnscontrol/compare/v3.3.0...v3.4.2) this needs to be related to `_getDomainObject`, which has changed quite heavily since the last time I took a looked in `helpers.js`. While looking through the changes and the code, and without debugging so far, I think I know where the problem resides in.

Important bits:
https://github.com/StackExchange/dnscontrol/blob/8205a8a3563f706eeda55231a93d12c0ba813242/pkg/js/helpers.js#L127-L128

The variable `domain` is being set to `null` there. As no `var domain` is used here, this is changed in the global context, therefore also overwriting the domain used in the example you've sent.

To verify: If you replace the variable `domain` in your example to something like else (`domain2` or so) the error shouldn't be reproducible anymore. Can you verify that?

If so, the fix would be replacing `domain = null;` to `var domain = null;` (preferably also for `domain_len` as well).

**Comment by trobotham** [comment]
This does appear to be the issue, changing "domain" to "domain2" seems to have resolved it.
