### ISSUE TITLE
Error: Invalid account identifier passed in your organization variable

### ISSUE THREAD

**Issue by wwwlde** [StackExchange/dnscontrol#929]
```
$ dnscontrol version
dnscontrol 3.4.2 ("ac3ee9afeafea88a3d468db34874651375f31834") built 12 Oct 20 18:57 CEST

$ dnscontrol create-domains
***  example.com
  - cloudflare
Added zone for example.com to Cloudflare account:
Error creating domain: [{"code":1067,"message":"Invalid account identifier passed in your organization variable"}]
```

Have this error message while trying to add new domain to account. I can't understand what this actually mean. Can someone help with this?

Thanks in advance!

**Comment by tlimoncelli** [comment]
Looks like an authentication issue.  Does `dnscontrol check-creds cloudflare CLOUDFLAREAPI` work?

**Comment by wwwlde** [comment]
@tlimoncelli Hi! Thanks for your reply!

Check creds doesn't return anything, but return code is good (success).

```
$ dnscontrol -v check-creds cloudflare CLOUDFLAREAPI
$ echo $?
0
```

My custom token is allowed to Edit "Zone -> Zone, Zone -> DNS, Zone -> PageRule". Is it enough for adding new domain?

In creads.json I have provided Cloudflare API token in form:

```
{
  "cloudflare": {
    "apitoken": "your-cloudflare-api-token"
  }
}
```

**Comment by tlimoncelli** [comment]
I believe that is correct.

Does adding domains to your account work through the webUI?

Tom

**Comment by wwwlde** [comment]
@tlimoncelli  Yes it is works correctly via UI without any issues. But for full automation I need to add domains via dnscontrol.

What can you tell me about strange API error 1067? I do not understand sense of this error. This is some issue with account? Should I also contact CloudFlare support?

**Comment by wwwlde** [comment]
@tlimoncelli Oh looks like I solve my issue :-) As API documentation said (https://api.cloudflare.com/#zone-create-zone) I should also provide account id of which the zone is created in. After I set "accountid" & "accountname" at creds.json problem was solved. I apologize for disturbing you. Good health and sunny days to you and your loved ones.

**Comment by tlimoncelli** [comment]
Glad you were able to solve the issue on your own.  Is there something we could add to `docs/_providers/cloudflare.md` so that the next person with this problem can solve the issue faster?  (or maybe won't have the problem?)
