### ISSUE TITLE
Idea: Ownership system

### ISSUE THREAD

**Issue by maxnasonov** [StackExchange/dnscontrol#935]
[NO_PURGE](https://stackexchange.github.io/dnscontrol/js#NO_PURGE) allows a domain to be managed by multiple systems. But `The main caveat of NO_PURGE is that intentionally deleting records becomes more difficult.`. `dnscontrol` could adopt some ownership system and provide it as an option. For example,`external-dns` [uses TXT records](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md#im-afraid-you-will-mess-up-my-dns-records).

Thanks for the nice project.

**Comment by tlimoncelli** [comment]
That's an interesting idea! 

There is "IGNORE_NAME()", which basically says, "I trust that someone else owns that label".  Is that what you are looking for?

**Comment by maxnasonov** [comment]
> There is "IGNORE_NAME()", which basically says, "I trust that someone else owns that label". Is that what you are looking for?

Unfortunately no. `dnscontrol` instances and other DNS record managers are not aware of other records and there is no record pattern to differentiate the records between managers.

**Comment by tlimoncelli** [comment]
Let's take external-dns as an example: What would you like the syntax to look like in dnsconfig.js if dnscontrol and external-dns were both managing a zone?

**Comment by tlimoncelli** [comment]
Closing stale issue.  Please re-open to continue the conversation.

**Comment by haslersn** [comment]
@tlimoncelli the idea is that for every record

```
<FQDN> <type> <content>
```

dnscontrol also creates a record that looks approximately like this:

```
_heritage_<type>.<FQDN> TXT "heritage=dnscontrol,dnscontrol/owner=<owner>"
```

(Here `<owner>` would be some persistent value configured in the `dnsconfig.js`.)

Example:

```
example.com. A 1.2.3.4
_heritage_a.example.com. TXT "heritage=dnscontrol,dnscontrol/owner=foo
```

When dnscontrol wants to update or delete the RRset `example.com. A`, it first checks whether the corresponding heritage record exists and has the correct owner. If not, dnscontrol is not allowed to update/delete the RRset. In case dnscontrol wanted to update the RRset, it returns an error to the user, stating that the RRset is not owned by the given `dnsconfig.js`.

**Comment by tlimoncelli** [comment]
@haslersn Thanks for the suggestion!  That's an interesting proposal.

**Comment by muhlba91** [comment]
@tlimoncelli any progress on that?
my use case is sinilar in that external-dns manages all records for my kubernetes services. i would like to manage external services or „global records“ (e.g. mx, spf, …) by dnscontrol.
for that it‘s necessary to only manage owned records and don‘t touch others - there‘s also no pattern in the external-dns created ones s.t. an ignore would solve it.

**Comment by tlimoncelli** [comment]
Have you tried [NO_PURGE](https://docs.dnscontrol.org/language-reference/domain-modifiers/no_purge) ?

**Comment by haslersn** [comment]
@tlimoncelli with NO_PURGE, dnscontrol will not delete records that it created. The point is that dnscontrol should purge records that are no longer configured, but only if they were created and thus owned by dnscontrol.

**Comment by muhlba91** [comment]
since it doesn't delete records and creates orphans, it's not a solution here.
using `NO_PURGE` we'd need to manually scan for orphans and delete them.
this is error-prone and, imo, defeats the purpose of such a tool if i need to manually intervene again.
if dnscontrol would mark ownership of is managed records, we can have multiple systems, or even multiple dnscontrol "instances", managing the same domain with different ownership attributes (or none).

**Comment by tlimoncelli** [comment]
I would accept a PR to add some kind of ownership system as you suggest.  I would also be glad to discuss design ideas for how to implement it.  I can't add this feature myself as I don't work on DNSControl full time and can only add features that my team needs.

Yes, my team also has that problem (needing to manually scan for records to delete).  However we find that our k8s clusters always have the same 3-4 records inserted by dnscontrol and they don't change often. Therefore, the risk is low for us. Not everyone is so lucky.

Ideally external-dns would have a mechanism to insert the global records.  That way there is 1 system controlling dns for that zone.

Tom

**Comment by tlimoncelli** [comment]
Another workaround idea:  If external-dns only adds A and CNAME records, and dnscontrol only adds TXT/MX/SPF records, then these are disjoint sets that IGNORE() can handle.  `IGNORE("*", "A,CNAME", "*")`
