### ISSUE TITLE
INWX: integration test "single_TXT:Create_TXT_with_single-quote" fails

### ISSUE THREAD

**Issue by svenpeter42** [StackExchange/dnscontrol#954]
looks a new integration test has been added since INWX support has been added and it seems to fail.
feel free to assign this to me. I will look into fixing it.

```
=== RUN   TestDNSProviders/testdomain.eu/08:single_TXT:Create_TXT_with_single-quote
    integration_test.go:180: CREATE TXT foo.testdomain.eu "blah`blah" ttl=300
    integration_test.go:199: Expected 0 corrections on second run, but found 1.
    integration_test.go:201: #0: MODIFY TXT foo.testdomain.eu: ("blahblah" ttl=300) -> ("blah`blah" ttl=300)
```

**Comment by svenpeter42** [comment]
Looks like INWX currently doesn't support ` in DNS records even when using the web interface.

**Comment by tlimoncelli** [comment]
> Looks like INWX currently doesn't support ` in DNS records even when using the web interface.

Feel free to just exclude it from the tests. I don't expect providers can handle all chars.

**Comment by svenpeter42** [comment]
INWX actually silently swallows these single-quote characters. I've written to their support to see if they want to return an error from the API instead. If they won't I think it would be a good idea to verify this inside dnscontrol and fail if the record contains any ` before sending it to INWX to prevent surprises.

**Comment by tlimoncelli** [comment]
I don't mind splitting this test out so that INWX can opt-out.  I bet that many providers will also fail.

**Comment by svenpeter42** [comment]
I'll create a PR for that later.

The thing I'm concerned about is that the INWX API silently ignores these quotes.
If I e.g. create a TXT record with contents "blah`blubb" it will reply with success but then only create "blahblubb". What do you think about adding a check for this in the INWX provider and just refuse to create the record in that case? Or should this be done somewhere else in case other providers also silently ignore such errors?
