### ISSUE TITLE
ROUTE53: Suppress default NS list from Delegation Set

### ISSUE THREAD

**Issue by caguiclajmg** [StackExchange/dnscontrol#958]
Is there currently a way to suppress the addition of the default R53 NS records when the hosted zone is in a delegation set?

From what I see the NS records from the delegation set are always added regardless even if there are explicitly-defined `NAMESERVER` entries.

https://github.com/StackExchange/dnscontrol/blob/6fe4ca6996da390cbc7afc4713ab5ca4b48082e5/providers/route53/route53Provider.go#L178-L182

Use case is when creating [white-label nameservers](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/white-label-name-servers.html).

Example:

    D("example.com", NewRegistrar('none', 'NONE'),
      A("ns1", "1.1.1.1"),
      AAAA("ns1", "2.2.2.2"),
      NAMESERVER("ns1.example.com."),
    );

Expected:

    NS example.com ns1.example.com.

Actual:

    NS example.com ns1.example.com.
    NS example.com ns-1081.awsdns-07.org.
    NS example.com ns-1825.awsdns-36.co.uk.
    NS example.com ns-608.awsdns-12.net.

**Comment by tlimoncelli** [comment]
Does it work if you add a DnsProvider and specify a "0" as the 2nd operand?

```
var DSP_R53 = NewDnsProvider("r53", "ROUTE53");      <<<NEW

D("example.com", NewRegistrar('none', 'NONE'),
  DnsProvider(DSP_R53, 0),                                           <<<NEW
  A("ns1", "1.1.1.1"),
  AAAA("ns1", "2.2.2.2"),
  NAMESERVER("ns1.example.com."),
);
```

**Comment by caguiclajmg** [comment]
Accidentally left out the `DnsProvider` lines in my initial post, but yes that seemed to do the trick. Totally missed `nsCount` on the docs.

Thanks!

**Comment by tlimoncelli** [comment]
nsCount is a sneaky little feature that can be verey powerful. Here are some more examples: https://stackexchange.github.io/dnscontrol/nameservers
