### ISSUE TITLE
Cloudflare: long TXT records now fail validation (related to AUTOSPLIT)

### ISSUE THREAD

**Issue by matt-sullivan** [StackExchange/dnscontrol#964]
Long TXT records supplied to cloudflare used to be applied successfully, but fail validation checks as of #947.

From a user perspective it previously worked without a problem: I _think_ the cloudflare API treats it as one string, but dns lookups return an array of strings. A validation check now fails with or without AUTOSPLIT, resulting in 'ERROR: TXT records with multiple strings not supported by cloudflare.com' & 'ERROR: txt target >255 bytes' respectively.

Should cloudflare have CanUseTXTMulti enabled or is this more complex to fix? Is there any workaround I can use in the short term? (Other than running an older version of dnscontrol? I am currently using the latest docker image.)

**Comment by tlimoncelli** [comment]
This is going to take some testing.  CanUseTXTMulti is a good idea.

Maybe the validation should print a warning for a few releases before we make this a hard error.

**Comment by tlimoncelli** [comment]
Take a look at https://github.com/StackExchange/dnscontrol/pull/978 and let me know if that fixes things.

**Comment by matt-sullivan** [comment]
Thanks @tlimoncelli, I can confirm it's now fixed.

**Comment by AshleyJackson** [comment]
I'm currently still experiencing this issue with version 3.5.0, which is confusing as this should have already been fixed.

```
2021/02/03 23:35:57 printIR.go:88: 3 Validation errors:
2021/02/03 23:35:57 printIR.go:94: ERROR: txt target >255 bytes and AUTOSPLIT not set: label="@" index=0 len=259 string[:50]="v=spf1 include:_spf.google.com include:*********..."
2021/02/03 23:35:57 printIR.go:94: ERROR: txt target >255 bytes and AUTOSPLIT not set: label="google._domainkey" index=0 len=410 string[:50]="v=DKIM1; k=rsa; p=*************************AQEFAAOCAQ8A..."
2021/02/03 23:35:57 printIR.go:94: ERROR: txt target >255 bytes and AUTOSPLIT not set: label="google._domainkey" index=0 len=410 string[:50]="v=DKIM1; k=rsa; p=*************************AQEFAAOCAQ8A..."
exiting due to validation errors
```

I'm getting this error without the AUTOSPLIT on the TXT records in Cloudflare.
Shouldn't the TXTMulti be allowing this to go through?

**Comment by tlimoncelli** [comment]
The handling of txt records larger than 255 bytes is a bite messy right now, with different providers handling things differently.  

Does using AUTOSPLIT work? (as a workaround)

**Comment by AshleyJackson** [comment]
It adds the records, but it has it listed as two strings each encased with their own quotation marks.
![image](https://user-images.githubusercontent.com/12793989/107444659-b4eaab80-6b86-11eb-83b2-4e46b6948589.png)

I'm not sure how email providers will like this with some domains having long TXT records for their SPF records.
