### ISSUE TITLE
Add HOST macro to helpers.js

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#989]
See https://github.com/StackExchange/dnscontrol/issues/965#issuecomment-737421349

**Comment by juliusrickert** [comment]
I have built a similar—but way simpler—higher-order function to group IPv4 and IPv6 addresses.
Mine takes an IPv4 and IPv6 address and returns a function that, in turn, takes a label and returns the set of IP addresses with the label attached.

```js
function HOST(ipv4, ipv6) {
  return function (label) {
    return [
      A(label, ipv4),
      AAAA(label, ipv6),
    ];
  };
}
```

The important difference to me is, that I do not need to pass the IP addresses on every use, but have a higher-order function that "saves" the set of addresses.

**Comment by tresni** [comment]
I originally did something similar, I changed away from it when I decided I wasn't going to require that all addresses be present (e.g. for an IPv4 or IPv6 only host), but still wanted it to auto-generate the PTR record.  Once I did that it got complicated.

**Comment by tlimoncelli** [comment]
My plan is to create a page in the documentation with "cool macros you might want to copy" or something like that.

Do either of you populate the metadata with Ethernet MAC addresses and use that info to generate ISC DHCP configurations?  I've heard people mention that but I haven't see it done yet.

**Comment by tresni** [comment]
I do not as we don't really use DHCP today.  Should be relatively easy since the macro already allows passing parameters beyond the hostname/ip and those extra arguments are passed to A/AAAA records (but not PTR, that may have been an oversight.)

**Comment by tlimoncelli** [comment]
I think this is too specific to any particular user.  At Stack, we implemented it and it has a ton of features that are specific to us.

Stripping it down to the basics, it looks like this:

```
function HOSTIP(ipaddr, name) {
    
    var dom;
    var fqdn;
    if (name.slice(-1) == ".") { // If name ends with "."
        // If name ends in a ".", we know that name is a FQDN.
        // extract the domain:
        dom = name.slice(name.indexOf(".") + 1);
        dom = dom.slice(0, -1);
        // fqdn is the name.
        fqdn = name
    } else {
        // "name" doesn't end in ".", make some assumptions:
        dom = "mydomain.example.com"
        fqdn = name + ".mydomain.example.com.";
    }
    
    // Add an "A" and "PTR" record for this host:
    D_EXTEND(dom,
        A(fqdn, ipaddr, TTL(ttl))
    );
    D_EXTEND(REV(ipaddr), 
        PTR(ipaddr, fqdn, TTL(ptrttl))
    );  
    
}
```


The fact that `D_EXTEND` is the "best match" and `REV(ipaddr)` does a lot of magic makes it super easy to implement.
