### ISSUE TITLE
Support NS TTL customization?

### ISSUE THREAD

**Issue by eliheady** [StackExchange/dnscontrol#99]
This project is awesome, thanks for making it public.

I'm not seeing a way to set a TTL for a nameserver record. Not a on delegated zone, but the NS records for the domain in D(). The hard-coded default of 300 is all I can get.

This is what I think is the case, but I hope there is a way that I'm not seeing:
```js
NAMESERVER('blah.', TTL(86400)), // TTL ignored
DEFAULTS(DefaultTTL(86400)); // doesn't apply to NS records set by NAMESERVER()
D(DefaultTTL(86400)); // ditto
```
Am I doing it wrong?

Thanks! Eli

**Comment by tlimoncelli** [comment]
TTLs for automatically generated (apex) NS records are controlled via the metadata token "ns_ttl".

From memory, it should be like this:

```
NAMESERVER('blah.', {"ns_ttl":"172800"}),
DEFAULTS({"ns_ttl":"172800"};
D(..., ..., {"ns_ttl":"172800"});
```
We should add this to the docs.

CC: @captncraig

**Comment by eliheady** [comment]
Thanks Tom. I'll take a stab at a PR

**Comment by eliheady** [comment]
I'm getting an error when using the form `NAMESERVER('blah.', {"ns_ttl":"172800"})`:

```
2017/04/28 12:36:39 main.go:56: Error executing javasscript in (dnsconfig.js): json: cannot unmarshal object into Go struct field Nameserver.target of type string
```

**Comment by captncraig** [comment]
Yeah, that snippet was inaccurate. 

In a domain you can do 

`D("ex.com", REG, DnsProvider(foo)...`
 
to automatically determine nameservers, or 

`D("ex.com", REG, .... NAMESERVER("ns1.foo.com.", "1.2.3.4"))`,

to manually define it. But NAMESERVER does not accept the ttl metadata. That belongs on the domain. Or you can apply it to all domains with `DEFAULTS({ns_ttl: 172800})`

**Comment by eliheady** [comment]
Thanks Craig. I omitted that usage from the examples added in #107
