### ISSUE TITLE
New release for the TXT auto-split BC

### ISSUE THREAD

**Issue by fhuitelec** [StackExchange/dnscontrol#991]
Hi!

The `AUTOSPLIT` breaking change<sup>1</sup> (cf. https://github.com/StackExchange/dnscontrol/pull/947 & [docs](https://stackexchange.github.io/dnscontrol/js#long-and-multiple-strings)) is not exposed through an official release.

Would it be possible to release a new version (on both Github and Docker hub) to avoid relying on the `latest` docker image tag (which is bound to `master` and might not be super stable)?

Thank you!

---

<sup>1</sup> You might not consider it a BC per se, I don't really mind about how you translate this change in semver :slightly_smiling_face:

**Comment by tlimoncelli** [comment]
Good timing!  I was planning on doing one this week. (It's in progress now).
