### ISSUE TITLE
Long string doc should mention DKIM()

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#992]
This page https://stackexchange.github.io/dnscontrol/js#long-and-multiple-strings 
should mention DKIM()

Add "if there are other protocols that require splitting long TXT records in particular ways, please add new macros to helpers.js"

**Comment by juliusrickert** [comment]
What is `DKIM`'s purpose regarding `AUTOSPLIT`?

**Comment by tlimoncelli** [comment]
DKIM gets the same results as AUTOSPLIT but in a different way.

The idea was that if we mark strings that are used for DKIM, maybe we could process them specially in the future.  (i.e. do things we wouldn't want to do with non-DKIM long strings).

In hindsight this is not the best design.  We should probably refactor the TXT handling code.

**Comment by juliusrickert** [comment]
Thank you for clarifying.

I am, in fact, of the opinion that `AUTOSPLIT` should be the default. I cannot remember any RFC that touched on multi-string TXT records and did not append them to one another without any whitespace in between.

**Comment by tlimoncelli** [comment]
I agree.  

The weirdest part about all this is that some providers only split long TXT records at 255-octet boundaries.  If you hand them `"foo" "bar"` you'll get back `"foobar"`.  If you give them strings of length 200 + 50 + 100 you get back strings of length 255 and 95.

I think what I'm going to do is have 3 modes:

1. Provider only supports TXT of 255 and less: Validation will be to assure the string is 255 octets or fewer.
2. Provider supports multiple strings in a TXT : Validation will assure each string is 255 octets or fewer.
3. Provider supports long strings but only on 255-octet boundaries: Validation will assure that the last string is 255 octets or fewer, and the others are 255 octets exactly.

I think that's a better way to do it, and hopefully I can do this in a way that doesn't break existing providers and dnsconfig.js files.

**Comment by juliusrickert** [comment]
> The weirdest part about all this is that some providers only split long TXT records at 255-octet boundaries. If you hand them `"foo" "bar"` you'll get back `"foobar"`

Why does every provider need to be _clever_ about their API in some way? 😭 

I think there is a fourth type of provider that accepts and returns strings of any length but splits them into 255-byte chunks when returning them via DNS, so you could hand them a string of any length. (IIRC http.net does that.)
And there ought to be a provider that only accepts a single string and splits it when serving, too.

**Comment by tlimoncelli** [comment]
True.  And if there is a 4th one, there will be a 5th one :-)

So...

I think the best thing would be for people to specify TXT() with any number of strings (one big one, a list of little ones, a mix, etc.), let the provider handle it as best they can, and return either a warning or an error.  The warning might be that the small strings have been concatenated and broken into 255-ocet chunks.  An error might be "I can't handle strings that long".

**Comment by tlimoncelli** [comment]
See https://github.com/StackExchange/dnscontrol/issues/1052

**Comment by tlimoncelli** [comment]
With the recent changes to TXT records, I've made DKIM a no-op.  #1084 has been merged into `master`.  Please take a look.

**Comment by tlimoncelli** [comment]
Obsolete
